### ISSUE TITLE
Blender Cycles render segfaults with ROCm 3.3.0 (Blender 2.8x)

### ISSUE THREAD

**Issue by thima2017** [ROCm/ROCm#1106]
I installed rocm3.3.0 from rocm's repo for Ubuntu (http://repo.radeon.com/rocm/apt/debian/). And I've read an installation guide (https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html#ubuntu).

[ROCm3.3.0+Blender2.82a-logs-infos-strace.zip](https://github.com/RadeonOpenCompute/ROCm/files/4604249/ROCm3.3.0%2BBlender2.82a-logs-infos-strace.zip)

**Comment by thima2017** [comment]
Maybe related https://developer.blender.org/T68809

**Comment by ableeker** [comment]
I have installed ROCm 3.3.0 on Ubuntu 20.04, and I'm running Blender 2.82a. Blender sees, and recognises my Radeon RX Vega 64. It doesn't segfault on my system, and even renders using the GPU. So, in a sense, it works. Unfortunately, it's working for me, but it's pretty useless. I've been trying it out, but it either doesn't seem to do much, it renders exactly as "fast" as CPU only, or it even will render MUCH slower... For example, a simple scene will render in 90 seconds as CPU only, but rendering as the GPU only won't render faster, as a matter of fact it will render a magnitude slower, or even more.

**Comment by Szalacinski** [comment]
Same thing here.  It also causes severe graphical corruptions and slowdowns in Gnome.

**Comment by iszotic** [comment]
the workaround is here https://github.com/RadeonOpenCompute/ROCm/issues/402

**Comment by ableeker** [comment]
I've tried it, and it seems to work, Blender with OpenCL rendered a bit faster (10%, or maybe 20% faster). But, and this kills this configuration for me, when I reboot the computer with it, it hangs during boot. When I restore the normal ROCM configuration, it boots again.

**Comment by Riteo** [comment]
Are there any updates on this whole opencl issue? Is there any planned fix for blender or slow performance, or is this project dead?

**Comment by olFi95** [comment]
> Are there any updates on this whole opencl issue? Is there any planned fix for blender or slow performance, or is this project dead?

I am also very interested in this Feature.

**Comment by ROCmSupport** [comment]
Hi @thima2017 and all,
Thanks for reaching out.
Developer is working on the issues and fixes will be ready and will be part of upcoming releases.
Please stay tuned.

**Comment by onodera-punpun** [comment]
As of 4.0.0 I am still having this issue.

**Comment by ROCmSupport** [comment]
Hi @onodera-punpun, we are aware this issue is not fixed yet.
As there are multiple issues with Blender, we are working on them.
The fixes will be part of upcoming releases definitely, but have no specific timelines as of now.
Will share more updates soon.
Thank you.

**Comment by ROCmSupport** [comment]
Hi All,

As per the latest information and clarity provided in our Documentation that ROCm does not support GUI applications officially.

Docs also updated accordingly @ https://github.com/RadeonOpenCompute/ROCm#hardware-and-software-support

Hardware and Software Support
ROCm is focused on using AMD GPUs to accelerate computational tasks such as machine learning, engineering workloads, and scientific computing. In order to focus our development efforts on these domains of interest, ROCm supports a targeted set of hardware configurations which are detailed further in this section.
Note: The AMD ROCm™ open software platform is a compute stack for headless system deployments. GUI-based software applications are currently not supported.

**Comment by Szalacinski** [comment]
There isn't anything fundamentally different between a GUI program using OpenCL, and a CLI program using OpenCL.  Incorrect results and system crashes are still major bugs no matter which way you look at it.  If ROCm can't deliver correct results without crashing the system, regardless of the program being GUI or CLI, then it is functionally useless.  This is basically just rewriting the rules to avoid solving massive problems with your system.  This is really a complete cop-out.  I was hoping that ROCm would improve over time, and that I could go back to using it. If this is the way that the ecosystem is going to go, I can't see myself ever using it again.

Oh, and Blender renders can be run as a CLI command, so this excuse is both wholly incorrect on a rational level, as well as a technical level.

**Comment by johnbridgman** [comment]
> There isn't anything fundamentally different between a GUI program using OpenCL, and a CLI program using OpenCL. Incorrect results and system crashes are still major bugs no matter which way you look at it. If ROCm can't deliver correct results without crashing the system, regardless of the program being GUI or CLI, then it is functionally useless. This is basically just rewriting the rules to avoid solving massive problems with your system. This is really a complete cop-out. I was hoping that ROCm would improve over time, and that I could go back to using it. If this is the way that the ecosystem is going to go, I can't see myself ever using it again.

Agree, and apologies for this. The README message was a bit too vague and is being misinterpreted. What it was trying to say was more like "the ROCm stack **releases** do not include userspace graphics components and are not tested for graphics", which has always been the case - you need to combine ROCm userspace compute components with a graphics stack to get a full solution. We currently include a subset of the ROCm stack (up to OpenCL) in our packaged graphics drivers and will be including more over time. 

We did a lot of testing and fixing of the ROCm OpenCL stack as part of the 20.45 release, including a lot of testing/fixing on Blender. Those fixes have not yet made it into a ROCm stack release AFAIK but they should appear shortly.

**Comment by ROCmSupport** [comment]
We are going to rephrase the text about GUI apps in our rocm documentation.
We have come up with some plans to handle GUI apps in a way.
I am reopening it now.
Thank you.

**Comment by tasso** [comment]
Is this still an issue?  If not, can we please close it?  Thanks!

**Comment by tasso** [comment]
Original ticket is more than a year old and the person that opened ticket originally has not responded to the latest request.  If this is still an issue, please file a new ticket and we will investigate.  Thanks

**Comment by abrasmelin** [comment]
This is still an issue. Arch linux user here. Installed hip-runtime-amd-blender package from AUR. I can see my gpu in preferences/system tab but when I try to render Blender just crashes. In Fedora I can use blender with my amd gpu. Whats the problem with rocm and arch linux? Thanks.

**Comment by kuhar** [comment]
+1, as of rocm 5.7 / radeon 7900xtx I have issues running rocm examples in a desktop environment alongside unrelated GUI apps
![image](https://github.com/ROCm/ROCm/assets/4612584/b7d5fe62-4cc5-498f-9283-1a3613e92cb5)

**Comment by tasso** [comment]
@kuhar Let's open up anew ticket.  Thanks!

**Comment by kuhar** [comment]
@tasso Filed a new issue here: https://github.com/ROCm/ROCm/issues/2820
