### ISSUE TITLE
rocm-validation-suite3.8.0 ./conf/deviceid.sh doesn't work. Wrong paths.

### ISSUE THREAD

**Issue by baryluk** [ROCm/ROCm#1233]
rocm-validation-suite3.8.0 3.4.30800

```
root@debian:/opt/rocm-3.8.0/rvs# ./conf/deviceid.sh 
./conf/deviceid.sh: line 99: /opt/rocm/rvs/rvs: No such file or directory
```

Providing `ROCM_PATH` environment variable doesn't help.

`RVS_EXE_PATH=/opt/rocm-3.8.0/rvs/rvs` appears to resolve the issue, but the script does nothing.

My suggestion:

1) Use proper paths by default.
2) Respect `ROCM_PATH`
3) Terminate script early (with error message and how to fix it) if the provided or computed `RVS_EXE_PATH` doesn't point to executable file that exists.

**Comment by pramenku** [comment]
Can you please try with latest release 3.9.

**Comment by baryluk** [comment]
> Can you please try with latest release 3.9.

Same.

**Comment by rkothako** [comment]
Thanks @baryluk 
This issue is known to us and we are working on the fix.
Thank you.

**Comment by ROCmSupport** [comment]
Hi @baryluk 
Issue is fixed and changes are pushed.
Request you to verify with ROCm 4.1 or 4.2.
Thank you.

**Comment by baryluk** [comment]
I will test when, 4.1 or 4.2 is out, packaged and available for testing.

**Comment by rkothako** [comment]
Hi @baryluk 
Hope the issue is resolved.
Please confirm.

**Comment by nartmada** [comment]
Closing the ticket as no response @baryluk.  Please re-open the ticket if issue still exists with latest ROCm6.0.0.  Thanks.
