### ISSUE TITLE
Wrong int64 multiplication test case

### ISSUE THREAD

**Issue by develancer** [ROCm/ROCm#1383]
AMD OpenCL compiler used for RX 5700 XT with ROCM 4.0.1 sometimes generates invalid code for integer multiplication.

The self-contained example is here: https://github.com/develancer/amd-opencl-test-case

Disabling all compiler optimizations does not help.

**Comment by ROCmSupport** [comment]
Thanks @develancer for reaching out.
I tried the same code on Vega20(MI50) + ROCm 4.0 and am able to reproduce the issue.

The output is same as below from ROCm 3.5 to ROCm 4.0
77262ca4b90e3fcb55f32ba92841024688802f53e75b16196c399de799377ba7

But the output is different in ROCm 3.3
3c7beaf9aafd3e3990b4d1a7a65338417296facf06209627f93941ffcb607414

Can you please share some info like what is this output and what to understand more from output.
Based on your information, I will work on it and move this ticket to next level.

I request you to remove 5700 XT from the title as its not specific to it and its observed in all hardware mostly.

Thank you.

**Comment by develancer** [comment]
Edited as requested. Thanks for taking time to reproduce this bug.

The output is a result of some abstract secp256k1 elliptic curve computations. Essentially, it calculates the group inverse of the product of z[0]…z[511] where z[i] is a z-element of the Jacobian form of the sum of prec[0]…prec[i], with prec being the included precomputed table. All calculations are performed on the secp256k1 elliptic curve.

As you can see, it does not have any intuitive interpretation. Unfortunately, it cannot be simplified, as any simpler test case I tried to come up with would not exhibit the same behavior anymore.

However, the calculations are 100% deterministic and don't include any undefined behavior. The correct result (as computed on NVidia GPUs or CPUs through POCL) should be
```
bbde464b6355ee6de6deba5ae860f8a66524937eee81dde224a0214efd795d09
```

**Comment by develancer** [comment]
Forgot to notify you so here it goes: @ROCmSupport

**Comment by ROCmSupport** [comment]
Thanks @develancer for the additional information.
I will assign to dev. Thank you.

**Comment by ROCmSupport** [comment]
Latest update:
I have assigned to OpenCL compiler team and he will start looking into it.
I will keep you posting.
Thank you.

**Comment by develancer** [comment]
@ROCmSupport Any news on this one?

**Comment by ROCmSupport** [comment]
Hi @develancer 
I am working with dev, let me share an update very soon.
Thank you.

**Comment by develancer** [comment]
@ROCmSupport Feel free to share an update ;-)

**Comment by develancer** [comment]
Hi @ROCmSupport, just wanted to remind you it's been a month since the last update.

**Comment by ROCmSupport** [comment]
I pinged developer and waiting for the update
Most probably issue will be fixed in ROCm 4.3.
Thank you.

**Comment by ROCmSupport** [comment]
I pinged developer and waiting for the update
Most probably issue will be fixed in ROCm 4.3.
Thank you.

**Comment by ROCmSupport** [comment]
I have pinged the developer and waiting for the update.
Most likely issue will be fixed by ROCm 4.3, anyway I will confirm soon.
Thank you.

**Comment by develancer** [comment]
Hi @ROCmSupport, another month has passed, so I wonder whether we have any timeframe for this fix?

Just wanted to emphasize that since the compiler generates invalid code in this case, it may as well do so in many different scenarios, most of which may slip undetected in various professional or scientific applications.

**Comment by ROCmSupport** [comment]
Hi @develancer 
Most likely it will be fixed with/before ROCm 4.4.

**Comment by develancer** [comment]
Hi @ROCmSupport, is the fix is still expected to happen with ROCm 4.4, or has the schedule changed?

**Comment by ROCmSupport** [comment]
Hi @develancer 
I reached developer on the same and will provide an update asap once I hear from them.
Thank you

**Comment by develancer** [comment]
Hi @ROCmSupport, another month has passed — I suspect the developer is on holiday?
My question from 18 Aug is still valid.

**Comment by ROCmSupport** [comment]
Hi @develancer 
As per the latest information, fix will be part of 5.0. Thank you.

**Comment by develancer** [comment]
@ROCmSupport Do you have any timeframe for the wide availability of ROCm 5.0?

**Comment by ROCmSupport** [comment]
I am sure that pacthes/fixes are ready, let me check with the developer on 5.0 tracker. Thank you.

**Comment by develancer** [comment]
@ROCmSupport Hello again! Were you able to check with the developer on this matter?

**Comment by ROCmSupport** [comment]
I just pinged the developer, waiting for the response.

**Comment by ROCmSupport** [comment]
Hi @develancer 
Good news. Fix is ready and its part of our internal builds already. ROCm 5.1 will have the fix.
5.1 will be released very soon in next few days and I request to verify once 5.1 is out.
Thank you.

**Comment by develancer** [comment]
Hi @ROCmSupport,
Any timeframe for the release of 5.1?

**Comment by ROCmSupport** [comment]
Hi @develancer 
Request to wait for a month(approx.).

**Comment by nartmada** [comment]
Hi @develancer, apologies for the slow/lack of response :( Can you please check latest ROCm 6.0.0 to confirm the issue is gone?  If  issue is no longer reproducible, please close the ticket.  Thanks.

**Comment by develancer** [comment]
Hi @ROCmSupport,
It’s been several years and I don’t have the card anymore.
I switched to NVIDIA and I recommend everyone else to do the same.
