### ISSUE TITLE
How to install RDC client on the management console

### ISSUE THREAD

**Issue by valeriob01** [ROCm/ROCm#1425]
This isn't clear to me by reading the PDF guide. I can install the RDC daemon on the compute nodes, but I'm stuck there.

**Comment by ROCmSupport** [comment]
Hi @valeriob01 
Thanks for reaching out.
Can you please share the exact steps you followed and the pdf guide/doc you used.
Thank you.

**Comment by valeriob01** [comment]
> Hi @valeriob01
> Thanks for reaching out.
> Can you please share the exact steps you followed and the pdf guide/doc you used.
> Thank you.

I follow the steps in the latest version 4.1 , just `apt install rdc`

**Comment by valeriob01** [comment]
> > Hi @valeriob01
> > Thanks for reaching out.
> > Can you please share the exact steps you followed and the pdf guide/doc you used.
> > Thank you.
> 
> I follow the steps in the latest version 4.1 , just `apt install rdc`

BTW, the installation shows a warning:
`useradd: Warning: missing or non-executable shell '/bin/nologin'`

I have `/bin/false` which substitutes it on Ubuntu.

**Comment by ROCmSupport** [comment]
Thanks @valeriob01 
I am able to reproduce this warning.
Other than that, I am able to install rdc well.

**Comment by valeriob01** [comment]
How do you install it? I cannot find rdc daemon after installation.

**Comment by valeriob01** [comment]
My original question was how to install rdc client on the management console, however this becomes second class question now, lets first install the daemon correctly.

**Comment by ROCmSupport** [comment]
sudo apt install rdc --> installs rdc under /opt/rocm
/opt/rocm/rdc/bin will have both rdcd(daemon) and rdci(client interfact).

**Comment by valeriob01** [comment]
> sudo apt install rdc --> installs rdc under /opt/rocm
> /opt/rocm/rdc/bin will have both rdcd(daemon) and rdci(client interfact).

Ok that's done, and generated the certs. In which directories shall I copy the certs?

**Comment by ROCmSupport** [comment]
Request you to follow the rdc docs for all of the information.

**Comment by valeriob01** [comment]
> Request you to follow the rdc docs for all of the information.

Some modifications are necessary:

1. System: Ubuntu 20.04
2. Still need to build gRPC from source;
2. gRPC branch 1.28.1 is not found in the repository;
3. Compiled and installed gRPC;
4. `rdci stats` fails with error: `ERROR RdcLibraryLoader.cc(43): Fail to open librdc_client.so: libgrpc.so.9: cannot open shared object file: No such file or directory`

**Comment by ROCmSupport** [comment]
Once you install rdc as apt install rdc, you will find /opt/rocm/rdc.
In that, you can see grpc also as a folder, so no need to compile/install explicitly.
If some library loading problem is there, recommend to export explicitly something like 
_export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/rocm-4.1.0/rdc/lib/:/opt/rocm-4.1.0/rdc/grpc/lib/:/opt/rocm-4.1.0/rdc/grpc/lib64:/opt/rocm-4.1.0/rocm_smi/lib/_

**Comment by valeriob01** [comment]
> Once you install rdc as apt install rdc, you will find /opt/rocm/rdc.
> In that, you can see grpc also as a folder, so no need to compile/install explicitly.
> If some library loading problem is there, recommend to export explicitly something like
> _export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/rocm-4.1.0/rdc/lib/:/opt/rocm-4.1.0/rdc/grpc/lib/:/opt/rocm-4.1.0/rdc/grpc/lib64:/opt/rocm-4.1.0/rocm_smi/lib/_

better but still:

`rdci stats --host localhost:50051 -s 2442 -g 1`
failed to connect to all addresses. Error code:14
rdci Error: RDC Client error

**Comment by ROCmSupport** [comment]
Hi @valeriob01 
Can you please confirm whether issue is still observed and also more information is really helpful to understand the problem better.
Thank you.

**Comment by valeriob01** [comment]
Yes, still present. Sorry I gave up using rdc for the moment and am using a different software to monitor gpus, however the error code should be clear to you as you programmed it :-)

**Comment by abhimeda** [comment]
@valeriob01 is this issue still persisting on the latest version of ROCm? If not can we close this ticket?

**Comment by nartmada** [comment]
Closing this ticket as no response from @valeriob01.  Please re-open if you still observe the issue.  Thanks.
