### ISSUE TITLE
Information table of supported features for several Hardware like in mesamatrix or better

### ISSUE THREAD

**Issue by stefano2734** [ROCm/ROCm#1463]
Information table of supported OpenCL features for several Hardware like in mesamatrix or better

See OpenCL tables at the end of website

https://mesamatrix.net/

**Comment by ROCmSupport** [comment]
Hi @stefano2734 
Thanks for reaching out.
I did not understand your point well. Are you sharing information or are you looking for some information?
Please clarify.
Thank you.

**Comment by stefano2734** [comment]
I want see same or better information tables in rocM also.
Mesamatrix with his tables shows not perfect but good the status of their development.
This tables can help users and developers.
Most functions are not used in software by asymmetrical information.
Internal  status of a software is complex.
Quality of code, performance, bugs, Features, todo list and much more.
And this all under permanent time pressure.
So sometimes a project Team must go in a helicopter ahead and see the world of their project.
And one helicopter tool is a table of supported functions also in relation to other implementation and teams.
Normally a standard is a wonderful milestone.
OpenCL 3.0 is a „broken“ standard. OpenCL 2.x is only optional. And many other functions are also optional not in the Standard. Not all hardware can do all of this. So there is a Matrix of possible.
A developer for many platforms must now, what he can use by base for his software. 
At the moment only OpenCL 1.2 is secure for actual and older hardware. Only very old is compatible only to OpenCL 1.1.
So 50% of your work less or more is actual not used.
Some functions are optional but available in most OpenCL-teams.
With public clear information more functions are used with progress in software.

Internal you should have status tables of your project with comparisons to the other teams of Nvidia, Intel and Mesa and others.

**Comment by stefano2734** [comment]
And see slides: FAST development and their problems with OpenCL features and OpenCL support in drivers
https://www.iwocl.org/wp-content/uploads/17-iwocl-syclcon-2021-smistad-slides.pdf
Gromacs goes to SYCL 
https://www.iwocl.org/wp-content/uploads/22-iwocl-syclcon-2021-alekseenko-slides.pdf

**Comment by ROCmSupport** [comment]
Thanks @stefano2734 
I will let developer to comment on this. Thank you.

**Comment by ROCmSupport** [comment]
Hi @stefano2734 
I got update from developer and pasting here.

**For extensions OpenCL supports, run clinfo, all will be listed for the GPU, as well as the platform extensions.**

Hope this helps.
Thank you.

**Comment by ROCmSupport** [comment]
I am closing this considering as requested information is shared.
Feel free to open a new issue, for any, for quick resolutions.
Thank you.

**Comment by nartmada** [comment]
Closing the ticket as requested info has been shared by ROCmSupport on May 13, 2022.
