### ISSUE TITLE
.AMDGPU.csdata codeLenInByte is wrong with inline assembly

### ISSUE THREAD

**Issue by preda** [ROCm/ROCm#1499]
Using ROCm 3.3.0 OpenCL, Linux kernel 5.12.12, Radeon VII.

When computing the value of codeLenInByte that is present in the ISA dump, in the presence of inline assembly, it seems every instruction in counted as 8-bytes in size. This produces a wrong codeLenInByte, as in reality some instructions are encoded on 4 bytes.

I'm not sure whether codeLenInByte is actually used for anything or acts just as a comment (this would impact the severity of this issue).

How to repro:
```
#define ATTR(x) __attribute__((x))
#define WGSIZE(n) ATTR(reqd_work_group_size(n, 1, 1))
typedef ulong u64;

kernel WGSIZE(64) void testKernel(global u64* io) {
  __asm("s_load_dwordx2 s[0:1], s[4:5], 0x0\n\t\
	v_lshlrev_b32_e32 v0, 3, v0\n\t\
	v_mov_b32_e32 v2, 0\n\t\
	v_mov_b32_e32 v3, v2\n\t\
	s_waitcnt lgkmcnt(0)\n\t\
	v_mov_b32_e32 v1, s1\n\t\
	v_add_co_u32_e32 v0, vcc, s0, v0\n\t\
	v_addc_co_u32_e32 v1, vcc, 0, v1, vcc\n\t\
	global_store_dwordx2 v[0:1], v[2:3], off"
        ::: "s0", "s1", "s2", "s3", "s4", "s5", "v0", "v1", "v2", "v3", "vcc");
}
```

The above kernel reports  codeLenInByte = 76, while the correct value is 48. The difference, 28, corresponds to 7 instructions that are encoded on 4bytes instead of 8bytes.

**Comment by ROCmSupport** [comment]
Thanks @preda for reaching out.
I am not an expert in understanding the logic behind this code.
I have assigned to compiler team to have a look.
Thank you.

**Comment by ROCmSupport** [comment]
Hi @preda 
Can you please help me with the exact steps to reproduce problem on my own?
And also I request you to check with the latest ROCm 4.2 and share the results.
Thank you.

**Comment by preda** [comment]
@ROCmSupport 
Put the above bit of source code in an OpenCL file (.cl) and compile it, dumping the result of the compilation using the OpenCL -save-temps= command line option. One of the dumped files contains the disassembly (.s), and in there you can see the value of codeLenInByte, and observer whether correct or wrong.

You can also compare with the disassembly of an equivalent kernel that does not use assembly such as
```
kernel WGSIZE(64) void testKernel2(global u64* io) {
  uint me = get_local_id(0);
  io[me] = 0;
}
```

I'll report back about ROCm 4.2 as soon as I boot kernel 5.13.

**Comment by preda** [comment]
@ROCmSupport I confirm the bug manifests itself in exactly the same way, on ROCm 4.2.0, Linux kernel 5.13.0, without rock-dkms.

**Comment by ROCmSupport** [comment]
Hi @preda 
Can you please verify with ROCm 4.5 and update us. Thank you.

**Comment by nartmada** [comment]
Hi @preda, is the bug still present in ROCm6.0.0?  If issue has been fixed, please close the ticket.  Thank you.

**Comment by nartmada** [comment]
Closing the ticket as it is stale and no response from @preda.  Please re-open the ticket if the issue still exists in ROCm6.0.0.  Thanks.
