### ISSUE TITLE
RPM packages: Not all header files are symlinked into /opt/rocm/include

### ISSUE THREAD

**Issue by Sturmflut** [ROCm/ROCm#1558]
The following official RPM packages symlink their header files into `/opt/rocm/include/`:

hipblas-0.46.0.40300-52.el7.x86_64
hipcub-2.10.9.40300-52.el7.x86_64
hipfft-1.0.3.40300-52.el7.x86_64
hipsparse-1.10.7.40300-52.el7.x86_64
hsakmt-roct-devel-20210520.3.071986.40300-52.el7.x86_64
hsa-rocr-dev-1.3.0.40300-52.el7.x86_64
miopen-hip-2.12.0.40300-52.el7.x86_64
rccl-2.8.4.40300-52.el7.x86_64
rocalution-1.12.1.40300-52.el7.x86_64
rocblas-2.39.0.40300-52.el7.x86_64
rocfft-1.0.12.40300-52.el7.x86_64
rocm-dbgapi-0.48.0.40300-52.el7.x86_64
rocprim-2.10.9.40300-52.el7.x86_64
rocprofiler-dev-1.0.0.40300-52.el7.x86_64
rocsolver-3.13.0.40300-52.el7.x86_64
rocsparse-1.20.2.40300-52.el7.x86_64
rocthrust-2.10.9.40300-52.el7.x86_64
roctracer-dev-1.0.0.40300-52.el7.x86_64

At least the following don't:

rocm-opencl-devel-2.0.0.40300-52.el7.x86_64
hip-base-4.3.21300.5994.40300-52.el7.x86_64

This makes it hard for us as an HPC provider to provide documentation and environment module files for our HPC users since we have to document multiple paths and cannot simply communicate `/opt/rocm/include/`.

**Comment by ROCmSupport** [comment]
Thanks @Sturmflut for reaching out.
I certainly understood the problem.
I will talk to packaging team on this and will share an update.
Thank you.

**Comment by abhimeda** [comment]
Is this still reproducible with the latest ROCm?  If not, can we please close it?  Thanks!

**Comment by nartmada** [comment]
Closing this ticket as it has become stale.  @Sturmflut, please re-open this ticket if you still see the issue with latest ROCm 6.0.0.  Thanks.
