### ISSUE TITLE
Any information about PMC blocks in hsa_ven_amd_aqlprofile?

### ISSUE THREAD

**Issue by WyldeCat** [ROCm/ROCm#1559]
Because rocprofiler doesn't support GFX10 (gfx1010 or gfx1030), I searched ROCm (4.2.0) header files for clues and found some enum about GFX10 at (rocm/include/hsa/hsa_ven_amd_aqlprofile.h) .

Is there any information about what those PMC blocks are?
```
  // GFX10 added blocks
  HSA_VEN_AMD_AQLPROFILE_BLOCK_NAME_GL1A = 26,
  HSA_VEN_AMD_AQLPROFILE_BLOCK_NAME_GL1C = 27,
  HSA_VEN_AMD_AQLPROFILE_BLOCK_NAME_GL2A = 28,
  HSA_VEN_AMD_AQLPROFILE_BLOCK_NAME_GL2C = 29,
  HSA_VEN_AMD_AQLPROFILE_BLOCK_NAME_GCR = 30,
  HSA_VEN_AMD_AQLPROFILE_BLOCK_NAME_GUS = 31,

  HSA_VEN_AMD_AQLPROFILE_BLOCKS_NUMBER
} hsa_ven_amd_aqlprofile_block_name_t;
```

**Comment by ROCmSupport** [comment]
Thanks @WyldeCat for reaching out.
I will work with hsa developer and share an update on this.
Thank you.

**Comment by nartmada** [comment]
Hi @WyldeCat, do you still need this ticket to be opened?  Do you still need the PCM blocks info?  Thanks.

**Comment by nartmada** [comment]
Closing this ticket as it is stale.  @WyldeCat, please re-open if you still need info on PCM blocks.  Thanks.
