### ISSUE TITLE
4.3.1 release: fails to download source

### ISSUE THREAD

**Issue by gggh000** [ROCm/ROCm#1597]
This is "re-opening" of following issue that was closed by amdsupport without actually fixing. Please do not close without fix! Doing so puts on a limelight that amdsupport is not interested in fixing issue but more looking like a finding an any excuse to close it asap.
https://github.com/RadeonOpenCompute/ROCm/issues/1579
Refer to latest update on 1579 and continue it here please.

**Comment by ROCmSupport** [comment]
Hi @gggh000 
Thanks for reaching out.
Can you please try with the latest 4.5 and update. Thank you.

**Comment by ROCmSupport** [comment]
Hi @gggh000 
This issue is fixed with 4.5, can you please check and let us know.
Thank you.

**Comment by nartmada** [comment]
As commented by ROCmSupport, the issue has been fixed with ROCm4.5.  If issue still exists with ROCm6.0, please re-open the ticket.  Thanks.
