### ISSUE TITLE
Unable to build rock dkms for custom kernel

### ISSUE THREAD

**Issue by tsipa** [ROCm/ROCm#1601]
What i did:

rpm -ivh rock-dkms-4.3-59.el7.noarch.rpm rock-dkms-firmware-4.3-59.el7.noarch.rpm
dkms build -m amdgpu -v 4.3-59.el7 -k 5.12.0
where 5.12.0 is a custom kernel
I got:
https://pastebin.com/AYf7DmTB
"gcc: fatal error: cannot specify -o with -c, -S or -E with multiple files"

I investigated a little up to the running make with debug and i know it's running something like:
https://pastebin.com/sSYqWppF
and the problem is `-I./include ./include/linux/compiler-version.h` stanza which incorrect in terms of syntax, but now i'm struggling to figure out where it's coming from in makefiles.

I know that this problem was reported relatively recently for ubuntu as well.
https://github.com/RadeonOpenCompute/ROCm/issues/1125

**Comment by ROCmSupport** [comment]
Thanks @tsipa for reaching out.
I recommend to open issues specific to kernel @ [https://github.com/RadeonOpenCompute/ROCK-Kernel-Driver](url) as they are handled separately. 
I found that you already filed a ticket there: https://github.com/RadeonOpenCompute/ROCK-Kernel-Driver/pull/117
So no pending action item is here and hence I am closing this issue. 
Feel free to open a new issue, if any. Thank you.

**Comment by ROCmSupport** [comment]
Hi @tsipa 
Good news. Some flags need to be enabled w.r.to newer versions of GCC.
Work is completed and changes are pushed into internal builds. It will be part of next ROCm versions like ROCm 5.0(most likely).
Thank you.

**Comment by nartmada** [comment]
Closing this issue as work is completed back in Nov 16, 2021.
