### ISSUE TITLE
deviceProp.name is an empty string for MI50 with rocm 4.5 

### ISSUE THREAD

**Issue by sbalint98** [ROCm/ROCm#1625]
In the case of using rocm 4.5 the `deviceProp.name` string does not contain the expected device name. 

The following code can reproduce the issue:

```
#include<iostream>
#include <hip/hip_runtime.h>
int main(){
  hipDeviceProp_t deviceProp;
  hipGetDeviceProperties(&deviceProp, 0);
  std::cout << deviceProp.name << std::endl;
}
```
This behaviour has been observed on a system with an MI50 accelerator

**Comment by ROCmSupport** [comment]
Thanks @sbalint98 for reaching out.
I certainly understood the problem.
We already found this issue internally and tracking it and fix is in progress. I will share further update soon.
Thank you.

**Comment by lanwatch** [comment]
Same issue here on MI100

**Comment by wyphan** [comment]
Same issue still happens with ROCm 5.2.0 with MI50, MI100, and MI210.

**Comment by doit-op** [comment]
This is still an issue with MI210's on 5.2.3.

**Comment by keryell** [comment]
Is this still an issue with the latest ROCm 5.3.3?

**Comment by nartmada** [comment]
Closing this ticket as it is stale.  Furthermore, an internal developer has confirmed issue has been fixed for MI250 and MI300 in ROCm6.0.0.  @sbalint98, please re-open the ticket if you are still seeing empty string.  Thanks.
