### ISSUE TITLE
[tf-serving] Is it possible to run tf-serving with AMD GPUs/ROCm? 

### ISSUE THREAD

**Issue by tgcandido** [ROCm/ROCm#1651]
Greetings,

I have an application that uses the [tf-serving docker container](https://hub.docker.com/r/tensorflow/serving) with the [nvidia-docker](https://nvidia.github.io/nvidia-docker/) container to enable GPU inference. 

Is it possible to run the tf-serving docker container with AMD GPU/ROCm for GPU inference?

Regards

**Comment by ROCmSupport** [comment]
Thanks @tgcandido for reaching out.
Let me gather some information on this and will update you asap.
Thank you.

**Comment by ppanchad-amd** [comment]
@ROCmSupport Do you have any update on this ticket? Thanks!

**Comment by ppanchad-amd** [comment]
@tgcandido Sorry for the lack of response.  Do you still assistance with this ticket? Thanks!

**Comment by ppanchad-amd** [comment]
@tgcandido Closing ticket.  Please re-open if you still need assistance with this ticket. Thanks!
