### ISSUE TITLE
Support hipGraphAddChildGraphNode

### ISSUE THREAD

**Issue by FreddieWitherden** [ROCm/ROCm#1653]
Currently, with the experimental HIP graph API it is not possible to embed one graph inside of another (cf cuGraphAddChildGraphNode).  The node type is listed in the relevant node type enum as hipGraphNodeTypeGraph, but there is no corresponding function.

Child graph nodes are useful if one wishes to include third party library calls in a graph, for example to rocBLAS.  Here, one can use the stream capturing functionality to obtain a graph which corresponds to the relevant third party kernels and then embed this as a child graph node.

**Comment by ROCmSupport** [comment]
Thanks @FreddieWitherden for reaching out.
Let me assign this to HIP team for some update. Thank you.

**Comment by shadidashmiz** [comment]
we do have support for hipGraphAddChildGraphNode, 
https://github.com/ROCm/HIP/blob/develop/include/hip/hip_runtime_api.h here is the header and also inside hip code the functionality is supported.
