### ISSUE TITLE
How to calculate the total number of the all FP64 instructions executed in the kernel?

### ISSUE THREAD

**Issue by vasslavich** [ROCm/ROCm#1664]
Hello!
I analyzing the performance of a several scientific libraries. And, I'd like to understand an actual arithmetic complexity of each. Which metrics of rocproof  I should use for this goal? 

I guess SQ_INSTS_VALU, then _the total number_ will be equal: 
`CU_NUM * SIMD_NUM * SQ_INSTS_VALU`.  Where, for AI100: `CU_NUM` is 120 CU, `SIMD_NUM` is 4. It's correct?

Thanks!

**Comment by Maxzor** [comment]
First, isn't `SIMD_NUM` 16, not 4 even on your CDNA MI100?
Then I would be surprised if `SQ_INSTS_VALU` was only FP64 instructions!

**Comment by ROCmSupport** [comment]
Hi @vasslavich 
Thanks for reaching out.
Let me assign to one of the developers to help you. Thank you.

**Comment by vasslavich** [comment]
Hi, 
A note, actually I'd like to know the total number FP64 for to calculate/comparision FLOPS of these specific kernels. It can be very interesting.

**Comment by rwnorth** [comment]
Hi @vasslavich, we have a metric for this on MI200 but not MI100. Is this still needed?

rocprofiler/src/core/counters/metrics/derived_counters.xml
The metric is called TOTAL_64_OPS

**Comment by nartmada** [comment]
Hi @vasslavich, do you still need help from AMD on this ticket?  If not, please close the ticket.  Thanks.

**Comment by nartmada** [comment]
Closing this ticket as there is no response from @vasslavich.  Please re-open if you are still looking for total number of all FP64 instructions executed in the kernel.
