### ISSUE TITLE
better document the need for LD_LIBRARY_PATH or ld.so.conf

### ISSUE THREAD

**Issue by bgoglin** [ROCm/ROCm#1665]
Hello
We're using rsmilib in hwloc, and hwloc is used in MPI. Some MPI users are surprised to see rsmi-related link error at runtime (they don't even know MPI uses hwloc). The issue is that some platforms don't have the path of lib rsmi in LD_LIBRARY_PATH or ld.so.conf. That's easy to fix, but it's not something that end-user should do here, since they don't use rsmi directly. It's rather something to fix on the admin side, the one who installed MPI and/or hwloc.

I see in https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation_new.html#post-install-actions-and-verification-process that "Users might set LD_LIBRARY_PATH to load the ROCm library version of choice." but I think this should be improved:
* change "might" into something stronger, maybe make it mandatory like competitors do
* talk about /etc/ld.so.conf being an easier alternative for admins
* say that RPM/DEB packages take care of adding the relevant files in /etc/ld.so.conf.d/rocm-foo.conf (I don't see it installed on platforms I have access to, but I see the code in your github repos).

Thanks
Brice

**Comment by bgoglin** [comment]
By the way, platforms I have access to didn't install /etc/ld.so.conf.d/x86_64-librocm_smi_lib.conf because ENABLE_LDCONFIG was OFF when building the rocm-smi-lib debian package, why don't you enable it?

**Comment by Maxzor** [comment]
I believe that the correct way to do this is to install the library in a default path found in default ld.so.conf.d, or even just a default lib directory such as plain /usr/lib.

**Comment by sofiageo** [comment]
I've found that librocalution.so for ROCm 5.0.0 (Ubuntu release) is missing the RPATH rocm paths. So some software (e.g Pytorch, JuliaGPU) won't run if you don't set LD_LIBRARY_PATH as well.

**Comment by sofiageo** [comment]
I'm still confused about the current situation. I'm trying to provide a package for users of Arch Linux that works, based on the Ubuntu release. I guess the only way at the moment is to ask them to manually set the LD_LIBRARY_PATH to every ROCm library path in /opt/rocm - if what gboglin says is correct (that the libraries are missing ENABLE_LDCONFIG) 

Feel free to link any article or blog post that will make me more educated on the subject. Thanks

**Comment by bgoglin** [comment]
@sofiageo If you're building your own Arch packages, you should be enable to set ENABLE_LDCONFIG. I was talking about the Debian packages build by AMD, those don't have ENABLE_LDCONFIG.

**Comment by sofiageo** [comment]
> @sofiageo If you're building your own Arch packages, you should be enable to set ENABLE_LDCONFIG. I was talking about the Debian packages build by AMD, those don't have ENABLE_LDCONFIG.

I'm not building the packages, I'm using the Ubuntu packages built by AMD. It's a quick way to provide ROCm binaries to people, I know there will probably be some other issues like P2P for devices not working, but for the most part this practice works. (ROCr OpenCL works / HIP works / etc). The package is `opencl-amd` and [opencl-amd-dev](https://aur.archlinux.org/packages/opencl-amd-dev) from AUR.

**Comment by klausbu** [comment]
I have a related issue:

I want to overwrite the default library location of  rocThrust /opt/rocm-5.4.0/include/thrust  with the location of my custom version located at /opt/rocm-5.4.0/myspecialrocm/include/thrust/

The following approaches have no effect, the hipcc compiler keeps using the default version:

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/rocm-5.4.0/myspecialrocm/include/thrust/  OR the hipcc parameter -I=/opt/rocm-5.4.0/myspecialrocm/include/thrust

How can I overwrite the default paths of selected libraries to be able to compile programs with my custom versions?

**Comment by spirosbond** [comment]
If you are here because of the below error when running rocm-smi:
```
Unable to load the rocm_smi library.
Set LD_LIBRARY_PATH to the folder containing librocm_smi64.so.1
Please refer to https://github.com/RadeonOpenCompute/rocm_smi_lib for the installation guide.

```

I managed to fix it by:
1. Installing python 3.11. I had the issue with python 3.12
2. Updating the libgcc to its latest version. 

For point 2, if you are running conda/miniconda you might need to use the conda-forge channel since it has a later version:
`conda install -c conda-forge libgcc`

After that, rocm-smi works as expected.

**Comment by ppanchad-amd** [comment]
@bgoglin Is your issue resolved in the latest rocm 6.1.2. Thanks!

**Comment by bgoglin** [comment]
@ppanchad-amd Can you point to some doc changes relevant to the issue?

**Comment by ppanchad-amd** [comment]
@bgoglin Link you have in your original post is no longer accessible.

This is the current documentation for installing ROCm SMI: https://rocm.docs.amd.com/projects/rocm_smi_lib/en/latest/install/install.html

Please confirm if this the document where you'd prefer your below changes to be made:
->change "might" into something stronger, maybe make it mandatory like competitors do
->talk about /etc/ld.so.conf being an easier alternative for admins
->say that RPM/DEB packages take care of adding the relevant files in /etc/ld.so.conf.d/rocm-foo.conf (I don't see it installed on platforms I have access to, but I see the code in your github repos).

**Comment by bgoglin** [comment]
@ppanchad-amd Yes, looks like the place to apply such changes.

**Comment by ppanchad-amd** [comment]
@bgoglin Created internal ticket to fix documentation. Thanks!

**Comment by sohaibnd** [comment]
Hi @bgoglin, are you getting librocm_smi64.so by building from source or installing ROCm. The most recent ROCm installation instructions already mention that users have to configure the dynamic linker using ldconfig ([source](https://rocm.docs.amd.com/projects/install-on-linux/en/latest/install/post-install.html)).

**Comment by bgoglin** [comment]
@sohaibnd Looks good to me then. I guess you may close this issue, thanks.

**Comment by sohaibnd** [comment]
@bgoglin Great, please feel free to create another ticket if you find missing/lacking documentation for anything else!
