### ISSUE TITLE
warning /opt/conda/lib/python3.6/site-packages/torch/cuda/amp/autocast_mode.py:120: UserWarning: torch.cuda.amp.autocast only affects CUDA ops, but CUDA is not available.  Disabling.

### ISSUE THREAD

**Issue by neqkir** [ROCm/ROCm#1667]
I don't know if this can reveal a defect. 

Running a pytorch code this warning occurs when building the learner

```
learn = Learner(dls, model,
                opt_func=ranger,loss_func=CrossEntropyLossFlat(),
                cbs=learn_cbs,splitter=partial(seq2seq_splitter, arch=hf_arch)).to_fp16()
```
WARNING:
```
/opt/conda/lib/python3.6/site-packages/torch/cuda/amp/autocast_mode.py:120: UserWarning: torch.cuda.amp.autocast only affects CUDA ops, but CUDA is not available.  Disabling.
  warnings.warn("torch.cuda.amp.autocast only affects CUDA ops, but CUDA is not available.  Disabling.")
```
[fine-tuning-bart-text-summarization.txt](https://github.com/RadeonOpenCompute/ROCm/files/8014508/fine-tuning-bart-text-summarization.txt)

**Comment by ROCmSupport** [comment]
Hi @neqkir 
Thanks for reaching out.
Can you please share the exact steps to replicate the issue?
Thank you.

**Comment by ROCmSupport** [comment]
I am planning to close this as there is no update on this ticket for a long time.
Request to file new issues, if any, for faster resolutions.
Thank you.

**Comment by nartmada** [comment]
Closing the ticket as no update for a long time.  @neqkir, please file a new ticket for any issue you have encountered.  Thanks.
