### ISSUE TITLE
Will Vega 64/56 support be dropped like Instinct MI25?

### ISSUE THREAD

**Issue by Bengt** [ROCm/ROCm#1669]
Hi,

I was just wondering if support for the Vega 56 and Vega 64 consumer GPUs will be dropped after ROCm 4.5 like with the Radeon Instinct MI25 server/workstation GPU. Both have the same GFX9 ISA, so I guess the vast majority of issues will affect both or neither.

Cheers,
Bengt

**Comment by ROCmSupport** [comment]
Hi @Bengt 
Thanks for reaching out.
AFAIK, Vega10 is also under EOL, anyhow I will double check with my product and documentation team and update asap.
Thank you.

**Comment by martinschwinzerl** [comment]
Are there any updates regarding this issue? I think there is a broader issue with respect to hardware support and (at least to me) the unclear situation which versions of the ROCm stack relate do support which hardware and/or features (i.e., only OpenCL or HIP / ML stacks, etc.), cf. #1714 .

Thanks in advance!

Cheers,
Martin

**Comment by DaveScream** [comment]
No answer were given, sad

**Comment by ppanchad-amd** [comment]
@Bengt Sorry for the lack of response. Vega64/56 is no longer supported.  Please check (https://rocm.docs.amd.com/projects/install-on-linux/en/latest/reference/system-requirements.html) for supported GPU's.  Thanks!
