### ISSUE TITLE
MIOpen(HIP): Warning [SQLiteBase] Unable to read system database file:/opt/rocm/miopen/share/miopen/db/gfx906_60.kdb Performance may degrade terminate called after throwing an instance of 'boost::filesystem::filesystem_error'

### ISSUE THREAD

**Issue by Griffintaur** [ROCm/ROCm#1677]
Full error message when I am trying to train a deep learning model.
```
MIOpen(HIP): Warning [SQLiteBase] Unable to read system database file:/opt/rocm/miopen/share/miopen/db/gfx906_60.kdb Performance may degrade
terminate called after throwing an instance of 'boost::filesystem::filesystem_error'`  
what():  boost::filesystem::permissions: No such file or directory: "/home/ssml/singh/.config/miopen//gfx906_60.HIP.2_11_0_993628deb.ufdb.txt"
```

**Comment by ROCmSupport** [comment]
Hi @Griffintaur 
Thanks for reaching us.
Can you please share the exact steps to reproduce the problem locally.
And also request to share few details like GPU, OS, outputs of /opt/rocm/bin/rocminfo and /opt/rocm/opencl/bin/clinfo.
Thank you.

**Comment by ROCmSupport** [comment]
I am going to close it as there is no update on this ticket for the last 4 months.
Request user to file new issues, if any, for quick resolutions.
Thank you.

**Comment by nartmada** [comment]
Closing this ticket as there is no update.  @Griffintaur, please file a new ticket for any issues you have encountered.  Thanks.
