### ISSUE TITLE
how to install Kernel Fusion Driver to support multi version Rocm?

### ISSUE THREAD

**Issue by wangzy0327** [ROCm/ROCm#1682]
how to install Kernel Fusion Driver to support multi version Rocm

**Comment by ROCmSupport** [comment]
Hi @wangzy0327 
Thanks for reaching out.

For installing kernel driver alone, follow as: sudo amdgpu-install --usecase=dkms --> solves this problem
For installing rocm, follow: [https://docs.amd.com/bundle/ROCm_Installation_Guidev5.0/page/How_To_Install_ROCm.html#_Installation_Methods](url)

Thank you.

**Comment by ROCmSupport** [comment]
If you are happy with the resolution, request to close this ticket.
Thank you.

**Comment by nartmada** [comment]
Closing this ticket as there is no response from @wangzy0327.  Please create a new ticket for any other issue that you have encountered.  Thanks.
