### ISSUE TITLE
Package ROCm as a Flatpak runtime.

### ISSUE THREAD

**Issue by RushingAlien** [ROCm/ROCm#1685]
Hello. I wonder if it is possible for ROCm to be packaged as a flatpak runtime. Flatpak apps run itself inside a sandbox, using libraries decoupled from the main system/host. Blender 3.1 is looking ot have HIP support, but it will be unachievable on the Flatpak version on Flathub without ROCm being available as a flatpak runtime. Thanks

**Comment by ROCmSupport** [comment]
Hi @RushingAlien 
Thanks for reaching out.
I will talk to Product team and will update asap.
Thank you.

**Comment by nanonyme** [comment]
Note specifically what would be desired most likely here is distribution as a runtime extension. (GL extension's are used for all display driver purposes confusingly including Vulkan, OpenCL etc) Then this can be combined with existing runtimes and apps.

**Comment by ROCmSupport** [comment]
Hi @RushingAlien 
We do not have plans to create complete ROCm as a flatpak runtime, which is not our strategy,
But cases like Blender can be handled in a different way, like: Corresponding libraries/runtime to be part of the Blender install process or when it is installed, it should pull the appropriate driver and shared libraries.
I am still not sure that whether this comes under ROCm or not, still gathering more points.

**Comment by erkinalp** [comment]
Containerised packages like snap and flatpak do not work well with quick development cycles. They are catered more towards end users.

**Comment by nanonyme** [comment]
While your claim has nothing to do with the request to provide ROCm for flatpak blender, that is also not really true as a blanket statement. There are various ways to quick rebuild with flatpak-builder including utilisation of ccache. If anything, flatpak normally makes quick development cycles easier through ensuring you have consistent SDK to develop against and development results in binaries that are guaranteed to work in target platform. This implies less time wasted in QA. In the special case of ROCm this does not help much since ROCm is expected to be consumed widely outside flatpak as well.

**Comment by RushingAlien** [comment]
Hello there! I have an attempt to package some rocm stuff as flatpak, namely rocm-cmake and rocm-llvm, however, I'm pretty new to this thing and have been struggling. Help will be appreciated.

**Comment by RushingAlien** [comment]
ok, compiling took hours, anyways, here:
```
collect2: fatal error: ld terminated with signal 9 [Killed]
compilation terminated.
[3990/4545] Linking CXX shared library lib/libclang-cpp.so.14git
ninja: build stopped: subcommand failed.
Error: module rocm-llvm: Proses anak keluar dengan kode 1
```

**Comment by xuhuisheng** [comment]
@RushingAlien 
Here is my building scripts: <https://github.com/xuhuisheng/rocm-build.git>
The scripts based on the ROCm-5.2.3 and ubuntu-20.04.

**Comment by RushingAlien** [comment]
```
[3983/4545] Linking CXX executable bin/clang-repl
FAILED: bin/clang-repl 
```
I think this is quite important

**Comment by orowith2os** [comment]
I'm continuing work, and attempting to contact someone at AMD to help with packaging it here: https://github.com/orowith2os/rocm-flatpak

**Comment by saadrahim** [comment]
Hi @orowith2os ,
Appreciate your work on enabling flatpak for ROCm. Is there something specific in terms of help that you looking for?

**Comment by orowith2os** [comment]
I'd appreciate docs on:

- What order to build everything in
- what options to build everything with (in a very minimal config)
- and a decent build server so it doesn't take an hour to build LLVM alone

**Comment by saadrahim** [comment]
I am starting to see a few parallel efforts to enable flatpak. See #1897 . Would it help to provide a central repository for all the efforts? It would still be community driven but work need not be duplicated?

**Comment by orowith2os** [comment]
Some repository maintained under the ROCm banner would be nice, ideally my repository would be the base for it, since that's where the effort is right now.

After it's ready for public use, it should be submitted to Flathub unless they're willing to allow it to be managed externally.

There's one more attempt that made it a bit farther than I did, but that's using buildstream, and I prefer flatpak-builder.

**Comment by user82622** [comment]
Anyone got this to work?

**Comment by pobthebuilder** [comment]
> Anyone got this to work?

yes; some time ago here.
https://github.com/pobthebuilder/rocm-flatpak

I just pushed an update to Freedesktop SDK 23.08 and Buildstream2.

**Comment by RushingAlien** [comment]
Is this with HIP or only OpenCL?

**Comment by abhimeda** [comment]
@RushingAlien  Hi, could we close this ticket?

**Comment by RushingAlien** [comment]
Hi, no, let's not close this as it's not full rocm, as  it seems to be opencl only with missing HIP support.

**Comment by pobthebuilder** [comment]
i am just spinning some updates to my rocm-flatpak package. i can look to add HIP support if it's useful.

**Comment by pobthebuilder** [comment]
i moved rocm-flatpak forward to 5.7.1 and added HIP and hipcc. i don't use hip, but i tested it like the link you mentioned:
https://nhaehnle.blogspot.com/2024/02/building-hip-environment-from-scratch.html

using HelloWorld.cpp linked there:
https://raw.githubusercontent.com/ROCm/HIP-Examples/master/HIP-Examples-Applications/HelloWorld/HelloWorld.cpp

/usr/lib/x86_64-linux-gnu/GL/ROCm/bin/clang \
        -x hip \
        --offload-arch=gfx1100 \
        --rocm-path=/usr/lib/x86_64-linux-gnu/GL/ROCm \
        -L/usr/lib/x86_64-linux-gnu/GL/default/lib \
        -L/usr/lib/x86_64-linux-gnu/GL/ROCm/lib \
        -rpath /usr/lib/x86_64-linux-gnu/GL/ROCm/lib \
        -rpath /usr/lib/x86_64-linux-gnu/GL/default/lib \
        -lstdc++ \
        -lhsa-runtime64 \
        -lamdhip64 \
        HelloWorld.cpp 

patches welcome.

**Comment by sohaibnd** [comment]
Hi @RushingAlien, as mentioned before, there are no plans to officially package ROCm as a flatpak so I'm going close this ticket but feel free to continue discussing progress on your own flatpaks for ROCm here.
