### ISSUE TITLE
source code of rocm-core 

### ISSUE THREAD

**Issue by xlindo** [ROCm/ROCm#1705]
Hello, 

I would like to compile ROCm totally from source code on RISC-V, but I can not find all the source codes, e.g. **rocm-core**. I just found https://repo.radeon.com/rocm/apt/4.5.2/pool/main/r/rocm-core/ for amd64 as `.deb`, apparently it can not work.

Can anyone help me?

It will also be great if anyone can give me the relative works on ROCm for RISC-V.

Thanks.

**Comment by xuhuisheng** [comment]
There is only a rocm-version.h in the rocm-core.
<https://github.com/xuhuisheng/rocm-build/blob/master/meta/rocm-core_5.0.0.50000-49_amd64/include/rocm/rocm_version.h>

**Comment by xlindo** [comment]
> There is only a rocm-version.h in the rocm-core. https://github.com/xuhuisheng/rocm-build/blob/master/meta/rocm-core_5.0.0.50000-49_amd64/include/rocm/rocm_version.h

Thanks for your reply.

Your repo is de facto guide to me. 

Have you ever thought of a compilation for ROCm on an unsupported GPU architecture? Or can you give me some tips for the **key source code components** related to heterogeneous architecture?

**Comment by xuhuisheng** [comment]
@xlindo 
Yes, I use my building scripts to support my RX580 - aka. gfx803 with latest ROCm-5.0.2.
<https://github.com/xuhuisheng/rocm-gfx803>

The mininium components should be ends with MIOpen, they are required by tensorflow and pytorch.

**Comment by xlindo** [comment]
> @xlindo Yes, I use my building scripts to support my RX580 - aka. gfx803 with latest ROCm-5.0.2. https://github.com/xuhuisheng/rocm-gfx803
> 
> The mininium components should be ends with MIOpen, they are required by tensorflow and pytorch.

So it means once I compiled MIOpen successfully on my platform, the upper framework will work well?

How about ROCm runtime, which components are necessary and hardware dependent?

🤣

**Comment by xuhuisheng** [comment]
@xlindo 
Yes, you need 00.rocm-core to 35.miopen, all of them need for tensorflow or pytorch to build and run.

There are three steps:

* when you properly build HIP, you can run some hip samples, like square, that make you using GPU to run some real samples.
* when you properly build miopen, you can use miopen to run some plan, something like cnn
* when you properly build tensorflow/pytorch, you can use python.

Bascly this is my path.

**Comment by xlindo** [comment]
> @xlindo Yes, you need 00.rocm-core to 35.miopen, all of them need for tensorflow or pytorch to build and run.
> 
> There are three steps:
> 
> * when you properly build HIP, you can run some hip samples, like square, that make you using GPU to run some real samples.
> * when you properly build miopen, you can use miopen to run some plan, something like cnn
> * when you properly build tensorflow/pytorch, you can use python.
> 
> Bascly this is my path.

Great! Thanks a lot.

I will try it now.

**Comment by ROCmSupport** [comment]
Hi @xlindo 
Hope you got the suggestions/inputs. Please let know if you need anything more, request to close this ticket if you do not need anything more.
Thank you.

**Comment by xlindo** [comment]
@ROCmSupport 

Please close it, thx

**Comment by ROCmSupport** [comment]
Thanks @xlindo 
I am closing this

**Comment by tpkessler** [comment]
Hi, Arch Linux package maintainer here! Any progress on the source code for rocm-core @ROCmSupport? It's required to build pytorch with ROCm backend.
