### ISSUE TITLE
Navi 1 w5700 w5500 Radeon Pro v520 ROCm support in 5.x series  

### ISSUE THREAD

**Issue by FCLC** [ROCm/ROCm#1706]
Following up on #1617 https://github.com/RadeonOpenCompute/ROCm/issues/1595 , https://github.com/RadeonOpenCompute/ROCm/issues/1592 https://github.com/RadeonOpenCompute/ROCm/issues/1547 https://github.com/RadeonOpenCompute/ROCm/issues/1544 https://github.com/RadeonOpenCompute/ROCm/issues/1539
We still haven't received an official update other than "soon" for support of:
W5700 (Navi 10)
W5500 (Navi 14)
Radeon Pro v520 (Navi 12) 
Workstation GPU's in ROCm. 

Originally the timeline expectation for support was h1 2021, then q3 2021, then q4 2022 and finally q1 2022. 

The Navi 10 gpu has been in market since July 7 2019, nearly 3 years ago now. 

When can we expect a real timeline for official support of RDNA 1 GPUs in the ROCm stack? 

Can we expect to have real support before the third birthday of the card? For Navi 10 at the very least? gfx1010?

**Comment by icodeforyou-dot-net** [comment]
As someone owning a Navi 14 based card, I'd appreciate some information on that. I think it is just a sad that consumer grade cards are not more in focus, given that many people get into deep learning and related things precisely on such hardware.

**Comment by FCLC** [comment]
per https://github.com/RadeonOpenCompute/ROCm/issues/1735#issuecomment-1128314977 is it true that even pro cards are not going to be receiving ROCm official binaries?

**Comment by ppanchad-amd** [comment]
@FCLC Sorry for the lack of response.  Please refer to the following page on what GPU's currently supported: https://rocm.docs.amd.com/projects/install-on-linux/en/latest/reference/system-requirements.html
