### ISSUE TITLE
Compile without GPU?

### ISSUE THREAD

**Issue by xlindo** [ROCm/ROCm#1712]
I am working on the ported stuff for RISC-V, and now stucked in the compilation of ROCR-Runtime.

Could anyone please tell me that if it is necessary to compile ROCm with an existing supported GPU? If not, please tell me the files I need to modify, and then compile without a GPU.

Thanks!

**Comment by xlindo** [comment]
@xuhuisheng 
Can you help me?

**Comment by xlindo** [comment]
> @xlindo Actually, I didnot need gpu to run build scripts. So what error do you meet?

Thanks for your information.

I have also just compiled the project successfully with your scripts. 

But it may not work without a GPU.

So, if a GPU is necessary for programming or working with ROCm?

If not, how to modify these stuff, i.e. program and run with CPU only.

Thanks.

**Comment by xuhuisheng** [comment]
No, You cannot run ROCm without a GPU.
The aim of ROCm is speed up computing ML. There is no reason to run HIP on CPU.

But, if you are interest in hip-cpu, I think you can have a look at <https://github.com/ROCm-Developer-Tools/HIP-CPU>
I havn't test it before, not sure whether it can run properly.

**Comment by xlindo** [comment]
@xuhuisheng 

Thanks for your advice.

Yes, I am actually testing HIP-CPU.

But it seems that the upper components like **MIOpen is not possible running upon it solely**? Since the lower components for MIOpen must be ROCm, and ROCm relies on GPU.

**Comment by xlindo** [comment]
@xuhuisheng 

I am working on RISC-V accelerator.

I want to use the fundamentals of the whole ROCm for CPU(RISC-V), heterogenuous CPU(multiple RISC-V) or CPU+GPU. And then optimize the pipeline.

First of all, I want to compile ROCm runtime. But I am not sure if ROCm on RISC-V solely works or not.

**Comment by xlindo** [comment]
@xuhuisheng 

In short, could you please tell me how to add a new device to ROCm?

Thanks a lot!

**Comment by xuhuisheng** [comment]
It is hard to say.
ROCm use roct-thunk-interface to fetch device information for drm. for my background, I cannot understand the driver codes, althought it is opensource.
And there could be some closesource codes in firmware.

So I will believe, you can try to imple your aql. Emm~, there was a hsafoudation, which is founded by AMD, apple, and I think OpenCL is part of it. Last year, the website had been shutdown, So I cannot show you the pdf.

**Comment by xlindo** [comment]
@xuhuisheng 

Great information. Thanks.

I will try, even it looks like hard.

**Comment by xuhuisheng** [comment]
Here is hsafoundation website : <https://hsafoundation.com/>, wish it could help

**Comment by abhimeda** [comment]
@xlindo Hi, is your issue resolved in the latest ROCm? If so can we close this ticket?

**Comment by xlindo** [comment]
> @xlindo Hi, is your issue resolved in the latest ROCm? If so can we close this ticket?

thx, but sorry I cannot answer since I am not working on it now

**Comment by xlindo** [comment]
> thx, but sorry I cannot answer since I am not working on it now

thx, but sorry I cannot answer since I am not working on it now
