### ISSUE TITLE
Please enable two factor authentication in your github account

### ISSUE THREAD

**Issue by DeeptimayeeSethi** [ROCm/ROCm#1718]
@nitishjohn;@guansong;@arodrigx7;@amdgerritcr;@dsquaredx2;@asroy;@ascollard;@ROCmSupport

We are going to enforce two factor authentication in (https://github.com/RadeonOpenCompute/) organization on 7th April , 2022 . Since we identified you as outside collaborator for this organization, you need to enable two factor authentication in your github account else you shall be removed from the organization after the enforcement. Please skip if already done.
To set up two factor authentication, please go through the steps in below link:

https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/configuring-two-factor-authentication

Please reach out to "Deeptimayee.Sethi@amd.com " for queries

**Comment by ROCmSupport** [comment]
Thanks Deeptimayee. I have sent you an email regarding this.

**Comment by nartmada** [comment]
Closing this ticket as info is stale.  Deeptimayee is no longer an AMD employee.  Thanks.
