### ISSUE TITLE
Cooperative Group is causing error on MI-250

### ISSUE THREAD

**Issue by JieyangChen7** [ROCm/ROCm#1729]
We are working on porting the ZFP lossy compressor onto AMD GPUs using HIP. Part of the implementation relies on the Cooperative Group (CG). The CG kernels run correctly without error on MI-100 GPU, but it is reporting `HSA_STATUS_ERROR_MEMORY_FAULT: Agent attempted to access an inaccessible address.` error on MI-250 GPU. This was tested with both ROCM 4.5.0 and 5.1.0.

Here is how to reproduce the issue:
First, build ZFP with HIP
```
mkdir -p zfp
zfp_src=./zfp/src
zfp_build=./zfp/build
git clone -b feature/hip-support https://github.com/JieyangChen7/zfp.git ${zfp_src}
cmake -S ${zfp_src} -B ${zfp_build} \
-DZFP_WITH_HIP=ON \
-DZFP_WITH_OPENMP=OFF \
-DCMAKE_HIP_ARCHITECTURES="gfx90a" \
-DCMAKE_C_COMPILER=amdclang \
-DCMAKE_CXX_COMPILER=amdclang++ \
-DZFP_HIP_STREAM_MEMSET=ON \
-DZFP_HIP_HOST_REGISTER=OFF
cmake --build ${zfp_build} -j
```

Then run
```
./zfp/build-crusher/bin/testexec
```

On MI-100, all tests can pass without error. On MI-250, we get the following error message:

```
Queue at 0x7f4e03654000 inactivated due to async error:
	HSA_STATUS_ERROR_MEMORY_FAULT: Agent attempted to access an inaccessible address.
Aborted
```

**Comment by nartmada** [comment]
Hi @JieyangChen7, please close the ticket if the issue has been fixed.  Thanks.
