### ISSUE TITLE
Does ROCm support MPS?

### ISSUE THREAD

**Issue by yulingao** [ROCm/ROCm#1734]
MPS takes work (e.g. CUDA kernel launches) that is issued from separate processes, and runs them on the device as if they emanated from a single process. As if they are running in a single context. 

I want 2 processes(parent and son process) to share a context. Can ROCm or a AMD GPU have this MPS-like feature?

**Comment by ipe-zhangyz** [comment]
https://github.com/RadeonOpenCompute/ROCm-docker/issues/62

**Comment by abhimeda** [comment]
@yulingao  Hi, is your issue resolved on the latest ROCm? If so can we close this ticket?

**Comment by yulingao** [comment]
Yes, please close it. I've been focusing on other research areas lately, and I might be able to address this when I revisit it in the future.

> @yulingao Hi, is your issue resolved on the latest ROCm? If so can we close this ticket?
