### ISSUE TITLE
Adding CentOS Stream 8/9 support

### ISSUE THREAD

**Issue by ghost** [ROCm/ROCm#1739]
Currently amdgpu-install rpm failed to detect the version of CentOS Stream series as CentOS Stream versioning only use one number (8 or 9) which differs from RHEL's dual number.
As CentOS Stream has different updating model than RHEL it may be tricky to maintain upstream with amdgpu-dkms but rocm repo seems to work fine.
Please add support for CentOS Stream.

**Comment by m1nicrusher** [comment]
It seems like currently there's still no RHEL 9 support? #1646
