### ISSUE TITLE
HIP Programming Guide Math - missing function

### ISSUE THREAD

**Issue by r-abishek** [ROCm/ROCm#1751]
The HIP math API documentation page shows __frcp_rd/__frcp_ru/__frcp_rz/__frcp_rn as valid functions here: https://rocmdocs.amd.com/en/latest/ROCm_API_References/HIP-MATH.html#frcp-rd

But these functions aren't listed under the math section of: https://github.com/RadeonOpenCompute/ROCm/blob/rocm-4.5.2/AMD_HIP_Programming_Guide.pdf

**Comment by Rmalavally** [comment]
Thank you for reaching out. Please refer to https://docs.amd.com for the latest HIP API documentation. 

ROCm Documentation Team

**Comment by nartmada** [comment]
Hi @r-abishek, please check latest ROCm Documentation and ROCm 6.0.0 to see if your query has been resolved.  If resolved, please close the ticket.  Thanks.
