### ISSUE TITLE
which CPU to choose?

### ISSUE THREAD

**Issue by GuiSilvaPA** [ROCm/ROCm#1754]
I currently own an RX 570 and am replacing the rest of my computer parts to be compatible with DDR5 Ram Memory. For that, I also want to change my CPU. Any suggestions for choosing a CPU that supports ROCm and DDR5.  So that I can use eg PyTorch?

**Comment by Bengt** [comment]
The only discrete GPU to be officially supported is the 6800W. Therefore, the RX 6800 is the closest consumer GPU to official support as it has the same chip / die. I would expect enterprise-grade levels of support for it. However, that may mean something else to you and me than to AMD. So please still be wary of that. Also, once available support has been dropped for still-selling hardware (gfx803) before. So also be careful with software updates and check for eventual regressions / dropped support. Finally, make sure that you use a supported operating system in a supported version. Specifically, Ubuntu is currently only supported in the second most-recent LTS version.

DDR5 or 4 should not be relevant to ROCm.

**Comment by nartmada** [comment]
Hi @GuiSilvaPA, please close the ticket if your query has been resolved.  Thanks.

**Comment by nartmada** [comment]
Hi @GuiSilvaPA, I am closing the ticket now.  Thanks @Bengt for your feedback.  Please re-open the ticket if your query is still not resolved.  Thanks.
