### ISSUE TITLE
roc-obj-extract consumes stdin even when arguments are specified.

### ISSUE THREAD

**Issue by bigtrak** [ROCm/ROCm#1755]
roc-obj-extract consumes stdin due to a coding error.    While it works interactively, if you 
script roc-object-extract, it  will try consuming stdin, and be confused by the input.

The fix to this is to check for argv having arguments, and NOT push stdin before argv in 
this case.     This is the patch I used to not read stdin when arguments are present after 
option parsing.   If you pipe roc-obj-ls to the modified roc-obj-extract with a  awk '{print $3;}' 
to select the URI, it works in that mode as well.

[roc-obj-extract.patch.txt](https://github.com/RadeonOpenCompute/ROCm/files/8922431/roc-obj-extract.patch.txt)

**Comment by nartmada** [comment]
Hi @bigtrak, thanks for your input.  Please close the ticket if no further action is needed.  Thanks.

**Comment by nartmada** [comment]
Also please check latest ROCm 6.0 to see if your issue has been fixed.  Thanks.

**Comment by nartmada** [comment]
Closing the ticket.  @bigtrak, please re-open if the issue still exists with latest ROCm.  Thanks.
