### ISSUE TITLE
Unreliable amdgpu driver

### ISSUE THREAD

**Issue by ye-luo** [ROCm/ROCm#1757]
Using amgpu paired with ROCm 5.1 release.
When failure happens, amdgpu crash.
OS ubuntu 18.04 5.4 HWE kernel. Radeon Pro W6800 GPU.
[dmesg.out.gz](https://github.com/RadeonOpenCompute/ROCm/files/8941164/dmesg.out.gz)

**Comment by xfyucg** [comment]
You can send this issue to amd-gfx@lists.freedesktop.org
1, Describe how to reproduce the issue.
2, Attach full dmesg.

**Comment by nartmada** [comment]
Hi @ye-luo, please check latest ROCm Documentation and ROCm 6.0.0 to see if your issue has been resolved.  If resolved, please close the ticket.  Thanks.
