### ISSUE TITLE
HIP as a CMake language issues

### ISSUE THREAD

**Issue by ye-luo** [ROCm/ROCm#1766]
hip-lang-config.cmake is still problematic in ROCm 5.2. I made bug report and fixes but didn't get feedback.
Initial issue https://github.com/ROCm-Developer-Tools/HIP/issues/2433
Latest fix https://github.com/ROCm-Developer-Tools/HIP/pull/2776

**Comment by nartmada** [comment]
Hi @ye-luo, please check latest ROCm Documentation and ROCm 6.0.0 to see if your query has been resolved.  If resolved, please close the ticket.  Thanks.
