### ISSUE TITLE
Drop Python 2 Dependencies

### ISSUE THREAD

**Issue by Bengt** [ROCm/ROCm#1767]
Currently, various components of ROCm rely on Python 2 as a dependency. This is problematic, because Python 2 is discontinued and Linux distributions tend to no longer include it in the repositories of their current OS releases. ROCm should therefore work towards dropping Python 2 dependencies in all its components.

**Comment by Bengt** [comment]
Idea for this issue: https://github.com/RadeonOpenCompute/ROCm/issues/1761#issuecomment-1178804147

**Comment by saadrahim** [comment]
Is there a list of ROCm components that use python2? That will be helpful but is not required for me to raise this issue internally.

**Comment by Bengt** [comment]
Hi, @saadrahim! I do not have a full list, but one approach would be to change all Shebangs to Python 3 and see what breaks. There are quite a few (115 at the time of writing) in this organization alone:

https://github.com/search?q=org%3ARadeonOpenCompute+%21%2Fusr%2Fbin%2Fenv+python&type=code

**Comment by ppanchad-amd** [comment]
Internal ticket is created to fix this issue. Thanks!

**Comment by jamesxu2** [comment]
Hi there, as of ROCm 6.1.2, I don't see that ROCm uses Python2 as a dependency. I'm able to install ROCm using the [amdgpu-installer](https://rocm.docs.amd.com/projects/install-on-linux/en/develop/install/amdgpu-install.html#ubuntu) on Ubuntu 22.04, and compile and run HIP applications without having python2 installed (check using ``` apt list --installed | grep python2```). 

Also, there is internal awareness about the discontinuation of Python 2 and an ongoing effort to purge it. Thanks for highlighting this issue.
