### ISSUE TITLE
ROCm 5.1.3 on Raven

### ISSUE THREAD

**Issue by FireBurn** [ROCm/ROCm#1774]
Hi

I had issues running ROCm on my Raven machine due to these two asserts:

https://github.com/RadeonOpenCompute/ROCR-Runtime/blame/fdd643ae1bb62ea68919bb1d898a7d0eb1d0aaf4/src/core/runtime/amd_gpu_agent.cpp#L858

https://github.com/ROCm-Developer-Tools/ROCclr/blame/rocm-5.1.3/device/rocm/rocdevice.cpp#L1125

I removed them, which allowed luxmark-3 (https://github.com/LuxCoreRender/LuxMark/releases/download/luxmark_v3.1/luxmark-linux64-v3.1.tar.bz2) to run, as long as fast-math was disabled (which is a known issue)

This rendered everything but then failed right at the end with:

```
[ 2054.973044] [drm] Fence fallback timer expired on ring gfx
[ 2205.230026] amdgpu: qcm fence wait loop timeout expired
[ 2205.230029] amdgpu: The cp might be in an unrecoverable state due to an unsuccessful queues preemption
[ 2205.230046] amdgpu: Pasid 0x8007 destroy queue 1 failed, ret -62
[ 2205.230068] amdgpu 0000:08:00.0: amdgpu: GPU reset begin!
[ 2205.230078] amdgpu: Failed to suspend process 0x8007
[ 2205.236051] ------------[ cut here ]------------
[ 2205.236055] refcount_t: decrement hit 0; leaking memory.
[ 2205.236063] WARNING: CPU: 2 PID: 138 at lib/refcount.c:31 0xffffffff81454b1e
[ 2205.236067] Modules linked in:
[ 2205.236070] CPU: 2 PID: 138 Comm: kworker/u32:6 Not tainted 5.19.0-rc8-tip+ #2386
[ 2205.236074] Hardware name: ASUS System Product Name/ROG STRIX X470-I GAMING, BIOS 4603 09/13/2021
[ 2205.236075] Workqueue: amdgpu-reset-dev 0xffffffff81603dc0
[ 2205.236078] RIP: 0010:0xffffffff81454b1e
[ 2205.236080] Code: 01 01 e8 95 29 bf ff 0f 0b c3 80 3d a7 cb 5b 01 00 0f 85 76 ff ff ff 48 c7 c7 51 fc 63 82 c6 05 93 cb 5b 01 01 e8 72 29 bf ff <0f> 0b c3 48 c7 c7 fb bc 5a 82 c6 05 79 cb 5b 01 01 e8 5c 29 bf ff
[ 2205.236083] RSP: 0018:ffff888103287d18 EFLAGS: 00010282
[ 2205.236086] RAX: 000000000000002c RBX: ffff888124a6e000 RCX: 0000000000000001
[ 2205.236088] RDX: ffffffff81e46a41 RSI: ffffffff82644f9a RDI: 00000000ffffffff
[ 2205.236090] RBP: ffff888124a6e010 R08: 0000000000000000 R09: ffff88881fa00000
[ 2205.236092] R10: 00000000ffffffff R11: ffff888820500000 R12: ffff888102367c00
[ 2205.236093] R13: 0000000000000283 R14: ffff888124a6e000 R15: ffff888124a6e010
[ 2205.236095] FS:  0000000000000000(0000) GS:ffff888820c80000(0000) knlGS:0000000000000000
[ 2205.236098] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[ 2205.236100] CR2: 00007f154bff0000 CR3: 0000000131299000 CR4: 00000000003506a0
[ 2205.236101] Call Trace:
[ 2205.236103]  <TASK>
[ 2205.236104]  ? 0xffffffff81585467
[ 2205.236107]  ? 0xffffffff81585862
[ 2205.236108]  ? 0xffffffff81e46616
[ 2205.236109]  ? 0xffffffff81585ad1
[ 2205.236111]  ? 0xffffffff81e46558
[ 2205.236112]  ? 0xffffffff8175910f
[ 2205.236113]  ? 0xffffffff81602d2b
[ 2205.236115]  ? 0xffffffff81603dd1
[ 2205.236116]  ? 0xffffffff81066d8f
[ 2205.236117]  ? 0xffffffff810671ec
[ 2205.236118]  ? 0xffffffff81066f10
[ 2205.236119]  ? 0xffffffff8106bf18
[ 2205.236120]  ? 0xffffffff8106be40
[ 2205.236122]  ? 0xffffffff810005cf
[ 2205.236123]  </TASK>
[ 2205.236124] ---[ end trace 0000000000000000 ]---
```

**Comment by nartmada** [comment]
Hi @FireBurn, please check latest ROCm 6.0.0 to see if your issue has been resolved.  If resolved, please close the ticket.  Thanks.

**Comment by nartmada** [comment]
Closing this ticket as there is no response from ticket reporter.  @FireBurn, please re-open this ticket if the issue still exists in ROCm 6.0.0.  Thanks.

**Comment by FireBurn** [comment]
fireburn@axion ~ $ rocminfo  --help
ROCk module is NOT loaded, possibly no GPU devices

[ebuild   R   #] dev-util/rocminfo-6.0.0:0/6.0::gentoo  0 KiB

**Comment by FireBurn** [comment]
fireburn@axion ~ $ dmesg | grep -i kfd
[    2.771408] kfd kfd: amdgpu: Allocated 3969056 bytes on gart
[    2.772215] kfd kfd: amdgpu: Total number of KFD nodes to be created: 1
[    2.775482] kfd kfd: amdgpu: added device 1002:73df
[    3.795668] kfd kfd: amdgpu: Allocated 3969056 bytes on gart
[    3.795677] kfd kfd: amdgpu: Total number of KFD nodes to be created: 1
[    3.796677] kfd kfd: amdgpu: added device 1002:1638

**Comment by kentrussell** [comment]
Can you attach a full dmesg for us to take a look at? The fact that KFD is able to add the device, but rocminfo says that it's not loaded, is a concern.

**Comment by FireBurn** [comment]
That issue was fixed by https://github.com/littlewu2508/rocminfo/commit/42c8f566f17d2ba62e756fd0161987933b26eaa1 I've applied that now and rocminfo and clinfo both give output

Running luxmark 3 on my Raven gives the following dmesg error over and over:

iommu ivhd0: AMD-Vi: Event logged [INVALID_DEVICE_REQUEST device=0000:09:00.0 pasid=0x08010 address=0x7f1f1c16e004 flags=0x0503]

[dmesg.txt](https://github.com/ROCm/ROCm/files/13814630/dmesg.txt)

**Comment by nartmada** [comment]
@FireBurn, do you still see this issue with ROCm 6.1.0?

**Comment by FireBurn** [comment]
It's not on Gentoo get, I'll be about building it from source

**Comment by harkgill-amd** [comment]
Hi @FireBurn, did you get a chance to check if the issue persists with ROCm 6.1 or 6.2? If you are able to reproduce the issue, please provide another dmesg output for us to investigate.

**Comment by FireBurn** [comment]
I no longer have a Raven system, it would have been nice to have full ROCm / OpenCL support in its lifetime

**Comment by harkgill-amd** [comment]
While it's not officially supported, issues such as this one can often be legitimate concerns and we appreciate your report. I will close this ticket out for now as there is no way to reproduce the issue.
