### ISSUE TITLE
The reasons of high fbar values in Profiler

### ISSUE THREAD

**Issue by vasslavich** [ROCm/ROCm#1783]
Hello, dear colleagues!
I have two kernels which implement the same algorithm, but the first kernel does its work in the LDS, and the second kernel distributes the data between the LDS and registers in half. The performance of the second kernel is ~2.5 times low as the first kernel. I've found that the **fbar** counter of the second kernel is more _higher_. 
Please, if anybody knows, how can I understand _the reasons_ for the higher value of **fbar**?
Thanks!

**Comment by ppanchad-amd** [comment]
@vasslavich Sorry for the lack of response.  Do you still need assistance with this ticket? Thanks

**Comment by vasslavich** [comment]
@ppanchad-amd, hi! No, thank you, it has already dismissed.
