### ISSUE TITLE
GUI crashes when running TensorFlow with ROCm 5.2.x

### ISSUE THREAD

**Issue by thesleort** [ROCm/ROCm#1793]
I want to perform training on my local computer using `tensorflow-rocm`, but currently it only works if I do it in a non-graphical view or stay at the login screen, while I SSH into the computer. This really defeats the purpose of training locally, as I then need my laptop to access and use TensorFlow on the desktop computer.

I suspect it might have something to do with video memory. When using `radeontop` it starts to consume all memory (shows it uses more than what is available)  when ever the smallest TensorFlow problem is started. This appears to be okay when in non-graphical mode, but using the GUI (Gnome 42) it freezes the GUI and crashes, and sends me back to the login screen (it logs me out). It also crashes the execution of the TensorFlow model/code, thus leaving me with nothing.

I have a Radeon VII installed with Ubuntu 22.04.1 LTS

[gui_dmesg.log](https://github.com/RadeonOpenCompute/ROCm/files/9386954/gui_dmesg.log)
[rocminfo.log](https://github.com/RadeonOpenCompute/ROCm/files/9386957/rocminfo.log)

Here is a simple example that fails to run in GUI mode, but runs without flaws and quickly in non-graphical mode.
[simple_example.zip](https://github.com/RadeonOpenCompute/ROCm/files/9386970/simple_example.zip)

**Comment by Rlhoste** [comment]
I have the same issue, did you find a solution?

**Comment by LucasSnatiago** [comment]
Same issue here.

**Comment by thesleort** [comment]
My temporary solution is/was to use my desktop as a home server when using TensorFlow. I start it up without a desktop/GUI. I then set up a Jupyter server that I can connect to from anywhere. This works incredibly well from my laptop, as I have the jupyter file locally, but all computation is performed on my desktop. This also means that I can work on my stuff from anywhere in the world, as I can always offload the computation with jupyter notebooks to the desktop-server at home.

**Comment by nartmada** [comment]
Hi @thesleort, please check latest ROCm Documentation and ROCm 6.0.0 to see if your query has been resolved.  If resolved, please close the ticket.  Thanks.

**Comment by nartmada** [comment]
Closing the ticket as there is a temporary solution.  @thesleort, please re-open if you still observe this issue with latest ROCm 6.0.2.  Thanks.
