### ISSUE TITLE
Is 5900HX iGPU is supported by ROCm now ?

### ISSUE THREAD

**Issue by timiil** [ROCm/ROCm#1799]
hi , as the title, i have brought a board which 5900 HX cpu,  i am looking to install an Ubuntu 20.04, and use ROCm to predict some PyTorch pretrainned mode (using TorchServe)

any idea ?

**Comment by xfyucg** [comment]
It is a gfx90c iGPU, not officially supported. But there is a hack, just run like this.

`
$ HSA_OVERRIDE_GFX_VERSION=9.0.0 python3
>>> import torch
>>> torch.cuda.is_available()
True
>>>
`

**Comment by timiil** [comment]
thanks a lot , i will make a try and post the result here , thanks again :)

**Comment by MatPoliquin** [comment]
@xfyucg Did it work?

**Comment by nartmada** [comment]
Hi @timiil, please check latest ROCm Documentation and ROCm 6.0.0 to see if your query has been resolved.  If resolved, please close the ticket.  Thanks.

**Comment by nartmada** [comment]
Hi @timiil, any luck with using xfyucg's work-around?  Thanks.

$ HSA_OVERRIDE_GFX_VERSION=9.0.0 python3
>>> import torch
>>> torch.cuda.is_available()
True
>>>

**Comment by nartmada** [comment]
Closing this ticket as no response from @timiil.  Please re-open if you are not able to work-around the issue.  Thanks.
