### ISSUE TITLE
About cl_amd_bus_addressable_memory seen in ROCM OpenCL

### ISSUE THREAD

**Issue by michaelwangat** [ROCm/ROCm#1801]
Just searching in the binary I see cl_amd_bus_addressable_memory extension in ROCM 5.1.4.
But when I check the OpenCL extensions,there is no cl_amd_bus_addressable_memory extension.
GPU:Radeon Pro W5500 （support DirectGMA）
System:Ubuntu 20.04.4 (5.13.0-19-generic kernel)
 
How can I enable cl_amd_bus_addressable_memory extension?And now is it supported in ROCM?

Any sugguestion would be appreciate. Thank you!

**Comment by nartmada** [comment]
Hi @michaelwangat, please check latest ROCm Documentation and ROCm 6.0.0 to see if your query has been resolved.  If resolved, please close the ticket.  Thanks.

**Comment by nartmada** [comment]
Closing the ticket as no response from @michaelwangat.  Please re-open if your query is not resolved in latest ROCm 6.0.2.  Thanks.
