### ISSUE TITLE
amdflang not workable because of broken package dependencies

### ISSUE THREAD

**Issue by bertwesarg** [ROCm/ROCm#1808]
when installing just the `rocm-llvm` Debian package for 5.2.3, the provided `amdflang` binary is not workable:

```console
$ amdflang -o conftest    conftest.f  -lz >&5
clang-14: error: unable to execute command: Executable "flang1" doesn't exist!
```

Because `flang1` is only provided in the (badly generic named) package `openmp-extras`:

```console
$ dpkg -S /opt/rocm-5.2.3/llvm/bin/amdflang 
rocm-llvm: /opt/rocm-5.2.3/llvm/bin/amdflang
$ dpkg -S /opt/rocm-5.2.3/llvm/bin/flang1
openmp-extras: /opt/rocm-5.2.3/llvm/bin/flang1
$ apt-cache depends openmp-extras
openmp-extras
  Depends: rocm-llvm
  Depends: rocm-device-libs
  Depends: rocm-core
```

**Comment by saadrahim** [comment]
Thank you for reporting the issue. @frepaul will be able to help resolve this issue.

**Comment by frepaul** [comment]
@bertwesarg  Once again thanks for reporting.
I hope you are able to continue with the usage once openmp-extras is installed.

Discussing internally on how to correct this issue by packaging flang related files in one and same package.

**Comment by bertwesarg** [comment]
It would be great, if the [ROCm docker images](https://github.com/RadeonOpenCompute/ROCm-docker/tree/master/dev) already install the `rocm-llvm` and `openmp-extras` packages.

**Comment by bertwesarg** [comment]
…and the while you are at it, `hip-runtime-amd` package would be great too.

**Comment by bertwesarg** [comment]
nevermind my last two comments, installing `python-is-python3` triggered the removal of these packages

**Comment by MathiasMagnus** [comment]
This issue was reported in 2022 September. I ran into it on 2023 August. I'd have thought that installing a defunct toolchain was something that would be prioritized higher. I understand that `rocm-terminal` and similar docker images install `openmp-extras`, but it's still a major bug for a package to install an executable that practically can't compile an empty main function.

**Comment by harkgill-amd** [comment]
Hi @bertwesarg, this issue was resolved in an earlier release of ROCm. If you are still seeing issues with `amdflang`, please open a new issue. Thanks!
