### ISSUE TITLE
Why does `flang` predefine `__PGLLVM__`?

### ISSUE THREAD

**Issue by bertwesarg** [ROCm/ROCm#1811]
This was pre-defined for the "classic" flang implementation. The new `flang` (based on `f18`, i.e., upstream) does not define it anymore.

**Comment by bertwesarg** [comment]
https://github.com/RadeonOpenCompute/llvm-project/blob/57b3d44fd613446a5ec0a535794715872057b4dc/clang/lib/Driver/ToolChains/AMDFlang.cpp#L711

**Comment by nartmada** [comment]
Hi @bertwesarg, please check latest ROCm Documentation and ROCm 6.0.0 to see if your query has been resolved.  If resolved, please close the ticket.  Thanks.
