### ISSUE TITLE
roc-obj searches for llvm-tools in wrong place

### ISSUE THREAD

**Issue by Melirius** [ROCm/ROCm#1814]
Using roc-obj in current 5.2.3 gives an error
``` shell
~/$ /opt/rocm/bin/roc-obj -d test
error: could not find llvm-objdump in /opt/rocm-5.2.3/bin /opt/rocm-5.2.3/bin/../../llvm/bin or PATH
```

Inspection shows that the search path is wrong, it should be `/opt/rocm-5.2.3/bin/../llvm/bin`. Line 140
``` shell
  for dir in "$BASE_DIR" "${HIP_CLANG_PATH:-"$BASE_DIR/../../llvm/bin"}"; do
```
of `roc-obj` script should be fixed to 
``` shell
  for dir in "$BASE_DIR" "${HIP_CLANG_PATH:-"$BASE_DIR/../llvm/bin"}"; do
```
After such a change it runs smoothly.

**Comment by nartmada** [comment]
Hi @Melirius, please check latest ROCm6.0.2 to see if your issue still exists.  Please close the ticket if your issue has been fixed.  Thanks.

**Comment by nartmada** [comment]
Closing the ticket as no response from @Melirius.  Please re-open the ticket if your issue still exists with latest ROCm 6.0.2.  Thanks.
