### ISSUE TITLE
Status of non-amd64 arch support? (arm64, power9, etc.)

### ISSUE THREAD

**Issue by adapt-L** [ROCm/ROCm#1825]
I'm just trying to get OpenCL working on a power9 computer, I can't seem to find any information anywhere concerning what architectures are supported other than amd64. 

This guide seems to suggest that version 3.5 mostly worked on power9: https://systems.nic.uoregon.edu/internal-wiki/index.php?title=Rocm_on_power9

However building a somewhat-recent version like 5.1.3 fails, amongst other things including a message about  -DNO_WARN_X86_INRINSICS, so I'm guessing that somewhere along the way ROCm was changed to no longer be architecture-agnostic.

**Comment by ppanchad-amd** [comment]
@adapt-L Apologies for the lack of response.  Please check:  https://rocm.docs.amd.com/projects/install-on-linux/en/latest/reference/system-requirements.html
