### ISSUE TITLE
Required to be root to list devices

### ISSUE THREAD

**Issue by illwieckz** [ROCm/ROCm#1826]
Here I'm running ROCm 5.3 on Ubuntu 22.04

I can't list devices as user:

```
illwieckz@test:~$ clinfo --list
```
 
But I can do it as root:

```
illwieckz@test:~$ sudo -u root clinfo --list
Platform #0: AMD Accelerated Parallel Processing
 `-- Device #0: gfx1033
```

Note that this is a computer upgraded from an Ubuntu 20.04 that was the first install.

On another computer, I can list the devices without being root, but this other computer has more than a decade of Ubuntu upgrades so maybe it inherited some configuration from old Ubuntu versions:

```
illwieckz@other:~$ clinfo --list
Platform #0: AMD Accelerated Parallel Processing
 `-- Device #0: gfx701
```

Note: the user is already in the `video` group.

**Comment by illwieckz** [comment]
I had to add the user to the `render` group as well:

This is written to be only required for Ubuntu 20.04 on this page:
https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html

Anyway this page is obsolete it is said to be for ROCm 4.3 that predates Ubuntu 22.04 as far as I know.

**Comment by nartmada** [comment]
Hi @illwieckz, do we still need this ticket to be opened? Please close it if your concern has been addressed.  Thanks.

**Comment by nartmada** [comment]
Closing the ticket.  @illwieckz, please re-open if you still see this issue in latest ROCm 6.0.2.  Thanks.
