### ISSUE TITLE
roctracer headers do not follow include rules

### ISSUE THREAD

**Issue by bertwesarg** [ROCm/ROCm#1830]
Starting with [ROCm 5.2](https://docs.amd.com/bundle/ROCm-Release-Notes-v5.2/page/Deprecations_and_Warnings.html), the headers advertise to use `/opt/rocm-ver/include/` as the `-I`-flag and prefix the headers with the component `roctracer`. But the headers from roctracers are not usable this way:

An example when including `<roctracer/roctracer.h>:

```
/opt/rocm-5.2.3/include/roctracer/roctracer.h:45:10: error: 'ext/prof_protocol.h' file not found with <angled> include; use "quotes" instead
#include <ext/prof_protocol.h>  
         ^~~~~~~~~~~~~~~~~~~~~  
         "ext/prof_protocol.h"  
1 error generated.
```

Here is a script to check all headers:

```sh
find /opt/rocm-5.2.3/include/roctracer -maxdepth 1 -type f -printf '%f\n' |
    while read header
    do
        cat >includetest.cc <<EOF
#include <roctracer/$header>
EOF
        echo $header
        amdclang++ \
            -D__HIP_PLATFORM_AMD__ \
            -E includetest.cc \
            -o includetest.i \
            -I/opt/rocm-5.2.3/include 2>&1 | head -n 23
    done

**Comment by bertwesarg** [comment]
With ROCm 5.3.2 I'm down to an error in `<roctracer/roctracer_hsa.h>`:

```console
$ cat includetest.cc
#include <roctracer/roctracer_hsa.h>
$ amdclang++ -D__HIP_PLATFORM_AMD__ -E includetest.cc -o includetest.i -I/opt/rocm-5.3.2/include
In file included from includetest.cc:1:
/opt/rocm-5.3.2/include/roctracer/hsa_prof_str.h:1212:10: error: 'hsa_ostream_ops.h' file not found with <angled> include; use "quotes" instead
#include <hsa_ostream_ops.h>
         ^~~~~~~~~~~~~~~~~~~
         "hsa_ostream_ops.h"
1 error generated.
```

Will try 5.4 build 67 next.

**Comment by nunnikri** [comment]
Thanks @bertwesarg  for the report. 
We had corrected all the #includes in the roctracer in ROCm 5.3 release. But looks like  hsa_prof_str.h is a generated file and got missed the changes.  We will get the changes asp to 5.4 new builds

**Comment by nartmada** [comment]
Hi @bertwesarg, please close the ticket if the issue has been fixed.  Thank you.
