### ISSUE TITLE
Linux Ubuntu 20.04 Blender HIP Radeon RX 6800 XT Crash

### ISSUE THREAD

**Issue by raydeepx** [ROCm/ROCm#1840]
Blender Version
3.3+

When using HIP Gpu render in view port after few seconds all freeze and getting this error.
drm.amdgpu_cs_ioctl [amdgpu] *ERROR* failed to initialize parser - 125!
Only reboot or restart X may bring control

What is interesting i can render with HIP gpu without any problems, only using view port rendering (when using HIP) getting this error. Only cpu render works fine

I know about some kernel problems making this kind of crash but in my case the only program making this is Blender.That;s why i reporting this bug here. All Games, programs working stable without this error.

Radeon Pro renderer works fine also . The only problem is GPU render in view port with cycles.

similar problem described here:
https://developer.blender.org/T100353

**Comment by raydeepx** [comment]
https://gitlab.freedesktop.org/drm/amd/-/issues/2145

**Comment by nartmada** [comment]
Hi @raydeepx, please check latest ROCm 6.0.2 to see if your still has been fixed.  If fixed, please close the ticket.  Thanks.

**Comment by raydeepx** [comment]
Hi @nartmada, I've updated to 6.0.2 and it change nothing. Blender works around 20s and crash

**Comment by nartmada** [comment]
Thank you @raydeepx.  Which GPU and OS are you using?  I will create an internal ticket for investigation.

**Comment by raydeepx** [comment]
Operating System: KDE neon 5.27  (Ubuntu 22.04 jammy)
KDE Plasma Version: 5.27.10
KDE Frameworks Version: 5.114.0
Qt Version: 5.15.12
Kernel Version: 6.5.0-15-generic (64-bit)
Graphics Platform: Wayland
Processors: 32 × AMD Ryzen 9 5950X 16-Core Processor
Memory: 62.7 GiB of RAM
Graphics Processor: AMD Radeon RX 6800 XT

**Comment by nartmada** [comment]
@raydeepx, please re-test with ROCm 6.1.0.  Thanks.

**Comment by nartmada** [comment]
Closing the ticket.  @raydeepx, please re-open if you still see the issue with ROCm 6.1.0.  Thanks.
