### ISSUE TITLE
Will the 6800M GPU be supported by ROCm in the very near future?

### ISSUE THREAD

**Issue by greymogh** [ROCm/ROCm#1848]
Hello,

I just got an Advantage Edition laptop (full AMD) with an amd 6800M.

To my surprise I couldn't get hip and rocm to work.

Should this gpu be supported in the very near future? Otherwise very honestly I would have to return this machine which is useless to me and rather expensive.

Thank you in advance for your answers.

**Comment by saadrahim** [comment]
There are no announced plans to support 6800M for ROCm software packages. Some packages may work but no functionality is officially supported by AMD on that GPU.

**Comment by greymogh** [comment]
> @greymogh Does the `HSA_OVERRIDE_GFX_VERSION=10.3.0` hack, which is mentioned all over the place, work for you?

Thanks for your answer, It wasn't working first but I tried again after your post and it's working now, so thanks again. I think I just had to reboot...

**Comment by greymogh** [comment]
> There are no announced plans to support 6800M for ROCm software packages. Some packages may work but no functionality is officially supported by AMD on that GPU.

It's a bad new, but thanks for answering.

**Comment by nartmada** [comment]
Closing this ticket as @greymogh's question has been answered.  Thanks.
