### ISSUE TITLE
Ubuntu 22.10 ROCk module is NOT loaded, possibly no GPU devices

### ISSUE THREAD

**Issue by zhishixiang** [ROCm/ROCm#1850]
using instinct mi50 graphic card and 5.19.0-23-generic kernel, why rocminfo cant detect my card

**Comment by xuhuisheng** [comment]
Execute dmesg to see if there is any errors for kfd
```
dmesg } grep kfd
```

**Comment by zhishixiang** [comment]
> Execute dmesg to see if there is any errors for kfd
> 
> ```
> dmesg } grep kfd
> ```

no output

**Comment by xuhuisheng** [comment]
if there is no output about kfd or amdgpu, it is said the kernel cannot awared there is amdgpu.

**Comment by zhishixiang** [comment]
> 

so how to solve this problem? or you mean i should replace my kernel?

**Comment by pramenku** [comment]
you can see https://docs.amd.com/bundle/ROCm-Release-Notes-v5.3.2/page/About_This_Document.html about OS and it' kernel supported

**Comment by FatCache** [comment]
@pramenku 

I spent quite bit of time today and could not get to install it either on Ubuntu 22.10. I do find it odd that one version above 22.04 results in entire AMD ROCM to be unsupported! 

Say in production and one mistakenly upgraded the OS, a full refresh or downgrade will be required to get AMD ROCM to work

**Comment by rtccreator** [comment]
As i see the issue is outdated, it is still actual to notice that you should pay attention to kernel versions by running `dpkg --list | grep linux-image` and `dpkg --list | grep linux-headers` and comparing to the supported ones on the desired ROCm version. 
If ubuntu updated your kernel to a fresh, but unsupported one, consider downgrading. 
This also solves amdgpu-dkms compilation problems.

**Comment by yang2674** [comment]
![Screenshot 2023-10-28 020649](https://github.com/RadeonOpenCompute/ROCm/assets/94493230/37795480-9c79-4519-a2b9-835e383673b4)

Running into the "ROCk module is NOT loaded" error: Does this mean I have to downgrade my kernel?

**Comment by ppanchad-amd** [comment]
@zhishixiang @hmongdev Apologies for the lack of response.  Has your issue been resolved? Thanks!

**Comment by hmongdev** [comment]
I switched over to Nvidia. Thanks!

**Comment by cliff85** [comment]
> I had a similar issue with fresh install (7900XT, 22.04.4, 6.1.2, but that is not a reason). The origin of the problem was AMD proprietary driver not working due to a missing add password step in secureboot. So, either install it properly, or simply disable secure boot (changing secureboot OS to Other Os solved that in my BIOS). Then, everything worked. Please note that secure boot prohibits the use of unsigned drivers during boot, so disabling it has some security risks

Thanks that was super helpful. I spent a decent amount of time troubleshooting this before coming across your comment. Would be nice to have that on the troubleshooting page.
