### ISSUE TITLE
Support for libtinfo6?

### ISSUE THREAD

**Issue by m1nicrusher** [ROCm/ROCm#1851]
Hi everyone,

According to these links:
[https://bugzilla.redhat.com/show_bug.cgi?id=2129865#c1](https://bugzilla.redhat.com/show_bug.cgi?id=2129865#c1)
[https://src.fedoraproject.org/rpms/ncurses/c/e9317e9d5d60bbafccec65f4181e05425db1a13b?branch=rawhide](https://src.fedoraproject.org/rpms/ncurses/c/e9317e9d5d60bbafccec65f4181e05425db1a13b?branch=rawhide)

The support of ncurses ABI 5 is now obsolete on Fedora stream.
Any plan for upgrading this dependency? I mean, this deprecation will eventually be applied on RHEL isn't it?

Cheers
Stephen

**Comment by abhimeda** [comment]
@m1nicrusher Hi, is this resolved on the latest ROCm? If so can we close this ticket?

**Comment by nartmada** [comment]
Closing the ticket as no response from @m1nicrusher.  Please re-open if your concern still needs to be addressed in latest ROCm 6.0.2.  Thanks.
