### ISSUE TITLE
ROCm equivalent of GDS cuFile API

### ISSUE THREAD

**Issue by Mark1626** [ROCm/ROCm#1854]
Hi,

I understand that P2P communication is available in ROCm through ROCmRDMA

https://rocmdocs.amd.com/en/latest/Remote_Device_Programming/Remote-Device-Programming.html

Is there an equivalent of the cuFile API in the ROCm universe?

**Comment by abhimeda** [comment]
@Mark1626  Hi, were you able to figure this out? If so can we close this ticket?

**Comment by Mark1626** [comment]
Can you provide an answer to my question? Is there an equivalent of GDS cuFile API planned for ROCm?

**Comment by nartmada** [comment]
Thanks @kentrussell for the internal reply.  

@Mark1626, there is currently no cuFile equivalent in ROCm.

**Comment by brockhargreaves-amd** [comment]
@Mark1626 In case you haven't stumbled across it yet, hipFile is rocm's equivalent to cuFile. It landed in the public github last October and is early access preview/development: https://github.com/ROCm/hipFile
