### ISSUE TITLE
gfx1010(RX5000 series) dosen't support fp16 on linux

### ISSUE THREAD

**Issue by AiPs1717** [ROCm/ROCm#1857]
currently using gfx1010.
In the latest version of ROCm, 5.3.2, gfx1010 cannot use fp16 calculations.
An attempt was made to calculate fp16 in the pytorch environment, but it did not work.
Is there a way to force the fp16 calculation in the gfx1010 series?

**Comment by zjin-lcf** [comment]
Could you run the HIP programs without errors in https://github.com/CHIP-SPV/chip-spv/blob/main/samples/fp16 ?

**Comment by Yougoshatenshi** [comment]
> Could you run the HIP programs without errors in https://github.com/CHIP-SPV/chip-spv/blob/main/samples/fp16 ?
Ran all 3 cpp files in hipcc without any errors, but also have the problem that i cant use FP16 in pytorch with ROCm on my 5700XT.
In directml on windows its working fine too, although almost as slow as FP32 in pytorch under linux.

**Comment by abhimeda** [comment]
@AiPs1717  Hi, is this resolved on the latest ROCm? If so can we close this ticket?

**Comment by Zakhrov** [comment]
> @AiPs1717 Hi, is this resolved on the latest ROCm? If so can we close this ticket?

It has been partially, see [https://github.com/ROCm/ROCm/issues/2527#issuecomment-2074468176](https://github.com/ROCm/ROCm/issues/2527#issuecomment-2074468176)

**Comment by jamesxu2** [comment]
Hi @AiPs1717 , let's consolidate the discussion in the thread @Zakhrov mentioned. 

Also, thank you for your efforts in documenting your process in enabling PyTorch for the community @Zakhrov.
