### ISSUE TITLE
Dotted I errors in amdgpu-install if one has Turkish or Azerbaijani as the locale

### ISSUE THREAD

**Issue by erkinalp** [ROCm/ROCm#1873]
Steps to reproduce: 
Run `sudo amdgpu-install`

Expected:
Everything goes normally

Actual:
`/usr/bin/amdgpu-install: satır 436: ${USECASE_GRAPHİCS_PACKAGES[*]}: hatalı ikame`

**Comment by abhimeda** [comment]
@erkinalp Hi, is your issue resolved on the latest ROCm? If so can we close this ticket?

**Comment by nartmada** [comment]
Closing the ticket as no response from @erkinalp.  Please re-open the ticket if you still have issue with latest ROCm 6.0.2.  Thanks.

**Comment by erkinalp** [comment]
ROCm 6.x counterpart: https://github.com/ROCm/ROCm/issues/2888
