### ISSUE TITLE
AMD Radeon RX 6800 - HIPRTC_ERROR_COMPILATION

### ISSUE THREAD

**Issue by dakiba** [ROCm/ROCm#1889]
Hello,

I try to run a pytorch project with my RX 6800 (clinfo: gfx_1030)
/sys/module/amdgpu/version: 5.18.2.22.40

I installed ROCm 5.3 and pytorch Preview (Nightly).

But then I start the project I get after some time that errors and warnings:

```
MIOpen(HIP): Warning [SQLiteBase] Missing system database file: gfx1030_30.kdb Performance may degrade. Please follow instructions to install: https://github.com/ROCmSoftwarePlatform/MIOpen#installing-miopen-kernels-package
MIOpen(HIP): Error [Compile] 'hiprtcCompileProgram(prog.get(), c_options.size(), c_options.data())' naive_conv.cpp: HIPRTC_ERROR_COMPILATION (6)
MIOpen(HIP): Error [BuildHip] HIPRTC status = HIPRTC_ERROR_COMPILATION (6), source file: naive_conv.cpp
MIOpen(HIP): Warning [BuildHip] /tmp/comgr-112729/input/CompileSource:39:10: fatal error: 'limits' file not found
#include <limits> // std::numeric_limits
         ^~~~~~~~
1 error generated when compiling for gfx1030.
terminate called after throwing an instance of 'miopen::Exception'
  what():  /MIOpen/src/hipoc/hipoc_program.cpp:299: Code object build failed. Source: naive_conv.cpp
Aborted (core dumped)
```

**Comment by tlaguz** [comment]
I had this exact issue on Ubuntu 22.04 with TensorFlow. It seems ROCm libraries are compiled using clang which on Ubuntu 22.04 is missing default libraries. Installing `libstdc++-12-dev` package solved the issue.

**Comment by theepicflyer** [comment]
Can confirm this is an issue with PyTorch on 22.04 on my 6900XT too. Installed `libstdc++-12-dev` as per @tlaguz and it works great.

**Comment by ExposedCat** [comment]
Not sure if all of these is required, but on Fedora 38 with RX 6800 XT I also installed `make automake gcc gcc-c++ kernel-devel rocminfo` (and `libstdc++-devel` as mentioned before) to make it work

**Comment by lancediarmuid** [comment]
Oh thanks!~ I got the same problem on my RX6600XT. It works when I installed `libstdc++-12-dev`.

**Comment by 14790897** [comment]
thanks

**Comment by nartmada** [comment]
Closing the ticket as reported issue has been resolved.  Thanks.
