### ISSUE TITLE
RHEL 9.1 compat - rocm-llvm - nothing provides libtinfo.so.5, move to .6

### ISSUE THREAD

**Issue by dcsouthwick** [ROCm/ROCm#1892]
There are no rpms that provide the old version of `libtinfo.so.5` required by rocm-llvm, among others. Either build against the shared library (`libtinfo.so`), or move to `libtinfo.so.6`. ROCm is not compatible with RHEL8 or RHEL9 as distributed.

> libtinfo.so.5 version was last supplied in RHEL 7. ncurses-libs is a [Level 2 compatibility component](https://access.redhat.com/articles/rhel-abi-compatibility), meaning its compatibility was only guaranteed within RHEL 7.
> 
> RHEL 8 and RHEL 9 provide the next library version libtinfo.so.6

**Comment by ppanchad-amd** [comment]
@dcsouthwick Can you please test with latest ROCm 6.1.0? If resolved, please close ticket. Thanks!
