### ISSUE TITLE
how to install rocm5 in offline env?

### ISSUE THREAD

**Issue by wangzy0327** [ROCm/ROCm#1900]
how to install rocm5 in offline env?

**Comment by xuhuisheng** [comment]
you can make a mirror repo, sync all requeired dependencies, then copy this mirror to you local environments.

**Comment by nartmada** [comment]
Hi @wangzy0327, do you still need this ticket to be opened?  Please close the ticket if your issue has been addressed.  Thank you.

**Comment by nartmada** [comment]
Closing the ticket as no response from @wangzy0327.  Please re-open if you still need help with ROCm installation in offline environment.  Thanks.
