### ISSUE TITLE
free and total memory reported by rocm-smi and hipMemGetInfo

### ISSUE THREAD

**Issue by zjin-lcf** [ROCm/ROCm#1909]
The free value reported by rocm-smi is different from that reported by the HIP API. Thanks.

$ rocm-smi --showmeminfo vram

```
======================= ROCm System Management Interface =======================
============================= Memory Usage (Bytes) =============================
GPU[0]          : VRAM Total Memory (B): 4278190080
GPU[0]          : VRAM Total Used Memory (B): 108814336
================================================================================
============================= End of ROCm SMI Log ==============================
```

However, hipMemGetInfo(&free, &total) also returns 4278190080 for both

**Comment by nartmada** [comment]
Hi @zjin-lcf, please close the ticket if the issue has been fixed.  Thanks.

**Comment by zjin-lcf** [comment]
Can  you please point out any difference between "VRAM used memory in bytes" and (total - free) ?

**Comment by kentrussell** [comment]
There is never a point where there is zero used memory on a booted system. SMI reports memory from the kernel's memory manager via amdgpu+amdkfd (see (https://github.com/ROCm/ROCK-Kernel-Driver/blob/master/drivers/gpu/drm/amd/amdgpu/amdgpu_vram_mgr.c#L117) . There is a chance that they might not align perfectly if memory is being used at the time, but having 100% total memory available in HIP is inaccurate from a kernel perspective. It may mean something different to HIP however.
