### ISSUE TITLE
sudo: amdgpu-uninstall: command not found

### ISSUE THREAD

**Issue by Enferlain** [ROCm/ROCm#1914]
Trying to get rocm working for something ai related, I'm on ubuntu 22.10, ran these commands 

> sudo apt-get update
> wget https://repo.radeon.com/amdgpu-install/5.4.3/ubuntu/jammy/amdgpu-install_5.4.50403-1_all.deb 
> sudo apt-get install ./amdgpu-install_5.4.50403-1_all.deb

At the end it puts "download is performed unsandboxed as root as file"

But when I check it says I have it installed 

![image](https://user-images.githubusercontent.com/15861396/222723770-d106d964-38b9-4f07-86e4-869e46c9670e.png)

I'm trying to remove it for troubleshooting with "sudo amdgpu-uninstall --rocmrelease=5.4.3" but it says "sudo: amdgpu-uninstall: command not found"

Why is that?

**Comment by arch-user-france1** [comment]
Perhaps it's not in `PATH` which is the variable the shell interpreter checks for binary files to run. Could you please try to run the command without `sudo`?
Please also show us your `$PATH` variable: `echo $PATH`.

**Comment by alexschroeter** [comment]
I usually don't install like this so I cannot check but in another issue, someone mentioned that it is actually. https://github.com/RadeonOpenCompute/ROCm/issues/1908#issuecomment-1435957473

`sudo amdgpu-install --uninstall`

**Comment by Enferlain** [comment]
> Perhaps it's not in the `PATH` which is the variable the shell interpreter checks for binary files to run. Could you please try to run the command without `sudo`? Please also show us your `$PATH` variable: `echo $PATH`.
> 
> You could try searching for the command in the folder `/opt`.

![Screenshot from 2023-03-04 12-45-45](https://user-images.githubusercontent.com/15861396/222898432-47dd0bcc-ebe7-46d1-bafe-ccea175b5455.png)



> I usually don't install like this so I cannot check but in another issue, someone mentioned that it is actually. [#1908 (comment)](https://github.com/RadeonOpenCompute/ROCm/issues/1908#issuecomment-1435957473)
> 
> `sudo amdgpu-install --uninstall`

This one works, prompts me to remove the 15gb of stuff, thanks!

**Comment by saadrahim** [comment]
Reopening to ensure this is included in our documentation.

**Comment by saadrahim** [comment]
@MathiasMagnus  is this still valid, can you assign to someone to check?

**Comment by kentrussell** [comment]
Some of the release packages didn't include amdgpu-uninstall. The Packaging guys (@Mystro256 is on the other repos but not this one) can check if it got legacied or whatever. But "amdgpu-install --uninstall" will always be present.

**Comment by MathiasMagnus** [comment]
We [don't `wget` unsandboxed](https://rocm.docs.amd.com/projects/install-on-linux/en/latest/how-to/amdgpu-install.html#installation) anymore in the docs, neither do we document the use of the removed utility and use [`amdgpu-install --uninstall`](https://rocm.docs.amd.com/projects/install-on-linux/en/latest/how-to/amdgpu-install.html#uninstalling-rocm)

@Enferlain Do these address your concern?

**Comment by ppanchad-amd** [comment]
Internal ticket has been created to updated documentation. Thanks!

**Comment by harkgill-amd** [comment]
Documentation [here](https://rocm.docs.amd.com/projects/install-on-linux/en/latest/how-to/amdgpu-install.html#uninstalling-rocm) now points to the correct command "sudo amdgpu-install --uninstall".
