### ISSUE TITLE
MI250X (gfx90a) not available as cuda device on pytorch

### ISSUE THREAD

**Issue by nishshah0** [ROCm/ROCm#1916]
I have MI250X system
![image](https://user-images.githubusercontent.com/122632692/222849737-e039480b-3b6f-4e1b-8334-079d205eefab.png)
with rocm5.4 installed
![image](https://user-images.githubusercontent.com/122632692/222849933-d47b49d4-103d-4256-97ed-28c6b1dac4af.png)
I installed pytorch using following command
`pip3 install --pre torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/nightly/rocm**5.4**/`
notice 5.4 at the end. The installation completed successfully.

But when I use torch.cuda.is_available(), it return False
![image](https://user-images.githubusercontent.com/122632692/222850473-76f4c929-e15c-49bc-bd07-f2cfd6a2e5e6.png)

what am I missing?

**Comment by TechScribe-Deaf** [comment]
I have the same problem on my 7900 XTX as well.

**Comment by yanbosmu** [comment]
> I have MI250X system ![image](https://user-images.githubusercontent.com/122632692/222849737-e039480b-3b6f-4e1b-8334-079d205eefab.png) with rocm5.4 installed ![image](https://user-images.githubusercontent.com/122632692/222849933-d47b49d4-103d-4256-97ed-28c6b1dac4af.png) I installed pytorch using following command `pip3 install --pre torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/nightly/rocm**5.4**/` notice 5.4 at the end. The installation completed successfully.
> 
> But when I use torch.cuda.is_available(), it return False ![image](https://user-images.githubusercontent.com/122632692/222850473-76f4c929-e15c-49bc-bd07-f2cfd6a2e5e6.png)
> 
> what am I missing?

hello, bro!
I got a AMD MI250X GPU card recently. Obviously it was a part from HPE cray EX235a system.
But I got problem in using it now in ubuntu.
So, do you have drivers or BIOS that can make my card alive? It is writtern D65201-OB Rev13 on GPU.

**Comment by ppanchad-amd** [comment]
@nishshah0 Do you still need assistance with this issue? Thanks!

**Comment by harkgill-amd** [comment]
Hi @nishshah0, if you are still experiencing this issue after following the steps here, [Installing PyTorch on ROCm](https://rocm.docs.amd.com/projects/install-on-linux/en/latest/how-to/3rd-party/pytorch-install.html), please re-open this ticket. Thanks!

**Comment by unclemusclez** [comment]
Yes this problem still exists. I first noticed this with openwebui, i have two different AMD cards on two different Linux systems that are running two different version of PyTorch that would fine with diffusion. it seems to be local to Whisper.  

` torch.cuda.is_available()` is expected with ROCm

**Comment by unclemusclez** [comment]
always try `sudo usermod -a -G render,video $USER:$GROUP` for each user using the audio
