### ISSUE TITLE
Complete the supported GPU list

### ISSUE THREAD

**Issue by saadrahim** [ROCm/ROCm#2044]
https://github.com/RadeonOpenCompute/ROCm/blob/19c0ba11505cf504d42b2096713d761236202361/docs/release/gpu_os_support.md?plain=1#L27-L65
The current list is incomplete. Let's fill it out.

**Comment by seanzhang9999** [comment]
I have an iMac with Radeon pro 5700 XT, it seem it will never be supported on ROCm?
I think I should to buy the NVIDIA.......

**Comment by Henevy-HDR** [comment]
Add support for RDNA3?

**Comment by johnnynunez** [comment]
any news about mainstream cards support in the following releases? @saadrahim

**Comment by theCollectiv** [comment]
Is there a roadmap for customer gpu support?
In other words ...will rocm be a feature available for every amd graphic card? Or only for some kind of graphic card series (and other series will not be supported)?

**Comment by pbaykalov** [comment]
> Is there a roadmap for customer gpu support? In other words ...will rocm be a feature available for every amd graphic card? Or only for some kind of graphic card series (and other series will not be supported)?

https://twitter.com/LisaSu/status/1669848494637735936

**Comment by johnnynunez** [comment]
> > any news about mainstream cards support in the following releases? @saadrahim
> 
> I do not have any information that I can share . I will ensure that any future PR that addresses this issue is mentioned here.

Thanks, if AMD supports the mainstream cards, AMD will have a lot of university students and people at home trying to improve the library and also much more feedback than now. I just hope this is present in AMD.

**Comment by theCollectiv** [comment]
> > Is there a roadmap for customer gpu support? In other words ...will rocm be a feature available for every amd graphic card? Or only for some kind of graphic card series (and other series will not be supported)?
> 
> https://twitter.com/LisaSu/status/1669848494637735936

I don't know, whether being in the position of being 'rescued' by GeorgeHotz is bad or a good sign.
But it maybe draws public attention, and at least AMD is hopefully more focusing on it.

**Comment by radudiaconu0** [comment]
any update here?

**Comment by radudiaconu0** [comment]
when we will have RDNA 3 support? This is the 3rd release in a row when you don't add it. you basically deleted the commit thatg added it....

**Comment by saadrahim** [comment]
RDNA3 support is now available and the GPU support list is up to date now. Closing this issue. Please raise separate issues if further clarification is needed.
