### ISSUE TITLE
rocm-device-lib-path missing in building ROCm for Ubuntu 22.04 LTS on RISC-V 

### ISSUE THREAD

**Issue by luyanaa** [ROCm/ROCm#2051]
I've been working on building ROCm (target Radeon VII + HiFive Unmatched), with Ubuntu 22.04 LTS. I've successfully built rocm-llvm, rocm-cmake, roct-thunk-interface, rocm-device-libs, rocminfo, rocr-runtime, rocm-compilersupport and hip for RISC-V so far. 

However, when I start to build rocBLAS, rocFFT etc. I found that the hipcc fail to find the rocm-device-lib-path, where in this case, locate in /usr/lib/riscv64-linux-gnu/amdgcn/bitcode, And this stuck my building procedure. I have no idea where I can pass the --rocm-device-lib-path to hipcc in the compiling procedure. 

btw: Is AMD interested in RISC-V & ARM support for ROCm?

**Comment by luyanaa** [comment]
The ROCm RISC-V project statement: https://docs.google.com/presentation/d/1xl9hv_deK7bOOm5KRGZVa7CkRFfw2vOVNFSXS-WFpO0/edit#slide=id.g22d7b151e0f_14_0 (RISC-V Open Hour 2023-April-12)

**Comment by luyanaa** [comment]
fixed, seems that declare -x DEVICE_LIB_PATH="/opt/rocm/amdgcn/bitcode" works.

**Comment by nartmada** [comment]
Thanks @luyanaa.  Closing the ticket as the reported issue has been fixed.
