### ISSUE TITLE
It is weired that RDNA2 support windows while Vega not

### ISSUE THREAD

**Issue by xuhuisheng** [ROCm/ROCm#2053]
Please refer here: <https://github.com/RadeonOpenCompute/ROCm/blob/19c0ba11505cf504d42b2096713d761236202361/docs/release/gpu_os_support.md?plain=1#L59-L60>

It is said that using Radeon Pro Driver, RDNA2 likes RX6900xt and Rx6600  can support HIP sdk and runtime on windows, while Radeon VII is not.

As we know, the `amdhip64.dll` is installed by amdgpu driver, so the HIP sdk and runtime should avaiable for both vega10, vega20, cdna, rdna2.

The documents seems point out there is special support on RDNA2, not for other ISA.

**Comment by Roachomg** [comment]
GCN的时代结束了...(唉)
Said goodbye to GCN.(/sigh)

**Comment by saadrahim** [comment]
The list will be update when resolving #2044.
