### ISSUE TITLE
Support for Windows

### ISSUE THREAD

**Issue by MoonRide303** [ROCm/ROCm#2065]
Please add native support for Windows. I was recently evaluating which new GPU with more VRAM I could buy, but lack of support for Windows basically makes AMD cards unusable for me.

I want to be able PyTorch 2.0 with GPU acceleration on Windows, natively - and GPUs that doesn't allow me to do so are simply no-go:

![image](https://user-images.githubusercontent.com/130458190/233003633-e41059f4-7b65-455f-bcc2-1aed6afefd54.png)

**Comment by shen9175** [comment]
According to tom's hardware and videocardz, ROCm 5.6.0 Alpha document (internal) shows will support Windows for RDNA2 cards, stay tuned, it seems not far away from now.

**Comment by evshiron** [comment]
@radudiaconu0

ROCm 5.5.0 does not guarantee the inclusion of Windows support. Stay tuned.

**Comment by radudiaconu0** [comment]
I know that..i just hoped from many speculation that the release after 5.4.3 will have windows release. Manny commits to docs said that. So now I am disappointed. They removed windows docs from develop branch for no reason and explanation. I am disappointed right now

**Comment by jkddw** [comment]
ROCm 5.6.0 does not have Windows support.

**Comment by evshiron** [comment]
Thanks for the notice. It seems like ROCm 5.6.0 is available in https://repo.radeon.com/amdgpu-install/5.6/ now.

**Comment by radudiaconu0** [comment]
Yep and we waited like fools

**Comment by comminux** [comment]
https://projects.blender.org/blender/blender/pulls/110519

**Comment by johnnynunez** [comment]
Will there be miopen support for windows in 6.0.1?

**Comment by briansp2020** [comment]
https://rocm.docs.amd.com/projects/install-on-windows/en/latest/

So, it seems they support windows with 5.7. Still no ML libraries, I think...

**Comment by johnnynunez** [comment]
> https://rocm.docs.amd.com/projects/install-on-windows/en/latest/
> 
> So, it seems they support windows with 5.7. Still no ML libraries, I think...

The page was not updated but 6.1 it is supported

**Comment by ppanchad-amd** [comment]
Please check latest ROCm 6.1.1
https://rocm.docs.amd.com/projects/install-on-windows/en/latest/

**Comment by johnnynunez** [comment]
> Please check latest ROCm 6.1.1 https://rocm.docs.amd.com/projects/install-on-windows/en/latest/

links is to 5.7.1

**Comment by ppanchad-amd** [comment]
@johnnynunez Sorry about the confusion.  Current HIP SDK version available for windows is 5.7.1

**Comment by MoonRide303** [comment]
> Support available. Please check latest ROCm 6.1.1 https://rocm.docs.amd.com/projects/install-on-windows/en/latest/

It doesn't look like "support available" to me:

![image](https://github.com/user-attachments/assets/d5289c01-ca63-4087-8577-50332cbc4366)

**Comment by evshiron** [comment]
@MoonRide303 

Use ROCm in WSL if you have a compatible GPU:

* https://rocm.docs.amd.com/projects/radeon/en/latest/docs/compatibility/wsl/wsl_compatibility.html

I have been using it for two months and it works (imo better than in Linux), with some tricks.

**Comment by MoonRide303** [comment]
> @MoonRide303
> 
> Use ROCm in WSL if you have a compatible GPU:
> 
> * https://rocm.docs.amd.com/projects/radeon/en/latest/docs/compatibility/wsl/wsl_compatibility.html
> 
> I have been using it for two months and it works (imo better than in Linux), with some tricks.

WSL is a workaround, not a native Windows support.

**Comment by evshiron** [comment]
> WSL is a workaround, not a native Windows support.

Alright. In my opinion, choosing to support WSL is a smart decision. It (almost) perfectly integrates with the existing ROCm ecosystem on Linux and can already support many professional workflows. I'm quite satisfied with my two-month experience.
