### ISSUE TITLE
ROCm 5.4.3 libstdc++ dependency version too high

### ISSUE THREAD

**Issue by ye-luo** [ROCm/ROCm#2084]
On SLES 15 SP4, using ROCm 5.4.3 is so difficult compared to 5.4.0 due to extremely tight libstdc++ version requirement.
amdclang and hip libraries both requires at least gcc12 equivalent libstdc++.
When I use gcc 11 as the host compiler and hip runtime library.
```
/soft/compilers/gcc/11.1.0/x86_64-suse-linux/bin/g++ main.cpp /soft/compilers/rocm/rocm-5.4.3/lib/libamdhip64.so.5.4.50403
/usr/bin/ld: /soft/compilers/rocm/rocm-5.4.3/lib/libamd_comgr.so.2: undefined reference to `std::condition_variable::wait(std::unique_lock<std::mutex>&)@GLIBCXX_3.4.30'
collect2: error: ld returned 1 exit status
```
main.cpp
```
#include <memory_resource>
int main()
{}
```
Please minimize the dependency version.

PS: no issue with amdclang due to its using ld.lld as the linker instead of ld and probably no symbol checks.

**Comment by nartmada** [comment]
Hi @ye-luo, just checking to see if this ticket can be closed.  Thanks.

**Comment by ye-luo** [comment]
Clearly AMD doesn’t bother to do anything about it. Even just acknowledge their poor practice.

**Comment by ye-luo** [comment]
"Some of these tickets are old and stale" and who's fault is it?

Wouldn't it be better if one first apologizes for being almost a year late in following up the issue and also asking if there was anything one could do to resolve the issue and improve the process rather than trying to close up the ticket upon initial review?

Commenting on ROCm github is a "public relations" subject. I am not blaming you personally, however perhaps the AMD/ROCm management should improve the situation, maybe additional staff training is necessary?  Please do not pretend as if nothing happened.

When I opened the issue, I intended to bring up this topic to resolve this issue and to raise awareness from other ROCm users who may suffer from the same issue. While I understand that it was unlikely to change a released software, but perhaps AMD could potentially make another point release to correct the problem or simply acknowledge the issue and prevent it from happening in the future.

 I gave you guys the opportunities to make the adjustments but the response was very disappointing.

So yes, this issue has not been resolved for almost a year and an investigation should have been started long ago. While I appreciate that you are trying to go through an endless sea of tickets, I would hope this time it does not take a year to start an investigation or to get a prompt reply via an internal ticket. 

Thank you and have a nice day.

**Comment by nartmada** [comment]
@ye-luo, thank you for your comment and my apologies for the slow/lack of response in the past.  I have re-opened the ticket and will assign a developer to investigate.

**Comment by nartmada** [comment]
Hi @ye-luo, I have asked one of my developers to try to repro your issue and he cannot repro.

"I cannot reproduce this issue on SLES 15 SP4, using ROCm-6.0.2. No linking problem with code compiled using G++-11."

Please confirm if you still see the issue with ROCm 6.0.2.

Thanks.

**Comment by ye-luo** [comment]
```
/soft/compilers/gcc/11.1.0/x86_64-suse-linux/bin/g++ main.cpp /soft/compilers/rocm/rocm-6.0.0/lib/libamdhip64.so 
/usr/bin/ld: /soft/compilers/rocm/rocm-6.0.0/lib/libamd_comgr.so.2: undefined reference to `std::condition_variable::wait(std::unique_lock<std::mutex>&)@GLIBCXX_3.4.30'
```
Here is the verbose output
```
/soft/compilers/gcc/11.1.0/x86_64-suse-linux/bin/g++ main.cpp /soft/compilers/rocm/rocm-6.0.0/lib/libamdhip64.so -v
Using built-in specs.
COLLECT_GCC=/soft/compilers/gcc/11.1.0/x86_64-suse-linux/bin/g++
COLLECT_LTO_WRAPPER=/soft/compilers/gcc/11.1.0/x86_64-suse-linux/libexec/gcc/x86_64-pc-linux-gnu/11.1.0/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
Target: x86_64-pc-linux-gnu
Configured with: ../gcc/configure --enable-offload-targets=nvptx-none --with-cuda-driver-include=/soft/compilers/cuda/cuda-10.2.89/include --with-cuda-driver-lib=/soft/compilers/cuda/cuda-10.2.89/lib64 --disable-bootstrap --disable-multilib --enable-languages=c,c++,fortran,lto --prefix=/soft/compilers/gcc/11.1.0/x86_64-suse-linux
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.1.0 (GCC) 
COLLECT_GCC_OPTIONS='-v' '-shared-libgcc' '-mtune=generic' '-march=x86-64' '-dumpdir' 'a-'
 /soft/compilers/gcc/11.1.0/x86_64-suse-linux/libexec/gcc/x86_64-pc-linux-gnu/11.1.0/cc1plus -quiet -v -D_GNU_SOURCE main.cpp -quiet -dumpdir a- -dumpbase main.cpp -dumpbase-ext .cpp -mtune=generic -march=x86-64 -version -o /tmp/cc0cRtsm.s
GNU C++17 (GCC) version 11.1.0 (x86_64-pc-linux-gnu)
	compiled by GNU C version 7.5.0, GMP version 6.1.0, MPFR version 3.1.4, MPC version 1.0.3, isl version isl-0.18-GMP

GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
ignoring nonexistent directory "/soft/compilers/gcc/11.1.0/x86_64-suse-linux/lib/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../x86_64-pc-linux-gnu/include"
#include "..." search starts here:
#include <...> search starts here:
 /soft/packaging/spack-builds/linux-opensuse_leap15-x86_64/gcc-10.2.0/hdf5-1.10.7-uapcktd3szlmtouy63p4o3nofnsj5au6/include
 /soft/compilers/gcc/11.1.0/x86_64-suse-linux/lib/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0
 /soft/compilers/gcc/11.1.0/x86_64-suse-linux/lib/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/x86_64-pc-linux-gnu
 /soft/compilers/gcc/11.1.0/x86_64-suse-linux/lib/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/backward
 /soft/compilers/gcc/11.1.0/x86_64-suse-linux/lib/gcc/x86_64-pc-linux-gnu/11.1.0/include
 /usr/local/include
 /soft/compilers/gcc/11.1.0/x86_64-suse-linux/include
 /soft/compilers/gcc/11.1.0/x86_64-suse-linux/lib/gcc/x86_64-pc-linux-gnu/11.1.0/include-fixed
 /usr/include
End of search list.
GNU C++17 (GCC) version 11.1.0 (x86_64-pc-linux-gnu)
	compiled by GNU C version 7.5.0, GMP version 6.1.0, MPFR version 3.1.4, MPC version 1.0.3, isl version isl-0.18-GMP

GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
Compiler executable checksum: 11ef32bb4038e7f20437fdf41a0a3e37
COLLECT_GCC_OPTIONS='-v' '-shared-libgcc' '-mtune=generic' '-march=x86-64' '-dumpdir' 'a-'
 as -v --64 -o /tmp/ccORIsYj.o /tmp/cc0cRtsm.s
GNU assembler version 2.41.0 (x86_64-suse-linux) using BFD version (GNU Binutils; SUSE Linux Enterprise 15) 2.41.0.20230908-150100.7.46
COMPILER_PATH=/soft/compilers/gcc/11.1.0/x86_64-suse-linux/libexec/gcc/x86_64-pc-linux-gnu/11.1.0/:/soft/compilers/gcc/11.1.0/x86_64-suse-linux/libexec/gcc/x86_64-pc-linux-gnu/11.1.0/:/soft/compilers/gcc/11.1.0/x86_64-suse-linux/libexec/gcc/x86_64-pc-linux-gnu/:/soft/compilers/gcc/11.1.0/x86_64-suse-linux/lib/gcc/x86_64-pc-linux-gnu/11.1.0/:/soft/compilers/gcc/11.1.0/x86_64-suse-linux/lib/gcc/x86_64-pc-linux-gnu/
LIBRARY_PATH=/soft/compilers/gcc/11.1.0/x86_64-suse-linux/lib/gcc/x86_64-pc-linux-gnu/11.1.0/:/soft/compilers/gcc/11.1.0/x86_64-suse-linux/lib/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../lib64/:/lib/../lib64/:/usr/lib/../lib64/:/soft/packaging/spack-builds/linux-opensuse_leap15-x86_64/gcc-10.2.0/hdf5-1.10.7-uapcktd3szlmtouy63p4o3nofnsj5au6/lib/:/soft/compilers/gcc/11.1.0/x86_64-suse-linux/lib/gcc/x86_64-pc-linux-gnu/11.1.0/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-v' '-shared-libgcc' '-mtune=generic' '-march=x86-64' '-dumpdir' 'a.'
 /soft/compilers/gcc/11.1.0/x86_64-suse-linux/libexec/gcc/x86_64-pc-linux-gnu/11.1.0/collect2 -plugin /soft/compilers/gcc/11.1.0/x86_64-suse-linux/libexec/gcc/x86_64-pc-linux-gnu/11.1.0/liblto_plugin.so -plugin-opt=/soft/compilers/gcc/11.1.0/x86_64-suse-linux/libexec/gcc/x86_64-pc-linux-gnu/11.1.0/lto-wrapper -plugin-opt=-fresolution=/tmp/cci1pg3n.res -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 /usr/lib/../lib64/crt1.o /usr/lib/../lib64/crti.o /soft/compilers/gcc/11.1.0/x86_64-suse-linux/lib/gcc/x86_64-pc-linux-gnu/11.1.0/crtbegin.o -L/soft/compilers/gcc/11.1.0/x86_64-suse-linux/lib/gcc/x86_64-pc-linux-gnu/11.1.0 -L/soft/compilers/gcc/11.1.0/x86_64-suse-linux/lib/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/soft/packaging/spack-builds/linux-opensuse_leap15-x86_64/gcc-10.2.0/hdf5-1.10.7-uapcktd3szlmtouy63p4o3nofnsj5au6/lib -L/soft/compilers/gcc/11.1.0/x86_64-suse-linux/lib/gcc/x86_64-pc-linux-gnu/11.1.0/../../.. /tmp/ccORIsYj.o /soft/compilers/rocm/rocm-6.0.0/lib/libamdhip64.so -lstdc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc /soft/compilers/gcc/11.1.0/x86_64-suse-linux/lib/gcc/x86_64-pc-linux-gnu/11.1.0/crtend.o /usr/lib/../lib64/crtn.o
/usr/bin/ld: /soft/compilers/rocm/rocm-6.0.0/lib/libamd_comgr.so.2: undefined reference to `std::condition_variable::wait(std::unique_lock<std::mutex>&)@GLIBCXX_3.4.30'
collect2: error: ld returned 1 exit status
```
Could you provide full verbose output?

**Comment by vstempen** [comment]
Here is the verbose output. Please review it. I'm not totally sure why checksum is 0, but the binary is successfully generated and executed. Also, we use quite different configuration. Not sure what parameters are important for your project. Please review it and let us know.
```
bdc077a6e406:~ # g++-11 main.cpp /opt/rocm-6.0.2/lib/libamdhip64.so -v
Using built-in specs.
COLLECT_GCC=g++-11
COLLECT_LTO_WRAPPER=/usr/lib64/gcc/x86_64-suse-linux/11/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-suse-linux
Configured with: ../configure --prefix=/usr --infodir=/usr/share/info --mandir=/usr/share/man --libdir=/usr/lib64 --libexecdir=/usr/lib64 --enable-languages=c,c++,objc,fortran,obj-c++,ada,go,d --enable-offload-targets=nvptx-none, --without-cuda-driver --enable-checking=release --disable-werror --with-gxx-include-dir=/usr/include/c++/11 --enable-ssp --disable-libssp --disable-libvtv --enable-cet=auto --disable-libcc1 --disable-plugin --with-bugurl=https://bugs.opensuse.org/ --with-pkgversion='SUSE Linux' --with-slibdir=/lib64 --with-system-zlib --enable-libstdcxx-allocator=new --disable-libstdcxx-pch --enable-libphobos --enable-version-specific-runtime-libs --with-gcc-major-version-only --enable-linker-build-id --enable-linux-futex --enable-gnu-indirect-function --program-suffix=-11 --without-system-libunwind --enable-multilib --with-arch-32=x86-64 --with-tune=generic --build=x86_64-suse-linux --host=x86_64-suse-linux
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 11.3.0 (SUSE Linux)
COLLECT_GCC_OPTIONS='-v' '-shared-libgcc' '-mtune=generic' '-march=x86-64' '-dumpdir' 'a-'
 /usr/lib64/gcc/x86_64-suse-linux/11/cc1plus -quiet -v -D_GNU_SOURCE main.cpp -quiet -dumpdir a- -dumpbase main.cpp -dumpbase-ext .cpp -mtune=generic -march=x86-64 -version -o /tmp/ccliuTqj.s
GNU C++17 (SUSE Linux) version 11.3.0 (x86_64-suse-linux)
        compiled by GNU C version 11.3.0, GMP version 6.1.2, MPFR version 4.0.2-p6, MPC version 1.1.0, isl version isl-0.18-GMP

GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
#include "..." search starts here:
#include <...> search starts here:
 /usr/include/c++/11
 /usr/include/c++/11/x86_64-suse-linux
 /usr/include/c++/11/backward
 /usr/lib64/gcc/x86_64-suse-linux/11/include
 /usr/local/include
 /usr/lib64/gcc/x86_64-suse-linux/11/include-fixed
 /usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/include
 /usr/include
End of search list.
GNU C++17 (SUSE Linux) version 11.3.0 (x86_64-suse-linux)
        compiled by GNU C version 11.3.0, GMP version 6.1.2, MPFR version 4.0.2-p6, MPC version 1.1.0, isl version isl-0.18-GMP

GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
Compiler executable checksum: 00000000000000000000000000000000
COLLECT_GCC_OPTIONS='-v' '-shared-libgcc' '-mtune=generic' '-march=x86-64' '-dumpdir' 'a-'
 /usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/as -v --64 -o /tmp/ccIfudWj.o /tmp/ccliuTqj.s
GNU assembler version 2.41.0 (x86_64-suse-linux) using BFD version (GNU Binutils; SUSE Linux Enterprise 15) 2.41.0.20230908-150100.7.46
COMPILER_PATH=/usr/lib64/gcc/x86_64-suse-linux/11/:/usr/lib64/gcc/x86_64-suse-linux/11/:/usr/lib64/gcc/x86_64-suse-linux/:/usr/lib64/gcc/x86_64-suse-linux/11/:/usr/lib64/gcc/x86_64-suse-linux/:/usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/
LIBRARY_PATH=/usr/lib64/gcc/x86_64-suse-linux/11/:/usr/lib64/gcc/x86_64-suse-linux/11/../../../../lib64/:/lib/../lib64/:/usr/lib/../lib64/:/usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/lib/:/usr/lib64/gcc/x86_64-suse-linux/11/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-v' '-shared-libgcc' '-mtune=generic' '-march=x86-64' '-dumpdir' 'a.'
 /usr/lib64/gcc/x86_64-suse-linux/11/collect2 -plugin /usr/lib64/gcc/x86_64-suse-linux/11/liblto_plugin.so -plugin-opt=/usr/lib64/gcc/x86_64-suse-linux/11/lto-wrapper -plugin-opt=-fresolution=/tmp/cc9ojnfj.res -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc --build-id --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 /usr/lib64/gcc/x86_64-suse-linux/11/../../../../lib64/crt1.o /usr/lib64/gcc/x86_64-suse-linux/11/../../../../lib64/crti.o /usr/lib64/gcc/x86_64-suse-linux/11/crtbegin.o -L/usr/lib64/gcc/x86_64-suse-linux/11 -L/usr/lib64/gcc/x86_64-suse-linux/11/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/lib -L/usr/lib64/gcc/x86_64-suse-linux/11/../../.. /tmp/ccIfudWj.o /opt/rocm-6.0.2/lib/libamdhip64.so -lstdc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc /usr/lib64/gcc/x86_64-suse-linux/11/crtend.o /usr/lib64/gcc/x86_64-suse-linux/11/../../../../lib64/crtn.o
COLLECT_GCC_OPTIONS='-v' '-shared-libgcc' '-mtune=generic' '-march=x86-64' '-dumpdir' 'a.'
bdc077a6e406:~ #
```

**Comment by ye-luo** [comment]
@vstempen here is what I found.

You are using g++11 installed via the OS package manager. It relies on libstdc++ from OS which is GLIBCXX_3.4.32 equivalent to GCC 13.2.0. This is achieved by softlinking `/usr/lib64/gcc/x86_64-suse-linux/11/libstdc++.so -> ../../../libstdc++.so.6` and your g++11 picks it up via `LIBRARY_PATH=/usr/lib64/gcc/x86_64-suse-linux/11`.

In my case, I have a standalone installation of gcc 11. This is common in HPC as we don't install compilers from the OS package manager. My gcc 11 finds the true gcc 11 shipped libstdc++ in my standalone gcc 11 installation.

When the libamdhip64 library changed dependency in the 5.4.3 minor release. My g++-11 complains but your g++-11 doesn't.

**Comment by vstempen** [comment]
@ye-luo, can you provide instructions of how to install and configure standalone gcc11, so we have better chance reproducing the issue. Or can we just use a package manager to force specific libstdc++?

**Comment by ye-luo** [comment]
> @ye-luo, can you provide instructions of how to install and configure standalone gcc11, so we have better chance reproducing the issue. Or can we just use a package manager to force specific libstdc++?

https://gcc.gnu.org/wiki/InstallingGCC

**Comment by vstempen** [comment]
I was able to reproduce the issue by compiling gcc11 to isolated location. In this case gcc is using GLIBCXX_3.4.30. When gcc is installed with package manager, it uses GLIBCXX_3.4.32.

Difference between those two versions GLIBCXX_3.4.30 has __cpp_lib_jthread undefined for condition_variable class which makes std::condition_variable::wait(std::unique_lock<std::mutex>&) unavailable.

Simply defining __cpp_lib_jthread in condition_variable to the value defined in stop_token or version, for example, causes many build errors. So, this does not seem to be a solution.

ROCm LLVM uses parallel processes in many occasions and synchronization between them is done using std::condition_variable::wait. But using multithreading is gated by LLVM_ENABLE_THREADS compilation flag. So, the problem can be resolved by rebuilding LLVM with LLVM_ENABLE_THREADS=OFF.

**Comment by vstempen** [comment]
I guess since GLIBCXX_3.4.32 supports std::condition_variable::wait, upgrading the library would be the best solution. From AMD side turning off LLVM multithreading enables using older libraries. Please let us know if we can close the issue.

**Comment by ye-luo** [comment]
> I guess since GLIBCXX_3.4.32 supports std::condition_variable::wait, upgrading the library would be the best solution. From AMD side turning off LLVM multithreading enables using older libraries. Please let us know if we can close the issue.

I'm not aware of g++ allowing pickup a newer libstdc++. The original issue was not about AMD compilers but about AMD runtime libraries having high libstdc++ version dependency. The questions was can you build libraries like `libamd_comgr.so.2` against lower version of libstdc++.

**Comment by vstempen** [comment]
If you have newer libstdc++ installed on your system, you can just use -L compilation key to use libraries from that location. For example, that works for me:
/soft/compilers/gcc_11/bin/g++ -L /usr/lib/gcc/x86_64-linux-gnu/11 -v main.cpp /opt/rocm/lib/libamdhip64.so.6
As for building libamd_comgr.so.2 against lower version, it will require changing ROCM LLVM not to use multithreading or implement thread synchronization without using methods from newer versions of libstdc++.  So, why not just use newer libstdc++ in your build?

**Comment by ye-luo** [comment]
My issue was never about how to get things work. I knew with a bit options here and there I can get things work although that is annoying. My questions is always why in a 5.4.3 minor release the libstdc++ version requirement jump from gcc 7 to gcc 12.
