### ISSUE TITLE
Backport all known issues from docs.amd.com to GitHub

### ISSUE THREAD

**Issue by saadrahim** [ROCm/ROCm#2087]
- Add ROCm version labels to verified issues.

**Comment by Naraenda** [comment]
docs.amd.com backporting checklist:
- [ ] 5.5.0
- [ ] 5.4.3
- [ ] 5.4.2
- [ ] 5.4.1
- [ ] 5.4.0
- [ ] 5.3.3
- [ ] 5.3.2
- [ ] 5.3.0
- [ ] 5.2.0
- [ ] 5.1.0
- [ ] 5.0.2
- [ ] 5.0.1
- [ ] 5.0.0

**Comment by saadrahim** [comment]
Fix link on known issues, can this be done via projects yaml file? Or via branchname?
