### ISSUE TITLE
Fix HIP error codes documentation

### ISSUE THREAD

**Issue by gsitaram** [ROCm/ROCm#2095]
Documentation for some error codes looks as if something is missing. See attached image. Link to the page is: [HIP API docs](https://rocmdocs.amd.com/projects/HIP/en/develop/.doxygen/docBin/html/hip__runtime__api_8h.html#aecfa4e26bd686ba79333cc3203453117)
![Screenshot from 2023-05-01 10-51-37](https://user-images.githubusercontent.com/74741442/235482574-fbf19cad-496b-4946-ae2c-80c51f0d626c.png)
There are a few such fields that require fixing.

**Comment by nartmada** [comment]
Hi @gsitaram and @Naraenda, has this issue been fixed?  Thanks.

**Comment by nartmada** [comment]
Fix is available in upcoming release ROCm 6.1.
