### ISSUE TITLE
Installing CUDA Toolkit broke ROCm installation

### ISSUE THREAD

**Issue by kaustubhcs** [ROCm/ROCm#2106]
Command rocminfo was working great until I installed the CUDA Toolkit 12.0
(The server blade has both AMD MI100 and NVIDIA V100 GPUs)
Now cuda works fine but I get the following error when running the command `rocminfo`
```
ktb@server:~ rocminfo
ROCk module is loaded
Unable to open /dev/kfd read-write: Cannot allocate memory
ktb is member of video group
```

Any suggestions?

**Comment by nartmada** [comment]
Hi @kaustubhcs, have you tried re-installing ROCm to see if it fixes the issue?  Latest ROCm is 6.0.2.  Thanks.

**Comment by kaustubhcs** [comment]
Hello @nartmada 
I was able to fix the issue. I updated my OS to Ubuntu 22 and installed latest versions of rocm and CUDA toolkit. 

Works smoothly now. Thanks

**Comment by nartmada** [comment]
@kaustubhcs, glad to hear.  I will close the ticket.  Thanks.
