### ISSUE TITLE
distributed/test_distributed_spawn Fails

### ISSUE THREAD

**Issue by Naraenda** [ROCm/ROCm#2107]
This issue is ported from the release notes.

When user applications call `ncclCommAbort` to destruct communicators and then create new
communicators repeatedly, subsequent communicators may fail to initialize.

**Comment by nartmada** [comment]
Hi @Naraenda, does this issue still exists with latest ROCm 6.0.2 ?  If issue is resolved, please close the ticket.  Thanks.

**Comment by nartmada** [comment]
Closing the ticket as no response from @Naraenda.  Please re-open if the issue is not fixed in latest ROCm6.0.2
