### ISSUE TITLE
--save-temps Compiler Option Error at Runtime

### ISSUE THREAD

**Issue by Naraenda** [ROCm/ROCm#2108]
This issue is ported from the release notes.

Some users may encounter a “Cannot find Symbol” error at runtime when using `--save-temps`. While most `--save-temps` use cases work correctly, this error may appear occasionally.

The known workaround is not to use `--save-temps` when the error appears.

**Comment by nartmada** [comment]
Hi @Naraenda, please close the ticket if the issue has been fixed.  Thanks.
