### ISSUE TITLE
Does the CU MASK really work

### ISSUE THREAD

**Issue by gofreelee** [ROCm/ROCm#2138]
Hi, I am learning CU_MASK mechanism, my experiment scenario is like this:
I used two separate sets of masks

unsigned int cuMaskAll[2] = {0xFFFFFFFF, 0xFFFFFFF0};
unsigned int cuMaskBE[2] = {0x11111111, 0x0000000};
They are used to create two streams, which are used to carry out a bert model inferrence
There is little difference in the infer latency between the two of them. cuMaskBE is supposed to enable only 8 CUS. Why wouldn't it ？
Thank you in advance.

**Comment by xfyucg** [comment]
Which GPU are you using?

**Comment by gofreelee** [comment]
AMGGPU MI50  with 4 SE, each SE 15 CUS

**Comment by xfyucg** [comment]
Make sure your workloads saturate all the CUs, then you will see the difference.

**Comment by ppanchad-amd** [comment]
@gofreelee Closing ticket since we haven't heard from you in a while. If you still see the issue with our latest ROCm stack, please re-open the issue. Thanks!
