### ISSUE TITLE
Navi 5000 Support

### ISSUE THREAD

**Issue by daniandtheweb** [ROCm/ROCm#2206]
It's been quite a lot of time since the first generation of RDNA cards have been released and still it seems to be the only cards generation without official ROCm support. Is there any plan to support this generation of cards?

**Comment by ganesh-rao** [comment]
I own an RX 5500 XT, and I'm very disappointed with the lack of support for this card. IMO, AMD's decision so far doesn't instill any confidence in staying with their products in the future when the equivalent Nvidia GPUs appear to be supported and working flawlessly with most ML libraries.

**Comment by TheChosenOne2019** [comment]
I own an RX 7600 XT, and I;m very disappointed with the support of AMD, How much?

**Comment by DifferentialityDevelopment** [comment]
I'm particularly interested in 7600 XT due to AI Accelerators and I cannot find any benchmarks online, no review does any benchmarks on those.
The 7600 reportedly comes with 60 AI Accelerators, I'd love to know how the card performs with ROCm running inference on a LLM, or better yet how it compares to tensor cores.

**Comment by johnnynunez** [comment]
> I'm particularly interested in 7600 XT due to AI Accelerators and I cannot find any benchmarks online, no review does any benchmarks on those. The 7600 reportedly comes with 60 AI Accelerators, I'd love to know how the card performs with ROCm running inference on a LLM, or better yet how it compares to tensor cores.

It's not ai accelerators, they are SIMD units... it's totally different to sistolic arrays(matrix cores from cdna), so no expect a big improvement performace

**Comment by ppanchad-amd** [comment]
@daniandtheweb Please refer to following link for supported GPUs in the latest ROCm 6.1.1 (https://rocm.docs.amd.com/projects/install-on-linux/en/latest/reference/system-requirements.html)
