### ISSUE TITLE
asm inline

### ISSUE THREAD

**Issue by qiji2023** [ROCm/ROCm#2225]
https://github.com/ROCm-Developer-Tools/HIP/tree/master/samples/2_Cookbook/10_inline_asm
The example is so easy！
For v_mad_u64_u32 instruction, how should i use it?

**Comment by preda** [comment]
IMO the best way is to state the arithmetic operation in a high-level language such as OpenCL (C) or C++, and rely on the compiler to generate the v_mad_u64_u32 where appropirate. You can look into the generated ISA, and if it's not what you expected, try to understand why. Use a simple kernel to try to understand the behavior of the compiler. In the unlikely case that you consider that the compiler/optimizer is not doing its job, you can report an issue.

If you write the ASM by hand, it's difficult, error-prone, and often slower than what the compiler was doing in the first place.

**Comment by ppanchad-amd** [comment]
@qiji2023 Do you still need assistance with this ticket? If not, please close ticket. Thanks!

**Comment by harkgill-amd** [comment]
Closing this ticket. If you still need help with inline assembly examples, please re-open this issue or file a new ticket. Thanks!
