### ISSUE TITLE
HIP RTC example re-uses "kernel" variable

### ISSUE THREAD

**Issue by skyreflectedinmirrors** [ROCm/ROCm#2239]
![image](https://github.com/RadeonOpenCompute/ROCm/assets/6463881/c7133e51-5471-4ab1-ba5c-a48c6df0e6d5)
![image](https://github.com/RadeonOpenCompute/ROCm/assets/6463881/703bbc08-3215-4a32-b8a8-d1fdb2ce2e4a)

I.e., if you're copy-pasting the examples, you'll get a duplicate variable name.

**Comment by arghdos** [comment]
https://rocm.docs.amd.com/projects/HIP/en/latest/user_guide/hip_rtc.html#example

**Comment by arghdos** [comment]
Honestly, I think a fully worked example, or linking to:

>Please have a look at saxpy.cpp and hiprtcGetLoweredName.cpp files for a detailed example.

would be helpful here (I can't seem to find those anymore)

**Comment by nartmada** [comment]
Hi @skyreflectedinmirrors, do you still need help with this ticket?  Thanks.

**Comment by skyreflectedinmirrors** [comment]
The same code is still present in the documentation, so yes the issue is still there.

See my comment here: https://github.com/ROCm/ROCm/issues/2239#issuecomment-1589838618

**Comment by nartmada** [comment]
@skyreflectedinmirrors, thank you for getting back.  Let me find someone to take a look.

**Comment by nartmada** [comment]
An internal ticket has been created for investigation.

**Comment by harkgill-amd** [comment]
Hi @skyreflectedinmirrors, the HIP RTC example has been updated to no longer have duplicate variable names. You can find the updated documentation at [Programming for HIP Runtime Compiler (RTC)](https://rocm.docs.amd.com/projects/HIP/en/latest/how-to/hip_rtc.html). 

Please close the ticket if the issue has been addressed, thanks!

**Comment by skyreflectedinmirrors** [comment]
Looks pretty good, I think there's one remaining issue:

```
hiprtcCreateProgram(&prog,                 // HIPRTC program
                    kernel,                // kernel string
                    "gpu_kernel.cu",       // Name of the file
                    num_headers,           // Number of headers
                    &header_sources[0],    // Header sources
                    &header_names[0]);     // Name of header files
```

Basically, this still uses "kernel" instead of "kernel_source"

**Comment by harkgill-amd** [comment]
Noted, I will look into this and get back to you.

**Comment by harkgill-amd** [comment]
Hi @skyreflectedinmirrors, the section with the call to `hiprtcCreateProgram` has been corrected to follow the `vector_add.cpp` example with `kernel_source`. 
```
hiprtcCreateProgram(&prog,                 // HIPRTC program handle
                    kernel_source,         // HIP kernel source string
                    "vector_add.cpp",      // Name of the HIP program, can be null or an empty string
                    0,                     // Number of headers
                    NULL,                  // Header sources
                    NULL);                 // Name of header files
```
Please take a look at the updated documentation [here ](https://rocm.docs.amd.com/projects/HIP/en/latest/how-to/hip_rtc.html#compilation-apis) and confirm if everything looks good.

**Comment by skyreflectedinmirrors** [comment]
LGTM, thanks!
