### ISSUE TITLE
[FAQ] what is CUDA GPU direct nvme equivalent thing in ROCm

### ISSUE THREAD

**Issue by gaowayne** [ROCm/ROCm#2251]
two questions on ROCm interface with storage?
1. if ROCm has similar thing like CUDA GPU direct NVMe?
2. if ROCm can connect NVMeOF now?

**Comment by ppanchad-amd** [comment]
@gaowayne Apologies for the delayed response.

1: Currently ROCm does not have a GPUDirect equivalent. 

2: RDMA is supported by ROCm, but there is no NVMEOF-specific code in ROCm. They’d have to check with the network driver (Mellanox, etc) to enable it.

**Comment by ppanchad-amd** [comment]
@gaowayne Can we close this ticket? Thanks!

**Comment by ppanchad-amd** [comment]
@gaowayne Closing ticket since there is no response for a while. If you still require assistance, please re-open the ticket. Thanks!

**Comment by gaowayne** [comment]
thank you so much
