### ISSUE TITLE
Adding community supported environments like JuliaLang's AMDGPU.jl

### ISSUE THREAD

**Issue by vchuravy** [ROCm/ROCm#2261]
cc: @pxl-th @jpsamaroo

Would a contribution be welcomed that added details on [AMDGPU.jl](https://github.com/JuliaGPU/AMDGPU.jl) the [Julia](https::/julialang.org) package that supports compilation of Julia code to AMD hardware.

I imagine that there might be other community packages that might be worth-mentioning and making those more discoverable through the ROCM docs would be beneficial, but before spending time on a PR I though I should ask.

**Comment by saadrahim** [comment]
Thank you for your suggestion. I will bring this up internally. Please wait 1-2 weeks for a response.

**Comment by saadrahim** [comment]
After a long delay, some positive news.

I encourage you to write a blog on Julia + ROCm. You can tell the story of how the community got together to build it and what features it has. I can accept your blog at https://github.com/ROCm/rocm-blogs/.

I don't know the best place in our docs for a link to the Julia community. Any ideas? We will have to work with the docs team to figure this out.

**Comment by nartmada** [comment]
@vchuravy, @pxl-th, @jpsamaroo, @saadrahim, what is the next step for this ticket?  If no further action is required, I would like to close this ticket.  Thanks.

**Comment by harkgill-amd** [comment]
Closing ticket as blog post has been created at https://rocm.blogs.amd.com/software-tools-optimization/julia-amdgpu/README.html. Thanks!
