### ISSUE TITLE
Create Issue Templates

### ISSUE THREAD

**Issue by saadrahim** [ROCm/ROCm#2268]
Need an issue template for 

- General ROCm bugs
- Documentation Issues
- Feature requests

**Comment by cgmb** [comment]
> Documentation Issues

A template for documentation issues has not been implemented.

**Comment by nartmada** [comment]
Template for documentation issues has been implemented.

![image](https://github.com/ROCm/ROCm/assets/144284448/3c11924a-4cec-48f4-9752-6cc58ced3c2f)
