### ISSUE TITLE
Issue with HSA_XNACK

### ISSUE THREAD

**Issue by Rmalavally** [ROCm/ROCm#2286]
Occasionally, HSA_XNACK forces some page faults, and memory may not initialize as expected in specific cases.

This issue is under investigation and will be fixed in a future release.

**Comment by nartmada** [comment]
Hi @Rmalavally, does this issue still exist in latest ROCm 6.0.2?  Thanks.

**Comment by nartmada** [comment]
Closing the issue as no response from @Rmalavally.  Please re-open if this issue still exists with latest ROCm 6.0.2.  Thanks.
