### ISSUE TITLE
Memory Leak with hipModuleLoad/hipModuleUnload APIs

### ISSUE THREAD

**Issue by Rmalavally** [ROCm/ROCm#2289]
A memory leak occurs when code object files are loaded/unloaded via the hipModuleLoad/hipModuleUnload APIs.

This issue is under investigation and will be fixed in a future release.

**Comment by nartmada** [comment]
Hi @Rmalavally, does this issue still exist with latest ROCm6.0.2?  Thanks.

**Comment by nartmada** [comment]
Closing the ticket as issue has been fixed in ROCm 5.6.1.
