### ISSUE TITLE
RdNA 3 

### ISSUE THREAD

**Issue by radudiaconu0** [ROCm/ROCm#2302]
Could someone explain me how am I suppose to run rocm on un ubuntu 22.04.2 with Rx 7900xtx if the kernel does not support that GPU? I tried to install Ubuntu and I get problems with GPU init on a black screen. Thanks for now i does support or propped RdNA 3 support on 5.6 release :)

**Comment by PMunkes** [comment]
Follow the Quickstart guide, specifically this section after adding the repositories: https://rocm.docs.amd.com/en/latest/deploy/linux/quick_start.html#install-drivers

**Comment by radudiaconu0** [comment]
i tried to install ubunut 22.04.2 but i cant boot it. THe kernel is the problem

**Comment by saadrahim** [comment]
RDNA 3 support will be available later this year.

**Comment by johnnynunez** [comment]
https://rocm.docs.amd.com/en/latest/release/windows_support.html

**Comment by nartmada** [comment]
@radudiaconu0, apologies for the lack of response.

Please refer to the below link for the supported GPUs.  
https://rocm.docs.amd.com/projects/install-on-linux/en/latest/reference/system-requirements.html
