### ISSUE TITLE
No RDNA 3 support? Really?

### ISSUE THREAD

**Issue by sucaiji** [ROCm/ROCm#2312]
why?

**Comment by sucaiji** [comment]
When can I used my 7900xt to run stable diffusion on windows?

**Comment by kankan1322** [comment]
stable-diffusion-webui-directml

**Comment by yatagai63** [comment]
I run stable diffusion on linux

mkdir $HOME/AI 
cd $HOME/AI
git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui
apt update && apt install python3.8-venv
cd stable-diffusion-webui
python3 -m venv venv
source venv/bin/activate
python3 -m pip install --upgrade pip wheel
export HIP_VISIBLE_DEVICES=0
export PYTORCH_ROCM_ARCH="gfx1100"
export CMAKE_PREFIX_PATH=$HOME/AI/stable-diffusion-webui/venv/
pip install -r requirements.txt
pip uninstall torch torchvision
mkdir repositories
cd repositories
git clone https://github.com/pytorch/pytorch
git clone https://github.com/pytorch/vision
cd pytorch
pip install cmake ninja
pip install -r requirements.txt
pip install mkl mkl-include
python3 tools/amd_build/build_amd.py
python3 setup.py install
cd ../vision
python3 setup.py install
cd $HOME/AI/stable-diffusion-webui
python3 launch.py --listen

**Comment by yamfun** [comment]
> I run stable diffusion on linux
> 
> mkdir $HOME/AI cd $HOME/AI git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui apt update && apt install python3.8-venv cd stable-diffusion-webui python3 -m venv venv source venv/bin/activate python3 -m pip install --upgrade pip wheel export HIP_VISIBLE_DEVICES=0 export PYTORCH_ROCM_ARCH="gfx1100" export CMAKE_PREFIX_PATH=$HOME/AI/stable-diffusion-webui/venv/ pip install -r requirements.txt pip uninstall torch torchvision mkdir repositories cd repositories git clone https://github.com/pytorch/pytorch git clone https://github.com/pytorch/vision cd pytorch pip install cmake ninja pip install -r requirements.txt pip install mkl mkl-include python3 tools/amd_build/build_amd.py python3 setup.py install cd ../vision python3 setup.py install cd $HOME/AI/stable-diffusion-webui python3 launch.py --listen

Did you managed to make kohya ss Optimizer AdamW8bit bitsandbytes-rocm to work?

**Comment by johnnynunez** [comment]
https://rocm.docs.amd.com/en/latest/release/windows_support.html

**Comment by ppanchad-amd** [comment]
@sucaiji RDNA 3 is supported as of latest ROCm 6.1.1  (https://rocm.docs.amd.com/projects/install-on-linux/en/latest/reference/system-requirements.html)
