### ISSUE TITLE
Environment Variables

### ISSUE THREAD

**Issue by samjwu** [ROCm/ROCm#2333]
For each project, have there be a Markdown (or XML) file for environment variables
- XML for common format for projects that do not use Markdown

In ROCm main docs, have a list of all the env vars, similar to how autotag compiles CHANGELOGS

Format:
Name | Component | Description

**Comment by icarus-sparry** [comment]
Environment variables for runtime or compile time or both?

If the variables are intended to be temporary, should they be added? If so what is the support implications? As an example suppose there is a need to sum the first N numbers. The code was written with a for loop "sum=0; for(i=0;i<=N;i++) sum+=i". Later it was suggested a better way was to use a formula attributed to Gauss "sum=N*(N-1)/2". For a trial period you can switch between the two ways by defining the SLOWSUM environment variable so you can check that you get the same result both ways. The long term aim is to remove the loop version of the code and the SLOWSUM variable, which is essentially there for internal debugging purposes.

**Comment by amd-isparry** [comment]
Environment variables for runtime or compile time or both?

If the variables are intended to be temporary, should they be added? If so what is the support implications? As an example suppose there is a need to sum the first N numbers. The code was written with a for loop "sum=0; for(i=0;i<=N;i++) sum+=i". Later it was suggested a better way was to use a formula attributed to Gauss "sum=N*(N-1)/2". For a trial period you can switch between the two ways by defining the SLOWSUM environment variable so you can check that you get the same result both ways. The long term aim is to remove the loop version of the code and the SLOWSUM variable, which is essentially there for internal debugging purposes.

**Comment by nartmada** [comment]
Hi @samjwu, is this task completed?  Just want to check if I can close the ticket.  Thanks.

**Comment by samjwu** [comment]
This initiative seems to have been dropped. Closing
