### ISSUE TITLE
Hardware support documentation and gfx1031

### ISSUE THREAD

**Issue by theAeon** [ROCm/ROCm#2353]
Hi! I was checking out the new HIP SDK for windows and I noticed that the hardware support page refers to the 67xx GPUs as gfx1032. I'm pretty sure this is incorrect? All other documentation I can find refers to Navi 22 GPUs as target gfx1031-and there _are_ reports of success compiling HIP for that target on the linux side of things. Is this an error, and if so can the documentation be corrected and support clarified? Appreciate it.

**Comment by saadrahim** [comment]
@Maetveis can you double check the tables? I think we probably made a typo.

**Comment by berinaniesh** [comment]
gfx1031 is not yet supported AFAIK. 
Tensorflow says "Ignoring visible gpu device (device: 0, name: , pci bus id: 0000:03:00.0) with AMDGPU version : gfx1031. The supported AMDGPU versions are gfx1030, gfx900, gfx906, gfx908, gfx90a."
Pytorch recognizes the GPU, but seg faults if any operation is done on the tensors stored on the GPU. 
My device is 6800m (Asus G513QY laptop).

**Comment by berinaniesh** [comment]
@cgmb `HSA_OVERRIDE_GFX_VERSION` works BTW.

**Comment by parbenc** [comment]
I double checked the architecture targets on both the windows and linux sides of the documentation. They are accurate and need no further changes

**Comment by parbenc** [comment]
I double checked the architecture targets on both the windows and linux sides of the documentation. They are accurate and need no further changes

**Comment by ai-nikolai** [comment]
@parbenc - we are running into interesting issues on our vllm inference on multi MI210, on the latest pytorch+rocm. Specifically, we see:

```
[1;36m(VllmWorker TP0 pid=931083)[0;0m /usr/local/lib/python3.12/dist-packages/vllm/model_executor/layers/utils.py:98: UserWarning: failed to open file '/app/afo_tune_device_0_full.csv' for writing; your tuning results will not be saved (Triggered internally at /app/pytorch/aten/src/ATen/hip/tunable/Tunable.cpp:645.)
[1;36m(VllmWorker TP0 pid=931083)[0;0m   return torch.nn.functional.linear(x, weight, bias)
Memory access fault by GPU node-4 (Agent handle: 0x4419e6b0) on address 0x7f74a1400000. Reason: Unknown.
```

---

Some sources suggested using `HSA_OVERRIDE_GFX_VERSION`. Do you think so too? If so, where can we look up the versions to use.
