### ISSUE TITLE
The ‘rocm-smi’ command does not take effect during cgroup isolation

### ISSUE THREAD

**Issue by Wercurial** [ROCm/ROCm#2366]
Hello, may I ask for your advice? I have encountered a problem. I have two GPUs with AMD. When I use the ‘rocm-smi’ command in a container that has applied for cgroup isolation of one GPU, it still displays two GPUs. Is this because the ‘rocm-smi’  command does not support cgroup isolation at the bottom level

**Comment by alexeykondrat** [comment]
Can you post the options that you use when you start the container? 
You can isolate GPUs with "--device=/dev/dri/renderD128" option, where "renderD128" is your GPU. You can also isolate GPU inside the container with environment variable "export ROCR_VISIBLE_DEVICES=0,1" (see rocm-smi for device ids).

**Comment by nartmada** [comment]
Closing the ticket as there is no response from @Wercurial.  Please re-open if you still encounter this issue.  Thanks.
