### ISSUE TITLE
Installing ROCm on windows with GPU RX 6700 XT (Navi 22)

### ISSUE THREAD

**Issue by darabon** [ROCm/ROCm#2370]
Hello, I have been doing Stable diffusion on my Rx 6700 xt for half a year now and I wanted to install ROCm on my windows 10 PC, but I get error 215. What is this error? If you know how to help me, please help. I've already tried cleaning and reinstalling the drivers, but that didn't help. Thank you in advance!

**Comment by Kademo15** [comment]
I think that rocm is on windows but pytorch isnt because there is still stuff that has to be ported you can check here https://github.com/vladmandic/automatic/issues/1880 therefore until pytorch is ported it will not work in the meantime you can use linux or the directml fork.

**Comment by NeedsMoar** [comment]
#2363 
^ This isn't related to pytorch, see that (closed) issue for the fix.

**Comment by shaner306** [comment]
Its likely failing because the 6800 is supported and the 6700XT is not. See https://rocm.docs.amd.com/en/latest/release/windows_support.html

**Comment by nartmada** [comment]
@darabon, apologies for the lack of response.  

Please refer to the below link for supported GPUs on Windows.
https://rocm.docs.amd.com/projects/install-on-windows/en/latest/reference/system-requirements.html

Thanks.

**Comment by tlee933** [comment]
Native therock 7.10 Radeon RX6700XT  (gfx1031)  Linux Fedora43
    
  I have a fork you can poke around on my personal commits.
 https://github.com/tlee933/TheRock/tree/gfx1031-upstream
  and some other gfx-1031 rocm 7.10 fedora43 building
  most of the stack working and some ollama llama.cpp fixing.  all testing still.
 https://github.com/tlee933/TheRock/tree/gfx1031-support-and-docs

rocBLAS working issue #2720
