### ISSUE TITLE
rocm 5.6. installation on RHEL 9.2 has wrong link

### ISSUE THREAD

**Issue by edgargabriel** [ROCm/ROCm#2373]
The ROCm 5.6 documentation for RHEL 9.2 contains an incorrect link, it points to a 5.5 repository instead of 5.6 (Link for RHEL 9.1 is correct as far as I can see).

```
sudo yum install https://repo.radeon.com/amdgpu-install/5.5.1/rhel/9.2/amdgpu-install-5.5.50501-1.el8.noarch.rpm
```
For comparison, the link for RHEL 9.1

```
sudo yum install https://repo.radeon.com/amdgpu-install/5.6/rhel/9.1/amdgpu-install-5.6.50600-1.el8.noarch.rpm
```

**Comment by nartmada** [comment]
Hi @edgargabriel, can we close this ticket?  Thanks.

**Comment by edgargabriel** [comment]
yes, looks good, thank you!
