### ISSUE TITLE
rocm-hip-runtime-dev : Depends: rocm-device-libs problem

### ISSUE THREAD

**Issue by habernir** [ROCm/ROCm#2378]
i try to install sudo amdgpu-install --usecase=rocm in ubuntu 22.04 (version 5.6.0)
but i get this

The following packages have unmet dependencies:
 rocm-hip-runtime-dev : Depends: rocm-device-libs (= 1.0.0.50600-67~22.04) but 5.0.0-1 is to be installed
 rocm-openmp-sdk : Depends: rocm-device-libs (= 1.0.0.50600-67~22.04) but 5.0.0-1 is to be installed
E: Unable to correct problems, you have held broken packages.
habernir@nirUbuntu:~/Documents$ 

thanks 
nir

**Comment by pramenku** [comment]
@habernir  Can you try again. I tried and it works.
You can try latest 5.7.1 or 5.6.0 itself

**Comment by nartmada** [comment]
Hi @habernir, do you still see this issue with latest ROCm 6.0.0?  If not, please close the ticket.  Thanks.
