### ISSUE TITLE
Make `roc-obj-*` utilities `PATH` insensitive

### ISSUE THREAD

**Issue by MathiasMagnus** [ROCm/ROCm#2395]
These utilities (when calling one another) expect that all of them are on the PATH. This is problematic if the user doesn't add `/opt/rocm/bin` to the PATH (as the APT packages don't by default) and is also problematic in multi-version scenarios.

Please make them PATH insensitive.

**Comment by nartmada** [comment]
@david-salinas, @kzhuravl, @MathiasMagnus, has the issue been fixed?  If fixed, can we close this ticket?  Thanks.

**Comment by david-salinas** [comment]
There have been no changes for this issue.  But I'd like to discuss it.  @MathiasMagnus do you have an example situation/case that demonstrates the issue you're experiencing?  I just want to make sure I understand the issue clearly.  

Of the three tools, really only "roc-obj" calls the other two (roc-obj-ls and roc-obj-extract).  And looking at the function/routine code here: https://github.com/ROCm/clr/blob/8ff39a54fc790454b95b325eb2d9cdfa06ba7968/hipamd/bin/roc-obj#L136  the tool should be using HIP_CLANG_PATH (if set) as a basis for its search first.  And this env var will usually be set based on the current location of the script/tool being called.

**Comment by nartmada** [comment]
Closing the ticket as it is stale.
