### ISSUE TITLE
Windows HIP installer failure and broken help link

### ISSUE THREAD

**Issue by gbeatty** [ROCm/ROCm#2405]
The HIP for Windows installer failed for me.
![install error](https://github.com/RadeonOpenCompute/ROCm/assets/1686028/f9542a5c-0425-4631-bb74-b6eb7d8230df)

Unfortunately, clicking the **Get More Details** button opens up a missing page
![page not found](https://github.com/RadeonOpenCompute/ROCm/assets/1686028/761bc3c3-99bc-4cd3-8d9d-2530ab28706e)

**Comment by Sabrewarrior** [comment]
AMD ROCm Windows Installation Error 215 : https://github.com/RadeonOpenCompute/ROCm/issues/2363 

>After updating my visual studio code it successfully installed, no further issue!

_Posted by @TheBurntWaffl3 in https://github.com/RadeonOpenCompute/ROCm/issues/2363#issuecomment-1664751584_

**Comment by nartmada** [comment]
@gbeatty, apologies for the lack of response.  Which GPU are you using?  Can you please try the Windows HIP Installer from ROCm 6.1.0?  Thanks.

**Comment by harkgill-amd** [comment]
Hi @gbeatty, I was not able to reproduce this issue with the latest HIP SDK for Windows found below. Please re-open this issue if you see it again. Thanks!

https://www.amd.com/en/developer/resources/rocm-hub/hip-sdk.html
