### ISSUE TITLE
undefined symbol: omp_get_mapped_ptr

### ISSUE THREAD

**Issue by Ashutosh-Londhe** [ROCm/ROCm#2413]
I am getting an error for `undefined symbol: omp_get_mapped_ptr` when compiling for OpenMP offload 

I am using following command
` clang++ -O3 -fPIC -DUNIX -Wall -g -std=c++11 -fopenmp -fopenmp=libomp -fopenmp-targets=amdgcn-amd-amdhsa -Xopenmp-target=amdgcn-amd-amdhsa -march=gfx908 -I/ext-home/asl/OPS_cg/OPS/ops/c/include -L/ext-home/asl/OPS_cg/OPS/ops/c/lib/clang  laplace2d_ops.cpp  -I. ./openmp_offload/openmp_offload_kernels.cpp   -lops_ompoffload -lomptarget -o laplace2d_ompoffload`

I am using a Rocm5.4.3 version.
I have another clang installation, in its libomptarget i found the `omp_get_mapped_ptr` using `nm` command
but its not there in libomptarget.so file under Rocm/llvm/lib

**Comment by Thyre** [comment]
ROCm 5.4 is based on LLVM 15 which did not contain `omp_get_mapped_ptr` as a symbol as well. I checked LLVM 16.0.6 and there it is present. ROCm 5.5.0 did use a pre-release LLVM 16 and did not contain the function either, but ROCm 5.6 has it for sure. Don't know about the patch releases in between 5.5 and 5.6.

**Comment by nartmada** [comment]
@Thyre, thank you for your comment.

@Ashutosh-Londhe, has your issue been resolved?  Thanks.

**Comment by nartmada** [comment]
Closing the issue as no response from @Ashutosh-Londhe.  Please re-open if you still observe this issue with latest ROCm 6.0.2.  Thanks.
