### ISSUE TITLE
ROCm 5.6.1 release repo

### ISSUE THREAD

**Issue by briansp2020** [ROCm/ROCm#2422]
https://repo.radeon.com/rocm/apt/latest/ is still pointing to https://repo.radeon.com/rocm/apt/5.6
I think it should point to https://repo.radeon.com/rocm/apt/5.6.1 since it is now released.

**Comment by chaudhariatul** [comment]
Broken links in documents

index.md:
- https://github.com/RadeonOpenCompute/ROCm/blob/develop/docs/release/gpu_os_support
- https://github.com/RadeonOpenCompute/ROCm/blob/develop/docs/release/compatibility

many more.

**Comment by briansp2020** [comment]
I'm closing this since 5.7 is relased and the [latest](https://repo.radeon.com/rocm/apt/latest/) is pointing to 5.7

**Comment by saadrahim** [comment]
The structural defect that you pointed out is still present. When 5.7.1 is released, latest will not point to it. The latest release only tracks X.Y changes in version numbers. Our version number is X.Y.Z. Any changes in Z is not reflected in the latest branch.

**Comment by briansp2020** [comment]
Are the links updated programmatically? I don't know how AMD's release process works. In any case, You can re-open it if you want to track the issue on Github. I was just going through all the issues I have open and decided to clean them up. I had issues that I opened 5 years which no one commented but were still open, cluttering up my issues page.

**Comment by nartmada** [comment]
@briansp2020, there is an ongoing action to address the structural defect.  As for the old tickets which are still open, there is also an ongoing action to clean them up and a process in place to address new incoming tickets.  Let's keep this ticket opened until the structural defect has been fixed.

**Comment by nartmada** [comment]
Issue has been fixed with ROCm 6.1.0.

![image](https://github.com/ROCm/ROCm/assets/144284448/56d5110c-054e-4689-a25d-68f329f94a9f)
