### ISSUE TITLE
ROCm 5.6 installation complete but opencl is not installed

### ISSUE THREAD

**Issue by Monoclinic** [ROCm/ROCm#2430]
Hello,
I followed the quick start installation guide at https://rocm.docs.amd.com/en/latest/deploy/linux/quick_start.html
and successfully installed ROCm 5.6 on my computer (5800x + 6800xt, ubuntu 22.04).
To check the installation, `dkms status` and `/opt/rocm/bin/rocminfo` works well, and `rocm-smi` also has a correct output.

However, when checking `/opt/rocm/opencl/bin/clinfo`, it will return "no such file or directory", and when I check the /opt/rocm/ directory, there is no opencl. All dirs are as follows:
```
bin  hipblas    hipfft   hipsolver  hsa      lib      llvm  rccl        rocblas  rocm_smi  rocsolver  share
hip  hipblaslt  hiprand  hipsparse  include  libexec  oam   rocalution  rocfft   rocrand   rocsparse
```
Also, when I check `torch.cuda.is_available()`, it will return `False`.

Looking forward to your kindly suggestions.

**Comment by vitduck** [comment]
Hi, 

if `rocminfo` shows correct information, then I don't think `clinfo` is strictly needed. 
But if you require it, then it is provided separately via ```rocm-clinfo``` package. 

Regarding pytorch, perhaps the runtime is not built to support `gfx1030`, you can override this behavior with 
```
$ export HSA_OVERRIDE_GFX_VERSION=10.3.0
```
You may be able to run pytorch, but there is no guaranteed of the outcome.

**Comment by nartmada** [comment]
Thanks @vitduck for your suggestions.  
@Monoclinic, any luck with vitduck's suggestions?  You can also try latest ROCm6.0.2 to check if your issue has been fixed or not.  Thanks.

**Comment by Monoclinic** [comment]
Hi, 
thanks for your concern!
As @vitduck says, it seems that opencl will not be installed by default following the quick start guide (when I opened this issue), or maybe I missed something.
I have solved this problem by using amdgpu-install and add the openclsdk usecase.
For pytorch, the official docker image works very well.

Have a nice day!

**Comment by Monoclinic** [comment]
Hi, 
thanks for your concern!
As @vitduck says, it seems that opencl is not installed by default following the quick start guide (when I opened this issue), or maybe I missed something.
I have solved this problem by using amdgpu-install and add the openclsdk usecase.
For pytorch, the official docker image works very well.

Have a nice day!
