### ISSUE TITLE
About amdgpu drive loading problem

### ISSUE THREAD

**Issue by BiliMiku** [ROCm/ROCm#2496]
Loading the amdgpu module in ubuntu 20.04 failed. Procedure
Hardware :Instinct MI250X
After the GPU is powered off, check the dmesg and find the following information:
[  103.397287] [drm] amdgpu: 4294967295M of VRAM memory ready
[  103.397290] [drm] amdgpu: 48114M of GTT memory ready.
[  103.397304] [drm] GART: num cpu pages 131072, num gpu pages 131072
[  103.397313] ioremap: invalid physical address 1000efff0000000
[  103.397316] amdgpu 0000:0a:00.0: amdgpu: (-12) kernel bo map failed
[  103.397319] [drm:amdgpu_fill_buffer [amdgpu]] *ERROR* Trying to clear memory with ring turned off.
Is such VRAM size recognition a hardware problem?
I've tried the vramlimit parameter, but it doesn't seem to work.

**Comment by kentrussell** [comment]
Is it possible to attach a full dmesg? I haven't seen that error before, but I'll see if I can find anything. It seems to have the right memory/page info. Which ROCm release are you using? Thanks!

**Comment by yanbosmu** [comment]
> Loading the amdgpu module in ubuntu 20.04 failed. Procedure Hardware :Instinct MI250X After the GPU is powered off, check the dmesg and find the following information: [ 103.397287] [drm] amdgpu: 4294967295M of VRAM memory ready [ 103.397290] [drm] amdgpu: 48114M of GTT memory ready. [ 103.397304] [drm] GART: num cpu pages 131072, num gpu pages 131072 [ 103.397313] ioremap: invalid physical address 1000efff0000000 [ 103.397316] amdgpu 0000:0a:00.0: amdgpu: (-12) kernel bo map failed [ 103.397319] [drm:amdgpu_fill_buffer [amdgpu]] _ERROR_ Trying to clear memory with ring turned off. Is such VRAM size recognition a hardware problem? I've tried the vramlimit parameter, but it doesn't seem to work.

hello, bro!
I got a AMD MI250X GPU card recently. Obviously it was a part from HPE cray EX235a system.
But I got problem in using it now in ubuntu. Probably no driver in ubuntu?
So, do you have drivers or BIOS that can make my card alive? It is writtern D65201-OB Rev13 on GPU.
THANK YOU!!!!

**Comment by ppanchad-amd** [comment]
@BiliMiku Were you able to resolve your issue? Thanks!

**Comment by ppanchad-amd** [comment]
@BiliMiku Closing ticket since there is no response for a while. If you still require assistance or believe this issue needs to remain open, please re-open the ticket. Thanks!
