### ISSUE TITLE
running on stream 0 and syncing stream 0 is faster than on other stream

### ISSUE THREAD

**Issue by jinhongyii** [ROCm/ROCm#2504]
I tried two approaches to run a program. In the first approach, I launch all the computation and rccl kernels on stream 0, and use hipStreamSynchronize to sync with stream 0 to ensure all the kernels are completed. In the second approach, I hipStreamCreate a new stream and launch all the kernels on it. Also, I use hipStreamSynchronize to sync with the created stream in the end. It's a bit surprising to me that approach 0 is 25% faster than approach 1. Is this an expected behavior?

**Comment by jinhongyii** [comment]
My HW is rtx 7900 xtx, and my rocm version is 5.7.

**Comment by schung-amd** [comment]
Hi @jinhongyii, can you provide the code you used when encountering this issue, or if not, any other code which exhibits this behaviour? Thanks!

**Comment by schung-amd** [comment]
Closing this issue for now, feel free to reopen with more details if you are still experiencing this issue on current ROCm. Running all of your computation on a new stream is not expected to provide any performance benefits, as the advantage of using streams is being able to compute with multiple streams concurrently. Without source code, it is difficult to say whether there is actually an issue here.
