### ISSUE TITLE
How is the rocm/hip patch version computed?

### ISSUE THREAD

**Issue by jczhang07** [ROCm/ROCm#2530]
By hip version, I mean 5.4.6, 5.5.2, 5.6.0, 5.6.1 etc.  In `/opt/rocm-5.6.0/include/hip/hip_version.h`, I see

```
      #define HIP_VERSION_MAJOR 5
      #define HIP_VERSION_MINOR 6
      #define HIP_VERSION_PATCH 31061
      #define HIP_VERSION    (HIP_VERSION_MAJOR * 10000000 + HIP_VERSION_MINOR * 100000 + HIP_VERSION_PATCH)
```

But how is the `HIP_VERSION_PATCH` mapped to the `z` in `rocm-x.y.z`?

**Comment by nartmada** [comment]
@jczhang07, apologies for the lack of response.

![image](https://github.com/ROCm/ROCm/assets/144284448/bbe17b6b-8d69-4611-aba2-6e3e3a851d51)
![image](https://github.com/ROCm/ROCm/assets/144284448/7dc1b541-fc4d-4418-a29f-b0f7df99b975)

Please reopen if I have not answered your question.  Thanks.
