### ISSUE TITLE
Difference between hip_bfloat16 and __hip_bfloat16?

### ISSUE THREAD

**Issue by pcmoritz** [ROCm/ROCm#2534]
I'm using ROCm 5.7. Currently there are two datatypes for `bfloat16` -- `hip_bfloat16` and `__hip_bfloat16`. They seem to be defined respectively as

```
struct __hip_bfloat16 {
  unsigned short data;
};
```
(in `/opt/rocm-5.7.0/include/hip/amd_detail/amd_hip_bf16.h`) and

```
struct hip_bfloat16
{
    __hip_uint16_t data;
   // ...
};
```
(in `/opt/rocm-5.7.0/include/hip/amd_detail/amd_hip_bfloat16.h`).

Unfortunately there doesn't seem to be an out-of-the box way to convert between them. Some of the HIP operations expect `hip_bfloat16` and others expect `__hip_bfloat16`.

Would it be possible to either define an automatic conversion between them, or get rid of one of them? Also if there is any guidance on how to convert between them manually in the mean time, that would be helpful (I'm trying to do it by just creating the respective struct and assigning the `data` field). I didn't find more details about it in the docs :)

Your help is very much appreciated.

**Comment by b-sumner** [comment]
@pcmoritz hip_bfloat16.h appeared before cuda_bf16.h and contains what was needed at the time.  hip_bf16.h is meant to match cuda_bf16.h, and is probably the header of choice at this point.  hip_bfloat16.h will remain for any developers that adopted it before hip_bf16.h appeared.

**Comment by pcmoritz** [comment]
Thanks a lot for the clarification! If you add this info to https://rocm.docs.amd.com/projects/HIP/en/latest/reference/math_api.html or https://rocm.docs.amd.com/projects/HIP/en/latest/reference/terms.html or add a section about bfloat16 to the docs, I think that would be very helpful for others.

**Comment by pcmoritz** [comment]
Btw, the reason why I was running into this is because currently `__hip_bfloat16` doesn't support the `+` operator -- maybe fixing that would be the highest ROI, see https://github.com/vllm-project/vllm/pull/1313/files#diff-de16383df6eb2fb3faca61a12fa02cc572ce5cdaf84bd4856d2408ee9b4b3211R113 :)

**Comment by b-sumner** [comment]
@pcmoritz hip_bf16.h is meant to simplify the porting of an application that include cuda_bf16.h.  The latter does not provide operators and nor does the former.  These headers instead provide functions like __hadd() which can be used if needed to implement operators.

**Comment by pcmoritz** [comment]
As the diff I posted above shows, the cuda data type does support `+`, so for convenience of porting it would be valuable if HIP supported that as well I think :)

**Comment by b-sumner** [comment]
@pcmoritz I don't know where that operator is coming from.  https://docs.nvidia.com/cuda/cuda-math-api/group__CUDA__MATH____BFLOAT16__FUNCTIONS.html certainly doesn't mention any operators.

**Comment by b-sumner** [comment]
Sorry, I now see them in section 1.3.2.

**Comment by pcmoritz** [comment]
Since others also seem to be running into this, is there any you are willing to fix it? That would be appreciated :)

**Comment by commandline-be** [comment]
with the near zero level of projects endorsing rocm and almost uniquely working with cuda, evading HIP, is this ever going to happen ?

truely perplexed both cuda and rocm are very much hardware specific and highly anti-compatible 
it seems the Radeon VII is mostly useless for anything else than hashcat, at least for now

**Comment by zichguan-amd** [comment]
Hi @pcmoritz, you can now directly convert between the two data types in the latest ROCm release.

**Comment by ZJLi2013** [comment]
> Hi @pcmoritz, you can now directly convert between the two data types in the latest ROCm release.

btw, can you provide the public image link for latest rocm build ?

a further question, what's relative for `__nv_bfloat16`,  still `hip_bfloat16` ?

**Comment by ZJLi2013** [comment]
another thing, if need `__float2bfloat16()`,  `__hip_bfloat16` has built-in apis, while `hip_bfloat16` doesn't

**Comment by zichguan-amd** [comment]
> btw, can you provide the public image link for latest rocm build ?

You can find the public images here: https://hub.docker.com/r/rocm/rocm-terminal. 6.2.2 release is on the way.
> a further question, what's the replacement for `__nv_bfloat16` in rocm, still `hip_bfloat16` ?

It's `__hip_bfloat16`. See [this line](https://github.com/ROCm/hipother/blob/e22853eb4d89460682ea89a091e43b315f957a4e/hipnv/include/hip/nvidia_detail/nvidia_hip_bf16.h#L36).

> another thing, if need `__float2bfloat16()`, `__hip_bfloat16` has built-in apis, while `hip_bfloat16` doesn't

See previous comment about the difference between the two:

> @pcmoritz hip_bfloat16.h appeared before cuda_bf16.h and contains what was needed at the time. hip_bf16.h is meant to match cuda_bf16.h, and is probably the header of choice at this point. hip_bfloat16.h will remain for any developers that adopted it before hip_bf16.h appeared.
