### ISSUE TITLE
Incorrect kernel names displayed on Perfetto for traces generated by rocprofv2 using Perfetto plugin on multi-stream applications

### ISSUE THREAD

**Issue by Rmalavally** [ROCm/ROCm#2553]
Perfetto displays incorrect kernel names for traces generated by rocprofv2 (beta release ROCm 5.7) using the Perfetto plugin on multi-stream applications.

Note that this issue appears only on parallel kernel dispatches.

As a workaround, use rocprofv1 to generate traces for visualizing Perfetto in such cases.

This issue is under investigation and will be fixed in a future release

**Comment by ppanchad-amd** [comment]
Issue resolved.
