### ISSUE TITLE
Read and display information failure on AMD Instinct™ MI210

### ISSUE THREAD

**Issue by Rmalavally** [ROCm/ROCm#2555]
The kernel driver may fail to read and display information for some platform configurations on AMD Instinct™ MI210. 

This known issue is under investigation and will be fixed in a future release.

**Comment by ppanchad-amd** [comment]
@Rmalavally Is this fixed in latest ROCm 6.1.1? Thanks!

**Comment by harkgill-amd** [comment]
Fixed as of ROCm 6.1.1.
