### ISSUE TITLE
demucs crash on ROCm 5.6.1 on RX 6700 XT

### ISSUE THREAD

**Issue by kode54** [ROCm/ROCm#2563]
I posted an issue here, but it's not the right place, since it's occurring inside of PyTorch.

https://github.com/facebookresearch/demucs/issues/556

**Comment by CarlGao4** [comment]
Maybe you should also open an issue under pytorch/pytorch

**Comment by nartmada** [comment]
Closing this ticket as issue has been fixed in https://github.com/pytorch/pytorch/issues/111355
