### ISSUE TITLE
hipRAND is missing from the repo manifest file

### ISSUE THREAD

**Issue by BenWibking** [ROCm/ROCm#2578]
There is no entry for hipRAND in the `default.xml` repo manifest file: https://github.com/RadeonOpenCompute/ROCm/blob/roc-5.7.x/default.xml

This makes it unnecessarily difficult to build a complete set of ROCm components.

**Comment by saadrahim** [comment]
rocRAND contains a submodule for hipRAND in 5.7.1. Please see https://github.com/ROCmSoftwarePlatform/rocRAND/tree/rocm-5.7.1. hipRAND code was historically included in the rocRAND repo. The slow separate of the code bases is nearly complete. ROCm 6.0 will contain hipRAND in the manifest.

**Comment by nartmada** [comment]
Hi @BenWibking, please close the ticket if your issue has been fixed in ROCm6.0.0.  Thanks.
