### ISSUE TITLE
UCX and UCC information missing in develop branch

### ISSUE THREAD

**Issue by saadrahim** [ROCm/ROCm#2584]

**Comment by nartmada** [comment]
Hi @LisaDelaney and @saadrahim, do we still need this ticket to be opened?  Please close it if you are done with the ticket.  Thanks.

**Comment by nartmada** [comment]
Closing the ticket.  @saadrahim, please re-open if work is still needed for this ticket.  Then I will create an internal ticket to track the progress.  Thanks.
