### ISSUE TITLE
[Issue]: OpenMP documentation openmp_toolchain.svg link not working

### ISSUE THREAD

**Issue by jithunnair-amd** [ROCm/ROCm#2597]
### Problem Description

https://rocm.docs.amd.com/en/latest/reference/openmp/openmp.html

![image](https://github.com/RadeonOpenCompute/ROCm/assets/37884920/b08ad18b-b125-4371-a809-0fc5f5898b1c)

### Operating System

NA

### CPU

NA

### GPU

NA

### ROCm Version

5.7.1

### Output of /opt/rocm/bin/rocminfo --support

NA

**Comment by SwRaw** [comment]
This was the original tag (which seems to have been changed):

```{figure-md} openmp-toolchain

<img src="/data/reference/openmp/openmp_toolchain.svg" alt="">

OpenMP Toolchain
```

**Comment by nartmada** [comment]
Internal ticket has been created to investigate the issue.

**Comment by nartmada** [comment]
![image](https://github.com/ROCm/ROCm/assets/144284448/a8b782ac-c1ac-47b4-b184-94931c1edbdd)
