### ISSUE TITLE
gfx1100. Why is this a thing?

### ISSUE THREAD

**Issue by AnonymousRonin** [ROCm/ROCm#2632]
### Problem Description

I find it disappointing that get full backend support for a GPU I paid alot of money for is still, today, lacking the support it needs.  I am building LLVM-17 with clang but I am almost certain that everything will be enabled for my system except the single thing I need to get my gpu to perform as advertized.  Why?  I am not much of a coder and pouring through the config files and hoping I don't change the wrong thing is not support.  I tried returning it because despite my efforts I've never enabled it.  They basically told me tough s***. So now I'm stuck with it so I went ahead and deleted ubuntu (cuz it sucks) and reloaded the OS I use for work.  I've been able through advice and trial and error get it to function almost corect.  I still have issues with vbox and  hashcat won't use it.  Considering the amount of time and the lack of solutions surrounding this elusive gfx11(00) I thinkn AMD and possibly Mesa and  LLVM need to explain this.  Every other version of gfx builds easily an d by default.  Yet gfx11 doesn't, and if you do get it built it sounds like one patch after the next.  Unacceptable.  Full stop.  You'te gonna charge that kind of money, it better work.  And if you're going to support Linux, then support it.  3 distros isn't support, that's just being lazy. If you focused more on compatibility with "debian based" and "arch based" compatibility y you'd probably sell more and have less problems. 9 months I've been waiting for you to figure it out.  Times up, time to put our money to work and fix this.

### Operating System

4 distros, 3 versions of one of those

### CPU

Intel i9 13th gen

### GPU

RX7900XTX

### ROCm Version

I don't think so, I use a combo of mesa, vulkan, khronos and python3

### ROCm Component

Is there one that isn't full of bugs

### Steps to Reproduce

Turning on my computer.

### Output of /opt/rocm/bin/rocminfo --support

Like I said.  Ironically my  3 yr old laptop with nvidia and linux work just great.  In fact that old GeForce 16 series is I think faster than my $1100 cooling system, yeah, the fans work fine.

**Comment by johnnynunez** [comment]
> I find it disappointing that get full backend support for a GPU I paid alot of money for is still, today, lacking the support it needs. I am building LLVM-17 with clang but I am almost certain that everything will be enabled for my system except the single thing I need to get my gpu to perform as advertized. Why? I am not much of a coder and pouring through the config files and hoping I don't change the wrong thing is not support. I tried returning it because despite my efforts I've never enabled it. They basically told me tough s***. So now I'm stuck with it so I went ahead and deleted ubuntu (cuz it sucks) and reloaded the OS I use for work. I've been able through advice and trial and error get it to function almost corect. I still have issues with vbox and hashcat won't use it. Considering the amount of time and the lack of solutions surrounding this elusive gfx11(00) I thinkn AMD and possibly Mesa and LLVM need to explain this. Every other version of gfx builds easily an d by default. Yet gfx11 doesn't, and if you do get it built it sounds like one patch after the next. Unacceptable. Full stop. You'te gonna charge that kind of money, it better work. And if you're going to support Linux, then support it. 3 distros isn't support, that's just being lazy. If you focused more on compatibility with "debian based" and "arch based" compatibility y you'd probably sell more and have less problems. 9 months I've been waiting for you to figure it out. Times up, time to put our money to work and fix this.

So you just have to wait, because they have been working hard for the last 6 months. The company's direction on AI has totally changed. Wait for rocm6 they are refactoring all code. They are working very hard since AMD decided to go all in one on AI.

**Comment by danielzgtg** [comment]
Vbox and hashcat (separately) were working with LLVM 15. They stopped working on the latest version. Try downgrading to the versions at this time of year last year when they were working.

**Comment by theron29** [comment]
> > I find it disappointing that get full backend support for a GPU I paid alot of money for is still, today, lacking the support it needs. I am building LLVM-17 with clang but I am almost certain that everything will be enabled for my system except the single thing I need to get my gpu to perform as advertized. Why? I am not much of a coder and pouring through the config files and hoping I don't change the wrong thing is not support. I tried returning it because despite my efforts I've never enabled it. They basically told me tough s***. So now I'm stuck with it so I went ahead and deleted ubuntu (cuz it sucks) and reloaded the OS I use for work. I've been able through advice and trial and error get it to function almost corect. I still have issues with vbox and hashcat won't use it. Considering the amount of time and the lack of solutions surrounding this elusive gfx11(00) I thinkn AMD and possibly Mesa and LLVM need to explain this. Every other version of gfx builds easily an d by default. Yet gfx11 doesn't, and if you do get it built it sounds like one patch after the next. Unacceptable. Full stop. You'te gonna charge that kind of money, it better work. And if you're going to support Linux, then support it. 3 distros isn't support, that's just being lazy. If you focused more on compatibility with "debian based" and "arch based" compatibility y you'd probably sell more and have less problems. 9 months I've been waiting for you to figure it out. Times up, time to put our money to work and fix this.
> 
> So you just have to wait, because they have been working hard for the last 6 months. The company's direction on AI has totally changed. Wait for rocm6 they are refactoring all code. They are working very hard since AMD decided to go all in one on AI and support all type of gpus, including risc-v, ffpga and ryzen

Well, I have a (still very good) R5600XT card, mainly for gaming. Also have a (pretty good) work laptop with Ryzen 7 5700u and a pretty decent iGPU.

Very recently got sucked into machine learning stuff. And I'm just... speechless that AMD, in all it's glory, supports 2 (in words: two!) GPUs on Linux?! They really expect anybody to use this... thing?

I love AMD, but I have to say I'm extremely disappointed by their complete lack of support in this. I'm very close to upgrading going the Green team again. Their GPU 'just work' on Linux (and have been for years now!) :hankey:

**Comment by johnnynunez** [comment]
Wait 6th December

**Comment by theron29** [comment]
> Wait 6th December

I really hope that we - ordinary Radeon endusers - will finally, after all those years, get something more than just a flashy PR presentation...

**Comment by theron29** [comment]
Ok, so:
- No mention of any kind of RDNA compute support
- No mention of (and currently no) support of Ryzen AI for Linux
To say this is massively frustrating is just a brutal understatement... :angry:

**Comment by bdenhollander** [comment]
Expanded Radeon support was mentioned briefly at [26:30](https://youtu.be/pVl25BbczLI?t=1590).

**Comment by AnonymousRonin** [comment]
> Wait 6th December

It's December 9th.  Still waiting

**Comment by NeedsMoar** [comment]
Nah, they said it, just have to go to their website from the 2 hour video which doesn't have a section on consumer hardware and check out something like the huggingface link on the ROCm 6 page you'll eventually find.  Not a ROCm 6 download page, mind you, just a page saying that the version number of ROCm will be 6 at some unforseen future date in case you were just born and don't understand how versions work.  Then you get this:

"On the GPU side, AMD and Hugging Face will first collaborate on the enterprise-grade Instinct MI2xx and MI3xx families, then on the customer-grade Radeon Navi3x family. In initial testing, AMD [recently reported](https://youtu.be/mPrfh7MNV_0?t=462) that the MI250 trains BERT-Large 1.2x faster and GPT2-Large 1.4x faster than its direct competitor." 

I'm on Windows and read this as "we're never going to finish MIOpen / ROCm for Windows, we'll put it off for Linux until everybody forgets or the next generation of cards comes out and they don't care, but buy an MI300X ($40,000 per) because we're making some really nice promises about how good that _will_ be at something rather than how good it _is_ at that thing just like RDNA3."  

The MI300X has been in the pipeline for 2 years and _should have already been working_ with every major AI model / framework a year ago and entered into the optimizing the heck out of it phase 6 months ago unless no functional parts were created until very recently which is perhaps worse.  The fact that this incredibly recent announcement is saying _"will first collaborate"_ is one of the more disturbing things I've read about a new piece of probably $30-40k hardware in years.  It would be like a car company announcing the day before it went on sale, _"we're collaborating with the electrical engineers to make sure the car steers and brakes when you operate the controls."_

**Comment by AnonymousRonin** [comment]
They obviously aren't going to pay any attention to their consumers.  Going this weekend to get a 4090.

**Comment by NeedsMoar** [comment]
I did so last year since they failed to deliver on two major features (and still haven't delivered).  You won't regret it if you're planning on touching any GPU rendering software or ML related stuff.
