### ISSUE TITLE
[Feature]: `HSA_OVERRIDE_GFX_VERSION` equivalent on Windows

### ISSUE THREAD

**Issue by pxl-th** [ROCm/ROCm#2654]
Is there an equivalent to `HSA_OVERRIDE_GFX_VERSION` on Windows?
On Linux this can be used to enable ROCm support for `gfx103x` other than `gfx1030`.

**Comment by riverzhou** [comment]
Same question.

**Comment by DGdev91** [comment]
I tried to run [Koboldcpp-rocm](https://github.com/YellowRoseCx/koboldcpp-rocm) on my RX 5700xt, on windows.
The "koboldcpp_rocm_files.zip" version comes with rocblas files packaged inside the zip, so i copied all the files related to gfx1030 changing the "1030" to "1010" using this script (seems like just renaming breaks something):
```
@echo off
setlocal enabledelayedexpansion

for %%F in (*1030*) do (
    set "newName=%%F"
    set "newName=!newName:1030=1010!"
    copy "%%F" "!newName!"
)

echo Copying completed.
pause
```

It outputs random gibberish, but i had a very similar issue as well on Linux when i tried to run autogptq-rocm, and it could be an issue related to just the 5700xt and rocblas.

If you have a different card, can you try that?

**Comment by ppanchad-amd** [comment]
@pxl-th No, there’s no available option like that on Windows. Thanks!
