### ISSUE TITLE
[Issue]: 23.11.1 Not working with HIP ROCm [Windows]

### ISSUE THREAD

**Issue by 108806** [ROCm/ROCm#2679]
### Problem Description

Installed `AMD-Software-PRO-Edition-23.Q3-Win10-Win11-For-HIP.exe`.

Downloaded hashcat 6.2.6, tried hashcat.exe, and it says:
**hiprtcCompileProgram is missing from HIPRTC shared library.**     

Tried also blender cycles on HIP-RT, and it also drops to the OpenCL, (CPU load is high, GPU is 0%)

### Operating System

Windows 10

### CPU

3700x

### GPU

7800xt

### ROCm Version

5.5

### Steps to Reproduce

Install Windows 10.
Install 23.11.1.
Install HIP SDK.
Try to use ROCm in any application.

### Output of /opt/rocm/bin/rocminfo --support

I don't have this on windows. Is it even supposed to work on windows?

**Comment by 108806** [comment]
I have managed to deal with blender, GPU usage is still pretty low in rendering though, and hashcat is still not working with ROCm, only OpenCL.

**Comment by Shazgul** [comment]
Any updates on here?

**Comment by ppanchad-amd** [comment]
@108806 Can you please try the latest HIP SDK 5.7.1 (https://www.amd.com/en/developer/resources/rocm-hub/hip-sdk.html)? Thanks!

**Comment by harkgill-amd** [comment]
Hi @108806, at this time, there are currently no plans for ROCm to support hashcat. Please open a new issue if you are still experiencing low GPU utilization on Blender with HIP SDK 5.7.1. Thanks!
