### ISSUE TITLE
[Issue]: abnormal output info from rocm-smi with one Radeon Pro W7900 GPU installed

### ISSUE THREAD

**Issue by alexhegit** [ROCm/ROCm#2681]
### Problem Description

1. Run rocm-smi
2. see the output
- unsupported info output from rocm-smi
- Why here are two GPUs info but just one Radeon Pro W7900 GPU installed

### Operating System

Ubuntu 22.04.3

### CPU

AMD Ryzen 7900

### GPU

AMD Radeon Pro W7900

### ROCm Version

5.7.1

### Steps to Reproduce

Run rocm-smi

### Output of /opt/rocm/bin/rocminfo --support

amd@AIG-PM:~$ rocm-smi

========================= ROCm System Management Interface =========================
=================================== Concise Info ===================================
Expected integer value from monitor, but got ""
Expected integer value from monitor, but got ""
GPU[0]          : get_power_avg, Unexpected data received
====================================================================================
====================================================================================
Expected integer value from monitor, but got ""
Expected integer value from monitor, but got ""
GPU[0]          : get_power_cap, Unexpected data received
ERROR: GPU[1]   : sclk clock is unsupported
====================================================================================
GPU[1]          : get_power_cap, Not supported on the given system
GPU  Temp (DieEdge)  AvgPwr  SCLK  MCLK     Fan  Perf     PwrCap       VRAM%  GPU%
0    N/A             N/A     None  None     0%   unknown  Unsupported    0%   0%
1    42.0c           0.159W  None  3000Mhz  0%   auto     Unsupported    3%   0%
====================================================================================
=============================== End of ROCm SMI Log ================================

**Comment by kentrussell** [comment]
This was due to a disconnect between the SMI and the kernel. I am not sure if the fix is  ROCm 6.0 or 6.1. @dmitrii-galantsev do you know offhand?

**Comment by dmitrii-galantsev** [comment]
@kentrussell 6.0 should have it fixed
likely https://github.com/ROCm/rocm_smi_lib/commit/41ade41d8467eadc37ab60c4a423a1ece9a65449 and https://github.com/ROCm/rocm_smi_lib/commit/a4b470fe71f723fe2c3b90480922820ae8102558 . Both in 6.0

**Comment by nartmada** [comment]
Hi @alexhegit, please close the ticket if the issue has been fixed.  Thanks.

**Comment by nartmada** [comment]
Closing the ticket as no response from @alexhegit.  Please re-open if the issue still exists with latest ROCm 6.0.2.  Thanks.
