### ISSUE TITLE
Support for Radeon RX 6700 XT (gfx1031)

### ISSUE THREAD

**Issue by paralin** [ROCm/ROCm#2720]
There is no TensileLibrary_lazy_gfx1031.dat which causes an error when trying to use rocBLAS with a RX 6700 XT.

How can I get this working with this GPU, or is this currently not supported? If it's not supported, will it be in the near future? Is it just HIP that's not working, or also the opencl integration?

I was able to get the opencl / clBLAST support to work with an older revision of rocm, fwiw.

### Operating System

Ubuntu 22.04.3 LTS

### ROCm Component

rocBLAS

**Comment by danielzgtg** [comment]
All 6000 GPUs should be (unofficially) supported. Have you tried `export HSA_OVERRIDE_GFX_VERSION=10.3.0` in `.bashrc` or before running the command you are trying to use?

**Comment by nartmada** [comment]
Sorry, gfx1031 is not officially supported by AMD.

https://rocm.docs.amd.com/projects/install-on-linux/en/latest/reference/system-requirements.html

**Comment by ccidral** [comment]
@nartmada Are there any plans to support gfx1031?

**Comment by wrobelda** [comment]
It is supported on Windows as of latest release, so I'd imagine Linux support is coming eventually

**Comment by NatoBoram** [comment]
I really puts into question why I bought this particular card if AMD hates it
