### ISSUE TITLE
Hang observed with rocSPARSE tests

### ISSUE THREAD

**Issue by Rmalavally** [ROCm/ROCm#2726]
Some tests in rocSPARSE, particularly csric0, csrilu0, and bsric0, appear to hang even when the tests are completed successfully.

These tests will be removed in the upcoming release.

**Comment by nartmada** [comment]
Hi @Rmalavally, can I close this ticket?  Thanks.

**Comment by Rmalavally** [comment]
This issue is fixed in the ROCm 6.1 release and is now closed.
