### ISSUE TITLE
Number of existing links are now broken

### ISSUE THREAD

**Issue by baryluk** [ROCm/ROCm#2740]
### Suggestion Description

This is the first Google result, when one searches: "rocm install":

[Deploy ROCm on Linux — ROCm 5.7.1 Documentation Home](https://rocm.docs.amd.com/en/latest/deploy/linux/index.html)
https://rocm.docs.amd.com/en/latest/deploy/linux/index.html
Now it is 404

When searching for "rocm changelog" one gets this:

[Release Notes — ROCm 5.7.1 Documentation Home](https://rocm.docs.amd.com/en/latest/release.html)
https://rocm.docs.amd.com/en/latest/release.html

Now it is 404

Same with https://rocm.docs.amd.com/en/latest/CHANGELOG.html

**Comment by saadrahim** [comment]
@LisaDelaney I added redirects to all the above reported issues. Can you validate and close this?

**Comment by LisaDelaney** [comment]
The redirects are now working.

**Comment by baryluk** [comment]
First one looks to be broken.

Also I found this link on internet https://rocm.docs.amd.com/en/latest/deploy/linux/install_overview.html

**Comment by samjwu** [comment]
Thanks baryluk

https://rocm.docs.amd.com/en/latest/deploy/linux/index.html

https://rocm.docs.amd.com/en/latest/deploy/linux/install_overview.html

These now redirect to https://rocm.docs.amd.com/projects/install-on-linux/en/latest/
