### ISSUE TITLE
Unable to run with 7900 xtx

### ISSUE THREAD

**Issue by AlfredTallMountain** [ROCm/ROCm#2746]
Hi I've tried every combination possible of rocm and pytorch
(with docker, without, from sources, 5.6, 5.7, with env variables, ...)
but all that I get is 100% CPU forever of immediate segfault.

This is on fresh ubuntu 22.04.

amdgpu-install has all the 'usecases', rocminfo and rocm-smi do work,
steam is able to run 3d accelerated games
and on windows the card works (tried stable diffusion, shark ai, directml)

Did anyone here have more luck ?

**Comment by AlfredTallMountain** [comment]
thanks for the info.
I guess that the consensus is that it's not production ready and it's better to wait ?

**Comment by AlfredTallMountain** [comment]
I'm happy to help, I can easily reproduce the segfault
(by just using the 'official' docker)

do you happen to know how to trace / collect info ?

**Comment by briansp2020** [comment]
You need to install the nightly build. Try installing it with the following command.
>pip3 install --pre --force-reinstall torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/rocm5.7

Also, I had better luck with the 5-series kernel. Ubuntu server installs kernel 5.15 instead of 6.2 that Ubuntu desktop uses, though I have not tested the 6-series kernel with ROCm6 yet.

**Comment by AlfredTallMountain** [comment]
> here is the journey so far.... since i started trying.... #2689

I see no reply from the rocm devs.
Are they usually reading / reacting ?

**Comment by nartmada** [comment]
@AlfredTallMountain, sorry for the delay in responding.  Can you please share your repro steps ?  We will try to repro your issue here at AMD.  Thanks.

**Comment by AlfredTallMountain** [comment]
@nartmada sorry for not updating this thread, I then managed to get the stack working
(tested with whisper and stablediffusion)
the solution was to disable the igpu (of the 7800X3D cpu)

this is clearly stated on your documentation here: https://rocm.docs.amd.com/projects/install-on-linux/en/latest/how-to/amdgpu-install.html
but i'm blind.

by the way, do you happen to know when rocm 6 will be picked up by pytorch ?
by the way x 2, are you aware of any performance boost between rocm 6 and rocm 5.6 ?

Thanks

**Comment by nartmada** [comment]
> @nartmada sorry for not updating this thread, I then managed to get the stack working (tested with whisper and stablediffusion) the solution was to disable the igpu (of the 7800X3D cpu)
> 
> this is clearly stated on your documentation here: https://rocm.docs.amd.com/projects/install-on-linux/en/latest/how-to/amdgpu-install.html but i'm blind.
> 
> by the way, do you happen to know when rocm 6 will be picked up by pytorch ? by the way x 2, are you aware of any performance boost between rocm 6 and rocm 5.6 ?
> 
> Thanks

@AlfredTallMountain, let me reach out to the internal team regarding your 2 questions.  Thanks.

**Comment by nartmada** [comment]
> > @AlfredTallMountain, sorry for the delay in responding. Can you please share your repro steps ? We will try to repro your issue here at AMD. Thanks.
> 
> There are a few of us who got 'further' but there is still a large memory bug out there - you can make the driver die pretty reliabliy with you are using >20Gb VRAM (but not exceeding it) within about 15-20 mins.
> 
> [@Veryunstablerice ](https://github.com/VeryUnstableRice) should be able to confirm.
> 
> #2689

Thanks @terryrankine.  I will reach out to the internal team and ask for guidance to debug the memory issue.

**Comment by nartmada** [comment]
Hi @terryrankine, sorry for the delay in getting back.  For the issue with "... >20Gb VRAM", #2689 has a similar signature to one of the internal issues which got fixed recently.  The fix should be included in the next ROCm release 6.0.1 (target date late Jan 2024).  For the 2 pytorch related questions, I am still waiting for internal team to get back to me.

**Comment by nartmada** [comment]
@terryrankine, @AlfredTallMountain, regarding the pytorch questions:

Do you happen to know when rocm 6 will be picked up pytorch?
-ETA probably another week.  We are in process of doing this, but we have hit an issue related to permission.

Are you aware of any performance boost between rocm 6 and rocm 5.6 ?
-There is optimization done throughout the ROCm stack.  So, in generally there is definitely performance improvement between ROCm 5.6 to ROCm 6.0.

Also, pytorch + ROCm 6.0 nightly wheel are available:  https://download.pytorch.org/whl/nightly/torch/
It can be used by any community user to try ROCm 6.0.

Hope I have answered your questions.

**Comment by AlfredTallMountain** [comment]
Terry thanks for the update.
I've tried a 'before and after' and I don't see a perf difference
but probably something in the whisper and stable-diffusion packages are still using rocm 5.7

**Comment by AlfredTallMountain** [comment]
I'm unable to upgrade torch, torchaudio and torchvision
I've tried:
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm6.0
(and nightly)

```
test@linux:~$ pip list|grep -i torch
pytorch-triton-rocm                   2.2.0+dafe145982
torch                                 2.3.0.dev20240123+rocm5.7
torchaudio                            2.2.0.dev20240123+rocm5.7
torchvision                           0.18.0.dev20240123+rocm5.7

**Comment by dominusbelial** [comment]
This is not good, I have the 2 greatest GPUs from AMD and both are basically useless for any kind of AI work. I'm selling my w7900 and going for a A100.

**Comment by nartmada** [comment]
rocm6.0.2 is available at https://rocm.docs.amd.com/en/latest/.  Please give it a try.  Thanks.

**Comment by dominusbelial** [comment]
This is actually looking great, I have comfy UI working and python code using cuda stuff is also working great, I had to re arrenge my GPUs and prefix all my commands to target it and now I can run pytorch example repo whiteout issues.

**Comment by nartmada** [comment]
Apologies for not following up in past few weeks.  Have all the concerns/issues listed in this ticket been fixed?  Thanks.

**Comment by nartmada** [comment]
Closing the ticket.  Please re-open if you are still observing concerns/issues listed in this ticket.  Thanks.
