### ISSUE TITLE
[Documentation] hipExtMallocWithFlags coherence mixup

### ISSUE THREAD

**Issue by gilbertlee-amd** [ROCm/ROCm#2753]
https://rocm.docs.amd.com/en/latest/conceptual/gpu-memory.html#coherence

There appear to be a number of typos in this section.

The hipHostMallocDefault flag should be hipDeviceMallocDefault and have coarse-grained coherence.
The coherence for hipDeviceMallocFinegrained should be fine-grained.

**Comment by nartmada** [comment]
Internal ROCDOC-292 has been created to track the progress of this ticket.

**Comment by randyh62** [comment]
Fixed in PR #2819

**Comment by samjwu** [comment]
https://github.com/ROCm/ROCm/pull/2819
