### ISSUE TITLE
[DOCS: Typo in the RHEL repository generator

### ISSUE THREAD

**Issue by lordrip** [ROCm/ROCm#2764]
### Problem Description

There's a typo in the RHEL repositories, it shows `...thel/...` and it should be `...rhel/...`

Related page:
https://rocm.docs.amd.com/projects/install-on-linux/en/latest/how-to/native-install/rhel.html#register-rocm-packages

See the following snapshot
![image](https://github.com/ROCm/ROCm/assets/16512618/0db09fd4-bfba-46bc-976e-7cb4f294b837)

### Operating System

Red Hat Enterprise Linux

### CPU

AMD Ryzen 7 5800X

### GPU

Other

### Other

RX 7800XT

### ROCm Version

ROCm 6.0.0

### ROCm Component

Other

**Comment by lordrip** [comment]
I tried to submit a fix for this but it looks like the either the repository is private or the link is wrong :smiley:

**Comment by nartmada** [comment]
The issue has been fixed.

https://rocm.docs.amd.com/projects/install-on-linux/en/latest/how-to/native-install/rhel.html#register-rocm-packages
![image](https://github.com/ROCm/ROCm/assets/144284448/8aab931b-c6ce-4cb8-8bcf-bdced7d95fcd)
![image](https://github.com/ROCm/ROCm/assets/144284448/adc5c889-9dfa-4d36-ad95-080463c91ed3)

**Comment by lordrip** [comment]
Thanks a lot 🙏  @nartmada
