### ISSUE TITLE
Search in documentation does not work with keywords alone

### ISSUE THREAD

**Issue by gsitaram** [ROCm/ROCm#2765]
I wanted to get documentation on __threadfence_block(), but when I searched for "threadfence", I didn't get any results. Even "threadfence_block" did not pull up any results. Only the exact "__threadfence_block" pulled up 2 results. Could the search functionality be improved so that users don't have to know the exact thing they want? That kind-of defeats the purpose..

**Comment by ppanchad-amd** [comment]
@gsitaram Internal ticket has been created to fix documentation. Thanks!

**Comment by samjwu** [comment]
![image](https://github.com/ROCm/ROCm/assets/22262939/25bf2633-5ff8-49db-976c-9e21cb9fc04f)

Matches for partial search

**Comment by samjwu** [comment]
the search across subprojects appears to be less detailed than the search in the current project
https://docs.readthedocs.io/en/stable/server-side-search/index.html

compare
https://rocm.docs.amd.com/en/latest/search.html?q=threadfence#
to
https://rocm.docs.amd.com/projects/HIP/en/latest/search.html?q=threadfence
and
https://rocm.docs.amd.com/projects/HIPIFY/en/latest/search.html?q=threadfence
