### ISSUE TITLE
Not link for rocm6 hip?

### ISSUE THREAD

**Issue by johnnynunez** [ROCm/ROCm#2778]
### Problem Description

error in link https://www.amd.com/en/developer/rocm-hub/hip-sdk.html

### Operating System

Windows 11

### CPU

7950x3d

### GPU

AMD Radeon RX 7900 XT

### ROCm Version

ROCm 6.0.0

### ROCm Component

ROCm

### Steps to Reproduce

Got to download page hip

**Comment by nartmada** [comment]
Internal ticket has been created to track the issue.

**Comment by johnnynunez** [comment]
@nartmada not exists rocm6 for windows... It will be published with rocm6.0.1 with miopen and migraphx?

**Comment by Spacefish** [comment]
> Internal ticket has been created to track the issue.

Well it has been 14 days now.. This is just stupid.. Why not upload the installer / binaries to github / provide the correct link here in the ticket?

**Comment by nartmada** [comment]
Sorry for the delay.  @johnnynunez, please try this link.  Thanks.
https://rocm.docs.amd.com/projects/install-on-windows/en/latest/how-to/install.html

**Comment by johnnynunez** [comment]
> Sorry for the delay. @johnnynunez, please try this link. Thanks. https://rocm.docs.amd.com/projects/install-on-windows/en/latest/how-to/install.html

Still not rocm6 for windows?
