### ISSUE TITLE
[Feature]: How to obtain the physical address given a device pointer?

### ISSUE THREAD

**Issue by xuantengh** [ROCm/ROCm#2786]
### Suggestion Description

NVIDIA provides a mechanism for developers to obtain the physical address of a allocated pointer [via their driver API](https://docs.nvidia.com/cuda/gpudirect-rdma/index.html). In AMD GPU and ROCm, is there any similar approach to achieve this, i.e., given a virtual address returned by `hipMalloc`, query the underlying phyiscal address corresponding to it.

**Comment by b-sumner** [comment]
@Huangxt57 would you please comment on why the physical address is interesting/useful to you?

**Comment by b-sumner** [comment]
Thanks for the information.
