### ISSUE TITLE
[Issue]: Unable to install rocm/6.0.0 on RHEL 8.7

### ISSUE THREAD

**Issue by xinye83** [ROCm/ROCm#2787]
### Problem Description

I was following the install guide at `https://rocm.docs.amd.com/projects/install-on-linux/en/latest/how-to/amdgpu-install.html` to try to install rocm/6.0.0 in a RHEL 8.7 container and it failed with the following error
```
[MIRROR] amdgpu-install-6.0.60000-1.el8.noarch.rpm: Status code: 404 for https://repo.radeon.com/amdgpu-install/6.0/rhel/8.7/amdgpu-install-6.0.60000-1.el8.noarch.rpm (IP: 10.78.90.46)
[MIRROR] amdgpu-install-6.0.60000-1.el8.noarch.rpm: Status code: 404 for https://repo.radeon.com/amdgpu-install/6.0/rhel/8.7/amdgpu-install-6.0.60000-1.el8.noarch.rpm (IP: 10.78.90.46)
[MIRROR] amdgpu-install-6.0.60000-1.el8.noarch.rpm: Status code: 404 for https://repo.radeon.com/amdgpu-install/6.0/rhel/8.7/amdgpu-install-6.0.60000-1.el8.noarch.rpm (IP: 10.78.90.46)
[MIRROR] amdgpu-install-6.0.60000-1.el8.noarch.rpm: Status code: 404 for https://repo.radeon.com/amdgpu-install/6.0/rhel/8.7/amdgpu-install-6.0.60000-1.el8.noarch.rpm (IP: 10.78.90.46)
[FAILED] amdgpu-install-6.0.60000-1.el8.noarch.rpm: Status code: 404 for https://repo.radeon.com/amdgpu-install/6.0/rhel/8.7/amdgpu-install-6.0.60000-1.el8.noarch.rpm (IP: 10.78.90.46)
Status code: 404 for https://repo.radeon.com/amdgpu-install/6.0/rhel/8.7/amdgpu-install-6.0.60000-1.el8.noarch.rpm (IP: 10.78.90.46)
```

### Operating System

RHEL 8.7

### CPU

null

### GPU

AMD Instinct MI250X

### ROCm Version

ROCm 6.0.0

### ROCm Component

ROCm

**Comment by yhuiYH** [comment]
Seems like RHEL 8.7 and 9.1 are no longer supported in ROCm 6.0: https://rocm.docs.amd.com/projects/install-on-linux/en/latest/reference/system-requirements.html.  The documentation did not update the RHEL instructions correctly.

Similar to #2737 , it seems other RHEL pages in the documentation need to be updated properly to 
1) Remove RHEL 8.7 and RHEL 9.1
2) Add RHEL 8.9 and RHEL 9.3

These are the pages that need to be fixed:
1) https://rocm.docs.amd.com/projects/install-on-linux/en/latest/tutorial/quick-start.html
2) https://rocm.docs.amd.com/projects/install-on-linux/en/latest/how-to/amdgpu-install.html

@xinye83 perhaps you can move your container to RHEL 8.8 until the documentation is fixed.
