### ISSUE TITLE
HIP SDK is broken links

### ISSUE THREAD

**Issue by ArtisticMusician** [ROCm/ROCm#2794]
https://www.amd.com/en/developer/rocm-hub/hip-sdk.html
https://rocm.docs.amd.com/en/docs-6.0.0/about/compatibility/windows-support.html

**Comment by yhuiYH** [comment]
Thanks for reporting this.  However, are you able to share what page led you to those broken links so the team can revise the links?

If they are bookmarks, unfortunately, as the websites evolves, the URLs may need to change.  You may want to bookmark the main page so when the URLs move around, you'll still be able to get to the content you're looking for.

i.e. https://www.amd.com/en/developer/resources/rocm-hub.html which now points to https://www.amd.com/en/developer/resources/rocm-hub/hip-sdk.html instead of the above link you provided.

**Comment by Sabrewarrior** [comment]
I found 2 pages have the stale link
https://rocm.docs.amd.com/projects/install-on-windows/en/latest/index.html#hip-install-quick

> For a quick summary on installing HIP SDK on Windows, follow the steps listed on this page. If you want a more in-depth installation guide, see [Install HIP SDK](https://rocm.docs.amd.com/projects/install-on-windows/en/latest/how-to/install.html#hip-install-full).

and

> Download the installer.
> 
> Download the installer from the [HIP-SDK download page](https://www.amd.com/en/developer/rocm-hub/hip-sdk.html).
> 

https://rocm.docs.amd.com/projects/install-on-windows/en/latest/how-to/install.html

> 1. Download the installer from the [HIP-SDK download page](https://www.amd.com/en/developer/rocm-hub/hip-sdk.html).

**Comment by yhuiYH** [comment]
Thanks guys!  Probably this is what #2778  is about too.  URL will be fixed soon.

**Comment by ArtisticMusician** [comment]
I believe I hot to one of the pages by a google search

**Comment by hiepxanh** [comment]
https://rocm.docs.amd.com/projects/install-on-windows/en/latest/

broken link location 

![image](https://github.com/ROCm/ROCm/assets/16970990/75a367ce-ac09-4335-a0f0-dcd9710213d0)

https://rocm.docs.amd.com/projects/install-on-windows/en/latest/how-to/install.html#hip-install-full
At this page, the link is 404 not found 
![image](https://github.com/ROCm/ROCm/assets/16970990/a173f099-8de5-4ab3-9019-ef101d686287)

**Comment by johnnynunez** [comment]
> https://rocm.docs.amd.com/projects/install-on-windows/en/latest/
> 
> broken link location
> 
> ![image](https://private-user-images.githubusercontent.com/16970990/297242115-75a367ce-ac09-4335-a0f0-dcd9710213d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNTg0MDIsIm5iZiI6MTcwNjI1ODEwMiwicGF0aCI6Ii8xNjk3MDk5MC8yOTcyNDIxMTUtNzVhMzY3Y2UtYWMwOS00MzM1LWEwZjAtZGNkOTcxMDIxM2QwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA4MzUwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1MTkyM2RiMGM4NzA4NjYzYjAwYzFmZjE3MDVlYjQwZDkzODliNjJlNTI2YjU1YjMzNmQ4ZjNmNzk3MjBiYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5f1Cj2abjoAp-ejfFgG4UvN6wvQE46RZd4HXETnnLCo)
> 
> https://rocm.docs.amd.com/projects/install-on-windows/en/latest/how-to/install.html#hip-install-full At this page, the link is 404 not found
> 
> is that link should be this or somewhere? https://www.amd.com/en/developer/resources/rocm-hub/hip-sdk.html
> 
> there is no version 6.0 on this page

yes, this is also my issue. Not exists rocm6 for windows

**Comment by Sabrewarrior** [comment]
@yhuiYH https://www.amd.com/en/developer/resources/rocm-hub/hip-sdk.html is also broken now.

**Comment by ArtisticMusician** [comment]
Wonder why it takes weeks to fix a couple broken links.

**Comment by hiepxanh** [comment]
Oh my god, finally
