### ISSUE TITLE
[Feature]: cuda::memcpy_async support

### ISSUE THREAD

**Issue by sorasoras** [ROCm/ROCm#2814]
### Suggestion Description

With cuda::memcpy_async, the thread block no longer stages data through registers, freeing the thread block from the task of moving data and freeing registers to be used by computations.

Do ROCm has something similar  to cuda::memcpy_async that could do this?

![journey-through-memory-hierarchy-1 1](https://github.com/ROCm/ROCm/assets/6722084/a434ba7b-4548-46d9-bf09-15fcafd791e6)

**Comment by ppanchad-amd** [comment]
@sorasoras There’s no HW support.  Would you want the API implemented anyway even though it would be synchronous.  Please advise. Thanks!

**Comment by sorasoras** [comment]
> @sorasoras There’s no HW support. Would you want the API implemented anyway even though it would be synchronous. Please advise. Thanks!
if this is the case, it's probably not worth to implement it. API implemented would only help compatible with cuda code. 
Thanks for answer my question.
