### ISSUE TITLE
[Issue]: Support link broken in Documentation

### ISSUE THREAD

**Issue by Spacefish** [ROCm/ROCm#2845]
### Problem Description

At: https://rocm.docs.amd.com/projects/install-on-windows/en/latest/how-to/install.html
the "Support" menu at the top of the page leads to a 404 on GitHub

### Operating System

irrelevant

### CPU

irrelevant

### GPU

AMD Instinct MI300X

### ROCm Version

ROCm 6.0.0

**Comment by yhuiYH** [comment]
Thanks for highlighting this.  Will pass this on.

**Comment by yhuiYH** [comment]
The support link seems to work and no longer getting 404.  Closing issue.  Please re-open, if necessary.
