### ISSUE TITLE
[Feature]: Little test app to check if ROCm/HIP works

### ISSUE THREAD

**Issue by HerbertBlenderman** [ROCm/ROCm#2848]
### Suggestion Description

Is there a little test/prg to check if ROCm/HIP (AMDGPU Driver) actually works? (Linux, Ubuntu 22.04)

### Operating System

Ubuntu

### GPU

AMD Radeon RX 6500 XT

### ROCm Component

all

**Comment by cjatin** [comment]
https://github.com/ROCm/HIP-Examples

**Comment by nartmada** [comment]
Thanks @cjatin.  @HerbertBlenderman, please close the ticket if you don't have any further question.  Thanks.

**Comment by nartmada** [comment]
Closing the ticket as [HIP examples ](https://github.com/ROCm/HIP-Examples) has been provided.
