### ISSUE TITLE
ROCM in macOS

### ISSUE THREAD

**Issue by johnnynunez** [ROCm/ROCm#2864]
### Suggestion Description

I think that could be incredible to use amd in macos systems also. It's a flavour point from Nvidia.
I see that you're working to support windows soon
https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/ 
![image](https://github.com/ROCm/ROCm/assets/22727137/c31bdcf9-e42e-480e-8328-bb9ef83619af)

**Comment by ppanchad-amd** [comment]
@johnnynunez Can you please close this ticket as this not an issue and open this ticket under 'Discussions' section? Thanks!
