### ISSUE TITLE
ROCm  on Ubuntu 22.04  Using PyTorch With  AMD RX-7900-XTX GPU

### ISSUE THREAD

**Issue by automatic-dolphin** [ROCm/ROCm#2866]
Hello,

I have ROCm installed on Ubuntu 22.04 . (dumps from  rocminfo and clinfo follow question)

I am trying various benchmarks for PyTorch.

It seems like PyTorch is still just using my CPU cores when testing benchmarks.

How can I test PyTorch and/or ROCm  using python3 to ensure use of the GPUs?

Thanks for any enlightenment.

'**rocminfo**' reports:

ROCm module is loaded
-----   
HSA System Attributes    
-----   
Runtime Version:         1.1
System Timestamp Freq.:  1000.000000MHz
Sig. Max Wait Duration:  18446744073709551615 (0xFFFFFFFFFFFFFFFF) (timestamp count)
Machine Model:           LARGE                              
System Endianness:       LITTLE                             
Mwaitx:                  DISABLED
DMAbuf Support:          YES

'**HSA Agents**'              

'**Agent 1**'          
                
  Name:                    AMD Ryzen Threadripper PRO 5965WX 24-Cores
  Uuid:                    CPU-XX                             
  Marketing Name:          AMD Ryzen Threadripper PRO 5965WX 24-Cores
  Vendor Name:             CPU                                
  Feature:                 None specified                     
  Profile:                 FULL_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        0(0x0)                             
  Queue Min Size:          0(0x0)                             
  Queue Max Size:          0(0x0)                             
  Queue Type:              MULTI                              
  Node:                    0                                  
  Device Type:             CPU                                
  Cache Info:              
    L1:                      32768(0x8000) KB                   
  Chip ID:                 0(0x0)                             
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   3800                               
  BDFID:                   0                                  
  Internal Node ID:        0                                  
  Compute Unit:            48                                 
  SIMDs per CU:            0                                  
  Shader Engines:          0                                  
  Shader Arrs. per Eng.:   0                                  
  WatchPts on Addr. Ranges:1                                  
  Features:                None
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: FINE GRAINED        
      Size:                    527984256(0x1f786680) KB           
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: KERNARG, FINE GRAINED
      Size:                    527984256(0x1f786680) KB           
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 3                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    527984256(0x1f786680) KB           
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
  ISA Info:                
                  
**Agent 2**                  
                 
  Name:                    gfx1100                            
  Uuid:                    GPU-0aac02dbebd629ee               
  Marketing Name:          Radeon RX 7900 XTX                 
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128(0x80)                          
  Queue Min Size:          64(0x40)                           
  Queue Max Size:          131072(0x20000)                    
  Queue Type:              MULTI                              
  Node:                    1                                  
  Device Type:             GPU                                
  Cache Info:              
    L1:                      32(0x20) KB                        
    L2:                      6144(0x1800) KB                    
    L3:                      98304(0x18000) KB                  
  Chip ID:                 29772(0x744c)                      
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   2371                               
  BDFID:                   8960                               
  Internal Node ID:        1                                  
  Compute Unit:            96                                 
  SIMDs per CU:            2                                  
  Shader Engines:          6                                  
  Shader Arrs. per Eng.:   2                                  
  WatchPts on Addr. Ranges:4                                  
  Coherent Host Access:    FALSE                              
  Features:                KERNEL_DISPATCH 
  Fast F16 Operation:      TRUE                               
  Wavefront Size:          32(0x20)                           
  Workgroup Max Size:      1024(0x400)                        
  Workgroup Max Size per Dimension:
    x                        1024(0x400)                        
    y                        1024(0x400)                        
    z                        1024(0x400)                        
  Max Waves Per CU:        32(0x20)                           
  Max Work-item Per CU:    1024(0x400)                        
  Grid Max Size:           4294967295(0xffffffff)             
  Grid Max Size per Dimension:
    x                        4294967295(0xffffffff)             
    y                        4294967295(0xffffffff)             
    z                        4294967295(0xffffffff)             
  Max fbarriers/Workgrp:   32                                 
  Packet Processor uCode:: 550                                
  SDMA engine uCode::      19                                 
  IOMMU Support::          None                               
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    25149440(0x17fc000) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: EXTENDED FINE GRAINED
      Size:                    25149440(0x17fc000) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 3                   
      Segment:                 GROUP                              
      Size:                    64(0x40) KB                        
      Allocatable:             FALSE                              
      Alloc Granule:           0KB                                
      Alloc Alignment:         0KB                                
      Accessible by all:       FALSE                              
  ISA Info:                
    ISA 1                    
      Name:                    amdgcn-amd-amdhsa--gfx1100         
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Size:      1024(0x400)                        
      Workgroup Max Size per Dimension:
        x                        1024(0x400)                        
        y                        1024(0x400)                        
        z                        1024(0x400)                        
      Grid Max Size:           4294967295(0xffffffff)             
      Grid Max Size per Dimension:
        x                        4294967295(0xffffffff)             
        y                        4294967295(0xffffffff)             
        z                        4294967295(0xffffffff)             
      FBarrier Max Size:       32
                                 
'** Done **'            

'**clinfo**' reports:

Number of platforms:                             1
  Platform Profile:                              FULL_PROFILE
  Platform Version:                              OpenCL 2.1 AMD-APP (3602.0)
  Platform Name:                                 AMD Accelerated Parallel Processing
  Platform Vendor:                               Advanced Micro Devices, Inc.
  Platform Extensions:                           cl_khr_icd cl_amd_event_callback 

  Platform Name:                                 AMD Accelerated Parallel Processing
Number of devices:                               1
  Device Type:                                   CL_DEVICE_TYPE_GPU
  Vendor ID:                                     1002h
  Board name:                                    Radeon RX 7900 XTX
  Device Topology:                               PCI[ B#35, D#0, F#0 ]
  Max compute units:                             48
  Max work items dimensions:                     3
    Max work items[0]:                           1024
    Max work items[1]:                           1024
    Max work items[2]:                           1024
  Max work group size:                           256
  Preferred vector width char:                   4
  Preferred vector width short:                  2
  Preferred vector width int:                    1
  Preferred vector width long:                   1
  Preferred vector width float:                  1
  Preferred vector width double:                 1
  Native vector width char:                      4
  Native vector width short:                     2
  Native vector width int:                       1
  Native vector width long:                      1
  Native vector width float:                     1
  Native vector width double:                    1
  Max clock frequency:                           2371Mhz
  Address bits:                                  64
  Max memory allocation:                         21890072576
  Image support:                                 Yes
  Max number of images read arguments:           128
  Max number of images write arguments:          8
  Max image 2D width:                            16384
  Max image 2D height:                           16384
  Max image 3D width:                            16384
  Max image 3D height:                           16384
  Max image 3D depth:                            8192
  Max samplers within kernel:                    16
  Max size of kernel argument:                   1024
  Alignment (bits) of base address:              1024
  Minimum alignment (bytes) for any datatype:    128
  Single precision floating point capability
    Denorms:                                     Yes
    Quiet NaNs:                                  Yes
    Round to nearest even:                       Yes
    Round to zero:                               Yes
    Round to +ve and infinity:                   Yes
    IEEE754-2008 fused multiply-add:             Yes
  Cache type:                                    Read/Write
  Cache line size:                               64
  Cache size:                                    32768
  Global memory size:                            25753026560
  Constant buffer size:                          21890072576
  Max number of constant args:                   8
  Local memory type:                             Scratchpad
  Local memory size:                             65536
  Max pipe arguments:                            16
  Max pipe active reservations:                  16
  Max pipe packet size:                          415236096
  Max global variable size:                      21890072576
  Max global variable preferred total size:      25753026560
  Max read/write image args:                     64
  Max on device events:                          1024
  Queue on device max size:                      8388608
  Max on device queues:                          1
  Queue on device preferred size:                262144
  SVM capabilities:                              
    Coarse grain buffer:                         Yes
    Fine grain buffer:                           Yes
    Fine grain system:                           No
    Atomics:                                     No
  Preferred platform atomic alignment:           0
  Preferred global atomic alignment:             0
  Preferred local atomic alignment:              0
  Kernel Preferred work group size multiple:     32
  Error correction support:                      0
  Unified memory for Host and Device:            0
  Profiling timer resolution:                    1
  Device endianess:                              Little
  Available:                                     Yes
  Compiler available:                            Yes
  Execution capabilities:                                
    Execute OpenCL kernels:                      Yes
    Execute native function:                     No
  Queue on Host properties:                              
    Out-of-Order:                                No
    Profiling :                                  Yes
  Queue on Device properties:                            
    Out-of-Order:                                Yes
    Profiling :                                  Yes
  Platform ID:                                   0x7fb2d71f0f90
  Name:                                          gfx1100
  Vendor:                                        Advanced Micro Devices, Inc.
  Device OpenCL C version:                       OpenCL C 2.0 
  Driver version:                                3602.0 (HSA1.1,LC)
  Profile:                                       FULL_PROFILE
  Version:                                       OpenCL 2.0 
  Extensions:                                    cl_khr_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_fp16 cl_khr_gl_sharing cl_amd_device_attribute_query cl_amd_media_ops cl_amd_media_ops2 cl_khr_image2d_from_buffer cl_khr_subgroups cl_khr_depth_images cl_amd_copy_buffer_p2p cl_amd_assembly_program

**Comment by ErykDev** [comment]
Hello,

Here is a simple script to test gpu usage.
[test-rocm.py.txt](https://github.com/ROCm/ROCm/files/14166421/test-rocm.py.txt)

make sure to use newest drivers
drivers : https://repo.radeon.com/amdgpu-install/23.40.2/

it's quite important to specify that you want rocm while installing
amdgpu-install --usecase=graphics,rocm

Also use pytorch/torchvision from AMD repos
pytorch/torchvision: https://repo.radeon.com/rocm/manylinux/rocm-rel-6.0/

Best of luck
Eryk Szmyt

**Comment by automatic-dolphin** [comment]
Hello Erik,

Thanks for the pointer to the wheel files for torch and torch-vision.

After installing and validating ROCm, and testing with the utilities, I was trying to build pyTorch from source.
I kept getting an error related to libncurses6 not being able to find functions in libtinfo.

objdump shows the functions as available. I can only guess that the **python setup develop**  script is somehow getting the  -ltinfo  -L<path to tinfo>   in the wrong order for xxxxxxLINKER_FLAGS .

I will try the wheel files for now and continue to figure out the pyTorch build.

**Comment by automatic-dolphin** [comment]
Thanks Terry,

I will look at trying that. Seems similar to my build PyTorch process.

I think I may just be missing a couple symbolic links to  libtinfo   in /usr/lib .
The binaries for libtinfo seem to live in an architecture path. 
There is also no 'tinfo-config'. The CMake build would have difficulty finding the correct -L and -l   paths for GCC.

**Comment by veb-101** [comment]
Unhelpful comment.

Please do post your benchmark results here if you get it running 🙌.

**Comment by automatic-dolphin** [comment]
Thanks Brian,

I am not using a container. This is a build on a workstation.

**Comment by automatic-dolphin** [comment]
Very nice Terry.

I have ROCm installed and working already.

My only (current) issue is performing a local build of PyTorch for installing into Anaconda.

The PyTorch build has no complaints at all about ROCm. The **setup.py**  for PyTorch is not finding  **libtinfo.so**  during link. This is indirectly a complaint about missing references on behalf of **NCURSES6**  .

![Screen Shot 2024-02-07 at 16 48 25](https://github.com/ROCm/ROCm/assets/158794430/99896b44-39eb-4aea-add4-ebd2a73f482e)

**Comment by automatic-dolphin** [comment]
Here are the tinfo packages.


--------------------------------------------------------------------------------------
apt list --installed | grep tinfo

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

lib32tinfo6/jammy-updates,jammy-security,now 6.3-2ubuntu0.1 amd64 [installed]
libtinfo-dev/jammy-updates,jammy-security,now 6.3-2ubuntu0.1 amd64 [installed,automatic]
libtinfo5/jammy-updates,jammy-security,now 6.3-2ubuntu0.1 amd64 [installed,automatic]
libtinfo6/jammy-updates,jammy-security,now 6.3-2ubuntu0.1 amd64 [installed]
libtinfo6/jammy-updates,jammy-security,now 6.3-2ubuntu0.1 i386 [installed,automatic]

**Comment by automatic-dolphin** [comment]
My PyTorch build is just using the simple instructions, and a few of peoples suggestions.

#get a fresh copy of the PyTorch repo
git clone https://github.com/pytorch/pytorch.git

#move into the download directory
cd pytorch/

#set some environnment variables
export PYTORCH_ROCM_ARCH=gfx1100
export USE_NINJA=1
export USE_CUDA=0
export USE_ROCM=1
export USE_LMDB=1
export USE_OPENCV=1
export MAX_JOBS=10

#make sure the git is fresh
git pull --recurse-submodules
git pull

#let it know its AMD
python tools/amd_build/build_amd.py

#run setup
python setup.py develop

**Comment by automatic-dolphin** [comment]
I had  **libtinfo-dev** but removed it to see if it was interfering.

You just made me think of something though. I will add those  dev packages back.

The thing that I am thinking of is when I ran  '**rocm-install**'  to do the ROCm build,  one of the missing bits in the documentation was that part of ROCm relies on legacy i386 architecture packages. ROCm would not build for me without:

**sudo dpkg --add-architecture i386**

My distro did not have both **amd64**  and  **i386** .

Once I added i386, ROCm built just fine.

**arch-test
amd64
i386** 


I am now wondering if I need to specify an install of  libtinfo:i386  because ROCm was originally linked against i386 libtinfo ...(?)


Anyone see that as a possibility?

**Comment by automatic-dolphin** [comment]
I used **amdgpu-install**  from the available amd.rocm  packages.

**wget https://repo.radeon.com/amdgpu-install/6.0.2/ubuntu/jammy/amdgpu-install_6.0.60002-1_all.deb
 
sudo dpkg -i amdgpu-install_6.0.60001-1_all.deb

sudo amdgpu-install --usecase=rocm,rocmdev,rocmdevtools,opencl,hip,hiplibsdk,graphics,dkms --vulkan=amdvlk,pro -y --accept-eula**

**Comment by automatic-dolphin** [comment]
Yeah, the deb versions are different. 
I aggregated some commands from two different shell histories. 
Hence the difference in the deb versions. The commands are from two different machines but used to provide context.
Good catch. I updated the post.

I think the only reason I added i386 as an architecture was I missed the  **--no-32**   flag.  The added architecture was the problem with the PyTorch build I believe. I am making a clean, 64 bit only, system to test this stuff. Should know in a day or so.

Incidentally, that was a brilliant bit of information from you.  I went and did **amdgpu-install --help**  and there it was.

**Comment by automatic-dolphin** [comment]
It's in the midst of the build now.      Very exciting!!!

This will show if all the settings result in a good  build of pytorch.

**Comment by ppanchad-amd** [comment]
@automatic-dolphin Have you resolved your issue? If so, please close the ticket. Thanks!

**Comment by harkgill-amd** [comment]
Hi @automatic-dolphin, did you get a chance to try the ROCm 6.1 or 6.2 PyTorch wheels for installation? After successful installation, you can use the `HIP_VISIBLE_DEVICES` environment variable to target your GPU, ensuring it's usage. Here is the latest documentation on [using a wheels package](https://rocm.docs.amd.com/projects/install-on-linux/en/latest/install/3rd-party/pytorch-install.html#using-a-wheels-package) to install PyTorch and also on [GPU Isolation Techniques](https://rocm.docs.amd.com/en/latest/conceptual/gpu-isolation.html#hip-visible-devices). 

I will close out this ticket. If you do still encounter issues following these steps, please leave a comment and I will re-open this ticket. Thanks!
