### ISSUE TITLE
[Issue]: Dotted I errors in amdgpu-install if one has Turkish or Azerbaijani as the locale 

### ISSUE THREAD

**Issue by erkinalp** [ROCm/ROCm#2888]
### Problem Description

` /usr/bin/amdgpu-install: satır 436: ${USECASE_GRAPHİCS_PACKAGES[*]}: hatalı ikame`

### Operating System

Ubuntu 22.04.3

### CPU

Amd Ryzen 9 5950X

### GPU

not relevant as this happens at ROCm installation

### ROCm Version

ROCm 6.0.0

### Steps to Reproduce

 Run `sudo amdgpu-install`

### (Optional for Linux users) Output of /opt/rocm/bin/rocminfo --support

Not relevant for this issue, as it happens while running the installer

**Comment by nartmada** [comment]
Hi @erkinalp, please provide the GPU info so that we can investigate the issue properly.  Thank you.

**Comment by erkinalp** [comment]
RX 5500, but not relevant to reproduce this particular issue; the issue kicks before any GPU code execution or even a GPU detection happens, thereby preventing installation in the first place.

**Comment by erkinalp** [comment]
More particularly, it sees `USECASE_GRAPHİCS_PACKAGES` instead of `USECASE_GRAPHICS_PACKAGES` (see the "İ" instead of "I"), and the former is a nonexistent variable.

**Comment by kentrussell** [comment]
@Mystro256 any thoughts?

**Comment by slava-abramov** [comment]
How the driver has been installed?  Specifically, where does the installer package comes from?

**Comment by erkinalp** [comment]
This applies to both .deb and compiled-from-source versions.

**Comment by erkinalp** [comment]
Status of the .rpm version unknown as I do not have a RPM-based testing machine.

**Comment by nartmada** [comment]
Hi @erkinalp, can you please clarify (as requested by Slava) where did the installer package come from?  Thanks.

**Comment by erkinalp** [comment]
In my case, it is the .deb version from repo.radeon.com

**Comment by nartmada** [comment]
Are you using this one?
![image](https://github.com/ROCm/ROCm/assets/144284448/f58062a4-ceb2-4810-a1b8-a64a6ffe220c)

**Comment by slava-abramov** [comment]
URL of the installer package would be more helpful.
Also, please upgrade the target system to Ubuntu 22.04.4.

**Comment by erkinalp** [comment]
> Are you using this one?

Yes

> Also, please upgrade the target system to Ubuntu 22.04.4.

Too late, already upgraded to 24.04 pre-release, but that detail is not relevant to the issue in hand, because shell expansions still work the same way as before.

**Comment by nartmada** [comment]
@erkinalp, can you please check if your issue still exists with ROCm 6.1.0?  Thanks.

**Comment by erkinalp** [comment]
yes, still persists in 6.1

**Comment by erkinalp** [comment]
offended line numbers changed but the error is still the same

`/usr/bin/amdgpu-install: satır 490: ${USECASE_GRAPHİCS_PACKAGES[*]}: hatalı ikame`

**Comment by Mystro256** [comment]
Sorry I didn't forget about this, I was just a bit busy. I'm not 100% sure why it's replacing the I with İ.

I opened the script with my system and it's clearly an "I".

**Comment by erkinalp** [comment]
> not 100% sure why it's replacing the I with İ.

in Turkish and Azerbaijani, the uppercase form of i is İ and the lowercase form of I is ı.

**Comment by erkinalp** [comment]
> sudo dpkg-reconfigure locales

I get the first two, but why should I regenerate my locale?

**Comment by kazimolmez** [comment]
I had the same problem and setting LC_ALL and LC_CTYPE solved the problem.

**Comment by ppanchad-amd** [comment]
@erkinalp Has this issue been resolved for you? Thanks!

**Comment by erkinalp** [comment]
No, still the same issue, although the workaround listed above temporarily works around.

**Comment by erkinalp** [comment]
persists in 6.2

**Comment by sohaibnd** [comment]
Hi @erkinalp, this issue has been fixed and should be part of the upcoming ROCm 6.3 release. If the issue has not been fixed by then, please feel free to re-open this ticket. In the meantime, you can use the workaround (setting LC_ALL and LC_CTYPE) @slava-abramov has suggested.
