### ISSUE TITLE
[Documentation]: The "Feedback" link uses email rocm-feedback@amd.com ‎which bounces emails.

### ISSUE THREAD

**Issue by AshleyT3** [ROCm/ROCm#2889]
### Description of errors

The documentation has a Feedback link which is a mailto to the email address `rocm-feedback@amd.com` ...

<img width="487" alt="image" src="https://github.com/ROCm/ROCm/assets/32182932/2b6fdc74-b4be-484c-af1a-a857f84a243c">

...but ROCm user feedback sent to that email address is bounced...

<img width="393" alt="image" src="https://github.com/ROCm/ROCm/assets/32182932/8b36fe0c-2dff-4ad4-823f-b955db888df0">

I tried a different email address just in case but the block seems general, as if the AMD email address, `rocm-feedback@amd.com`, is internal and not truly meant as a channel for feedback from the public.

**Comment by yhuiYH** [comment]
@AshleyT3, thanks again for bringing it to our attention.  We worked with the teams to allow external/public emails, to get through.  If you'd like to confirm, please feel free to send an email to rocm-feedback@amd.com.  I will close this issue now, but if you find the emails still bounce, please re-open the issue.
