### ISSUE TITLE
[Documentation]: Supported GPU names are inconsistent

### ISSUE THREAD

**Issue by conboy** [ROCm/ROCm#2904]
### Description of errors

The naming conventions between the GPUs are different between the Linux and Windows System requirements

### Attach any links, screenshots, or additional evidence you think will be helpful.

![image](https://github.com/ROCm/ROCm/assets/24994803/761470e0-1057-4ac9-905f-d7d611b4c0c4)
![image](https://github.com/ROCm/ROCm/assets/24994803/cee9b376-94e0-4971-96bb-6726fc9bb4f0)

**Comment by yhuiYH** [comment]
Thanks for pointing this out.  Our team will review and make them consistent.  Leaving issue open while we resolve it.

**Comment by yhuiYH** [comment]
The Windows table was updated to match the Linux one.  Please have a look and thank you (again) for pointing this out to us.  I will close the issue now, please re-open, if necessary.
