### ISSUE TITLE
[Issue]: RocBLAS error on AMD Radeon RX 7600 XT

### ISSUE THREAD

**Issue by SusieDreemurr** [ROCm/ROCm#2914]
Rocm is showing my GPU but I get this error when trying to load an AI model: 

rocBLAS error: Cannot read /home/krusie/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/lib/rocblas/library/TensileLibrary.dat: No such file or directory
Aborted (core dumped)

**Comment by nartmada** [comment]
Hi @SusieDreemurr, 

RX 7600 XT is not officially supported by AMD.  Please refer to the System Requirement link https://rocm.docs.amd.com/projects/install-on-linux/en/latest/reference/system-requirements.html

Unofficially some people have a workaround by setting environment variable HSA_OVERRIDE_GFX_VERSION=11.0.0.  This is not supported by AMD but some have had success with it.

Thanks.

**Comment by SusieDreemurr** [comment]
Ah, bummer. :/  Well, hopefully there will be official support but in the meantime, thanks for the workaround!

**Comment by nartmada** [comment]
Closing this ticket as a workaround has been provided for this issue.  Thanks.
