### ISSUE TITLE
[Feature]: PyTorch Windows Support

### ISSUE THREAD

**Issue by ZhiQiu-Kinsey** [ROCm/ROCm#2915]
I am using ROCm on Windows to run deep learning models, but I found that it does not support PyTorch and TensorFlow, two popular deep learning frameworks. I wonder if you have any plans to support these frameworks.

My expectations are:

- **I hope that ROCm on Windows can support PyTorch and TensorFlow, or at least tell me when it will be able to support them. Do you have this plan? Is it in development? Is there any progress?**
- **I hope to be able to run deep learning models on AMD GPUs, without having to switch to other platforms or devices**

My actual results are:

I cannot use PyTorch and TensorFlow on ROCm on Windows, and I have not found any relevant information or documentation
I feel that ROCm on Windows has very limited support for deep learning, which does not meet my needs

### Operating System

Windows

### GPU

RX7800XT

### ROCm Component

PyTorch

**Comment by johnnynunez** [comment]
> I am using ROCm on Windows to run deep learning models, but I found that it does not support PyTorch and TensorFlow, two popular deep learning frameworks. I wonder if you have any plans to support these frameworks.
> 
> My expectations are:
> 
> * **I hope that ROCm on Windows can support PyTorch and TensorFlow, or at least tell me when it will be able to support them. Do you have this plan? Is it in development? Is there any progress?**
> * **I hope to be able to run deep learning models on AMD GPUs, without having to switch to other platforms or devices**
> 
> My actual results are:
> 
> I cannot use PyTorch and TensorFlow on ROCm on Windows, and I have not found any relevant information or documentation I feel that ROCm on Windows has very limited support for deep learning, which does not meet my needs
> 
> ### Operating System
> Windows
> 
> ### GPU
> RX7800XT
> 
> ### ROCm Component
> PyTorch

To be compatible, the entire RocM pipeline must first be compatible. For IA it is MIOpen and AMDMIGraphX. As you can see in their PRs in MiOpen they were all attached and in AMDMIGraphX there are 3 pending.

**Comment by johnnynunez** [comment]
@ZhiQiu-Kinsey rocm6.1 will support windows as changelongs says

**Comment by ZhiQiu-Kinsey** [comment]
> 正如 Changelongs 所说，ROCM6.1 将支持 Windows

Thanks for the update! Could you please share the source or reference for the information about ROCm 6.1 supporting Windows? I'd like to get more details on it.

**Comment by johnnynunez** [comment]
> > rocm6.1 will support windows as changelongs says
> 
> @johnnynunez Thanks for the update! Could you please share the source or reference for the information about ROCm 6.1 supporting Windows? I'd like to get more details on it.


https://github.com/ROCm/AMDMIGraphX/commit/40f306377b5ab1a0af0c080b08cdc54f3190193c

**Comment by Arondight** [comment]
> > > rocm6.1 will support windows as changelongs says
> > 
> > 
> > @johnnynunez Thanks for the update! Could you please share the source or reference for the information about ROCm 6.1 supporting Windows? I'd like to get more details on it.
> 
> [ROCm/AMDMIGraphX@40f3063](https://github.com/ROCm/AMDMIGraphX/commit/40f306377b5ab1a0af0c080b08cdc54f3190193c)

it is just initial code i think

**Comment by Arondight** [comment]
> I am using ROCm on Windows to run deep learning models, but I found that it does not support PyTorch and TensorFlow, two popular deep learning frameworks. I wonder if you have any plans to support these frameworks.

哥们，要么换系统，要么换硬件，我去年买 7950x + 7900xtx 的票上了这条破船，居家办公又没法换系统，我只能又搞了一个 2696v3 + 2080ti22g x 2 的机器，我觉得还是不要对 amd 抱有什么期望为好

我之前用他家写在官网首页上的 storemi，你选软件前五里面就有，我只想说这玩意儿用着真的可能会死人，别对 amd 有啥幻想了，好多东西都是赶鸭子上架弄得

**Comment by ZhiQiu-Kinsey** [comment]
> > I am using ROCm on Windows to run deep learning models, but I found that it does not support PyTorch and TensorFlow, two popular deep learning frameworks. I wonder if you have any plans to support these frameworks.
> 
> 哥们，要么换系统，要么换硬件，我去年买 7950x + 7900xtx 的票上了这条破船，居家办公又没法换系统，我只能又搞了一个 2696v3 + 2080ti22g x 2 的机器，我觉得还是不要对 amd 抱有什么期望为好
> 
> 我之前用他家写在官网首页上的 storemi，你选软件前五里面就有，我只想说这玩意儿用着真的可能会死人，别对 amd 有啥幻想了，好多东西都是赶鸭子上架弄得

AI方面amd就不行，打不过英伟达的CUDA生态,我当时买amd就是为了性价比，主要用来打游戏，最近玩Stable Diffusion，AMD显卡没法全性能运行。

**Comment by znsoftm** [comment]
AMD consistently champions the battles of tomorrow, not today's.

**Comment by znsoftm** [comment]
苏妈的软件一直不太灵。 The software of AMD sucks.

**Comment by Arondight** [comment]
> 苏妈的软件一直不太灵。 The software of AMD sucks.

雀食按摩店萨克斯，2080ti22g x2 的炉子花了 9000 块钱，当初要是上 4090 还能剩下不少，一声叹息，希望早日支持 windows 吧（而且不要有啥八哥），我还是很希望手里的 xtx 能发光发热的
