### ISSUE TITLE
[Documentation]: Installation error Ubuntu 22.04 workaround

### ISSUE THREAD

**Issue by FabianWildgrube** [ROCm/ROCm#2933]
### Description of errors

I ran into an issue with ROCm installation on Ubuntu 22.04 with a multi-version setup.
The following commands:
```
sudo apt update                                       
wget https://repo.radeon.com/amdgpu-install/6.0.2/ubuntu/jammy/amdgpu-install_6.0.60002-1_all.deb
sudo apt install ./amdgpu-install_6.0.60002-1_all.deb
sudo amdgpu-install --rocmrelease=6.0.2 --usecase=rocm
```
resulted in the following error during the `amdgpu-install` command:
```
Processing triggers for man-db (2.10.2-1) ...
Error! Could not locate dkms.conf file.
File: /var/lib/dkms/amdgpu/5.18.13-1577590.22.04/source/dkms.conf does not exist.
WARNING: amdgpu dkms failed for running kernel
```

I had seen this error before on older ROCm versions, so luckily I knew what to do:
```
sudo dpkg-reconfigure amdgpu-dkms
```

This could be added to the official documentation in a "Common issues" section or something similar.

**Comment by phubner** [comment]
I am running into this with WSL2 on Windows 11. You can run with `--no-dkms` but that really doesn't solve anything. I have not found any way of getting dkms loaded on my ubuntu 22.04.04 instance.

**Comment by preda** [comment]
But you don't need dkms on Ubuntu 22.04 (it runs perfectly well with the amdgpu driver that's included in the stock kernel).

**Comment by FabianWildgrube** [comment]
> But you don't need dkms on Ubuntu 22.04 (it runs perfectly well with the amdgpu driver that's included in the stock kernel).

The docs only say this:
> The installer script tries to install the kernel mode driver along with the requested use cases. This might be unnecessary as in the case of docker containers or you may wish to keep a specific version when using multi-version installation, and not have the last installed version overwrite the kernel mode driver.
> 
> To skip the installation of the kernel-mode driver add the `--no-dkms` option when calling the installer script.

Maybe this could be extended with a note that mentions --no-dkms is recommended for Ubuntu 22.04?

**Comment by phubner** [comment]
Any follow up here? I would love some verification that room on WSL2 ubuntu 22.04.04 does indeed work.

**Comment by AMD7900XTX** [comment]
> So after running `sudo amdgpu-install --usecase=rocm -y` and the dkms failing to install. I try to run `rocminfo` with this result
> 
> ```
> rocminfo
> ROCk module is NOT loaded, possibly no GPU devices
> ```
> 
> This is repeatable with `--no-dkms` in the `amdgpu-install` step.
> 
> Again this is ubuntu 22.04.04 kernel 15.5 on WSL2 windows 11.
> 
> I have a RX 7900 XTX and the latest drivers installed on the host machine. Also running a 7800X3D.

same bug with ubtunu OS，and i note that the clock of 7900XTX can reach 3200+(sclk) and 1200+(mclk),which causes the GPU broken when use rocm. 
The most important, I can't control the sclk/mclk of the GPU (kernel 6.5.x),  I can only choose sclk level by `/opt/rocm/bin/rocm-smi --setsclk LEVEL` and level 1 and 2 are 2500+, level 0 is 500+(already add amdgpu.ppfeaturemask=0xfff7ffff) .

**Comment by harkgill-amd** [comment]
Hi @phubner, have you tried installing with the wsl usecase and --no-dkms specified?
```
amdgpu-install -y --usecase=wsl,rocm --no-dkms
```

**Comment by phubner** [comment]
Hi @harkgill-amd, I will double check but when I used the `--no-dkms` previously the `rocm` commands wouldn't work. For example, running `rocm-info` did not work. 

(I will follow up)

**Comment by xaxaxa7b9** [comment]
any update on this? @phubner

**Comment by phubner** [comment]
Hey @xaxaxa7b9 I did verify that with `https://repo.radeon.com/amdgpu-install/6.1.3/ubuntu/jammy/` on `22.04` I can not at a minimum see my RTX 7900 xtx with `rocminfo`

```
*******
Agent 2
*******
  Name:                    gfx1100
  Marketing Name:          AMD Radeon RX 7900 XTX
  Vendor Name:             AMD
  Feature:                 KERNEL_DISPATCH
```

**Comment by harkgill-amd** [comment]
Hi @phubner, the beta release for WSL with ROCm is now out. Please find instructions on how to install ROCm and run PyTorch on WSL below.

1. [Install Radeon software for WSL with ROCm](https://rocm.docs.amd.com/projects/radeon/en/latest/docs/install/wsl/install-radeon.html)
2. [Install PyTorch for Radeon GPUs on WSL](https://rocm.docs.amd.com/projects/radeon/en/latest/docs/install/wsl/install-pytorch.html)

@FabianWildgrube Are you still running into this issue with the multi-version setup on ROCm 6.1.2?

**Comment by harkgill-amd** [comment]
Hi @FabianWildgrube, I tried to reproduce this issue by installing 6.2.0 and 6.1.2 in a multi-version environment but did not encounter any dkms conflicts. There are also new instructions on how to configure a multi-version installation at [Installing multiple ROCm versions](https://rocm.docs.amd.com/projects/install-on-linux/en/latest/install/native-install/multi-version-install.html#using-your-package-manager). I will close this issue for now, if you experience any issues with this new documentation, please leave a comment and I will re-open this ticket.
