### ISSUE TITLE
AMD e intel 

### ISSUE THREAD

**Issue by PedroLucasLima** [ROCm/ROCm#2937]
https://d9edb8f8-371c-4cd2-96ff-b2257831dbab-00-1uqwr22xsrkq1.kirk.replit.dev/

**Comment by nartmada** [comment]
Hi @PedroLucasLima, please complete the Issue Template when creating the GitHub ticket.  Thanks.

**Comment by nartmada** [comment]
Closing this ticket as there is no response from @PedroLucasLima.  Please complete the Issue Template if you decide to re-open this ticket.  Thanks.
