### ISSUE TITLE
[Documentation]: Missing command

### ISSUE THREAD

**Issue by seraasch** [ROCm/ROCm#2947]
### Description of errors

https://rocm.docs.amd.com/projects/install-on-linux/en/latest/how-to/native-install/ubuntu.html

Somewhere in the "Installing" section, you need to add "sudo apt update", which is missing after adding the ROCm package repo

### Attach any links, screenshots, or additional evidence you think will be helpful.

https://rocm.docs.amd.com/projects/install-on-linux/en/latest/how-to/native-install/ubuntu.html

**Comment by nartmada** [comment]
Internal ticket has been created to track the issue.

**Comment by nartmada** [comment]
Issue has been fixed in ROCm 6.1.0.  Thanks.
