### ISSUE TITLE
[Issue]: hipcc does not work with O0

### ISSUE THREAD

**Issue by noderyagever132** [ROCm/ROCm#2957]
### Problem Description

I've been trying to compile hip source code for AMD GPU RX7600 for a while now. I had some bugs in my code so I tried to compile the source code with O0 (optimization level). With the O0 optimization level - the kernel does not seem to dispatch with error code 401 (Invalid state of device - I have no clue what it means and could not find any documentation). When compiled with any other optimization level - everything seems to work fine.

I tried using the precompiled hipcc (which is installed with rocm) and even tried to compile it by myself using aomp and it doesn't work in both cases.

### Operating System

Ubunutu 20.06 LTS

### CPU

intel i5 12600

### GPU

AMD Radeon RX 7900 XT

### ROCm Version

ROCm 6.0.0

### ROCm Component

aomp, HIPCC

### Steps to Reproduce

Compile any code with hipcc -O0 and dispatch a kernel

**Comment by nartmada** [comment]
Internal ticket has been created for investigation.

**Comment by noderyagever132** [comment]
The problem was atomic PCIe - I did have support on my computer but only for one pcie port - switched a port and it worked like magic.

**Comment by RnMss** [comment]
@noderyagever132  I find '-O0' very broken. (6.0.0) I think your case worked just because you were lucky this time. For me `-O0` generate wrong results compared to `-O1` `-O2` `-O3` of hipcc and all levels including `-G` of nvcc. And 6.1.0+ is even more broken.
