### ISSUE TITLE
[Documentation]: Radeon RX 7600 XT specifications missing from architecture reference

### ISSUE THREAD

**Issue by garrdbyrd** [ROCm/ROCm#2972]
### Description of errors

The Radeon RX 7600 XT specifications are missing from architecture reference. The following specifications should be correct and can just be pasted into `docs/reference/gpu-arch/gpu-arch-spec-overview.rst` at line ~468.

```
          - Radeon RX 7600 XT
          - RDNA3
          - gfx1102
          - 16 GiB
          - 32
          - 32
          - 128 KiB
          - 32 MiB
          - 2 MiB
          - 256 KiB
          - 32 KiB
          - 16 KiB
          - 32 KiB
          - 256 KiB
          - 20 KiB
```
![radeon7600xt-missing](https://github.com/ROCm/ROCm/assets/24244993/5bc386c0-e09e-4a43-af4c-1cd250a20876)

**Comment by nartmada** [comment]
Hi @garrdbyrd, Radeon RX 7600 XT is not a support configuration.

https://rocm.docs.amd.com/projects/install-on-linux/en/latest/reference/system-requirements.html

**Comment by DarkStar-DarkGold** [comment]
> 明白了，但为什么会列出 7600、7700 XT 和 7800 XT？
hi，Is RX7600  supported by rocm?

**Comment by winfriedgerlach** [comment]
@DarkStar-DarkGold at least it is listed under [Windows supported GPUs](https://rocm.docs.amd.com/projects/install-on-windows/en/latest/reference/system-requirements.html), see also #2788
