### ISSUE TITLE
[QUESTION] Quotesion related to HSA_OVERRIDE_GFX_VERSION and optimization? 

### ISSUE THREAD

**Issue by serhii-nakon** [ROCm/ROCm#2976]
I not fully understand does this variable is solution or just trick/workaround. I mean if we can use gfx1100 code for gfx1103 or gfx1102 why just not link all this codes internally inside ROCM why it force users to use this variable? Does it produce some problem (like performance or etc) of using existing code but for another compatible GPU

Also I want to know what difference in case if I rebuild ROCM especially for gfx1102 or gfx1103, does it will produce exactly the same files like for gfx1100 but with another name or it will produce optimized code/files for specific architecture?

If it produce optimized code, what parts of already prebuilt ROCM need to rebuild - if I correctly understand it should be enough to rebuild only this packages: rocBLAS, rocFFT, rocSPARSE, MIOpen, rocRAND, rccl... is not it?

**Comment by serhii-nakon** [comment]
I ask about it because this https://salsa.debian.org/rocm-team/community/team-project/-/wikis/Supported-GPU-list#architecture-notes show that ROCM can technically work with almost all GPUs. And I need to know what best way to use ROCM for unofficially supported GPUs. Does better to rebuild or just use env variable and it will do exactly the same as for rebuild...

**Comment by GZGavinZhao** [comment]
Perhaps [this thread](https://www.reddit.com/r/ROCm/comments/1bd8vde/comment/kvux38v/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) on Reddit may answer some of your questions.

**Comment by serhii-nakon** [comment]
@GZGavinZhao Hello
Hmm, I just now have laptop with gfx1012 with pre-compiled ROCm 5.4 for especially for it, if it true that 6.1 will released with gfx1010 I will benchmark it.

**Comment by serhii-nakon** [comment]
@GZGavinZhao One more question where I can check all available gfx101* in new ROCm release? Also does it mean that Docker container will with already prebuild ML frameworks? 
Because I don't see here gfx101* https://hub.docker.com/layers/rocm/pytorch-nightly/latest/images/sha256-9520c161d80bc72132b54ebcd32bd1ac842d18ecd73099dcab81c1d5f416c7ab?context=explore

**Comment by ppanchad-amd** [comment]
@serhii-nakon gfx101* series are not supported in the latest ROCm 6.1.2 release. Thanks!

**Comment by serhii-nakon** [comment]
@ppanchad-amd Hello, yes you can
