### ISSUE TITLE
[Documentation]: Fix typo

### ISSUE THREAD

**Issue by gsitaram** [ROCm/ROCm#2989]
### Description of errors

Please fix typo "differentce" to "difference" in https://rocm.docs.amd.com/projects/HIP/en/latest/user_guide/faq.html#can-hip-api-support-c-style-application-what-is-the-differentce-between-c-and-c

**Comment by gsitaram** [comment]
Another one: initializtion

**Comment by nartmada** [comment]
Internal ticket has been created to track the fix.

**Comment by nartmada** [comment]
The issue has been fixed in ROCm 6.1.0.

https://rocm.docs.amd.com/projects/HIP/en/latest/old/user_guide/faq.html#can-hip-api-support-c-style-application-what-is-the-difference-between-c-and-c

**Comment by gsitaram** [comment]
Not this one: 
"initializtion" in https://rocm.docs.amd.com/projects/HIP/en/latest/old/user_guide/faq.html#can-hip-api-support-c-style-application-what-is-the-difference-between-c-and-c

While you are at it, could you also fix this title: 
[What is maximum limit of kernel launching parameter?](https://rocm.docs.amd.com/projects/HIP/en/latest/old/user_guide/faq.html#what-is-maximum-limit-of-kernel-launching-parameter)
to 
What are the maximum limits of kernel launch parameters?

**Comment by gsitaram** [comment]
There may be many other typos. Is there a spell check program that we can run on our documentation pages?

**Comment by nartmada** [comment]
Thanks @gsitaram.  I have notified the documentation team.

**Comment by harkgill-amd** [comment]
Hi @gsitaram, both typos have been fixed. You can find the latest revision at [Frequently asked questions](https://rocm.docs.amd.com/projects/HIP/en/latest/how-to/faq.html#can-hip-api-support-c-style-application-what-is-the-difference-between-c-and-c). Thanks!
