### ISSUE TITLE
[Documentation]: compatibility gpu v1605b

### ISSUE THREAD

**Issue by sancelot** [ROCm/ROCm#2998]
### Description of errors

Hi, It is not very clear for myself to understand if the v1605B gpu is supported, although  has (very few) cores

### Attach any links, screenshots, or additional evidence you think will be helpful.
https://www.amd.com/system/files/documents/v1000-family-product-brief.pdf
_No response_

**Comment by nartmada** [comment]
Sorry @sancelot, v1605b is vega8-based (GCN5.0) and it is not supported.

https://www.amd.com/en/product/7281
https://rocm.docs.amd.com/projects/install-on-linux/en/latest/reference/system-requirements.html
