### ISSUE TITLE
custom accelerator using rocm.

### ISSUE THREAD

**Issue by notlober** [ROCm/ROCm#3014]
can i build a custom accelerator that support rocm api to have rocm as a bridge between my hardware and the target program? will there be any problems like license or law issues? just asking.

**Comment by IMbackK** [comment]
you can def implement the hip api with no issue, its an open standart, and people have done so: https://github.com/illuhad/hipCPU hip itself is also quite small and very fesable to implement.

However to make something like pytorch work is a totally different animal and is _hard_ and a huge tonne of work as it depends on highly complex libiaries like rocBlas and miopen that are agressively machine specific to amd gpus, you will have write new, api compatable versions of those, an impossible undertakeing if your not a large team
