### ISSUE TITLE
[Feature]: Support for pytorch for ROCm 6.1 release.

### ISSUE THREAD

**Issue by kannan-scalers-ai** [ROCm/ROCm#3041]
### Suggestion Description

Currently the torch stable support is at ROCm 5.7 and nightly support is untill 6.0. The official ROCm pytorch image supports upto ROCm 6.0.2.

When can we expect a docker image release with torch on ROCm 6.1? Is there is any plan to provide ROCm 6.1 stable support on torch?

### Operating System

Ubuntu

### GPU

MI300X

### ROCm Component

ROCm

**Comment by nartmada** [comment]
@kannan-scalers-ai, 

•	When can we expect a docker image release with torch on ROCm 6.1 ?
o	Rocm/pytorch docker images will be showing up in a few days as QA is currently testing them. Generally speaking, the rocm/pytorch docker images show up a few days after GA for any ROCm release.
•	Is there any plan to provide ROCm 6.1 stable support on torch ?
o	We are currently working on getting PyTorch nightly wheels upgraded to ROCm6.1. PyTorch2.4 will be the earliest version where will have stable wheels with ROCm6.1 or later.

**Comment by kannan-scalers-ai** [comment]
@nartmada Thanks for your updates on the release timeline.
