### ISSUE TITLE
ROCm repo slow download 

### ISSUE THREAD

**Issue by Vexi23** [ROCm/ROCm#3042]
Hi, i'm from Poland as you can see on screenshot i have very slow download from ROCm repo when i download from other repo's i don't have issues, if you could fix that.

It seems like its the same issue as #2444 
![Zrzut ekranu z 2024-04-18 18-01-54](https://github.com/ROCm/ROCm/assets/126606733/9f965e92-945b-4d28-9828-c6b3cfdae0d4)

**Comment by Bocchi-Chan2023** [comment]
use apt-fast

**Comment by saadrahim** [comment]
Please let me know if you still have slow downloads tomorrow. A major change in our download infrastructure is rolling out today.

**Comment by Vexi23** [comment]
> Please let me know if you still have slow downloads tomorrow. A major change in our download infrastructure is rolling out today.

![image](https://github.com/ROCm/ROCm/assets/126606733/c9f4e179-45c6-4848-be32-f99100e298ce)

Yes, it works extremely fast now, thank you saadrahim, give my thanks to your colleagues involved in solving this issue.

**Comment by saadrahim** [comment]
Appreciate the fast feedback. I am closing this ticket as your issue is resolved.
