### ISSUE TITLE
[Issue]: rocm 6.1 not include gfx1103?

### ISSUE THREAD

**Issue by wszgrcy** [ROCm/ROCm#3059]
### Problem Description

I run command `ls /opt/rocm/lib/rocblas/library|grep 110` both native and docker(rocm 6.1). but I can't find 1103.but rocm 6.1 document mention it

### Operating System

Ubuntu 22.04.4 LTS (Jammy Jellyfish)

### CPU

 AMD Ryzen 7 8845HS w/ Radeon 780M Graphics

### GPU

780m
### ROCm Version

ROCm 6.1.0

### ROCm Component

ROCm

### Steps to Reproduce

ls /opt/rocm/lib/rocblas/library|grep 110

**Comment by nartmada** [comment]
@wszgrcy, gfx1103 is not supported in ROCm 6.1.0.

https://rocm.docs.amd.com/projects/install-on-linux/en/latest/reference/system-requirements.html

**Comment by wszgrcy** [comment]
> @wszgrcy, gfx1103 is not supported in ROCm 6.1.0.
> 
> https://rocm.docs.amd.com/projects/install-on-linux/en/latest/reference/system-requirements.html

![image](https://github.com/ROCm/ROCm/assets/9607121/154c7db3-6b2b-4725-aa2f-167a1bdc9982)
So what does this document mean by gfx1103?

**Comment by nartmada** [comment]
@wszgrcy, please share the link of your screen capture so I can follow up with internal teams.

**Comment by wszgrcy** [comment]
> @wszgrcy, please share the link of your screen capture so I can follow up with internal teams.

https://github.com/ROCm/ROCm/releases/tag/rocm-6.1.0

**Comment by kentrussell** [comment]
That's for Composable Kernel, not for the entire ROCm stack. Hence it being in the Composable Kernel documentation. It doesn't say that it supports gfx1103 on the entire ROCm stack. Just that you can use Composable Kernels in gfx1103. Because they enabled support for that in their specific component.

**Comment by jnolck** [comment]
I just noticed that fedora rawhide has a package for rocblas-gfx1103. Haven't tested it though. Check if Ubuntu has a similar package.

**Comment by NeoChen1024** [comment]
> I just noticed that fedora rawhide has a package for rocblas-gfx1103. Haven't tested it though. Check if Ubuntu has a similar package.

Ubuntu doesn't have packages similar to thoese in Fedora rawhide.
