### ISSUE TITLE
[Issue]: Proble with HSA_OVERRIDE_GFX_VERSION

### ISSUE THREAD

**Issue by Who-are-me** [ROCm/ROCm#3065]
### Problem Description

How is set HSA_OVERRIDE_GFX_VERSION for each GPU?

### Operating System

OpenSUSE Leap 15.5

### CPU

r7 2700

### GPU

AMD Radeon VII

### ROCm Version

ROCm 5.6.0

**Comment by nartmada** [comment]
Hi @Who-are-me, your "AMD Radeon VII" is a supported GPU.  You don't need to use HSA_OVERRIDE_GFX_VERSION.

**Comment by nartmada** [comment]
@Who-are-me, you can also google "how to use HSA_OVERRIDE_GFX_VERSION".  Thanks.

**Comment by Who-are-me** [comment]
Thx, but HSA_OVERRIDE_GFX_VERSION work on all GPUs, it's possible override version for one specific GPU (for example for second gpu)?

**Comment by Who-are-me** [comment]
for example for second GPU (rx 6600)

**Comment by Who-are-me** [comment]
Yes, it's possible?

**Comment by AdamNiederer** [comment]
I ran into the same issue; I believe https://github.com/ROCm/ROCT-Thunk-Interface/pull/104 would solve this.
