### ISSUE TITLE
[Issue]: hipDeviceProp_t name attribute is empty 

### ISSUE THREAD

**Issue by abagusetty** [ROCm/ROCm#3069]
### Problem Description

Reopening since the attribute name for the device string is empty with rocm-6.0.0 on MI250, MI100, MI250x. Tagging @nartmada 
```bash
HIP version: 6.0.32830-d62f6a171
AMD clang version 17.0.0 (https://github.com/RadeonOpenCompute/llvm-project roc-6.0.0 23483 7208e8d15fbf218deb74483ea8c549c67ca4985e)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /soft/compilers/rocm/rocm-6.0.0/llvm/bin
Configuration file: /soft/compilers/rocm/rocm-6.0.0/lib/llvm/bin/clang++.cfg
```

### Operating System

openSUSE Leap 15.4

### CPU

AMD EPYC 7543 32-Core Processor

### GPU

AMD Instinct MI250X, AMD Instinct MI250, AMD Instinct MI100

### ROCm Version

ROCm 6.0.0

### ROCm Component

HIP

### Steps to Reproduce

```c++
#include<iostream>
#include <hip/hip_runtime.h>
int main(){
  hipDeviceProp_t deviceProp;
  hipGetDeviceProperties(&deviceProp, 0);
  std::cout << deviceProp.name << std::endl;
}
```

### Additional Information

Mentioned in these issues: https://github.com/ROCm/ROCm/issues/1625, https://github.com/ROCm/ROCm/issues/1778

**Comment by nartmada** [comment]
@abagusetty, can you please try ROCm 6.1.0?  Thanks.
![image](https://github.com/ROCm/ROCm/assets/144284448/a98e0e5f-af27-4d21-9181-29817b1fac1f)

**Comment by ppanchad-amd** [comment]
@abagusetty Can you please try with latest ROCm 6.1.2 and let us know if you still see the issue? Thanks!

**Comment by harkgill-amd** [comment]
Hi @abagusetty, I was not able to reproduce this issue with ROCm 6.12 on a MI100 system. If you see this issue again, please re-open this ticket, thanks!
