### ISSUE TITLE
[Documentation]: link leads to 404 error

### ISSUE THREAD

**Issue by gsitaram** [ROCm/ROCm#3080]
### Description of errors

The link to the repo in this description for [hipMemcpyToSymbol](https://rocm.docs.amd.com/projects/HIP/en/latest/reference/kernel_language.html#_CPPv417hipMemcpyToSymbolPKvPKv6size_t6size_t13hipMemcpyKind) does not exist. Please scan through documentation for broken links and fix them. The link in question in this paragraph is: [ROCm/HIP](https://github.com/ROCm/HIP/blob/develop/docs/user_guide/hip_porting_guide.md). The problem seems to be the branch this link points to.

**Comment by ppanchad-amd** [comment]
@gsitaram Internal ticket has been raised to fix the broken link. Thanks!

**Comment by randyh62** [comment]
This link has been fixed. Thanks for reporting it.
