### ISSUE TITLE
[Feature]: RX 7700 XT ROCM Support

### ISSUE THREAD

**Issue by louiellywton** [ROCm/ROCm#3142]
### Suggestion Description

Please give rx 7700 xt ROCM support aswell, I want to learn deeper about AI using pytorch but I just realize that my rx 7700 xt doesn't have ROCM support. I don't want to spend lots of time using my laptop with nvidia since I'm more comfortable with my PC, and I know I can use DirectML or something else but the performance might not be as good. Please make ROCM available for rx 7700 xt aswell. Thankyou

### Operating System

Windows

### GPU

gfx1100

**Comment by ppanchad-amd** [comment]
@louiellywton I am closing this ticket here. Please re-open under 'Discussions'. Thanks
