### ISSUE TITLE
[Issue]:6.1.x default.xml loss definition of  <remote name="KhronosGroup">

### ISSUE THREAD

**Issue by SpinEch0** [ROCm/ROCm#3146]
### Problem Description

branch 6.1.x

repo init faile with wrong manifest:
```
fatal: manifest 'default.xml' not available
fatal: remote KhronosGroup not defined in .repo/manifests/default.xml
================================================================================
Repo command failed: UpdateManifestError
	Unable to sync manifest default.xml
```

### Operating System

macos

### CPU

none

### GPU

AMD Instinct MI300X

### ROCm Version

ROCm 6.1.0

### ROCm Component

ROCm

**Comment by ppanchad-amd** [comment]
@SpinEch0 Please provide OS and steps to reproduce your issue? Thanks!

**Comment by lgrz** [comment]
Remote name for `KhronosGroup` is missing from the default.xml:

https://github.com/ROCm/ROCm/pull/3098/files#diff-d9b8e4a48f8e111ec5d21480d9d33a893b365dfa7f8550bbc0577e4d42afeac8L4

**Comment by perovskikh** [comment]
I suggest https://github.com/ROCm/ROCm/pull/3172  gh pr checkout 3172

**Comment by SpinEch0** [comment]
> I suggest #3172 gh pr checkout 3172
yes, this pr solves the problem, I close the issue.

**Comment by saadrahim** [comment]
Don't close an issue until the PR is merged.

**Comment by samjwu** [comment]
added back:
https://github.com/ROCm/ROCm/blob/roc-6.1.x/default.xml#L4
