### ISSUE TITLE
mi300x supported os

### ISSUE THREAD

**Issue by Asyvix** [ROCm/ROCm#3150]
We are testing the MI300x system.

Does the MI300x support Ubuntu 22.04 with a 6.5 kernel? I am currently running it on 6.5, and it seems to be working fine with the RVS test. I am aware that the documentation states that only 5.15 is supported. Is it better to use 5.15?

**Comment by harkgill-amd** [comment]
Hi @Asyvix, it would be best to use kernel version 5.15 as it is officially supported. Other unsupported kernels may work but could lead to compatibility issues.
