### ISSUE TITLE
[Issue]: Repo not found

### ISSUE THREAD

**Issue by tsaist1** [ROCm/ROCm#3191]
### Problem Description

Install instructions for SUSE Linux does not work 
https://rocm.docs.amd.com/projects/install-on-linux/en/latest/tutorial/quick-start.html
```
sudo zypper refresh
Retrieving repository 'AMDGPU 6.1.1 repository' metadata ....................................[error]
Repository 'AMDGPU 6.1.1 repository' is invalid.
[amdgpu|https://repo.radeon.com/amdgpu/6.1.1/sle/20240524/main/x86_64] Valid metadata not found at specified URL
History:
 - [|] Error trying to read from 'https://repo.radeon.com/amdgpu/6.1.1/sle/20240524/main/x86_64'
 - Download (curl) error for 'https://repo.radeon.com/amdgpu/6.1.1/sle/20240524/main/x86_64/content':
   Error code: Curl error 56
   Error message: The requested URL returned error: 404
```

GPU: AMD Radeon RX6700S
ROCM version: 6.1.1

### Operating System

openSUSE Tumbleweed

### CPU

AMD Ryzen 9 6900HS with Radeon Graphics

### GPU

AMD Radeon RX 7900 XT

### ROCm Version

ROCm 6.1.0

**Comment by harkgill-amd** [comment]
Hi @tsaist1 openSUSE Tumbleweed is not supported by ROCm, please see a list of supported operating systems below. I could not reproduce this issue on SUSE Linux Enterprise Server. Please re-open if you see this issue on a supported OS. Thanks!

https://rocm.docs.amd.com/projects/install-on-linux/en/latest/reference/system-requirements.html
