### ISSUE TITLE
rocm-6.1.1 ./bin/repo init

### ISSUE THREAD

**Issue by perovskikh** [ROCm/ROCm#3231]
### Problem Description

error:
Repo command failed due to the following SyncFailFastError errors:
GitCommandError: 'fetch --quiet --progress KhronosGroup --prune --recurse-submodules=no --tags tag rocm-6.1.1 +refs/tags/rocm-6.1.1:refs/tags/rocm-6.1.1 +refs/tags/:refs/tags/' on OpenCL-ICD-Loader failed
stdout: fatal: couldn't find remote ref refs/tags/rocm-6.1.1
GitCommandError: 'fetch --quiet --progress KhronosGroup --prune --recurse-submodules=no --tags tag rocm-6.1.1 +refs/tags/rocm-6.1.1:refs/tags/rocm-6.1.1 +refs/tags/:refs/tags/' on OpenCL-ICD-Loader failed
stdout: fatal: couldn't find remote ref refs/tags/rocm-6.1.1 

Solution:
OpenCL-Runtime Environment is archived https://github.com/ROCm/ROCm-OpenCL-Runtime located in default.xml but it is not needed there, it has been replaced by clr https://github.com/ROCm/clr

Please take a look https://github.com/ROCm/ROCm/pull/3205 . I've checked everything works with these fixes. The full rocm 6.1.1 with all components has been downloaded.

### Operating System

ubuntu 22.04

### CPU

amd ryzen 5500

### GPU

AMD Radeon VII

### ROCm Version

ROCm 6.1.0

**Comment by ppanchad-amd** [comment]
@perovskikh Please confirm if this ticket can be close now. Thanks!

**Comment by harkgill-amd** [comment]
Closing ticket as fix has been implemented here https://github.com/ROCm/ROCm/commit/b2f0f0acdf56c3c9f7a1b34460f97d3e225a6b58. Please open a new ticket if you encounter this issue with ROCm 6.1.2, thanks!
