### ISSUE TITLE
[Documentation]: link to rocm.docs.amd.com is broken

### ISSUE THREAD

**Issue by ckuethe** [ROCm/ROCm#3355]
### Description of errors

The link to the rocm doc site at readthedocs is broken. rocm.docs.amd.com redirects to advanced-micro-devices-demo.readthedocs-hosted.com which throws a 404.

I also don't find any obvious "rocm" top level site when searching RTD for rocm... https://readthedocs.org/search/?q=rocm

### Attach any links, screenshots, or additional evidence you think will be helpful.

![Screenshot_2024-06-24_09-48-50](https://github.com/ROCm/ROCm/assets/1131751/88e39d65-ebed-4350-a1f6-def6d9b24869)

**Comment by harkgill-amd** [comment]
Hi @ckuethe, could you please check if you are still seeing an issue with the link? There was a system level update in the morning which may have caused this issue.

**Comment by ckuethe** [comment]
I am now able to see https://rocm.docs.amd.com/en/latest/. Thanks!
