### ISSUE TITLE
[Issue]: 

### ISSUE THREAD

**Issue by FLAKDaddy** [ROCm/ROCm#3413]
### Problem Description

when I run `rocminfo`
I got back this result:
`ROCR: unsupported GPU`
`hsa api call failure at: ./sources/wsl/tools/rocminfo/rocminfo.cc:1087
Call returned HSA_STATUS_ERROR_OUT_OF_RESOURCES: The runtime failed to allocate the necessary resources. This error may also occur when the core runtime library needs to spawn threads or create internal OS-specific events.`

Using WSL
NAME="Ubuntu"
VERSION="22.04.3 LTS (Jammy Jellyfish)"

GPU: 7600XT

### Operating System

Ubuntu 22.04.3 LTS (Jammy Jellyfish)

### CPU

AMD 5600x

### GPU

AMD Radeon RX 7900 XT

### ROCm Version

ROCm 6.1.0

### Steps to Reproduce

Using WSL
NAME="Ubuntu"
VERSION="22.04.3 LTS (Jammy Jellyfish)"

GPU: 7600XT

Attempted install of ollama docker rocm
pulled image but upon running...
`docker: Error response from daemon: error gathering device information while adding custom device "/dev/kfd": no such file or directory.`

So I followed this doc: https://rocm.docs.amd.com/projects/radeon/en/latest/docs/install/wsl/install-radeon.html#post-install-verification-check

used the WSL usecase

Install seemed okay, only hiccup was:
`"WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv"`

BUT when I ran `rocminfo`
I got back this result:
`ROCR: unsupported GPU`
`hsa api call failure at: ./sources/wsl/tools/rocminfo/rocminfo.cc:1087
Call returned HSA_STATUS_ERROR_OUT_OF_RESOURCES: The runtime failed to allocate the necessary resources. This error may also occur when the core runtime library needs to spawn threads or create internal OS-specific events.`

### Additional Information

I couldn't select my GPU but afaik the 7600xt is supported?

**Comment by FLAKDaddy** [comment]
oh, looks like a shorter list for WSL
https://rocm.docs.amd.com/projects/radeon/en/latest/docs/compatibility/wsl/wsl_compatibility.html

**Comment by harkgill-amd** [comment]
Hi @FLAKDaddy , the beta release of ROCm on WSL only supports the GPUs listed under [compatibility matrices](https://rocm.docs.amd.com/projects/radeon/en/latest/docs/compatibility/wsl/wsl_compatibility.html). Unfortunately, the 7600XT is not currently supported for WSL.

**Comment by Jameson-Crate** [comment]
I saw for previous versions of ROCm people were able to use HSA_OVERRIDE_GFX_VERSION=10.3.0 as a work around, is there anything similar for this version of ROCm or do we just have to wait around for support?

**Comment by A-Ghorab** [comment]
> I saw for previous versions of ROCm people were able to use HSA_OVERRIDE_GFX_VERSION=10.3.0 as a work around, is there anything similar for this version of ROCm or do we just have to wait for support?

nope, https://github.com/ROCm/ROCm/issues/3402#issuecomment-2218312649

but according to that post soon more SKU will be supported

**Comment by brianangulo** [comment]
> Hi @FLAKDaddy , the beta release of ROCm on WSL only supports the GPUs listed under [compatibility matrices](https://rocm.docs.amd.com/projects/radeon/en/latest/docs/compatibility/wsl/wsl_compatibility.html). Unfortunately, the 7600XT is not currently supported for WSL.

Hey @harkgill-amd sorry to be a bug. But just curious on the reason for limiting to certain SKUs only? Is this a sort of soft limitation due to lack of testing on these otherGPUs? Just wondering if maybe there is some setting or configuration that by building rocm from source could be modified to allow support for something like a 7800 (which is kinda crazy is not supported to begin with tbh). Thankful for any guidance you can share on this 🙏.

**Comment by harkgill-amd** [comment]
Hi @brianangulo, unfortunately this is a hard limitation in WSL and cannot be worked around. Please refer to https://github.com/ROCm/ROCm/discussions/2599 for more information.
