### ISSUE TITLE
What is the suggested repository for using `bitsandbytes` with a ROCm backend?

### ISSUE THREAD

**Issue by garrettbyrd** [ROCm/ROCm#3447]
AMD has forked `bitsandbytes` [here](https://github.com/ROCm/bitsandbytes). There was a [bit of confusion](https://github.com/ROCm/ROCm/issues/3132) regarding the installation and usage of this fork and its `rocm_enabled` branch; I have not tested this fork/branch within a week or so, but it seems that it is still unclear if this will work out of the box, or even if this is the correct fork/branch to be using.

The developers at the [upstream branch](https://github.com/bitsandbytes-foundation/bitsandbytes) have recently released the `bitsandbytes/multi-backend-refactor` branch ([link](https://github.com/bitsandbytes-foundation/bitsandbytes/tree/multi-backend-refactor?tab=readme-ov-file)) that is in the testing phase for supporting AMD GPUs and Intel GPUs.

Which of these two, between `ROCm/bitsandbytes` and `bitsandbytes-foundation/bitsandbytes` should be considered the go-to? Is AMD contributing to the upstream branch? If not, why? What has been developed for the ROCm branch that is not in the `multi-backend-refactor` upstream branch?

**Comment by ppanchad-amd** [comment]
@garrettbyrd Internal ticket is created to assist with your issues. Thanks!

**Comment by schung-amd** [comment]
Hi @garrettbyrd, I reached out to the internal team handling `ROCm/bitsandbytes`. Changes to the AMD fork are also pushed to the `multi-backend-refactor` upstream branch, so you should be able to use either. I can see from your linked open issue (https://github.com/ROCm/ROCm/issues/3132) that you're having install or configuration issues with `ROCm/bitsandbytes`. If you decide to try the `multi-backend-refactor` upstream branch and experience similar issues, please comment on this in your existing issue or open a new issue.

If this answers your question, you can close this issue. If not or if there are any additional items you'd like clarified, you can reach out to me here or to @pnunna93 in your existing issue. Thanks!

**Comment by saadrahim** [comment]
@schung-amd can you check where this will be documented for posterity? This question may be repeated by others.

**Comment by schung-amd** [comment]
@saadrahim Great suggestion, thanks. Incorporation of the ROCm fork to the upstream branch was noted [here](https://github.com/bitsandbytes-foundation/bitsandbytes/issues/1271), but this isn't the most visible; I'm reaching out to @pnunna93 to see if we can get something added to the description of the ROCm fork.

**Comment by garrettbyrd** [comment]
@schung-amd Thanks for the information. I will be happy to close if/once something is added to the description of the ROCm fork, as you suggested.

**Comment by pnunna93** [comment]
I have updated our fork to reflect this. Thanks for the feedback @garrettbyrd!

**Comment by garrettbyrd** [comment]
@pnunna93 Lovely! Thanks for the addition.
