### ISSUE TITLE
[Feature]: Support of ROCm libraries on RHEL 9.4

### ISSUE THREAD

**Issue by varshaprasad96** [ROCm/ROCm#3456]
### Suggestion Description

According to the [ROCm documentation](https://rocm.docs.amd.com/projects/install-on-linux/en/latest/how-to/native-install/rhel.html#register-repositories), it appears that RHEL 9.4 is currently supported exclusively on the AMD Instinct MI300A GPU. We are interested in knowing when support for RHEL 9.4 will be extended to other GPU types? (like the AMD Instinct MI210).

Could you please provide a timeline or any planned updates regarding ROCm support for RHEL 9.4?

### Operating System

RHEL 9.4

**Comment by harkgill-amd** [comment]
Hi @varshaprasad96, with the release of ROCm 6.2, support on RHEL 9.4 has been extended to all GPUs listed at [Supported GPUs](https://rocm.docs.amd.com/en/latest/compatibility/compatibility-matrix.html). For a more complete overview of OS support across past and present releases, please visit the [Compatibility Matrix](https://rocm.docs.amd.com/en/latest/compatibility/compatibility-matrix.html).
