### ISSUE TITLE
[Question] What's the status of monitoring tooling of AMD GPU

### ISSUE THREAD

**Issue by yx-lamini** [ROCm/ROCm#3481]
Things equivalent to NVIDIA DCGM (and DCGM exporter), are they available (I couldn't find any).
Would like to have an authoritative description.

Additionally, what are the roadmap in this area?

(Please kindly let me know if this question should go to a different repo/venue)

**Comment by kentrussell** [comment]
I think what you're looking for is https://github.com/ROCm/rdc . You can raise any requests there for more information, but that's the ROCm Data Centre tool and should be the closest offering to the DCGM

**Comment by yx-lamini** [comment]
I think there is a poor discoverability.

https://github.com/ROCm/rdc
This thing never popped up to me.
I googled amd gpu monitoring, searched on github, and generally have been searching for monitoring tools for AMD GPUs. This repo never appear in the results.

Please consider expand the reference to various tools.
