### ISSUE TITLE
[Issue]: Memcpy to device burns 100% CPU in WaitRelaxed if long-running kernels are present

### ISSUE THREAD

**Issue by FeepingCreature** [ROCm/ROCm#3483]
**Edit** for future readers who find this on Google:

# This is intentional behavior!

CUDA does the same thing. Google `hipSetDeviceFlags(hipDeviceScheduleBlockingSync)` for how to turn it off.

### Problem Description

I've run into this with ComfyUI, but there's been variants of this issue a few times already (just search the issues for `WaitRelaxed`), but there's usually been some other issue that was fixed eventually, so I want to go ahead and file a bug for *just* `WaitRelaxed` burning 100% CPU.

As far as I can tell, this goes back to `DmaBlitManager::hsaCopyStaged` calling `releaseMemoryFence`, which, via `CpuWaitForSignal`, goes into a `HSA_WAIT_STATE_ACTIVE` `WaitRelaxed` call, which then spends 80% of CPU load on the `now()` call in the loop. To add insult to injury, `g_enable_mwaitx` has somehow become `false` even though my CPU definitely supports it.

So it just hot-busyloops for many milliseconds waiting for the kernel to finish.

### Operating System

Ubuntu 24.04

### CPU

AMD Ryzen 7950X3D

### GPU

AMD Radeon RX 7900 XTX

### ROCm Version

ROCm 6.1.0

### ROCm Component

clr

### Steps to Reproduce

- Launch ComfyUI
- Set latent size to 2048x2048 to ensure some nice long-running kernels
- Queue Prompt
- Observe high CPU load.
- Observe `rdtsc` taking >80% in profiler.

### (Optional for Linux users) Output of /opt/rocm/bin/rocminfo --support

ROCk module is loaded
=====================    
HSA System Attributes    
=====================    
Runtime Version:         1.13
Runtime Ext Version:     1.4
System Timestamp Freq.:  1000.000000MHz
Sig. Max Wait Duration:  18446744073709551615 (0xFFFFFFFFFFFFFFFF) (timestamp count)
Machine Model:           LARGE                              
System Endianness:       LITTLE                             
Mwaitx:                  DISABLED
DMAbuf Support:          YES

==========               
HSA Agents               
==========               
*******                  
Agent 1                  
*******                  
  Name:                    AMD Ryzen 9 7950X3D 16-Core Processor
  Uuid:                    CPU-XX                             
  Marketing Name:          AMD Ryzen 9 7950X3D 16-Core Processor
  Vendor Name:             CPU                                
  Feature:                 None specified                     
  Profile:                 FULL_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        0(0x0)                             
  Queue Min Size:          0(0x0)                             
  Queue Max Size:          0(0x0)                             
  Queue Type:              MULTI                              
  Node:                    0                                  
  Device Type:             CPU                                
  Cache Info:              
    L1:                      32768(0x8000) KB                   
  Chip ID:                 0(0x0)                             
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   5759                               
  BDFID:                   0                                  
  Internal Node ID:        0                                  
  Compute Unit:            32                                 
  SIMDs per CU:            0                                  
  Shader Engines:          0                                  
  Shader Arrs. per Eng.:   0                                  
  WatchPts on Addr. Ranges:1                                  
  Features:                None
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: FINE GRAINED        
      Size:                    32568860(0x1f0f61c) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: KERNARG, FINE GRAINED
      Size:                    32568860(0x1f0f61c) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 3                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    32568860(0x1f0f61c) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
  ISA Info:                
*******                  
Agent 2                  
*******                  
  Name:                    gfx1100                            
  Uuid:                    GPU-7b8755ac387dcb5c               
  Marketing Name:          Radeon RX 7900 XTX                 
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128(0x80)                          
  Queue Min Size:          64(0x40)                           
  Queue Max Size:          131072(0x20000)                    
  Queue Type:              MULTI                              
  Node:                    1                                  
  Device Type:             GPU                                
  Cache Info:              
    L1:                      32(0x20) KB                        
    L2:                      6144(0x1800) KB                    
    L3:                      98304(0x18000) KB                  
  Chip ID:                 29772(0x744c)                      
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   2526                               
  BDFID:                   768                                
  Internal Node ID:        1                                  
  Compute Unit:            96                                 
  SIMDs per CU:            2                                  
  Shader Engines:          6                                  
  Shader Arrs. per Eng.:   2                                  
  WatchPts on Addr. Ranges:4                                  
  Coherent Host Access:    FALSE                              
  Features:                KERNEL_DISPATCH 
  Fast F16 Operation:      TRUE                               
  Wavefront Size:          32(0x20)                           
  Workgroup Max Size:      1024(0x400)                        
  Workgroup Max Size per Dimension:
    x                        1024(0x400)                        
    y                        1024(0x400)                        
    z                        1024(0x400)                        
  Max Waves Per CU:        32(0x20)                           
  Max Work-item Per CU:    1024(0x400)                        
  Grid Max Size:           4294967295(0xffffffff)             
  Grid Max Size per Dimension:
    x                        4294967295(0xffffffff)             
    y                        4294967295(0xffffffff)             
    z                        4294967295(0xffffffff)             
  Max fbarriers/Workgrp:   32                                 
  Packet Processor uCode:: 202                                
  SDMA engine uCode::      20                                 
  IOMMU Support::          None                               
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    25149440(0x17fc000) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:2048KB                             
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: EXTENDED FINE GRAINED
      Size:                    25149440(0x17fc000) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:2048KB                             
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 3                   
      Segment:                 GROUP                              
      Size:                    64(0x40) KB                        
      Allocatable:             FALSE                              
      Alloc Granule:           0KB                                
      Alloc Recommended Granule:0KB                                
      Alloc Alignment:         0KB                                
      Accessible by all:       FALSE                              
  ISA Info:                
    ISA 1                    
      Name:                    amdgcn-amd-amdhsa--gfx1100         
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Size:      1024(0x400)                        
      Workgroup Max Size per Dimension:
        x                        1024(0x400)                        
        y                        1024(0x400)                        
        z                        1024(0x400)                        
      Grid Max Size:           4294967295(0xffffffff)             
      Grid Max Size per Dimension:
        x                        4294967295(0xffffffff)             
        y                        4294967295(0xffffffff)             
        z                        4294967295(0xffffffff)             
      FBarrier Max Size:       32                                 
*** Done ***

**Comment by ppanchad-amd** [comment]
@FeepingCreature Internal ticket has been created to investigate this issue. Thanks!

**Comment by schung-amd** [comment]
Hi @FeepingCreature, are you able to reproduce this on ROCm 6.2? Also, to clarify, does your kernel proceed while the CPU is spinning or are you getting a hang? I'm currently investigating some other issues with DMA and this might be related. Thanks!

**Comment by FeepingCreature** [comment]
It's proceeding fine, the Python process is just additionally sitting on high CPU. Yes this happens  on 6.2, the dropdown just didn't have that as an option when I filed the bug.

**Comment by schung-amd** [comment]
Thanks for the quick response! A few follow-up questions: Is this a new issue you're running into, or have you experienced this CPU spin with multiple configurations (i.e. on other distros, older versions, or on other hardware)? Is the CPU usage constantly high throughout? Does this issue appear only on large workloads like the one you've provided, or are you seeing the CPU spin on smaller tasks as well?

**Comment by FeepingCreature** [comment]
I've always seen Python at high CPU load with ComfyUI, but I never looked at it in a profiler before so I can't confirm it's the same function. Also to be safe I just reproed the issue on a clean ComfyUI install with AnythingXL. Also, the issue seems constant no matter how big I make the tasks, ie. if I run 256x256 for 200 steps, rdtsc still dominates the profiler, though a lot more is burned in pure Python: in that one, rdtsc sits at 18%. Which is still a lot! I suspect the 80% are burnt by Python before Rocm gets a chance to burn it. Only thing I could do to make it cleaner is boot into a Livecd, does that seem worthwhile? Also, do you want me to just upload a perf capture somewhere?

**Comment by schung-amd** [comment]
I think a clean install could be helpful just to cover all the bases, but I don't think it's likely to fix your problem, so that's up to your discretion. A configuration issue is possible since high CPU usage doesn't seem to be commonly reported for this workflow, but that could manifest from sources outside of the ROCm install. A profile would be interesting; one possibility is that the spinlock is intentional but the memory transfer that's blocking is taking longer than it should. What settings are you using in ComfyUI, so I can try to reproduce your exact issue?

**Comment by FeepingCreature** [comment]
It happens with the default workflow. I'm testing with AnythingXL, but I really doubt it depends on which SDXL checkpoint you use. I'm trying to set up a clean 22.04 boot and rocm/pytorch install off the 22.04.2 livecd on my end currently, will report back how that behaves.

**Comment by FeepingCreature** [comment]
Yep, reproduced on a livecd chroot. I haven't done these *exact* steps, but that suggests this should work:

1. Install Ubuntu 22.04.4
2. `apt update`
3. `apt full-upgrade`
4. `apt install "linux-headers-$(uname -r)" "linux-modules-extra-$(uname -r)"`
5. `usermod -a -G render,video $LOGNAME`
6. `wget https://repo.radeon.com/amdgpu-install/6.2/ubuntu/jammy/amdgpu-install_6.2.60200-1_all.deb`
7. `apt install ./amdgpu-install_6.2.60200-1_all.deb`
8. `apt update`
9. `apt install amdgpu-dkms rocm`
10. `modprobe amdgpu`
11. `apt install linux-tools-common linux-tools-5.15.0-94-generic # for perf`
12. `apt install python3-pip`
13. `pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/rocm6.1
14. `git clone https://github.com/comfyanonymous/ComfyUI.git`
15. `cd ComfyUI`
16. `pip3 install -r requirements.txt`
17. download a model such as SDXL or https://civitai.com/models/9409/or-anything-xl to `models/checkpoints`
18. `python3 main.py --listen`
19. confirm that running with 1024x1024 evinces 100% CPU load in `htop` while the KSampler in the default workflow is running, and that `libhsa-runtime64.so` tops the chart in `perf top`
20. `apt install hsa-rocr-dbgsym`
21. give torch the system libhsa runtime so we can profile it
22. `/home/ubuntu-server/.local/lib/python3.10/site-packages/torch/lib/libhsa-runtime64.so`
23. `ln -s /opt/rocm-6.2.0/lib/libhsa-runtime64.so.1.14.60200 /home/ubuntu-server/.local/lib/python3.10/site-packages/torch/lib/libhsa-runtime64.so`
24. observe that `rocr::core::InterruptSignal::WaitRelaxed` leads the chart while ComfyUI runs.

**Comment by schung-amd** [comment]
Thanks for the detailed reproduction instructions! My setup is on Ubuntu 22.04 with ROCm 6.2, with a 7900XTX and 5995WX. I set up ComfyUI with Anything XL and ran it with latent size 1024x1024. Instead of using the nightly torch builds, however, I used specific versions of torch, torchvision, and triton confirmed for ROCm 6.2 support:
```
wget https://repo.radeon.com/rocm/manylinux/rocm-rel-6.2/torch-2.3.0%2Brocm6.2.0-cp310-cp310-linux_x86_64.whl
wget https://repo.radeon.com/rocm/manylinux/rocm-rel-6.2/torchvision-0.18.0%2Brocm6.2.0-cp310-cp310-linux_x86_64.whl
wget https://repo.radeon.com/rocm/manylinux/rocm-rel-6.2/pytorch_triton_rocm-2.3.0%2Brocm6.2.0.1540b42334-cp310-cp310-linux_x86_64.whl
pip3 uninstall torch torchvision pytorch-triton-rocm numpy
pip3 install torch-2.3.0+rocm6.2.0-cp310-cp310-linux_x86_64.whl torchvision-0.18.0+rocm6.2.0-cp310-cp310-linux_x86_64.whl pytorch_triton_rocm-2.3.0+rocm6.2.0.1540b42334-cp310-cp310-linux_x86_64.whl numpy==1.26.4
```
With this setup, single CPU threads occasionally spin up to 100%, but only one thread at a time. After looking into the source code in our stack where you've pointed (i.e. the `WaitRelaxed` call), I believe this is intended behavior, as the thread is spinlocking waiting for a memory transfer to complete. If you're observing more than one thread spinning, try those versions of torch, torchvision, and triton.

**Comment by FeepingCreature** [comment]
It sort of looks like WaitRelaxed is supposed to be switching to an event-based sleep. I'm not sure why it doesn't happen.

**Comment by FeepingCreature** [comment]
The matter is starting to clear up. Apparently `hipSetDeviceFlags` lets you deliberately opt in to this behavior. Trying to figure out who sets this and why.

**Comment by FeepingCreature** [comment]
Resolution! Apparently this is behavior that's been copied from CUDA, where it also occurs. https://github.com/pytorch/pytorch/issues/28224 So I just have to figure out how to `hipSetDeviceFlags(hipDeviceScheduleBlockingSync)` from Python somehow.

For skimming future readers:

# This is intentional behavior.

**Comment by FeepingCreature** [comment]
```
import ctypes

# Load the HIP runtime library
hip = ctypes.CDLL('libamdhip64.so')

# Define the function prototype
hip.hipSetDeviceFlags.argtypes = [ctypes.c_uint]
hip.hipSetDeviceFlags.restype = ctypes.c_int

# Define the flag value
cudaDeviceScheduleBlockingSync = 0x04

# Call hipSetDeviceFlags
result = hip.hipSetDeviceFlags(cudaDeviceScheduleBlockingSync)

# Check the result
if result != 0:
    print(f"hipSetDeviceFlags failed with error code {result}")
else:
    print("hipSetDeviceFlags succeeded")
```

I dropped this code (thanks Claude 3.5 Sonnet!) at the top of main.py, and CPU load drops to 10% with 1024x1024. Problem solved. Sorry for wasting your time.

**Comment by schung-amd** [comment]
Thanks for the deep dive! I'm glad you found a workaround for your system, and for future readers who also find this to be an issue. I'll make a note of this internally so we can take a closer look if/when it becomes higher priority.

As for the documentation issue, do you mean that you've tried setting hipDeviceScheduleYield and it doesn't have the same function, or hipDeviceScheduleYield is being set internally somewhere when hipDeviceScheduleBlockingSync should be set, or something else?

**Comment by FeepingCreature** [comment]
No, the docs currently say that BlockingSync does not have any effect other than Yield. BlockingSync does a blocking sync, because it sets `device->setActiveWait(false)`. `Yield` and `Spin` are the ones that have the same effect.

**Comment by schung-amd** [comment]
I see, I'll bring that up to the internal team, thanks!
