### ISSUE TITLE
[Feature]: Z1 | Z1 Extreme support

### ISSUE THREAD

**Issue by ZZ0R0** [ROCm/ROCm#3484]
### Suggestion Description

Hello, 
Is there any plans to support ROCm drivers on recent APUs Z1 or Z1 Extreme ?
Have a good day

### Operating System

Ubuntu/Debian

### GPU

Z1 Extreme

**Comment by ppanchad-amd** [comment]
@ZZ0R0 Please open this ticket under 'Discussions'. Closing ticket. Thanks!
