### ISSUE TITLE
Omniperf out-of-the-box issues with ROCm 6.2.0

### ISSUE THREAD

**Issue by peterjunpark** [ROCm/ROCm#3498]
**Error when running Omniperf with an application with command line arguments**. As a workaround, create an intermediary script to call the application with the necessary arguments, then call the script with Omniperf. This issue is fixed in a future release of Omniperf. See [#347](https://github.com/ROCm/omniperf/issues/347).

---

**Omniperf might not work with AMD Instinct MI300 accelerators out of the box**, resulting in the following error: “ERROR gfx942 is not enabled rocprofv1. Available profilers include: [‘rocprofv2’]”. As a workaround, add the environment variable export ROCPROF=rocprofv2.

---

**Omniperf’s Python dependencies may not be installed with your ROCm installation**, resulting in the following message:

“[ERROR] The ‘dash>=1.12.0’ package was not found in the current execution environment.

[ERROR] The ‘dash-bootstrap-components’ package was not found in the current execution environment.

Please verify all of the Python dependencies called out in the requirements file are installed locally prior to running omniperf.

See: /opt/rocm-6.2.0/libexec/omniperf/requirements.txt”

As a workaround, install these Python requirements manually: pip install /opt/rocm-6.2.0/libexec/omniperf/requirements.txt.

**Comment by harkgill-amd** [comment]
Both **Error when running Omniperf with an application with command line arguments** and **Omniperf might not work with AMD Instinct MI300 accelerators out of the box** have been resolved as of ROCm 6.3.0 and no longer require any workarounds. 

Installing Python dependencies using `requirements.txt` has also now been documented in the [ROCm Compute Profiler installation guide](https://rocm.docs.amd.com/projects/rocprofiler-compute/en/latest/install/core-install.html#install-via-package-manager). This will avoid the errors highlighted in **Omniperf’s Python dependencies may not be installed with your ROCm installation**.

Closing out these known issues as they have been addressed.
