### ISSUE TITLE
[Documentation]: Broken links in ROCm 6.2.0 Release notes

### ISSUE THREAD

**Issue by xelibrion** [ROCm/ROCm#3512]
### Description of errors

Section: PyTorch support for Autocast
Sentence: For more information, see
[Automatic mixed precision](https://rocm.docs.amd.com/en/docs-6.2.0/how-to/rocm-for-ai/train-a-model#automatic-mixed-precision-amp).

### Attach any links, screenshots, or additional evidence you think will be helpful.

![Uploading Screenshot 2024-08-03 at 9.33.59 AM.png…]()

**Comment by Sabrewarrior** [comment]
I can see the missing .html before #automatic-mixed-precision-amp in [6.2.0.md](https://github.com/ROCm/ROCm/blob/71a306d62a0a15627e447f287ee198802fc285ed/tools/autotag/templates/highlights/6.2.0.md?plain=1#L118) line 118, not really sure where its used on the website though.

**Comment by harkgill-amd** [comment]
Thank you @xelibrion and @Sabrewarrior! The links have been fixed in [RELEASE.md](https://github.com/ROCm/ROCm/blob/develop/RELEASE.md) and will be fixed for [6.2.0.md](https://github.com/ROCm/ROCm/blob/develop/tools/autotag/templates/highlights/6.2.0.md?plain=1) shortly as well.

**Comment by harkgill-amd** [comment]
Both instances of broken links have now been fixed, will close out the ticket. Thanks again for the help.
