### ISSUE TITLE
[Documentation]: Windows release versioning

### ISSUE THREAD

**Issue by bdenhollander** [ROCm/ROCm#3540]
### Description of errors

ROCm release versioning should be updated to mention 6.0 and 6.1.

| ROCm version | Linux support | Windows support |
-- | -- | --
5.5 | ✅ | ✅
5.6 | ✅ | ❌
5.7 | ✅ | ✅
6.0 | ✅ | ❌
6.1 | ✅ | ✅
6.2 | ✅ | 

### Attach any links, screenshots, or additional evidence you think will be helpful.

https://rocm.docs.amd.com/projects/install-on-windows/en/latest/conceptual/release-versioning.html

**Comment by harkgill-amd** [comment]
Hi @bdenhollander, thank you for bringing this to our attention. I will forward this to our documentation team.

**Comment by harkgill-amd** [comment]
Hi @bdenhollander, the documentation at [ROCm Release Versioning](https://rocm.docs.amd.com/projects/install-on-windows/en/latest/conceptual/release-versioning.html) has been updated! Could you please take a look and close out the issue if everything looks good.
