### ISSUE TITLE
[Documentation]: Current device requirements for HIP API calls

### ISSUE THREAD

**Issue by sogartar** [ROCm/ROCm#3543]
I would like to know what HIP API functions require the current device to match the one from explicit arguments like streams or graphs.

For example `hipFreeAsync`. Does it require the current device to match the one associated with the stream argument?
There are some obvious functions that would depend on the current device, like `hipMalloc`.
It seems the [HIP documentation](https://rocm.docs.amd.com/projects/HIP/en/latest/) is lacking this information.
I am concerned for pretty much all functions from the API. Does the omission of restrictions in the doc mean it is allowed?

**Comment by harkgill-amd** [comment]
Hi @sogartar, let me look into your query and circle back to you.

**Comment by schung-amd** [comment]
Closing this, feel free to comment if you need additional guidance on HIP API calls taking explicit stream arguments.
