### ISSUE TITLE
[Documentation]: MI250X Peak Flops typo

### ISSUE THREAD

**Issue by ausellis0** [ROCm/ROCm#3547]
### Description of errors

AMD Instinct™ MI250 microarchitecture page

`Therefore, the theoretical maximum FP64 peak performance per GCD is 45.3 TFLOPS for vector instructions.`
should be
`Therefore, the theoretical maximum FP64 peak performance for both GCDs is 45.3 TFLOPS for vector instructions.`
or
`Therefore, the theoretical maximum FP64 peak performance per GCD is 22.6 TFLOPS for vector instructions.`

### Attach any links, screenshots, or additional evidence you think will be helpful.

https://rocm.docs.amd.com/en/latest/conceptual/gpu-arch/mi250.html

**Comment by harkgill-amd** [comment]
Hi @ausellis0, thank you for reporting this issue. I'll verify this and get back to you.

**Comment by harkgill-amd** [comment]
@ausellis0, the documentation has been updated to the following:

`Therefore, the theoretical maximum FP64 peak performance per GCD is 22.6 TFLOPS for vector instructions. This equates to 45.3 TFLOPS for vector instructions for both GCDs together.`

Please close out the ticket if everything looks good at [AMD Instinct™ MI250 microarchitecture](https://rocm.docs.amd.com/en/latest/conceptual/gpu-arch/mi250.html).
