### ISSUE TITLE
[Feature]: Is there a plan to support newer versions of torch via wsl 2

### ISSUE THREAD

**Issue by Kademo15** [ROCm/ROCm#3571]
### Suggestion Description

Currently, only PyTorch 2.1 is supported via WSL 2. However, there have been significant improvements in newer versions of PyTorch that would greatly benefit users working with WSL 2.

Could you please provide any information or roadmap regarding when or if support for these newer versions might be available? 

### Operating System

windows via wsl 2

### GPU

rx7900xtx

**Comment by harkgill-amd** [comment]
@Kademo15, unfortunately, I can't provide a timeline at this moment. There is currently work being done to extend support to 6.2 and I will provide more updates as soon as they're available.

**Comment by evshiron** [comment]
You can install newer PyTorch from PyPI in WSL by running the command for Linux, as long as you replace that `libhsa-runtime64.so` after installing with the script ([source](https://rocm.docs.amd.com/projects/radeon/en/latest/docs/install/wsl/install-pytorch.html)):

```
location=`pip show torch | grep Location | awk -F ": " '{print $2}'`
cd ${location}/torch/lib/
rm libhsa-runtime64.so*
cp /opt/rocm/lib/libhsa-runtime64.so.1.2 libhsa-runtime64.so
```

If you compile PyTorch in WSL, the above steps can be ignored.

**Comment by githust66** [comment]
> You can install newer PyTorch from PyPI in WSL by running the command for Linux, as long as you replace that `libhsa-runtime64.so` after installing with the script ([source](https://rocm.docs.amd.com/projects/radeon/en/latest/docs/install/wsl/install-pytorch.html)):
> 
> ```
> location=`pip show torch | grep Location | awk -F ": " '{print $2}'`
> cd ${location}/torch/lib/
> rm libhsa-runtime64.so*
> cp /opt/rocm/lib/libhsa-runtime64.so.1.2 libhsa-runtime64.so
> ```
> 
> If you compile PyTorch in WSL, the above steps can be skipped.

Hi, is it possible to use rocm 6.1 with a higher version of pytorch on wsl, such as 2.4.0?

**Comment by evshiron** [comment]
> Hi, is it possible to use rocm 6.1 with a higher version of pytorch on wsl, such as 2.4.0?

Definitely. Just install PyTorch for ROCm and run the script above.

**Comment by githust66** [comment]
> > Hi, is it possible to use rocm 6.1 with a higher version of pytorch on wsl, such as 2.4.0?
> 
> Definitely. Just install PyTorch for ROCm and run the script above.

I tried it today, and after upgrading pytorch, Execute python 3-c' import torch; print (torch.cuda. is _ available () output is false. can you give me an upgrade step

**Comment by evshiron** [comment]
@githust66 

https://asciinema.org/a/VRT7DVw2QZxq0DlIgzoAOeiv2

**Comment by Kademo15** [comment]
@githust66 i just tried it following the normal steps and it worked without any issues. Make sure you are still in the venv when doing the runtime64 patch.

**Comment by githust66** [comment]
> @githust66
> 
> [pytorch/pytorch#133259](https://github.com/pytorch/pytorch/issues/133259)
I can't use amd-smi and rocm-smi on wsl, only rocminfo can.

**Comment by githust66** [comment]
> @githust66
> 
> > I can't use amd-smi and rocm-smi on wsl, only rocminfo can.
> 
> Me too. Could you read the discover part in that issue again?
> 
> pip3 uninstall amdsmi nvidia-ml-py

![image](https://github.com/user-attachments/assets/4ca7f3c0-b629-4bbf-a417-883536ae1e31)
Will there be any impact if you uninstall it?,If there is a problem, will the environment become normal if you install it back?

**Comment by evshiron** [comment]
Activating a virtual environment is only 1 or 2 lines of code, and I have demonstrated it in [that asciinema link](https://asciinema.org/a/VRT7DVw2QZxq0DlIgzoAOeiv2).

You can run `pip3 uninstall pynvml` and try again.

**Comment by githust66** [comment]
> pip3 uninstall pynvml

![image](https://github.com/user-attachments/assets/eeb39b64-abb5-484d-8866-54e8c0e4e469)
That's it, thanks

**Comment by githust66** [comment]
> Activating a virtual environment is only 1 or 2 lines of code, and I have demonstrated it in [that asciinema link](https://asciinema.org/a/VRT7DVw2QZxq0DlIgzoAOeiv2).
> 
> You can run `pip3 uninstall pynvml` and try again.

I still can t uninstall pynvml and I have other apps that need this

**Comment by harkgill-amd** [comment]
With the release official release of ROCm 6.2.3 for WSL, support for torch has been extended to torch 2.3.0. You can find the install instructions at [Install PyTorch for ROCm](https://rocm.docs.amd.com/projects/radeon/en/latest/docs/install/wsl/install-pytorch.html) and the relevant packages at https://repo.radeon.com/rocm/manylinux/rocm-rel-6.2.3/. Thanks!
