### ISSUE TITLE
[Issue]: Undefined reference to ncurses libraries

### ISSUE THREAD

**Issue by avickars** [ROCm/ROCm#3574]
### Problem Description

When compiling a very simple test program, whenever I link to any external library (i.e. anything not hip), I am getting the following error

```
/usr/bin/ld: /opt/rocm/lib/libamd_comgr.so.2: undefined reference to `tigetnum@NCURSES6_TINFO_5.0.19991023'
/usr/bin/ld: /opt/rocm/lib/libamd_comgr.so.2: undefined reference to `del_curterm@NCURSES6_TINFO_5.0.19991023'
/usr/bin/ld: /opt/rocm/lib/libamd_comgr.so.2: undefined reference to `setupterm@NCURSES6_TINFO_5.0.19991023'
/usr/bin/ld: /opt/rocm/lib/libamd_comgr.so.2: undefined reference to `set_curterm@NCURSES6_TINFO_5.0.19991023'
```

### Operating System

Ubuntu 22.04

### CPU

Ryzen 7900X

### GPU

AMD Radeon RX 7900 XT

### ROCm Version

ROCm 6.2.0, ROCm 6.1.0

### ROCm Component

HIP

### Steps to Reproduce

Unpack the following file: [rocm-ex.zip](https://github.com/user-attachments/files/16593948/rocm-ex.zip)

Run the following
```
mkdir build
cmake ..
make
```

Note, currently the cmake file uses opencv libraries as the external library, feel free to change that.

It **will** compile if you remove line 46 of the `CMakeLists.txt` file.

### Additional Information

I suspect it is something extremely small that I am doing incorrectly in my cmake but I can't figure out what it is for the life of me.

**Comment by ppanchad-amd** [comment]
@avickars Internal ticket has been created to investigate this issue. Thanks!

**Comment by schung-amd** [comment]
Hi @avickars, I was able to build this on my system without errors by adding a line to tell cmake where the HIP and opencv cmake modules are: `set(CMAKE_PREFIX_PATH /opt/rocm /usr/local/lib/cmake/opencv4/)` as the first line in your dependencies section (i.e. before `if ( ENABLE_HIP )`). The paths you need to pass may vary based on where you've installed HIP and opencv (or any other external library you'd like to use). Let me know if this solves your issue.

**Comment by avickars** [comment]
Thanks @schung-amd , I was building it in a conda environment, and determined that after running `conda install opencv`, it would no longer build for some reason.  Blowing away the conda environment and doing `apt-get install -y libopencv-dev` fixes it.

**Comment by avickars** [comment]
Hi @schung-amd , were you able to reproduce the linking error I had as I am still having issues?  For some additional information, I am having this issue on clean install of both Ubuntu 22.04 and Ubuntu 24.04

**Comment by schung-amd** [comment]
Hi @avickars, glad you have found the cause of your issue. Did you mean to reopen this?
