### ISSUE TITLE
[Issue]: hipcc --version takes a minute to respond

### ISSUE THREAD

**Issue by mcordery** [ROCm/ROCm#3598]
### Problem Description

Installed new version of rocm6.2 after using 6.1
A response from hipcc --version takes nearly a minute
This was definitely not the case with 6.1

mcordery@DESKTOP-J13NI0K:~$ time hipcc --version
HIP version: 6.2.41133-dd7f95766
AMD clang version 18.0.0git (https://github.com/RadeonOpenCompute/llvm-project roc-6.2.0 24292 26466ce804ac523b398608f17388eb6d605a3f09)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm-6.2.0/lib/llvm/bin
Configuration file: /opt/rocm-6.2.0/lib/llvm/bin/clang++.cfg

real    1m0.048s
user    0m57.240s
sys     0m3.346s

### Operating System

Ubuntu 22.04.4 LTS (Jammy Jellyfish)

### CPU

Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz

### GPU

AMD Radeon RX 7900 XT

### ROCm Version

ROCm 6.2.0

### Steps to Reproduce

time hipcc --version

**Comment by ppanchad-amd** [comment]
@mcordery Internal ticket has been created to investigate this issue. Thanks!

**Comment by schung-amd** [comment]
Hi @mcordery, I can't reproduce this locally; hipcc --version takes under 0.1s to run in ROCm 6.2 as well as ROCm 6.1. Does anything else run slowly for you with ROCm 6.2, or is it just hipcc --version so far? Could you try uninstalling ROCm completely and reinstalling? Also, can you provide the output of `sudo dmesg | grep atomic`? Thanks!

**Comment by mcordery** [comment]
Yeah, I was trying to avoid that but I'll give it a try. There is nil output from the command that you requested that I run.

**Comment by harkgill-amd** [comment]
Hi @mcordery, are you still experiencing a delay when running `hipcc --version` on ROCm 6.2?

**Comment by mcordery** [comment]
[AMD Official Use Only - AMD Internal Distribution Only]

Yes but I think it’s ignorable for now. It’s probably just me.

Matthew J Cordery, PhD
Principal Member of Technical Staff
AI Group
