### ISSUE TITLE
[Issue]: MI210 Not show under rocm-smi.  Error:  amdgpu: Fatal error during GPU init

### ISSUE THREAD

**Issue by GowriShankarEAAS** [ROCm/ROCm#3712]
### Problem Description

MI210 GPUs are not shown under rocm-smi. following is the error from OS logs

[   16.284320] [drm] amdgpu kernel modesetting enabled.
[   16.284345] [drm] amdgpu version: 6.8.5
[   16.284981] amdgpu: Virtual CRAT table created for CPU
[   16.285142] amdgpu: Topology: Add CPU node
[   16.323366] amdgpu: PeerDirect support was initialized successfully
[   16.323773] amdgpu 0000:48:00.0: enabling device (0000 -> 0002)
[   16.324081] amdgpu 0000:48:00.0: amdgpu: Fatal error during GPU init
[   16.324195] amdgpu: probe of 0000:48:00.0 failed with error -12
[   16.324216] amdgpu: legacy kernel without apple_gmux_detect()

Kindly suggest how to debug this.

i have reinstalled os and rocm, still the issue is not resolved

### Operating System

ubuntu 22.04.04

### CPU

AMD EPYC 9554 64-Core Processor

### GPU

AMD Instinct MI210

### ROCm Version

ROCm 6.2.0

### Steps to Reproduce

rocm-smi

**Comment by harkgill-amd** [comment]
Hi @GowriShankarEAAS, could you please provide the complete dmesg output and Linux kernel version as well?

**Comment by GowriShankarEAAS** [comment]
Linux kernel version : 5.15.0-101-generic

dmesg output:
[ 16.284320] [drm] amdgpu kernel modesetting enabled.
[ 16.284345] [drm] amdgpu version: 6.8.5
[ 16.284981] amdgpu: Virtual CRAT table created for CPU
[ 16.285142] amdgpu: Topology: Add CPU node
[ 16.323366] amdgpu: PeerDirect support was initialized successfully
[ 16.323773] amdgpu 0000:48:00.0: enabling device (0000 -> 0002)
[ 16.324081] amdgpu 0000:48:00.0: amdgpu: Fatal error during GPU init
[ 16.324195] amdgpu: probe of 0000:48:00.0 failed with error -12
[ 16.324216] amdgpu: legacy kernel without apple_gmux_detect()

**Comment by GowriShankarEAAS** [comment]
the issue occurred after kernel upgraded to 6.8 and i have reverted back to 5.15, but the problem exists

**Comment by GowriShankarEAAS** [comment]
The issue is resolved after OS upgrade. close this issue
