### ISSUE TITLE
How to disable creation of unneeded packages

### ISSUE THREAD

**Issue by jdumke** [ROCm/ROCm#3742]
With the default build cmd:
make -f ROCm/tools/ROCm.mk  all
all variants of packages will be created, which I don't need respectively use, I only need DEB. How can I disable the creation of all other, espacially RPM, which fails due an outdated rpmbuild in Debian stable.

Thanks for helping.

**Comment by harkgill-amd** [comment]
Hi @jdumke, let me confirm if this is possible with the current scripts and get back to you.

**Comment by harkgill-amd** [comment]
@jdumke, by default the CPACKGEN is set to DEB, allowing for only Debian packages to be created. Could you please point out which RPM packages are being created?

**Comment by jdumke** [comment]
In my case it were the rpm for amd_smi_lib, but it seems that the workaround given to me in #3743 solves this issue too. I added Debian to list distro list in envsetup.sh and all works fine.
