### ISSUE TITLE
[Feature]: ROCm supports SgLang

### ISSUE THREAD

**Issue by githust66** [ROCm/ROCm#3744]
### Suggestion Description

ROCm supports SgLang and vLLM

### Operating System

ubuntu 22.04

### GPU

7900xt

### ROCm Component

torch2.4.0+ROCm 6.1

**Comment by githust66** [comment]
At present, ROCm 6.2 already supports vLLM, is there a plan to support SgLang in the future?

**Comment by harkgill-amd** [comment]
Hi @githust66, you can find instructions on how to run SGLang with ROCm in our new published blog, [SGLang: Fast Serving Framework for Large Language and Vision-Language Models on AMD GPUs](https://rocm.blogs.amd.com/artificial-intelligence/sglang/README.html).

You can also find AMD/ROCm specific install instructions directly on the [SGLang project page](https://sgl-project.github.io/start/install.html#install-sglang). These developments are fairly new and as such, only MI/Instinct cards are currently supported.

**Comment by githust66** [comment]
> Hi @githust66, you can find instructions on how to run SGLang with ROCm in our newly published blog, [SGLang: Fast Serving Framework for Large Language and Vision-Language Models on AMD GPUs](https://rocm.blogs.amd.com/artificial-intelligence/sglang/README.html).
> 
> You can also find AMD/ROCm specific install instructions directly on the [SGLang project page](https://sgl-project.github.io/start/install.html#install-sglang). These developments are fairly new and as such, only MI/Instinct cards are currently supported.

OK, Thanks

**Comment by harkgill-amd** [comment]
Even better! Feel free to create a new issue if you encounter any difficulties running SGLang.

**Comment by a-huk** [comment]
Hello @githust66,

Could you quickly explain how you got it to run on a 7900XTX, I am struggling...

Thank you
