### ISSUE TITLE
RCCL multi-node performance degradation with Linux kernel 6.8.0+ on RoCE networks

### ISSUE THREAD

**Issue by peterjunpark** [ROCm/ROCm#3772]
On systems running Linux kernel 6.8.0, such as Ubuntu 24.04, Direct Memory Access (DMA) transfers between the GPU and NIC are disabled and impacts multi-node RCCL performance.
 
This issue was reproduced with RCCL 2.20.5 (ROCm 6.2.0 and 6.2.1) on systems with Broadcom Thor-2 NICs and affects other systems with RoCE networks using Linux 6.8.0 or newer. Older RCCL versions are also impacted.
 
This issue will be addressed in a future ROCm release.

**Comment by joellliu** [comment]
will this impact ubuntu 22.04?

**Comment by hassanhub** [comment]
Is there a fix or an ETA for this issue to be resolved?

**Comment by peterjunpark** [comment]
Fixed in ROCm 6.3.0.
