### ISSUE TITLE
Remove GPU choice from Github Issue template

### ISSUE THREAD

**Issue by Germano0** [ROCm/ROCm#3797]
### Problem Description

Everytime I fill an issue here I am forced to choose a random GPU in the GPU menu because the list is very limited and just contains a few models. Please remove it at all

**Comment by harkgill-amd** [comment]
Hi @Germano0, thank you for the feedback. I do agree it can be quite confusing trying to figure out what the exact configuration is when the real GPU isn't listed. I will work on getting this changed to a generic text field.

**Comment by harkgill-amd** [comment]
Done! Please let me know if you have any feedback or issues with the new issue report template.
