### ISSUE TITLE
[Issue]: No hipcc.exe

### ISSUE THREAD

**Issue by nazar-pc** [ROCm/ROCm#3817]
### Problem Description

I expected HIP SDK to contain `hipcc.exe`, but it is not there. Instead there is `hipcc`, which is a perl script and there is `hipcc.bin.exe`, which is a very confusing name instead of the normal one. Together with https://github.com/ROCm/ROCm/issues/2336 this results in a very frustrating experience on Windows.

### Operating System

Windows 11 (10.0.22631)

### CPU

AMD 7970X

### GPU

AMD Radeon RX 7900 XTX

### ROCm Version

ROCm 6.1.2 (installed using `AMD-Software-PRO-Edition-24.Q3-WinSvr2022-For-HIP.exe`)

### ROCm Component

HIPCC

**Comment by nazar-pc** [comment]
After manually updating `PATH` I'm getting this:
>   Output { status: ExitStatus(ExitStatus(1)), stdout: "", stderr: "'perl' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n" }

Of course I don't have `perl` installed, this is 2024! Official documentation at https://rocm.docs.amd.com/projects/HIPCC/en/latest/ says:
> There are both Perl and C++ executable versions of the hipcc and hipconfig compiler driver utilities provided. By default the C++ version is used when hipcc is run. To enable the Perl versions of these commands set the environment variable HIP_USE_PERL_SCRIPTS=1.

Which in my case is exactly the opposite!

The page seems to correspond to ROCm 6.2.1, but that doesn't seem to exist for Windows (the latest on downloads page is 6.1.2 for some reason).

Very frustrating experience so far.

**Comment by ppanchad-amd** [comment]
Hi @nazar-pc, internal ticket has bene created to investigate your issue. Thanks!

**Comment by nazar-pc** [comment]
It'd be better if `hipcc` was not a Perl script, so Perl if not required unless `HIP_USE_PERL_SCRIPTS` is used, but hopefully Perl version will go away altogether soon.
