### ISSUE TITLE
[Feature]: Use automation to update Docker images.

### ISSUE THREAD

**Issue by rudiservo** [ROCm/ROCm#3832]
### Suggestion Description

Docker hub does not have latest version of ROCm images, I recommend using some sort of automation to build new images and publish in docker hub and in github.
Update the base image to 24.04.

**Comment by harkgill-amd** [comment]
Hi @rudiservo, you can find the latest Ubuntu 24.04 ROCm docker image at https://hub.docker.com/r/rocm/dev-ubuntu-24.04. Is there a specific image you are referring to?

**Comment by rudiservo** [comment]
Hi @harkgill-amd, I think that at the time 24.04 didn't have 6.2.1 the latest version is 6.2.2, a minor change so I don't know how relevant the update is.

**Comment by harkgill-amd** [comment]
We do now have automation in place to build and publish new images to docker hub in the form of a GitHub action. The automation is triggered by a PR, which was just done for ROCm 6.2.2. You should see the new image up shortly.
