### ISSUE TITLE
Missing ISO_Fortran_binding.h

### ISSUE THREAD

**Issue by rbberger** [ROCm/ROCm#3867]
The `ISO_Fortran_binding.h` which is part of `flang`/`amdflang` is not part of the ROCm installation. It doesn't show up in any ROCm rpms. LLVM has the necessary install rule:
https://github.com/llvm/llvm-project/blob/main/flang/CMakeLists.txt#L543-L547
and apparently so does the ROCm/llvm-project:
https://github.com/ROCm/llvm-project/blob/rocm-6.2.2/flang/CMakeLists.txt#L508-L512
So it might just be a packaging error.

**Comment by lamb-j** [comment]
@bcornille

**Comment by bcornille** [comment]
Hi @rbberger,
Just for some clarification, https://github.com/ROCm/flang is the current implementation of `amdflang`. This is built on the "classic-flang" compiler, which is distinct from LLVM's flang. As you can see we are also working hard on the LLVM flang compiler via our fork of the upstream LLVM repo and so we have repos for both compilers named `flang` in the ROCm organization. From what I can tell, there is no `ISO_Fortran_binding.h` in the "classic-flang"-based `flang` repo. So I don't think there is any packaging error, just unfortunate overloading of the "flang" name and maybe some lack of clarity about which "flang" is included in ROCm.
