### ISSUE TITLE
[Issue]: HIP error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by AtiqurRahmanAni** [ROCm/ROCm#3894]
### Problem Description

My configuration is
OS: Ubuntu 24.04.1 LTS
GPU: AMD Radeon RX 6600
Python version: 3.12.3
Rocm version: 6.1.3.60103-122~20.04

The problem is following:
![image](https://github.com/user-attachments/assets/a69e4e82-9925-4b4f-b05a-5c1b8cbed430)

This works fine if I run this code on the Ubuntu OS disk, more specifically, where the ROCm is installed. But I am running out of Ubuntu system disk space. That's why I created a virtual environment on another disk, which is a mounted volume, installed PyTorch ROCm, . When I try to run this code I get the error shown in the image. How to solve this issue. Basically I am trying to run code on another volume.

**Note: I have seleted AMD Radeon VII because my GPU is not listed there.**

### Operating System

Ubuntu 24.04.1 LTS

### CPU

Intel core i5 10400

### GPU

AMD Radeon VII

### ROCm Version

ROCm 6.1.0

**Comment by harkgill-amd** [comment]
Hi @AtiqurRahmanAni, thank you for the report. An internal ticket has been created to further investigate this issue.

**Comment by tcgu-amd** [comment]
Hi @AtiqurRahmanAni, thanks for reporting! The issue is odd for sure. As long as rocm is installed properly, it shouldn't matter where rocm-pytorch is installed. Would you mind providing some additional context? How did you set up the virtual environment? It looks like you are running a notebook as well, sometimes it could also be a misconfiguration of the notebook, please double check if the notebook is set to use the python environment on your mounted disk. 

On a side note, it might be easier to run rocm with pytorch on docker. You can configure docker's root directory on your mounted disk and install rocm/pytorch there.

**Comment by AtiqurRahmanAni** [comment]
I created the virtual environment using `python3 -m venv <myenvname>` this command. The notebook is detecting the virtual environment just fine. Even you can see from my screenshot that `cuda` is available. That means `PyTorch ROCm` is installed successfully. I also changed all the files of that disk permissions, but no luck. Now what I am doing is creating the virtual environment on the system drive where the ROCm and Ubuntu are installed and using that VM. It works fine, but I have to create the virtual environment on the same drive where ROCm is installed.

And another question: how long will ROCm support the RDNA2 GPUs? Many people use old 6000 series GPUs and tying to run deep learning models on their GPUs. 
Thank you so much for identifying my issue.

**Comment by tcgu-amd** [comment]
> I created the virtual environment using `python3 -m venv <myenvname>` this command. The notebook is detecting the virtual environment just fine. Even you can see from my screenshot that `cuda` is available. That means `PyTorch ROCm` is installed successfully. I also changed permission of all the files that disk, but no luck. Now what I am doing is creating the virtual environment on the system drive where the ROCm and Ubuntu are installed and using that virtual env . It works fine, but I have to create the virtual environment on the same drive where ROCm is installed.

I see. In that case, can you try running the following lines in python on your external drive environment and let us know the outputs?
```
import torch
print(torch.cuda.get_device_name())
```
Just wanted to see if it is recognizing your dgpu properly. Sometimes it can mistakenly target the iGPU.
also
```
import sys
print(sys.path)
```
to show that the venv is properly including the python path;
and finally
```
import os
print(os.listdir("/opt/rocm"))
```
To see if it has permission to access the ROCM path. 

> And another question: how long will ROCm support the RDNA2 GPUs? Many people use old 6000 series GPUs and tying to run deep learning models on their GPUs.  Thank you so much for identifying my issue. Please let me know if you need more information regarding this issue.

Unfortunately, I can't give you a definite answer to this. However, many older cards and cards that are not "officially" supported can still run ROCm just fine for the most part, and if you encounter any issues you can always reach out to us on Github and we will try our best to help you diagnose and solve those problems.

Hope this helps!

**Comment by AtiqurRahmanAni** [comment]
I deleted the previously created virtual environment and created it again. Then installed PyTorch ROCm. Then I ran the following code to test, and surprisingly, it worked.
  
![test](https://github.com/user-attachments/assets/a3d5f77f-65e2-42c6-8c60-b85bc45ada33)

**Comment by AtiqurRahmanAni** [comment]
Ok, I tried to ran another code on the same environment. The code is:
```
from PIL import Image
import torch
import os
import pandas as pd
import numpy as np
from tqdm import tqdm
from torch.utils.data import Dataset
from pytorch_grad_cam.utils.image import show_cam_on_image
from pytorch_grad_cam import GradCAM
from pytorch_grad_cam.utils.model_targets import ClassifierOutputTarget
from torchvision import transforms
from torchvision.models import resnet152
from torch import nn

os.environ['HSA_OVERRIDE_GFX_VERSION'] = '10.3.0'
os.environ['HIP_VISIBLE_DEVICES'] = '0'

seed = 42
if torch.cuda.is_available():
        torch.cuda.manual_seed(seed)
torch.manual_seed(seed)
np.random.seed(seed)
torch.backends.cudnn.benchmark = False
torch.backends.cudnn.deterministic = True

DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(DEVICE)

class WaterbirdDataset(Dataset):
    def __init__(self, df, root_dir, transform=None):
        self.root_dir = root_dir
        self.df = df
        self.transform = transform

    
    def __len__(self):
        return len(self.df)
    
    
    def __getitem__(self, idx):
        img_filename = self.df.iloc[idx]['img_filename']
        img = Image.open(os.path.join(self.root_dir, img_filename)).convert("RGB")
        if self.transform:
            img = self.transform(img)
        
        label = self.df.iloc[idx]['y']
        place = self.df.iloc[idx]['place']
            
        return img_filename, img, label, place
    


root_dir = './dataset/waterbird'

df = pd.read_csv(os.path.join(root_dir, 'metadata.csv'))
test_df = df[df['split'] == 2].reset_index(inplace=False)


transform = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ])

test_set = WaterbirdDataset(df=test_df, root_dir=root_dir, transform=transform)


model = resnet152(weights=None)
model.fc = nn.Linear(model.fc.in_features, 2)
model = model.to(DEVICE).eval()
model.load_state_dict(torch.load("./Waterbird-results/Augmented-Results/Resnet152/800_sample_2/resnet152_augmented_800_sample_2.pth", weights_only=True, map_location=DEVICE))


target_layers = [model.layer4[-1]]
cam = GradCAM(model=model, target_layers=target_layers)


metadata = {
    'img_filename': [],
    'cam_filename': [],
    'y': [],
    'place': [],
    'prediction': []
}

saving_dir = '/media/atiqur/Extra/Download/Waterbird/Resnet152/Grad-cam'

for i in tqdm(range(test_set.__len__())):
    torch.cuda.empty_cache()
    img_filename, inp, label, place = test_set.__getitem__(i)
    inp = inp.unsqueeze(0).to(DEVICE)

    with torch.no_grad():
        logits = model(inp)
        pred = torch.argmax(logits, dim=1).cpu().item()

    target = [ClassifierOutputTarget(label)]
    
    rgb_img = Image.open(os.path.join(root_dir, img_filename)).convert('RGB').resize((224, 224))
    rgb_img = np.float32(rgb_img) / 255

    cam_out = cam(input_tensor=inp, targets=target)
    cam_out = cam_out[0, :]
    visualization = show_cam_on_image(rgb_img, cam_out, use_rgb=True)

    cam_filename = f'{i}_{img_filename.split('/')[-1]}'
    metadata['img_filename'].append(img_filename)
    metadata['cam_filename'].append(cam_filename)
    metadata['y'].append(label)
    metadata['place'].append(place)
    metadata['prediction'].append(pred)

    # img = Image.fromarray(visualization)
    # img.save(os.path.join(saving_dir, cam_filename))
    # break
```

And getting the same errors:
```
cuda
  0%|                                                                                                                        | 0/5794 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/media/atiqur/Study/Study Materials/Paper works/AS-Project/heatmap.py", line 97, in <module>
    logits = model(inp)
             ^^^^^^^^^^
  File "/media/atiqur/Study/Study Materials/Paper works/AS-Project/linuxvenv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/atiqur/Study/Study Materials/Paper works/AS-Project/linuxvenv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/atiqur/Study/Study Materials/Paper works/AS-Project/linuxvenv/lib/python3.12/site-packages/torchvision/models/resnet.py", line 285, in forward
    return self._forward_impl(x)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/media/atiqur/Study/Study Materials/Paper works/AS-Project/linuxvenv/lib/python3.12/site-packages/torchvision/models/resnet.py", line 270, in _forward_impl
    x = self.relu(x)
        ^^^^^^^^^^^^
  File "/media/atiqur/Study/Study Materials/Paper works/AS-Project/linuxvenv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/atiqur/Study/Study Materials/Paper works/AS-Project/linuxvenv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/atiqur/Study/Study Materials/Paper works/AS-Project/linuxvenv/lib/python3.12/site-packages/torch/nn/modules/activation.py", line 133, in forward
    return F.relu(input, inplace=self.inplace)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/atiqur/Study/Study Materials/Paper works/AS-Project/linuxvenv/lib/python3.12/site-packages/torch/nn/functional.py", line 1702, in relu
    result = torch.relu_(input)
             ^^^^^^^^^^^^^^^^^^
RuntimeError: HIP error: no kernel image is available for execution on the device
HIP kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing AMD_SERIALIZE_KERNEL=3
Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.
```

![image](https://github.com/user-attachments/assets/c4ee58ab-077c-453d-acdb-ddba0b91f75c)

Can you tell me what is wrong here?

**Comment by tcgu-amd** [comment]
@AtiqurRahmanAni Thanks for the update! I am glad that you were able to make it work. As to why it doesn't work again following your old setup, the only thing I can think of is the spaces in your venv path. Would you be able to remove them and see if anything changes! Thanks again!

**Comment by tcgu-amd** [comment]
@AtiqurRahmanAni I am able to confirm that it is likely the space.. I was able to reproduce it on my end as well...

**Comment by AtiqurRahmanAni** [comment]
I got it; this is very strange, and I did not figure out it before. In my old setup where it was working, before creating this environment, I changed the disk name with no space for other reasons. Basically, in my old setup, there were no spaces between the paths. Now, I can understand why on my new disk I am facing the same error. Thank you so much. I am closing the issue.
