### ISSUE TITLE
[Issue]: rocminfo doesn't show GPU

### ISSUE THREAD

**Issue by urbandroid** [ROCm/ROCm#3897]
### Problem Description

NAME="Ubuntu"
VERSION="24.04.1 LTS (Noble Numbat)"
CPU: 
model name	: Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz
GPU:
  Name:                    Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz
  Marketing Name:          Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz

### Operating System

24.04.1 LTS (Noble Numbat)

### CPU

amd radeon hd 8750m

### GPU

AMD Radeon Pro W7900

### ROCm Version

ROCm 6.2.0

### Steps to Reproduce

just run rocminfo

### (Optional for Linux users) Output of /opt/rocm/bin/rocminfo --support

/opt/rocm/bin/rocminfo --support
ROCk module version 6.8.5 is loaded
=====================    
HSA System Attributes    
=====================    
Runtime Version:         1.14
Runtime Ext Version:     1.6
System Timestamp Freq.:  1000.000000MHz
Sig. Max Wait Duration:  18446744073709551615 (0xFFFFFFFFFFFFFFFF) (timestamp count)
Machine Model:           LARGE                              
System Endianness:       LITTLE                             
Mwaitx:                  DISABLED
DMAbuf Support:          YES

==========               
HSA Agents               
==========               
*******                  
Agent 1                  
*******                  
  Name:                    Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz
  Uuid:                    CPU-XX                             
  Marketing Name:          Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz
  Vendor Name:             CPU                                
  Feature:                 None specified                     
  Profile:                 FULL_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        0(0x0)                             
  Queue Min Size:          0(0x0)                             
  Queue Max Size:          0(0x0)                             
  Queue Type:              MULTI                              
  Node:                    0                                  
  Device Type:             CPU                                
  Cache Info:              
    L1:                      32768(0x8000) KB                   
  Chip ID:                 0(0x0)                             
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   2600                               
  BDFID:                   0                                  
  Internal Node ID:        0                                  
  Compute Unit:            4                                  
  SIMDs per CU:            0                                  
  Shader Engines:          0                                  
  Shader Arrs. per Eng.:   0                                  
  WatchPts on Addr. Ranges:1                                  
  Memory Properties:       
  Features:                None
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: FINE GRAINED        
      Size:                    12124424(0xb90108) KB              
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: KERNARG, FINE GRAINED
      Size:                    12124424(0xb90108) KB              
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 3                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    12124424(0xb90108) KB              
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
  ISA Info:                
*** Done ***             

### Additional Information

dpkg -l | grep rocm
ii  rocm                                             6.2.2.60202-116~24.04                     amd64        Radeon Open Compute (ROCm) software stack meta package
ii  rocm-cmake                                       0.13.0.60202-116~24.04                    amd64        rocm-cmake built using CMake
ii  rocm-core                                        6.2.2.60202-116~24.04                     amd64        Radeon Open Compute (ROCm) Runtime software stack
ii  rocm-dbgapi                                      0.76.0.60202-116~24.04                    amd64        Library to provide AMD GPU debugger API
ii  rocm-debug-agent                                 2.0.3.60202-116~24.04                     amd64        Radeon Open Compute Debug Agent (ROCdebug-agent)
ii  rocm-developer-tools                             6.2.2.60202-116~24.04                     amd64        Radeon Open Compute (ROCm) Runtime software stack
ii  rocm-device-libs                                 1.0.0.60202-116~24.04                     amd64        Radeon Open Compute - device libraries
ii  rocm-gdb                                         14.2.60202-116~24.04                      amd64        ROCgdb
ii  rocm-hip-libraries                               6.2.2.60202-116~24.04                     amd64        Radeon Open Compute (ROCm) Runtime software stack
ii  rocm-hip-runtime                                 6.2.2.60202-116~24.04                     amd64        Radeon Open Compute (ROCm) Runtime software stack
ii  rocm-hip-runtime-dev                             6.2.2.60202-116~24.04                     amd64        Radeon Open Compute (ROCm) Runtime software stack
ii  rocm-hip-sdk                                     6.2.2.60202-116~24.04                     amd64        Radeon Open Compute (ROCm) Runtime software stack
ii  rocm-language-runtime                            6.2.2.60202-116~24.04                     amd64        Radeon Open Compute (ROCm) Runtime software stack
ii  rocm-llvm                                        18.0.0.24355.60202-116~24.04              amd64        ROCm core compiler
ii  rocm-ml-libraries                                6.2.2.60202-116~24.04                     amd64        Radeon Open Compute (ROCm) Runtime software stack
ii  rocm-ml-sdk                                      6.2.2.60202-116~24.04                     amd64        Radeon Open Compute (ROCm) Runtime software stack
ii  rocm-opencl                                      2.0.0.60202-116~24.04                     amd64        clr built using CMake
ii  rocm-opencl-dev                                  2.0.0.60202-116~24.04                     amd64        clr built using CMake
ii  rocm-opencl-icd-loader                           1.2.60202-116~24.04                       amd64        OpenCL-ICD-Loader built using CMake
ii  rocm-opencl-runtime                              6.2.2.60202-116~24.04                     amd64        Radeon Open Compute (ROCm) Runtime software stack
ii  rocm-opencl-sdk                                  6.2.2.60202-116~24.04                     amd64        Radeon Open Compute (ROCm) Runtime software stack
ii  rocm-openmp-sdk                                  6.2.2.60202-116~24.04                     amd64        Radeon Open Compute (ROCm) OpenMP Software development Kit.
ii  rocm-smi-lib                                     7.3.0.60202-116~24.04                     amd64        AMD System Management libraries
ii  rocm-utils                                       6.2.2.60202-116~24.04                     amd64        Radeon Open Compute (ROCm) Runtime software stack
ii  rocminfo                                         1.0.0.60202-116~24.04                     amd64        Radeon Open Compute (ROCm) Runtime rocminfo tool

lsmod | grep amdgpu
amdgpu              19632128  0
amddrm_ttm_helper      12288  1 amdgpu
amdttm                110592  2 amdgpu,amddrm_ttm_helper
amddrm_buddy           20480  1 amdgpu
amdxcp                 12288  1 amdgpu
drm_exec               12288  1 amdgpu
drm_suballoc_helper    16384  1 amdgpu
amd_sched              61440  1 amdgpu
amdkcl                 32768  3 amd_sched,amdttm,amdgpu
drm_display_helper    237568  2 amdgpu,i915
i2c_algo_bit           16384  2 amdgpu,i915
video                  73728  3 acer_wmi,amdgpu,i915

**Comment by harkgill-amd** [comment]
Hi @urbandroid, could you please confirm which GPU you're using and provide the output of rocminfo?

**Comment by urbandroid** [comment]
i have run  DRI_PRIME=1 glxgears in one terminal and while its running i run the rocminfo in another terminal

rocminfo
ROCk module version 6.8.5 is loaded
=====================    
HSA System Attributes    
=====================    
Runtime Version:         1.14
Runtime Ext Version:     1.6
System Timestamp Freq.:  1000.000000MHz
Sig. Max Wait Duration:  18446744073709551615 (0xFFFFFFFFFFFFFFFF) (timestamp count)
Machine Model:           LARGE                              
System Endianness:       LITTLE                             
Mwaitx:                  DISABLED
DMAbuf Support:          YES

==========               
HSA Agents               
==========               
*******                  
Agent 1                  
*******                  
  Name:                    Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz
  Uuid:                    CPU-XX                             
  Marketing Name:          Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz
  Vendor Name:             CPU                                
  Feature:                 None specified                     
  Profile:                 FULL_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        0(0x0)                             
  Queue Min Size:          0(0x0)                             
  Queue Max Size:          0(0x0)                             
  Queue Type:              MULTI                              
  Node:                    0                                  
  Device Type:             CPU                                
  Cache Info:              
    L1:                      32768(0x8000) KB                   
  Chip ID:                 0(0x0)                             
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   2600                               
  BDFID:                   0                                  
  Internal Node ID:        0                                  
  Compute Unit:            4                                  
  SIMDs per CU:            0                                  
  Shader Engines:          0                                  
  Shader Arrs. per Eng.:   0                                  
  WatchPts on Addr. Ranges:1                                  
  Memory Properties:       
  Features:                None
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: FINE GRAINED        
      Size:                    12124424(0xb90108) KB              
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: KERNARG, FINE GRAINED
      Size:                    12124424(0xb90108) KB              
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 3                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    12124424(0xb90108) KB              
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
  ISA Info:

**Comment by harkgill-amd** [comment]
Is it possible to disable the integrated/hybrid graphics setup in the BIOS? Would be worth seeing if the dGPU appears after being forced on. If you could please provide the laptop model I'll investigate this on my end as well.

**Comment by urbandroid** [comment]
packard  bell easy note TE 
SKU Number: EasyNote TE69HW_0776_V2.10
i'm going to try disabling  integrated/hybrid in BIOS as well

**Comment by urbandroid** [comment]
There is nothing about  integrated/hybrid in BIOS settings.
no Advanced option either is this a must? Can we move on?

**Comment by kentrussell** [comment]
1: You're using an 8750M (Mars), so I don't know if that's using radeon or amdgpu for the driver. Does dmesg say anything regarding the GPU? lspci showing both implies that the GPU is turned on, but couldn't initialize. To try to enable it, make sure that CONFIG_DRM_AMDGPU_SI=y in your kernel config. Attaching a full dmesg here will help to confirm that, though.
2: Note that gfx6 isn't supported in ROCm, and never has been. In ROCm's initial delivery, gfx7 was the oldest GFX family that supported ROCm, and that was just on Hawaii. gfx8 was the minimum HW architecture at that time. While ROCm doesn't support gfx8 officially, the bits are all there in theory to make it work. But gfx6 was never validated and is missing key architecture functionality to support ROCm. You'll officially need gfx9 or gfx10 for ROCm, support. gfx8 could work, but it's not tested so it may have issues with newer ROCm drops.

**Comment by urbandroid** [comment]
Because when i try to run Gradio and load a model  it says:

rocBLAS error: Could not initialize Tensile host: No devices found

**Comment by harkgill-amd** [comment]
>  is this info incorrect?

While this is correct, it looks like Gradio is trying to interface with rocBLAS (One of the math libraries within ROCm). Any library or package that relies on ROCm will likely fail as the kfd driver is incompatible with your GPU.

**Comment by urbandroid** [comment]
I was able to run with cpu i was trying to run with gpu.

Is there a way that doesn't require kfd or can ability of detecting gpu without kfd added to ROC possibility?

**Comment by harkgill-amd** [comment]
Unfortunately, there's no way to workaround the dependency on the kfd driver. It serves as the foundation for all things compute related.

**Comment by urbandroid** [comment]
Can OLAND support be added to kfd in the future?

**Comment by kentrussell** [comment]
CPUs are able to get things done in KFD, but unfortunately GPUs can be restricted due to the actual HW architecture. GFX6 won't work, unfortunately. You can reference https://github.com/RadeonOpenCompute/ROCm/issues/509#issuecomment-422999215 or https://github.com/ROCm/ROCm/issues/2232 for similar responses.

**Comment by unfixa1** [comment]
Check if your AMD GPU (Radeon Pro W7900) is in the list of GPUs supported by ROCm. ROCm may not support some older or specific models of GPUs.
Also install the driver.

In addition, you can use [Servbay](servbay.com) to check your development environment, which is better than Docker on Mac and can ensure that there is no compatibility conflict in the environment

**Comment by harkgill-amd** [comment]
Closing out this ticket as the failure to detect GPU is related to incompatible hardware. @urbandroid, if you have any more questions, feel free to leave a comment on this thread.
