### ISSUE TITLE
Reduce RocM Image size

### ISSUE THREAD

**Issue by michaelfeil** [ROCm/ROCm#3935]
Note: If I am raising this issue at the wrong place, please forward it to the correct location

https://hub.docker.com/r/rocm/pytorch currently is a ~32 GB decompressed container size.
Most build systems, e.g. github actions only have 25/29GB of total disk space available for the build

**Comment by harkgill-amd** [comment]
Hi @michaelfeil, we are aware of this issue and there are ongoing efforts to minimize the ROCm docker image sizes. The main cause of this is the ROCm installation itself which is under scrutiny. 

A workaround would be to use multi-stage docker build with only the specific ROCm components required for your usecase. The rocm/pytorch also includes a conda environment (~15% of it's total size) which can be avoided in a custom build. I will close this issue out for now as this is being tracked internally by the respective teams. Please feel free to leave a comment with any further questions.
