### ISSUE TITLE
[Feature]: ROCm support on arm64 (Ampere, Raspberry Pi, etc.)

### ISSUE THREAD

**Issue by geerlingguy** [ROCm/ROCm#3960]
### Suggestion Description

I have gotten various generation AMD graphics cards working on the Raspberry Pi 5 (see https://github.com/geerlingguy/raspberry-pi-pcie-devices/issues/222), as well as on Ampere Altra and AmpereOne workstations and servers (see https://community.amperecomputing.com/t/amd-gpus-on-the-altra-devkit-and-other-altras-patches-available-now/336).

For many of these systems, running software like Ollama or other LLMs would be beneficial, and having an alternative to Nvidia graphics cards would provide more options for vendors (and more cash to AMD, since Pro/RX/Enterprise cards could be justified on these systems).

As of 2021, [ROCm was not supported on arm64](https://github.com/ROCm/ROCm/issues/1052), but a few years later, we have much better `amdgpu` driver support (though still requiring some fixes for Arm PCIe implementations where cache coherency is different than amd64).

Is it possible for arm64 support to be explored for AMD GPUs?

**Comment by geerlingguy** [comment]
Extending this line of thinking: RISC-V is finally exiting the 'development only' mode, and is a viable platform with some servers and desktops coming on the market—which *also* work with AMD GPUs, albeit with similar driver fixups.

Going multi-arch would be useful to allow AMD GPUs to be a standard across any architecture, and building for arm64 would likely introduce fixes that _also_ make it easier to work with RISC-V, as many of the code paths that are broken are due to x86/amd64-isms.

**Comment by sohaibnd** [comment]
Hi @geerlingguy, your points are valid and we have been listening to the demand there is for ARM support, but this is not something that is planned yet. If this changes, rest assured that AMD will officially announce this!

**Comment by geerlingguy** [comment]
At least I can get Vulkan to work since ROCm won't (and bonus, with llama.cpp at least, this enables a lot of older or lower power cards too, like the 6500 and 7600 XT I'm testing now!).

**Comment by yuningliang** [comment]
@geerlingguy you absolutely correct on ROCm of RISC-V. we @deepcomputing are putting effort in porting them too. but we got stuck as lots of hardcoded x86 stuffs.
