### ISSUE TITLE
[Issue]: Can't install rocm 6.2.3

### ISSUE THREAD

**Issue by WareZTv** [ROCm/ROCm#3980]
### Problem Description

Hello, have the 6.8.0.48 kernel and the comand "amdgpu-install -y --usecase=graphics,rocm" is giving me this error:
Err:7 https://repo.radeon.com/amdgpu/6.2.3/ubuntu jammy/main amd64 Packages
  File has unexpected size (14796 != 14502). Mirror sync in progress?

### Operating System

Ubuntu 22.04.5LTS

### CPU

ryzen 7 7800x3d

### GPU

rx 7900xtx

### ROCm Version

ROCm 6.2.3

### Steps to Reproduce

sudo apt-get update
sudo apt-get dist-upgrade
sudo apt update
wget https://repo.radeon.com/amdgpu-install/6.2.3/ubuntu/jammy/amdgpu-install_6.2.60203-1_all.deb
sudo apt install ./amdgpu-install_6.2.60203-1_all.deb
amdgpu-install -y --usecase=graphics,rocm

**Comment by harkgill-amd** [comment]
Hi @WareZTv, thanks for the report! Will look into this further and get back to you.

**Comment by harkgill-amd** [comment]
@WareZTv, the error with our CDN has been addressed and the ROCm 6.2.3 installation is now working. Could you please confirm the issue is resolved on your end as well?

**Comment by WareZTv** [comment]
@harkgill-amd Thanks a lot for your help, the rocm 6.2.3 installation now works with my gpu

**Comment by harkgill-amd** [comment]
Great! Happy to help.

**Comment by imkow** [comment]
r u kidding me? 

Err:7 https://repo.radeon.com/rocm/apt/6.2.4 noble/main amd64 Packages
  File has unexpected size (68560 != 29552). Mirror sync in progress?

**Comment by jontomas1000** [comment]
I have the same message on a fresh ubuntu server install.  Just added the repo and did sudo apt update. GPU is RX6700XT

`Failed to fetch https://repo.radeon.com/rocm/apt/6.2.4/dists/noble/main/binary-amd64/Packages.gz  File has unexpected size (68560 != 29552). Mirror sync in progress? [IP: 104.96.169.171 443]`
