### ISSUE TITLE
[Documentation]: Install Migraphx for radeon gpus <migraphx-driver : command not found> and <ERROR: Could not find a version that satisfies the requirement onnxruntime-rocm>

### ISSUE THREAD

**Issue by WareZTv** [ROCm/ROCm#3989]
### Description of errors

Hello, theses two lines:
```
echo 'export PATH=$PATH:/opt/rocm-6.2.3/bin' >> ~/.bashrc
source ~/.bashrc
```
needs to be added in the documentation here https://rocm.docs.amd.com/projects/radeon/en/latest/docs/install/native_linux/install-migraphx.html after the command "sudo apt install migraphx" or else the command "migraphx-driver perf --test" will not be found.

another important error is this one: "ERROR: Could not find a version that satisfies the requirement onnxruntime-rocm" after typing the command 
```pip3 install onnxruntime-rocm -f https://repo.radeon.com/rocm/manylinux/rocm-rel-6.0/```
because the right command is this one:
```
pip3 install onnxruntime-rocm -f https://repo.radeon.com/rocm/manylinux/rocm-rel-6.2.3/
```
You can modify the second error in this webpage: https://rocm.docs.amd.com/projects/radeon/en/latest/docs/install/native_linux/install-migraphx.html#install-migraphx-for-onnx-runtime

**Comment by harkgill-amd** [comment]
Hi @WareZTv, thanks for pointing this out. This will be fixed shortly.

**Comment by WareZTv** [comment]
no problem, it helps everyone including me so i'm happy to share the issues here

**Comment by harkgill-amd** [comment]
Both issues have been addressed over at [Install MIGraphX for ONNX Runtime](https://rocm.docs.amd.com/projects/radeon/en/latest/docs/install/native_linux/install-migraphx.html#install-migraphx-for-onnx-runtime). It was decided to reference the absolute path for `migraphx-driver` for simplicity as it's a simple check to verify the installation. Could you please confirm that the instructions work on your end and close out the ticket?

**Comment by WareZTv** [comment]
@harkgill-amd  Works perfectly fine now. Something related to the subject but is less important is this. Under the "Verify MIGraphX installation for ONNX Runtime" section in the same webpage: https://rocm.docs.amd.com/projects/radeon/en/latest/docs/install/native_linux/install-migraphx.html#verify-migraphx-installation-for-onnx-runtime, if i copy paste 
1) first this line:
```
python3
```
then these two lines:
```
import onnxruntime as ort
ort.get_available_providers()
```
then the result is as expected: 
```
>>> import onnxruntime as ort
>>> ort.get_available_providers()
['MIGraphXExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider']
```

But if i copy paste the 3 lines at the same time only 
```python3```
is taken into account so i have to copy paste the two other lines again which can be destabilizing for those not comfortable with the python console

so maybe this command will be more appropriate for the tutorial:
```
python3 -c "import onnxruntime as ort; print(ort.get_available_providers())"
```

or you can separate the first line from the two others lines, as you prefer

**Comment by WareZTv** [comment]
Anyway thanks a lot for being responsive. Not many companies care about their customer like you do

**Comment by harkgill-amd** [comment]
> python3 -c "import onnxruntime as ort; print(ort.get_available_providers())"

The docs have been updated to use this command. Thanks!

**Comment by WareZTv** [comment]
your welcome 👍
