### ISSUE TITLE
[Issue]:  /usr/bin/amdgpu-install: satır 436: ${USECASE_GRAPHİCS_PACKAGES[*]}: hatalı ikame

### ISSUE THREAD

**Issue by LmEnes** [ROCm/ROCm#4026]
### Problem Description

i will describe it shorly
languages that has İ letter has this issue, copy of https://github.com/ROCm/ROCm/issues/2888
i had to change my language from linux mint language setting and set it to en_US
after changing language my problem was fixed

### Operating System

Linux Mint 22 Cinnamon

### CPU

AMD Ryzen 5 5500

### GPU

Rx 6600XT

### ROCm Version

ROCm 6.2.3, ROCm 6.2.2, ROCm 6.2.1, ROCm 6.2.0, ROCm 6.1.0, ROCm 6.0.0

### Steps to Reproduce

Installing any os with Turkish or Azerbaijan language pack must do, im using linux mint but same issue encoured with Ubuntu 22.04.3 or/& newest versions too.
sudo amdgpu-install 
Here's the thing; if i do amdgpu-install --usecase=dkms and sudo amdgpu-install --usecase=rocm it actually installs but if i try to sudo amdgpu-install --usecase=graphics it fails.

### Additional Information

No, i described everything. Its about the İ letter. amdgpu-installer changes its install language by local language, if Turkish or Azeribaijani language detected en_US language may used.

**Comment by harkgill-amd** [comment]
Hi @LmEnes, the fix mentioned in https://github.com/ROCm/ROCm/issues/2888 will be apart of the ROCm 6.3 release. It will simply set the `LC_ALL` environment variable to `C`  which forces the system to use the default, minimal locale settings. You can set this on your end with `export LC_ALL=C`. Please let me know if this resolve your issue.

**Comment by LmEnes** [comment]
Okey

**Comment by LmEnes** [comment]
Yeah, fixed the issue.
