### ISSUE TITLE
[Feature]: global synchronization 

### ISSUE THREAD

**Issue by johnnynunez** [ROCm/ROCm#4120]
### Suggestion Description

Rocm has cooperative_groups.this_grid().sync()? (This is from nvidia cooperative groups)
I mean Global Synchronization in the grid, it is like cooperative_groups.this_grid().sync()

also:
Does rocm also have shared memory?
That you can use with “asynchronous copies,” where what interests me the most is the ability to move data from the device to shared memory without going through the registers.

**Comment by b-sumner** [comment]
Cooperative groups are supported, including this_grid.sync().

HIP, like Cuda, has __shared__ variables.  HIP doesn't currently support some of the Cuda async functions.
