### ISSUE TITLE
[Issue]: Cannot report issue against ROCm 6.3 ;) 

### ISSUE THREAD

**Issue by prarit** [ROCm/ROCm#4131]
### Problem Description

The drop down for ROCm Version in the issue reporting tool does not have a 6.3 option.

### Operating System

n/a

### CPU

n/a

### GPU

n/a

### ROCm Version

ROCm 6.2.3

### Steps to Reproduce

1.  Enter in a new issue.
2.  For ROCm Version select "6.3" -- no option is available.

**Comment by harkgill-amd** [comment]
Hi @prarit, thanks for the heads up! The issue template has been updated.
