### ISSUE TITLE
[Documentation]: Need fny information for explain how work with ROCm for inference model Yolov8

### ISSUE THREAD

**Issue by ViktorPavlovA** [ROCm/ROCm#4139]
### Description of errors

Hello, ROCm community. 

I have a question how to use this environment to infer the model and translate the model from fp32 -> fp16 without using tensorflow or pytorch . For example in tensorrt (sorry for this ) i have cpp and python3 api to transfer model in onnx to graphic card model format. Is it possible to do it with using ROCm?

Thank you so much!

### Attach any links, screenshots, or additional evidence you think will be helpful.

.

**Comment by harkgill-amd** [comment]
Hi @ViktorPavlovA, this can be done with ROCm using the MIGraphX library. Here is an example of quantization of YOLOv4 to FP16 ([Object Detection with YoloV4](https://github.com/ROCm/AMDMIGraphX/blob/develop/examples/vision/python_yolov4/yolov4_inference.ipynb)). In this example, we start with an ONNX model and use the `migraphx-driver` tool with flag `--fp16` to compile it to FP16.

Please also refer to the [MIGraphX Driver Options](https://github.com/ROCm/AMDMIGraphX/tree/0860461d626f8cd42a443335c0764925f8195e9c/examples/migraphx/migraphx_driver#options) for a more extensive list of the tools features.

**Comment by harkgill-amd** [comment]
No problem! 

I'll close out this issue for now. Feel free to leave a comment if you have any other questions.
