### ISSUE TITLE
[Documentation]: windows is not updated

### ISSUE THREAD

**Issue by johnnynunez** [ROCm/ROCm#4171]
### Description of errors

hip sdk 6.2.0 now is on windows:
https://www.amd.com/en/developer/resources/rocm-hub/eula/licenses.html?filename=AMD-Software-PRO-Edition-24.Q4-Win10-Win11-For-HIP.exe

**Comment by ppanchad-amd** [comment]
Hi @johnnynunez. Internal ticket has been created to update docs. Thanks!

**Comment by johnnynunez** [comment]
solved:
![image](https://github.com/user-attachments/assets/bc0ad6fa-6157-48a2-aa48-dad9ffcf3a64)
