### ISSUE TITLE
missed carry-idiom optimization

### ISSUE THREAD

**Issue by preda** [ROCm/ROCm#477]
I use this idiom in OpenCL to express the carry resulting from a V_MAD_U64_U32:
uint a;
ulong b;
ulong x = a * (ulong) a + b;
uint carry = (x < b);

Yet ROC 1.9.2 generates this ISA:
	v_mad_u64_u32 v[6:7], s[0:1], v3, v3, v[8:9]
	v_cmp_lt_u64_e32 vcc, v[6:7], v[8:9]

What we see here is that the compiler discards the carry in the v_mad, just to compute it again below.

Expected behavior: the compiler understands the carry idiom, and maps it to the carry generated by the MAD.

**Comment by b-sumner** [comment]
Thanks, we'll look into this

**Comment by ROCmSupport** [comment]
Hi @preda 
Thanks for reaching out.
Can you please verify with the latest ROCm 4.0 and update the status asap.
Thank you.

**Comment by preda** [comment]
Update: the issue is still present on ROCm 3.3 and ROCm 4.1.1 .

Some more detail/clarification:
The carry idiom is correctly recognized for uint (32bit), but it is not recognized for ulong (64bit).
Consider this kernel:
```
kernel void testKernel(global uint* io) {
  uint me = get_local_id(0);

  uint a = io[me];
  uint b = io[me + 1];
  uint s = a + b;
  bool carry = (s < a);
  io[me] = s + carry;
}
```
It is compiled correctly to:
```
v_add_co_u32_e32 v2, vcc, v3, v2
v_addc_co_u32_e32 v2, vcc, 0, v2, vcc
```

Now the same operation on 64bit:
```
kernel void testKernel(global ulong* io) {
  uint me = get_local_id(0);

  ulong a = io[me];
  ulong b = io[me + 1];
  ulong s = a + b;
  bool carry = (s < a);
  io[me] = s + carry;
}
```
And it is compiled to:
```
v_add_co_u32_e32 v0, vcc, v2, v0
v_addc_co_u32_e32 v1, vcc, v3, v1, vcc
v_cmp_lt_u64_e32 vcc, v[0:1], v[2:3]
v_cndmask_b32_e64 v2, 0, 1, vcc
v_add_co_u32_e32 v0, vcc, v0, v2
v_addc_co_u32_e32 v1, vcc, 0, v1, vcc
```
Expected:
```
v_add_co_u32_e32 v0, vcc, v2, v0
v_addc_co_u32_e32 v1, vcc, v3, v1, vcc
v_add_co_u32_e32 v0, vcc, 0, v0, vcc
v_addc_co_u32_e32 v1, vcc, 0, v1, vcc
```

**Comment by preda** [comment]
Another manifestation of the same issue is in such code being generated:
```
v_add_co_u32_e32 v2, vcc, v0, v8
v_addc_co_u32_e32 v3, vcc, v1, v9, vcc
v_cmp_lt_u64_e32 vcc, v[2:3], v[0:1]
```
where the last line (v_cmp) is perfectly un-necessary, as it produces the same value in VCC as it already had, and this should be obvious to the optimizer.

**Comment by preda** [comment]
Also, while fixing this for 64bits, probably it makes sense to keep an eye on 128bits as well (long long, unsigned long long in clang OpenCL).

**Comment by preda** [comment]
@b-sumner please have a look, looks like a missed LLVM optimization, a pretty basic one they may want to fix. Added new data and verified present in ROCm 4.1.1.

**Comment by yashssh** [comment]
Hi @preda! Thanks for pointing out the issue. Hopefully [D137932](https://reviews.llvm.org/D137932) fixes the issue in GISel pipeline. 
Still have to look into MAD instruction and DAG pipeline

**Comment by tasso** [comment]
Is this still an issue?  If not; can we please close it?

**Comment by tasso** [comment]
Original ticket is more than a year old and the person that originally opened ticket  has not responded to the latest request.  If this is still an issue, please file a new ticket and we will investigate it.  Thanks!
