### ISSUE TITLE
inefficient codegen: OpenCL wide add

### ISSUE THREAD

**Issue by preda** [ROCm/ROCm#488]
This is a 3-word-wide add-with-carry in OpenCL:
```
uint3 add(uint3 a, uint3 b) {
  ulong x = a.x + (ulong) b.x;
  ulong y = a.y + (ulong) b.y + (x >> 32);
  uint  z = a.z + b.z + (y >> 32);
  return (uint3) (x, y, z);
}
```
This code can be compiled to 3 v_add instructions (with carry-in/carry-out as appropriate). But this is what is generated:
```
	v_add_co_u32_e32 v2, vcc, v7, v4                           // 000000003D74: 32040907
	v_addc_co_u32_e64 v0, s[0:1], 0, 0, vcc                    // 000000003D78: D11C0000 01A90080
	s_waitcnt vmcnt(1)                                         // 000000003D80: BF8C0F71
	v_add_co_u32_e32 v3, vcc, v8, v5                           // 000000003D84: 32060B08
	v_addc_co_u32_e64 v5, s[0:1], 0, 0, vcc                    // 000000003D88: D11C0005 01A90080
	v_add_co_u32_e32 v3, vcc, v3, v0                           // 000000003D90: 32060103
	v_addc_co_u32_e32 v0, vcc, 0, v5, vcc                      // 000000003D94: 38000A80
	v_add_u32_e32 v4, v9, v6                                   // 000000003D98: 68080D09
	v_add_u32_e32 v4, v4, v0
```
Which is 8 adds.

Apparently the compiler does not understand the carry expressed in OpenCL as widening add.

Below is the expected ISA snippet:
```
	v_add_co_u32_e32 v2, vcc, v4, v7                           // 000000003D74: 32040F04
	v_addc_co_u32_e32 v3, vcc, v5, v8, vcc                     // 000000003D78: 38061105
	v_addc_co_u32_e32 v4, vcc, v6, v9, vcc                     // 000000003D7C: 38081306
```

**Comment by gstoner** [comment]
Can you send me email.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by b-sumner** [comment]
Thanks.  We'll look into this.

**Comment by preda** [comment]
@gstoner : my email is mhpreda@gmail.com

**Comment by ROCmSupport** [comment]
Hi @preda
Thanks for reaching out.
Can you please verify with the latest ROCm 4.0 and update the status asap.
Thank you.

**Comment by arsenm** [comment]
Some work is in flight to address this https://reviews.llvm.org/D138814

**Comment by tasso** [comment]
Has this issue been fixed? If so, can we please close it?

**Comment by tasso** [comment]
Original ticket is more than a year old and the person that opened ticket originally has not responded to the last request.  If this is still an issue, please file a new ticket and we will be happy to investigate it.  Thanks!
