### ISSUE TITLE
ROCm doesn't support intel_iommu=on without iommu=pt

### ISSUE THREAD

**Issue by TheGoddessInari** [ROCm/ROCm#597]
Are there any technical reasons for not supporting regular Intel IOMMU usage without passthrough-only mode? I don't see this problem/limitation documented anywhere.

Using an X99 chipset with IOMMU with full DMAR/interrupt-remapping/x2apic features, ROCm will only give protection faults, unless SWIOTLB is used instead of the IOMMU for any OpenCL-based apps. 

Anything that doesn't use ROCm works correctly in this situation.

**Comment by TheGoddessInari** [comment]
It's looking as if this may only apply to the second GPU. GPU1 on an ASUS X99-A USB/3.1 is on bus3, and GPU2 is on bus6.

 The error messages always reference bus 6, despite the IOMMU groups being setup correctly.

If GPU2 is set offline, the errors don't occur.

I'm hoping the ROCm developers become active on issues again. ROCm not working with GPU2 when the IOMMU is used for DMA remapping is pretty serious.

**Comment by tasso** [comment]
Original ticket is more than a year old and the person that originally opened ticket  has not responded to the latest request.  If this is still an issue, please file a new ticket and we will be happy to investigate it.  Thanks!
