### ISSUE TITLE
ROCm + Vulkan = hang on Vega FE

### ISSUE THREAD

**Issue by TheGoddessInari** [ROCm/ROCm#603]
It doesn't matter if AMDVLK or RADV is used with Vega FE, anything touching ROCm will cause sooner or later cause an unrecoverable hang if Vulkan is used at the same time.

This isn't observed with OpenGL or other facilities, only Vulkan that I can tell.

It doesn't occur if only ROCm or only Vulkan is used, but occurs frequently when the two are combined. Most reliably seen with Overwatch, but happens on anything that uses Vulkan, including native Linux games.

**Comment by TheGoddessInari** [comment]
As of latest `amd-staging-drm-next`, this is just freezing the GPUs (still can't switch to console or recover), and not the entire system as sysrq still works. It won't let me trigger a kernel crashdump when this occurs.

Does this need more information?

**Comment by boberfly** [comment]
Hi @TheGoddessInari

I haven't tried them at the same time here yet but I can test easily (also running Vega FE).

**Comment by TheGoddessInari** [comment]
@boberfly Would be nice if someone else could confirm. Sometimes it takes a while, sometimes it's instant. For me it's been happening on every DXVK game, and HITMAN for Linux very reliably.

I've mostly been using xmr-stak with ROCm, but it didn't seem to matter what was using ROCm to trigger it.

I've tried different kernels, different mesa versions and `amd-staging-drm-next` at different times, but nothing's resolved it so far. I don't know if there's someone I could get in touch with more directly to try and help, as I'm programmatically literate but this bug ends up being the only reason I'm not on Linux full-time yet.

**Comment by TheGoddessInari** [comment]
Still occurs with latest Mesa, ROCm 1.9.2, and Vega 10 firmware version 18.40.

**Comment by dlight** [comment]
Does this occur with ROCm 3.7?

**Comment by ROCmSupport** [comment]
Thanks @TheGoddessInari 
Can you please check with the latest ROCm 4.0 and share an update asap to move this issue to next level.
Thank you.

**Comment by tasso** [comment]
Original ticket is more than a year old and the person that originally opened ticket  has not responded to the latest request.  If this is still an issue, please file a new ticket and we will be happy to investigate it.  Thanks!
