### ISSUE TITLE
Vulkan driver in ROCm

### ISSUE THREAD

**Issue by aryamazaheri** [ROCm/ROCm#706]
Does ROCm include Vulkan driver? I cannot find anywhere that ROCm supports Vulkan. Should I install AMDGPU-Pro driver instead?

**Comment by ms178** [comment]
ROCm is AMD's compute stack. If you want Vulkan support, you have two options. 1) the Mesa community RADV driver or 2) AMD's AMDVLK driver (which should be also part of their AMDGPU-PRO driver).

**Comment by preda** [comment]
On ubuntu this may help:
```
sudo apt install mesa-vulkan-drivers
```

**Comment by tasso** [comment]
Is this still an issue?  if not, can you please close it?
