### ISSUE TITLE
Vega 64/56/FE how to change SoC Clock from 1107 to 1200?

### ISSUE THREAD

**Issue by marcrblevins** [ROCm/ROCm#713]
Can rocm-smi change the SoC Clock value?
Not talking about Core or Memory frequencies.
Look at:
https://docs.google.com/spreadsheets/d/1-rhYsaRXO1ahk3PyrEgT9gXzs7ImAzh-sbqtgwy8HQg/edit#gid=964538665
See SoC Clock?
6C B0 01 -> 1107
C0 D4 01 -> 1200
Thanks,
Marc

**Comment by jlgreathouse** [comment]
@kentrussell can tell you more about this. I believe that we do not support changing SOCCLK as of ROCm 2.1, but it is an expected feature in a future ROCm release.

**Comment by marcrblevins** [comment]
For mining purposes, we need that 1200 SoC clock to compete with the FPGAs and ASIC.  GPU mining is a dying breed.  :(  Thanks for your quick response...

**Comment by kentrussell** [comment]
Indeed, 2.2 will have support for this in the SMI. If /sys/class/drm/card0/device/pp_dpm_socclk exists, you can modify it yourself by doing:
echo # | sudo tee /sys/class/drm/card0/device/pp_dpm_socclk
Where # is the level that you want to apply. I can't remember if those changes are in the 2.1 kernel or not, but the SMI supports it in 2.2 once it comes out. 
Note: I used card0 assuming that you don't have any integrated graphics or control GPUs installed. It might be card1/card2/etc, depending on your system configuration

**Comment by jlgreathouse** [comment]
The `rock-dkms` module that comes with ROCm 2.1 does not include `pp_dpm_socclk`, at least on my test system with a Vega 10 GPU.

**Comment by marcrblevins** [comment]
Found this link:
https://www.phoronix.com/scan.php?page=news_item&px=Vega-10-More-PowerPlay-Controls

I’ll wait.

Thanks,
Marc

**Comment by nioroso-x3** [comment]
I use pptables to change clocks on my vegas, does that mean the soc clock in is ignored then?
If I create a pptable with the soc clock at 1300mhz my vegas crash, so that means something is changing.

**Comment by marcrblevins** [comment]
> I use pptables to change clocks on my vegas, does that mean the soc clock in is ignored then?
> If I create a pptable with the soc clock at 1300mhz my vegas crash, so that means something is changing.

What do you use to create pptables?  Editor?  You can only go up to 1200mhz max for Vega FE/64s.

**Comment by ddobreff** [comment]
Socclk above 1107Mhz requires a bit more voltage, you should keep Socclk idx you use usually just a tad upper than actual Memclk.

**Comment by nioroso-x3** [comment]
> > I use pptables to change clocks on my vegas, does that mean the soc clock in is ignored then?
> > If I create a pptable with the soc clock at 1300mhz my vegas crash, so that means something is changing.
> 
> What do you use to create pptables? Editor? You can only go up to 1200mhz max for Vega FE/64s.

Just convert hex to binary, I used a python script for it. Then you can load it to /sys/class/cardX/device/pp_table using cat.

**Comment by tasso** [comment]
Original ticket is more than a year old and the person that originally opened ticket  has not responded to the latest request.  If this is still an issue, please file a new ticket and we will investigate it.  Thanks!
