### ISSUE TITLE
where the roc-2.3 tag of this repo

### ISSUE THREAD

**Issue by wormwang** [ROCm/ROCm#763]

**Comment by johnbridgman** [comment]
Not sure about tags, but a roc-2.3.0 branch was just added to the repo (it was missing before, sorry). 

Doing a repo sync will still run into problems with lld and llvm because those repos were each split into two parts between 2.2 and 2.3... work is being done on that now.

**Comment by wormwang** [comment]
some repo still lost roc-2.3.0 tag

warning: redirecting to https://github.com/RadeonOpenCompute/lld/
fatal: Couldn't find remote ref refs/tags/roc-2.3.0
warning: redirecting to https://github.com/RadeonOpenCompute/llvm/
fatal: Couldn't find remote ref refs/tags/roc-2.3.0
warning: redirecting to https://github.com/RadeonOpenCompute/lld/
fatal: Couldn't find remote ref refs/tags/roc-2.3.0
warning: redirecting to https://github.com/RadeonOpenCompute/llvm/
fatal: Couldn't find remote ref refs/tags/roc-2.3.0
error: Cannot fetch lld from http://github.com/RadeonOpenCompute/lld
error: Cannot fetch llvm from http://github.com/RadeonOpenCompute/llvm

error: Exited sync due to fetch errors

**Comment by nartmada** [comment]
Hi @wormwang, please check latest ROCm 6.0 to see if your issue still exists ?  If issue is fixed, please close the ticket.  Thanks.
