### ISSUE TITLE
GROMACS regression in ROCm 2.3

### ISSUE THREAD

**Issue by pszi1ard** [ROCm/ROCm#773]
The major GROMACS kernel flavors regressed by ~30% on both Fiji and Vega from 2.2 to 2.3.

**Comment by sunway513** [comment]
Hi @pszi1ard , could you provide the samples/steps to reproduce the performance regression?

**Comment by pszi1ard** [comment]
The wall-time of the top (time-wise) kernel should indicate where the issue is. I believe AMD has internal pref regression testing of GROMACS, so I'm hoping I don't need to write line-by-line instructions here as perf-testing GROMACS should be a known thing.

**Comment by gowthamcr** [comment]
Hi @pszi1ard 
Can you provide us the version of the Gromacs you are observing issue with?

**Comment by pszi1ard** [comment]
I did the performance measurements with the 2019.2 code but I doubt it is very dependent on the GROMACS version.

I observe major regressions in multiple kernels; for the a 192k sized input (e.g. inputs inside this tarball 0192/ -- generate input tpr with gmx grompp -f pme.mdp)(http://ftp.gromacs.org/benchmarks/water_GMX50_bare.tar.gz):
nbnxn_kernel_ElecEw_VdwLJCombGeom_F_opencl: -32%
pmeGatherKernel: -350%
pmeSolveXYZKernel: -26%
clFFT kernels: ballpark 2x slower

**Comment by pszi1ard** [comment]
> pmeGatherKernel: -350%

This one issues a warning about failing to unroll a loop, so that is probably (part?) of the reason. Can I force unroll?

**Comment by pszi1ard** [comment]
Wrestled through the pain of running the profiler, the most likely main reasons for the nbnxn_kernel_ElecEw_VdwLJCombGeom_F_opencl regression is VGPR/SGPR usage that went from 77/62 to 95/66 dropping occupancy to 0.2; already the original VGPR use is higher than what I believe it should be (I think this should be able to run at 0.5 occupancy).

I hope this helps. Please let me know if there is any progress and what the ETA for the fix to land in a release is -- the current 2.3 is just unusable even for development.

**Comment by pszi1ard** [comment]
Still no fix after the 2.5 release.

**Comment by pszi1ard** [comment]
FYI: The 2.8 release is still severely regressed (so was the 2.7).

**Comment by pszi1ard** [comment]
FYI: no change in 2.9 either.

**Comment by pszi1ard** [comment]
This bug is still not fixed in 3.8.

I've identified it to be related to a missed optimization of float3 register array allocation which was introduced sometime after ROCm 2.2 (at least based on my historic performance data).

**Comment by pszi1ard** [comment]
This is all about the GROMACS OpenCL backend, I don't think this was ever addressed, but this backend is deprecated in favor of the SYCL backed.

**Comment by tasso** [comment]
Thanks for the reply!
