### ISSUE TITLE
Can I use the closed source drivers with rocm?

### ISSUE THREAD

**Issue by EricTheMagician** [ROCm/ROCm#798]
Hi,

I need opengl rendering for the application that I am developing.
Can I use the closed source drivers from AMD with rocm or do I need to use Mesa?

**Comment by kentrussell** [comment]
You can always try, but there's no guarantee about compatibility. There are some shared features, and our code is pretty close, but there's no guarantee that it will work. It's always worth a try though.

**Comment by tasso** [comment]
Is this still an issue? If not, can we please close it? Thanks!

**Comment by EricTheMagician** [comment]
It ended up not really working well, but it was years ago at this point. I haven't tried since.
