### ISSUE TITLE
Rocm 2.4 poor optimization

### ISSUE THREAD

**Issue by gwoltman** [ROCm/ROCm#803]
Using GpuOwl https://github.com/preda/gpuowl
Ubuntu 19.04, Linux kernel 5.0.7, Radeon VII

A critical component of Fast Fourier Transforms is butterfly operations.  In preda's FFT code, a butterfly operation should take 16 f64 add ops, but rocm 2.4 is generating 18 f64 add ops.  

The relevant code (where T2 is a typedef for two doubles representing a complex number) is:

#define X2(a, b) { T2 t = a; a = t + b; b = t - b; }
#define X2_mul_t4(a, b) { T2 t = a; a = t + b; t.x = b.x - t.x; b.x = t.y - b.y; b.y = t.x; }

void fft4Core(T2 *u) {
  X2(u[0], u[2]);
  X2_mul_t4(u[1], u[3]);
  X2(u[0], u[1]);
  X2(u[2], u[3]);
}

Using straightforward code generation, each X2 operation should generate 4 f64 add ops.

**Comment by tasso** [comment]
Is this issue still reproducible?  If not, can we please close it?

**Comment by gwoltman** [comment]
Closing ticket.  I'm no longer doing Radeon VII development work.
