### ISSUE TITLE
Q: OpenCL preprocessor define to identify ROCm or __asm() support

### ISSUE THREAD

**Issue by preda** [ROCm/ROCm#805]
Is there a way, in the OpenCL source, to identify whether it's the ROCm OpenCL that is compiling the code (as opposed to, e.g. amdgpu-pro or something else).

In particular, I'd like to be able to #if case in OpenCL whether __asm() is supported. Being able to identify ROCm would bring me halfway there as I know that ROCm-OpenCL supports __asm().

**Comment by nartmada** [comment]
@preda, I have forwarded your question to internal team.

**Comment by schung-amd** [comment]
Hi @preda, are you still experiencing this issue? If so, can you provide more details on your workflow?

**Comment by preda** [comment]
Here is an example:
```
u32 bfi(u32 u, u32 mask, u32 bits) {
#if HAS_ASM
  u32 out;
  __asm("v_bfi_b32 %0, %1, %2, %3" : "=v"(out) : "v"(mask), "v"(u), "v"(bits));
  return out;
#else
  return (u & mask) | bits;
#endif
}
```
(take from https://github.com/preda/gpuowl/blob/88383e11b63331264dbda70df767519bc61fb9ef/src/cl/weight.cl#L36 )

As you see, the decision whether to use __asm() is based on an outside custom define (HAS_ASM). I would like a solution that does not require this outside-generated define.

Please ask if this usage example is not clear.

**Comment by schung-amd** [comment]
Thanks for the reply @preda, I can see how this could be useful to you. Since asm support is non-standard, it's going to depend on the compiler and platform being used. Currently, the ROCm compilers are built around clang (https://rocm.docs.amd.com/en/latest/reference/rocmcc.html), so you might be able to check for the clang definitions (https://github.com/cpredef/predef/blob/master/Compilers.md#clang). Let me know if this works for you, I'll continue digging for other preprocessor defines you might be able to grab.

**Comment by sohaibnd** [comment]
Hi @preda, you can use the clGetPlatformInfo and clGetDeviceInfo functions to get information about the platform (i.e implementation of OpenCL such as ROCm OpenCL) and the device that you are using which you can use when compiling your OpenCL program. Is that what you are looking for?

**Comment by preda** [comment]
@schung-amd Indeed using the clang defines (such as __clang__ ) should allow me to infer whether the OpenCL compiler is supporting asm().

@sohaibnd Using the host runtime such as clGetPlatformInfo, clGetDeviceInfo is not as straightforward as I'd still need to infer from that the nature of the OpenCL compiler, to know whether various special features such as asm() are supported by the compiler.

Overall I consider this issue as addressed, thank you!
