### ISSUE TITLE
repo.radeon.com/rocm/yum/rpm/: why not HTTPS or at least sign the RPMs

### ISSUE THREAD

**Issue by drwetter** [ROCm/ROCm#807]
?

**Comment by drwetter** [comment]
or at least please sign http://repo.radeon.com/rocm/yum/rpm/repodata/repomd.xml (signature in http://repo.radeon.com/rocm/yum/rpm/repodata/repomd.xml.asc) -- best with a signed/known key.

**Comment by drwetter** [comment]
Anybody out there?

Also the RPMs are not signed. In total this seems to be a software distribution transport mechanism from the 2000 era, latest.

**Comment by nartmada** [comment]
Hi @drwetter, apologies for the lack of response.  We have confirmed RPM files are signed.

# First, Download and Import the GPG key
wget https://repo.radeon.com/rocm/rocm.gpg.key
sudo rpm --import rocm.gpg.key
```
```
# Then, Download the RPM files
wget -r -l1 -np "https://repo.radeon.com/rocm/yum/rpm/" -A ".rpm"
```
```
# Finally, Verify the signatures
cd repo.radeon.com/rocm/yum/rpm
rpm -K *.rpm
```
```
# Sample of output
rocprofiler-2.0.60000.60000-91.el7.x86_64.rpm: digests signatures OK
rocprofiler6.0.0-2.0.60000.60000-91.el7.x86_64.rpm: digests signatures OK
rocprofiler-devel-2.0.60000.60000-91.el7.x86_64.rpm: digests signatures OK
rocprofiler-devel6.0.0-2.0.60000.60000-91.el7.x86_64.rpm: digests signatures OK
rocprofiler-docs-2.0.60000.60000-91.el7.x86_64.rpm: digests signatures OK
rocprofiler-docs6.0.0-2.0.60000.60000-91.el7.x86_64.rpm: digests signatures OK
rocprofiler-plugins-2.0.60000.60000-91.el7.x86_64.rpm: digests signatures OK
rocprofiler-plugins6.0.0-2.0.60000.60000-91.el7.x86_64.rpm: digests signatures OK
rocrand-2.10.17.60000-91.el7.x86_64.rpm: digests signatures OK
rocrand6.0.0-2.10.17.60000-91.el7.x86_64.rpm: digests signatures OK
rocrand-devel-2.10.17.60000-91.el7.x86_64.rpm: digests signatures OK
rocrand-devel6.0.0-2.10.17.60000-91.el7.x86_64.rpm: digests signatures OK
```

**Comment by nartmada** [comment]
Closing the ticket as we have confirmed RPM files are signed.
