### ISSUE TITLE
OpenCL build log does not print error details

### ISSUE THREAD

**Issue by blueberry** [ROCm/ROCm#817]
Hi,

I'm using ROCm 2.4 on linux.
When I compile a kernel with an error, the build log is always the same:
"Error: Failed to compile opencl source (from CL to LLVM IR)." 

Earlier, when I was using old proprietary AMD's OpenCL 2.0 driver provided by catalyst, the build log displayed the offending source in a usable compilation report.

Is there a way to get that sort of report with ROCm OpenCL?

**Comment by tasso** [comment]
Is this still reproducible?  If not, can we please close it?  Thanks!

**Comment by tasso** [comment]
Original ticket is more than a year old and the person that opened ticket originally has not responded to the latest request.  If this is still an issue, please file a new ticket and we will happy to investigate it.  Thanks!
