### ISSUE TITLE
ROCm 2.5: Process device data doesn't exist

### ISSUE THREAD

**Issue by dreitzle** [ROCm/ROCm#820]
After an oops was fixed (at least for me) in 2.5 (see #658 ), i am now encountering a different issue:
When i try to run rocminfo, i get
> $ /opt/rocm/bin/rocminfo 
> hsa api call failure at line 900, file: /home/1001/jenkins-root/workspace/sandbox-centos/rocm-rel-2.5/rocm-2.5-27-20190603/centos/rocminfo/rocminfo.cc. Call returned 4104

and clinfo doesn't show the platform.
The kernel emits a warning, when any of those commands is run:

> [  123.577018] WARNING: CPU: 26 PID: 20139 at mm/page_alloc.c:3189 __alloc_pages_slowpath+0x6f/0x724
> [  123.577020] Modules linked in: nf_conntrack_netlink xt_set xt_multiport ip_set_hash_ip rpcsec_gss_krb5 auth_rpcgss nfsv4 dns_resolver nfs lockd grace fscache ip6t_rpfilter ipt_REJECT nf_reject_ipv4 ip6t_REJECT nf_reject_ipv6 xt_conntrack ip_set nfnetlink ebtable_nat ebtable_broute bridge stp llc ip6table_nat nf_conntrack_ipv6 nf_defrag_ipv6 nf_nat_ipv6 ip6table_mangle ip6table_security ip6table_raw iptable_nat nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 nf_nat nf_conntrack iptable_mangle iptable_security iptable_raw ebtable_filter ebtables ip6table_filter ip6_tables iptable_filter sunrpc dm_mirror dm_region_hash dm_log dm_mod vfat fat amdgpu(OE) mxm_wmi iTCO_wdt iTCO_vendor_support sb_edac intel_powerclamp coretemp intel_rapl iosf_mbi kvm_intel kvm irqbypass crc32_pclmul ghash_clmulni_intel aesni_intel
> [  123.577052]  lrw gf128mul glue_helper ablk_helper cryptd snd_hda_codec_hdmi amdttm(OE) amd_sched(OE) pcspkr snd_hda_intel snd_hda_codec joydev snd_hda_core snd_hwdep snd_seq snd_seq_device snd_pcm i2c_i801 snd_timer sg snd amdkcl(OE) amd_iommu_v2 mei_me soundcore lpc_ich mei ioatdma ipmi_si ipmi_devintf ipmi_msghandler wmi acpi_power_meter acpi_pad ip_tables xfs libcrc32c raid10 sd_mod crc_t10dif crct10dif_generic drm_kms_helper syscopyarea sysfillrect sysimgblt fb_sys_fops ttm igb drm crct10dif_pclmul crct10dif_common crc32c_intel ahci ptp pps_core libahci dca i2c_algo_bit drm_panel_orientation_quirks libata
> [  123.577082] CPU: 26 PID: 20139 Comm: rocminfo Kdump: loaded Tainted: G           OE  ------------   3.10.0-957.21.2.el7.x86_64 #1
> [  123.577083] Hardware name: Supermicro SYS-4028GR-TR2/X10DRG-O+-CPU, BIOS 2.0a 07/27/2016
> [  123.577085] Call Trace:
> [  123.577091]  [<ffffffff85562fe7>] dump_stack+0x19/0x1b
> [  123.577097]  [<ffffffff84e97768>] __warn+0xd8/0x100
> [  123.577099]  [<ffffffff84e978ad>] warn_slowpath_null+0x1d/0x20
> [  123.577101]  [<ffffffff8555dfa7>] __alloc_pages_slowpath+0x6f/0x724
> [  123.577107]  [<ffffffff84fc11c6>] ? __alloc_pages_nodemask+0x176/0x420
> [  123.577112]  [<ffffffff8501cb6c>] ? kmem_cache_alloc_trace+0x3c/0x200
> [  123.577114]  [<ffffffff84fc1454>] __alloc_pages_nodemask+0x404/0x420
> [  123.577117]  [<ffffffff8500e308>] alloc_pages_current+0x98/0x110
> [  123.577119]  [<ffffffff84fbbb9e>] __get_free_pages+0xe/0x40
> [  123.577122]  [<ffffffff85019a1e>] kmalloc_order_trace+0x2e/0xa0
> [  123.577124]  [<ffffffff8501da61>] __kmalloc+0x211/0x230
> [  123.577173]  [<ffffffffc0943f29>] amdgpu_vm_update_ptes+0x629/0x6a0 [amdgpu]
> [  123.577176]  [<ffffffff8501da3b>] ? __kmalloc+0x1eb/0x230
> [  123.577194]  [<ffffffffc094b7f8>] ? amdgpu_sync_get_owner+0x38/0x60 [amdgpu]
> [  123.577229]  [<ffffffffc0944057>] amdgpu_vm_bo_update_mapping+0xb7/0xe0 [amdgpu]
> [  123.577255]  [<ffffffffc09455a9>] amdgpu_vm_bo_update+0x349/0x830 [amdgpu]
> [  123.577295]  [<ffffffffc0a149cb>] update_gpuvm_pte.isra.7+0x1b/0x50 [amdgpu]
> [  123.577326]  [<ffffffffc0a173b3>] amdgpu_amdkfd_gpuvm_map_memory_to_gpu+0x463/0x700 [amdgpu]
> [  123.577354]  [<ffffffffc09ffbc3>] kfd_process_alloc_gpuvm+0xb3/0x1f0 [amdgpu]
> [  123.577381]  [<ffffffffc09ffe56>] kfd_process_device_init_vm+0x156/0x240 [amdgpu]
> [  123.577407]  [<ffffffffc09f66cb>] kfd_ioctl_acquire_vm+0xab/0xd0 [amdgpu]
> [  123.577433]  [<ffffffffc09f8ff4>] kfd_ioctl+0x334/0x500 [amdgpu]
> [  123.577458]  [<ffffffffc09f6620>] ? kfd_ioctl_free_memory_of_gpu+0xe0/0xe0 [amdgpu]
> [  123.577463]  [<ffffffff84fec27d>] ? handle_mm_fault+0x39d/0x9b0
> [  123.577468]  [<ffffffff850569d0>] do_vfs_ioctl+0x3a0/0x5a0
> [  123.577473]  [<ffffffff85570628>] ? __do_page_fault+0x228/0x4f0
> [  123.577475]  [<ffffffff85056c71>] SyS_ioctl+0xa1/0xc0
> [  123.577479]  [<ffffffff85575ddb>] system_call_fastpath+0x22/0x27
> [  123.577480] ---[ end trace 0d418592a15c8884 ]---
> [  123.577482] kfd2kgd: amdgpu_vm_bo_update failed
> [  123.577631] kfd2kgd: update_gpuvm_pte() failed
> [  123.577773] kfd2kgd: Failed to map bo to gpuvm
> [  123.578160] ida_remove called for id=32768 which is not allocated.

Looking at the sources of my kernel, this warning from __alloc_pages_slowpath is
```
	/*
	 * In the slowpath, we sanity check order to avoid ever trying to
	 * reclaim >= MAX_ORDER areas which will never succeed. Callers may
	 * be using allocators in order of preference for an area that is
	 * too large.
	 */
	if (order >= MAX_ORDER) {
		WARN_ON_ONCE(!(gfp_mask & __GFP_NOWARN));
		return NULL;
	}
```
But i didn't get any further than this. Any ideas, what's causing this? Maybe some misconfiguration on my part?
Full dmesg output is attached.

[dmesg.txt](https://github.com/RadeonOpenCompute/ROCm/files/3285651/dmesg.txt)

**Comment by streamhsa** [comment]
Hi dreitzle 
What is the GPUs you are using and CentOS version with kernel details.

Thanks

**Comment by pramenku** [comment]
Hi dreitzle
What is the GPU plugged into the system.

Thanks

**Comment by dreitzle** [comment]
This is a machine with 2x Xeon E5-2640v4 and 8x R9 Nano on CentOS 7.6 with the latest kernel 3.10.0-957.21.2.el7.x86_64.

**Comment by dreitzle** [comment]
It seems the above warning was fixed in the new kernel 3.10.0-957.21.3.el7.x86_64.
Still, i can't get it working.
When i boot the new kernel, dmesg looks like this: 
[dmesg-2T-512G.txt](https://github.com/RadeonOpenCompute/ROCm/files/3325283/dmesg-2T-512G.txt)
For each GPU, i get: 

```
[   15.172056] amdgpu 0000:0f:00.0: enabling device (0100 -> 0103)
[   15.172305] [drm] initializing kernel modesetting (FIJI 0x1002:0x7300 0x1002:0x0B36 0xCA).
[   15.172326] [drm] register mmio base: 0xC7100000
[   15.172328] [drm] register mmio size: 262144
[   15.172350] [drm] probing gen 2 caps for device 10b5:9797 = 14796903/f0e
[   15.172354] [drm] probing mlw for device 10b5:9797 = 14796903
[   15.172359] [drm] add ip block number 0 <vi_common>
[   15.172361] [drm] add ip block number 1 <gmc_v8_0>
[   15.172364] [drm] add ip block number 2 <tonga_ih>
[   15.172366] [drm] add ip block number 3 <powerplay>
[   15.172368] [drm] add ip block number 4 <dm>
[   15.172371] [drm] add ip block number 5 <gfx_v8_0>
[   15.172373] [drm] add ip block number 6 <sdma_v3_0>
[   15.172376] [drm] add ip block number 7 <uvd_v6_0>
[   15.172378] [drm] add ip block number 8 <vce_v3_0>
[   15.172396] [drm] UVD is enabled in physical mode
[   15.172399] [drm] VCE enabled in physical mode
[   16.106122] ATOM BIOS: 113-C8820200-102
[   16.106153] [drm] GPU posting now...
[   16.191496] [drm] vm size is 64 GB, 2 levels, block size is 10-bit, fragment size is 9-bit
[   16.191516] amdgpu 0000:0f:00.0: BAR 2: releasing [mem 0x27f10000000-0x27f101fffff 64bit pref]
[   16.191519] amdgpu 0000:0f:00.0: BAR 0: releasing [mem 0x27f00000000-0x27f0fffffff 64bit pref]
[   16.191540] pcieport 0000:0a:14.0: BAR 15: releasing [mem 0x27f00000000-0x27f101fffff 64bit pref]
[   16.191581] pcieport 0000:0a:14.0: BAR 15: no space for [mem size 0x180000000 64bit pref]
[   16.191584] pcieport 0000:0a:14.0: BAR 15: failed to assign [mem size 0x180000000 64bit pref]
[   16.191591] amdgpu 0000:0f:00.0: BAR 0: no space for [mem size 0x100000000 64bit pref]
[   16.191594] amdgpu 0000:0f:00.0: BAR 0: failed to assign [mem size 0x100000000 64bit pref]
[   16.191597] amdgpu 0000:0f:00.0: BAR 2: no space for [mem size 0x00200000 64bit pref]
[   16.191600] amdgpu 0000:0f:00.0: BAR 2: failed to assign [mem size 0x00200000 64bit pref]
[   16.191603] pcieport 0000:09:00.0: PCI bridge to [bus 0a-0f]
[   16.191607] pcieport 0000:09:00.0:   bridge window [io  0x2000-0x5fff]
[   16.191612] pcieport 0000:09:00.0:   bridge window [mem 0xc7100000-0xc74fffff]
[   16.191616] pcieport 0000:09:00.0:   bridge window [mem 0x27f00000000-0x27f701fffff 64bit pref]
[   16.191622] pcieport 0000:0a:14.0: PCI bridge to [bus 0f]
[   16.191626] pcieport 0000:0a:14.0:   bridge window [io  0x2000-0x2fff]
[   16.191631] pcieport 0000:0a:14.0:   bridge window [mem 0xc7100000-0xc71fffff]
[   16.191635] pcieport 0000:0a:14.0:   bridge window [mem 0x27f00000000-0x27f101fffff 64bit pref]
[   16.191646] [drm] Not enough PCI address space for a large BAR.
[   16.191650] amdgpu 0000:0f:00.0: BAR 0: assigned [mem 0x27f00000000-0x27f0fffffff 64bit pref]
[   16.191661] amdgpu 0000:0f:00.0: BAR 2: assigned [mem 0x27f10000000-0x27f101fffff 64bit pref]
[   16.191691] amdgpu 0000:0f:00.0: VRAM: 4096M 0x000000F400000000 - 0x000000F4FFFFFFFF (4096M used)
[   16.191694] amdgpu 0000:0f:00.0: GTT: 1024M 0x0000000000000000 - 0x000000003FFFFFFF
[   16.191696] [drm] Detected VRAM RAM=4096M, BAR=256M
[   16.191698] [drm] RAM width 512bits HBM
[   16.192296] [drm] amdgpu: 4096M of VRAM memory ready
[   16.192299] [drm] amdgpu: 4096M of GTT memory ready.
[   16.192313] [drm] GART: num cpu pages 262144, num gpu pages 262144
[   16.192364] [drm] PCIE GART of 1024M enabled (table at 0x000000F400040000).
[   16.192459] amdgpu 0000:0f:00.0: irq 107 for MSI/MSI-X
[   16.192502] [drm] Chained IB support enabled!
[   16.193882] [drm] Found UVD firmware Version: 1.91 Family ID: 12
[   16.193887] [drm] UVD ENC is disabled
[   16.197812] [drm] Found VCE firmware Version: 54.1 Binary ID: 3
[   16.268104] [drm] Display Core initialized with v3.1.38!
[   16.268630] [drm] Supports vblank timestamp caching Rev 2 (21.10.2013).
[   16.268632] [drm] Driver supports precise vblank timestamp query.
[   16.298264] [drm] UVD initialized successfully.
[   16.399270] [drm] VCE initialized successfully.
[   16.468368] kfd kfd: Allocated 3969056 bytes on gart
[   16.468390] Virtual CRAT table created for GPU
[   16.468392] Parsing CRAT table with 1 nodes
[   16.468407] Creating topology SYSFS entries
[   16.469894] Topology: Add dGPU node [0x7300:0x1002]
[   16.469982] kfd kfd: added device 1002:7300
[   16.472016] [drm] Cannot find any crtc or sizes
[   16.473363] [drm] Initialized amdgpu 3.25.0 20150101 for 0000:0f:00.0 on minor 7
```

I realised that the mmio base was set to 2T, so i lowered it to 512G and set the size to 256G. The adresses change, but it still does not work:
[dmesg-512G-256G.txt](https://github.com/RadeonOpenCompute/ROCm/files/3325302/dmesg-512G-256G.txt)

I also tried booting with pci=nocrs. Then, the failed BAR allocations disappear, but nothing else changes:
[dmesg-512G-256G-2.txt](https://github.com/RadeonOpenCompute/ROCm/files/3325331/dmesg-512G-256G-2.txt)

The only error i get now is:
```
[ 1420.793616] Process device data doesn't exist
[ 1420.793752] Process device data doesn't exist
[ 1420.793900] Process device data doesn't exist
```

These appear when trying to run rocminfo or clinfo (only as root, as a user i get nothing at all).
The errors are coming from the kfd driver, but i have no idea, what they mean...

**Comment by sdh4** [comment]
I am also seeing similar symptoms. rocminfo also gives me: 
```
hsa api call failure at line 900, file: /home/1001/jenkins-root/workspace/sandbox-centos/rocm-rel-2.5/rocm-2.5-27-20190603/centos/rocminfo/rocminfo.cc. Call returned 4104
``` 
and
```
[   30.278372] ------------[ cut here ]------------
[   30.278381] WARNING: CPU: 5 PID: 11434 at mm/page_alloc.c:3189 __alloc_pages_slowpath+0x6f/0x724
[   30.278383] Modules linked in: xt_CHECKSUM ipt_MASQUERADE nf_nat_masquerade_ipv4 tun devlink ip6t_rpfilter ipt_REJECT nf_reject_ipv4 ip6t_REJECT nf_reject_ipv6 xt_conntrack ip_set nfnetlink ebtable_nat ebtable_broute bridge stp llc ip6table_nat nf_conntrack_ipv6 nf_defrag_ipv6 nf_nat_ipv6 ip6table_mangle ip6table_security ip6table_raw iptable_nat nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 nf_nat nf_conntrack iptable_mangle iptable_security iptable_raw ebtable_filter ebtables ip6table_filter ip6_tables iptable_filter edt(POE) fuse vfat fat amdgpu(OE) amd64_edac_mod edac_mce_amd kvm_amd kvm irqbypass mos7840 crc32_pclmul ghash_clmulni_intel aesni_intel raid1 lrw gf128mul glue_helper ablk_helper cryptd joydev cdc_acm amdttm(OE) amd_sched(OE) snd_hda_codec_hdmi snd_hda_intel pcspkr das4020_12(OE) snd_hda_codec
[   30.278420]  snd_hda_core snd_hwdep snd_seq snd_seq_device snd_pcm sg snd_timer snd amdkcl(OE) soundcore amd_iommu_v2 ipmi_ssif ccp k10temp i2c_piix4 ipmi_si ipmi_devintf ipmi_msghandler pinctrl_amd i2c_designware_platform i2c_designware_core acpi_cpufreq Cs8xxx(OE) auth_rpcgss sunrpc ip_tables xfs sd_mod crc_t10dif crct10dif_generic ast i2c_algo_bit drm_kms_helper syscopyarea sysfillrect bnx2x sysimgblt fb_sys_fops ttm drm ahci mpt2sas libahci crct10dif_pclmul crct10dif_common crc32c_intel mdio libata ptp pps_core raid_class libcrc32c scsi_transport_sas drm_panel_orientation_quirks nfit libnvdimm dm_mirror dm_region_hash dm_log dm_mod
[   30.278452] CPU: 5 PID: 11434 Comm: X Kdump: loaded Tainted: P           OE  ------------   3.10.0-957.21.3.el7.x86_64 #1
[   30.278453] Hardware name: GIGABYTE MZ31-AR0-00/MZ31-AR0-00, BIOS F07 06/05/2018
[   30.278455] Call Trace:
[   30.278461]  [<ffffffff9eb63107>] dump_stack+0x19/0x1b
[   30.278465]  [<ffffffff9e497768>] __warn+0xd8/0x100
[   30.278468]  [<ffffffff9e4978ad>] warn_slowpath_null+0x1d/0x20
[   30.278470]  [<ffffffff9eb5e0c7>] __alloc_pages_slowpath+0x6f/0x724
[   30.278473]  [<ffffffff9e42a621>] ? __switch_to+0x151/0x580
[   30.278477]  [<ffffffff9e61cb6c>] ? kmem_cache_alloc_trace+0x3c/0x200
[   30.278481]  [<ffffffff9e5c1454>] __alloc_pages_nodemask+0x404/0x420
[   30.278484]  [<ffffffff9e60e308>] alloc_pages_current+0x98/0x110
[   30.278486]  [<ffffffff9e5bbb9e>] __get_free_pages+0xe/0x40
[   30.278489]  [<ffffffff9e619a1e>] kmalloc_order_trace+0x2e/0xa0
[   30.278491]  [<ffffffff9e61da61>] __kmalloc+0x211/0x230
[   30.278525]  [<ffffffffc0cc9f29>] amdgpu_vm_update_ptes+0x629/0x6a0 [amdgpu]
[   30.278528]  [<ffffffff9e61da3b>] ? __kmalloc+0x1eb/0x230
[   30.278554]  [<ffffffffc0cd17d7>] ? amdgpu_sync_get_owner+0x17/0x60 [amdgpu]
[   30.278579]  [<ffffffffc0cca057>] amdgpu_vm_bo_update_mapping+0xb7/0xe0 [amdgpu]
[   30.278604]  [<ffffffffc0ccb5a9>] amdgpu_vm_bo_update+0x349/0x830 [amdgpu]
[   30.278628]  [<ffffffffc0cb4289>] amdgpu_gem_va_ioctl+0x3c9/0x490 [amdgpu]
[   30.278631]  [<ffffffff9e5f755c>] ? page_add_file_rmap+0x8c/0xc0
[   30.278654]  [<ffffffffc0cb3ec0>] ? amdgpu_gem_metadata_ioctl+0x1e0/0x1e0 [amdgpu]
[   30.278666]  [<ffffffffc0230f2c>] drm_ioctl_kernel+0x6c/0xb0 [drm]
[   30.278688]  [<ffffffffc0231647>] drm_ioctl+0x1e7/0x420 [drm]
[   30.278711]  [<ffffffffc0cb3ec0>] ? amdgpu_gem_metadata_ioctl+0x1e0/0x1e0 [amdgpu]
[   30.278734]  [<ffffffffc0c9504b>] amdgpu_drm_ioctl+0x4b/0x80 [amdgpu]
[   30.278742]  [<ffffffff9e6569d0>] do_vfs_ioctl+0x3a0/0x5a0
[   30.278745]  [<ffffffff9eb70628>] ? __do_page_fault+0x228/0x4f0
[   30.278747]  [<ffffffff9e656c71>] SyS_ioctl+0xa1/0xc0
[   30.278750]  [<ffffffff9eb75ddb>] system_call_fastpath+0x22/0x27
[   30.278752] ---[ end trace e5645e7404aa9202 ]---
```
Then I get a bunch of: 
```
[drm:amdgpu_gem_va_ioctl [amdgpu]] *ERROR* Couldn't update BO_VA (-12)
```
I also see:
```
[  100.773734] kfd2kgd: amdgpu_vm_bo_update failed
[  100.773760] kfd2kgd: update_gpuvm_pte() failed
[  100.773774] kfd2kgd: Failed to map bo to gpuvm
[  100.774163] ida_remove called for id=32768 which is not allocated.
```

The system is attempting to show an X display, but the image is corrupted (along the lines of what would be expected from an incorrect framebuffer size/offset)

When starting X, it prints the following message:
```
amdgpu: Not enough memory for command submission.
amdgpu: The CS has been cancelled because the context is lost.
```

**Comment by tasso** [comment]
Is this still reproducible?  If not, can we please close it?  Thanks!

**Comment by dreitzle** [comment]
The machine this was seen on no longer exists, so i cannot test anymore.
As far as i am concerned, this may be closed.

**Comment by tasso** [comment]
Thanks for the reply!
