### ISSUE TITLE
ppc64le support

### ISSUE THREAD

**Issue by ticlazau** [ROCm/ROCm#830]
Hello,

is ROCm supported on ppc64le - CentOS or Ubuntu?

Thx,
FM

**Comment by illuhad** [comment]
Early versions of ROCm claimed to support ppc64le - no idea what happened since then. I played with recent versions on Power8 but was unsuccessful (see #800)

**Comment by darkbasic** [comment]
AMD, is there any news on this? Do we really need to wait for rusticl to support SyCL and HIP? Hopefully ROCm won't be the next AMDVLK, but I'm starting to lose hope.

**Comment by nartmada** [comment]
I am really sorry for the delay.  It should work in latest ROCm 6.0.2.  Can you please give it a try?  Thanks.

**Comment by darkbasic** [comment]
@nartmada awesome I'll give it a try, thanks!

**Comment by nartmada** [comment]
@darkbasic, please let us know how it goes with ROCm 6.0.2.  Thanks.

**Comment by darkbasic** [comment]
@nartmada I'm sorry for the delay, unfortunately I still have the same issue as before:
```
talos2 ~ # clinfo 
clinfo: /var/tmp/portage/dev-libs/rocm-opencl-runtime-6.0.2/work/clr-rocm-6.0.2/rocclr/os/os_posix.cpp:321: static void amd::Os::currentStackInfo(unsigned char**, size_t*): Assertion `Os::currentStackPtr() >= *base - *size && Os::currentStackPtr() < *base && "just checking"' failed.
Aborted (core dumped)
```

Previous archived issue about this: https://github.com/ROCm/ROCm-OpenCL-Runtime/issues/158
In addition to the previous patches/workarounds I had to use the `-DNO_WARN_X86_INTRINSICS` compile flag to get it to build, but it still fails at runtime as it did before.

**Comment by darkbasic** [comment]
Full build log without `-DNO_WARN_X86_INTRINSICS`: [rocm-opencl-runtime-6.0.2.build.log](https://github.com/ROCm/ROCm/files/14402368/rocm-opencl-runtime-6.0.2.build.log)

**Comment by darkbasic** [comment]
I've also opened a brand new issue on the new repo: https://github.com/ROCm/clr/issues/61

**Comment by tucnak** [comment]
@nartmada We have been trying to get our MI50 card working on a POWER9 system, and in this quest we had built everything from scratch, had to mess with some obscure kernel versions (freedesktop) that is what AMD is using apparently for their cutting-edge changes but to no avail. The runtime would still be incredibly unreliable, have to be recovered periodically, running into [horrible issues](https://github.com/ROCm/ROCK-Kernel-Driver/issues/147) which haven't bee addressed. I understand that the consumer cards aren't supported, but isn't MI50 datacenter-grade and supposed to be stable? We no longer have appetite for messing with the kernels, and would have to stick to debian-stable, i.e. 6.1.76 at the time of writing this comment. AMD is the only vendor to properly support IOMMU, and indeed we're prepared to go through the effort of building userspace ROCm components in a VM image but before we would do that, we want to be sure that the kernel business is stable, and isn't going to mess up our host like it did numerous times prior.

**Comment by saadrahim** [comment]
ROCm only supports x86_64 based CPU architectures. In addition, we have additional dependencies on CPU and PCIe features as documented at https://rocm.docs.amd.com/projects/install-on-linux/en/latest/reference/system-requirements.html#cpu-support.

@nartmada was mistaken when he suggested to try the latest versions.

**Comment by darkbasic** [comment]
"dependencies on CPU and PCIe features" sounds like corporate bullsh*t to me: it translates to pcie atomics according to that page. @madscientist159 doesn't power 8 already support PCIe atomics?

Honestly it looks like George Hotz was right suggesting to look at Intel for compute.
