### ISSUE TITLE
ROCm 2.7 with RX5700: Device not found

### ISSUE THREAD

**Issue by valeriob01** [ROCm/ROCm#865]
ROCm 2.7 cannot find RX5700
System: Debian

Issue opened on the application git page:
https://github.com/preda/gpuowl/issues/60#issue-480930426

**Comment by JMadgwick** [comment]
The RX 5700 is a Navi based GPU. Navi GPUs are not supported by ROCm ([not in the supported list](https://github.com/RadeonOpenCompute/ROCm#supported-gpus)).
As far as I know this should be the expected behaviour with Navi and ROCm.
To use OpenCL with Navi you can use the standard [AMDGPU-Pro drivers from the AMD website](https://www.amd.com/en/support/kb/release-notes/rn-amdgpu-unified-linux).

**Comment by valeriob01** [comment]
Thanks, I close the issue and go to install amdgpu-pro.

**Comment by valeriob01** [comment]
Not sure how to tell it but, after installing amdgpu-pro I got exactly the same error.

**Comment by JMadgwick** [comment]
What is the result of clinfo?
Have you tried other OpenCL programs?

**Comment by valeriob01** [comment]
> What is the result of clinfo?
This is in my plan to paste the clinfo output here

> Have you tried other OpenCL programs?
no I only run this program.

**Comment by valeriob01** [comment]
It just seems Navi support starts with kernel 5.3
https://www.phoronix.com/scan.php?page=news_item&px=AMD-Navi-DRM-Next-Lands

**Comment by valeriob01** [comment]
In hindsight this can be resolved by adding the necessary files navi*.bin into the directory /lib/firmware/amdgpu/

**Comment by valeriob01** [comment]
> The RX 5700 is a Navi based GPU. Navi GPUs are not supported by ROCm ([not in the supported list](https://github.com/RadeonOpenCompute/ROCm#supported-gpus)).
> As far as I know this should be the expected behaviour with Navi and ROCm.
> 
> To use OpenCL with Navi you can use the standard [AMDGPU-Pro drivers from the AMD website](https://www.amd.com/en/support/kb/release-notes/rn-amdgpu-unified-linux).
> Note: You will want to install the ["pro stack"](https://amdgpu-install.readthedocs.io/en/latest/install-overview.html), this contains the OpenCL driver.

I have done the following test: on a machine with Ubuntu 18.04 and ROCm 2.7 and Kernel 5.3-rc6, **rocm-smi sees the RX5700XT gpu**, clinfo segfaults, and gpuowl segfaults. Other programs like mfakto segfault too.

**Comment by valeriob01** [comment]
Update: with amdgpu-pro and kernel 5.3-rc7:
- clinfo shows "No device found".
- gpuowl stops with error on getdeviceids.

**Comment by EwoutH** [comment]
@valeriob01 Still the same issue with ROCm 2.8?

**Comment by valeriob01** [comment]
> @valeriob01 Still the same issue with ROCm 2.8?

I don't know. I have installed amdgpu-pro 19.30 on Ubuntu 18.04, then installed kernel 5.4-rc1, but the problem still persists with RX5700: NO DEVICE FOUND.

**Comment by linzhanyu** [comment]
1. rock-dkms  conflicts with amdgpu-dkms 
2. ubuntu18.04 black screen restart after installing rocm
Will ROCm support RX5700XT in the future?

**Comment by sarunasb** [comment]
This not an answer about ROCm and Navi (3.1 still doesn't seem to support Navi), but if all you need is working OpenCL, here is a workaround: upstream Linux kernel driver (open source amdgpu) works with OpenCL part from AMDGPU-PRO. After downloading the latest AMDGPU-PRO, run

`amdgpu-pro-install --opencl=pal --headless --no-dkms`

I keep an updated version of instruction and what worked for me [here](https://math.dartmouth.edu/~sarunas/amdgpu.html).

**Comment by nuliknol** [comment]
@JMadgwick 
why isn't RX5700 card supported ? If I am understanding correctly, all that needs to be done is to recompile the code using LLVM with `-mcpu gfx1010`, or is there any more complications than that?

**Comment by tasso** [comment]
Is this issue still reproducible?  If not; can we please close it?  Thanks!

**Comment by tasso** [comment]
Original ticket is more than a year old and the person that opened ticket originally has not responded to the latest request.  If this is still an issue, please file a new ticket and we will happy to investigate it.  Thanks!
