### ISSUE TITLE
2.7 tags can not build hcc

### ISSUE THREAD

**Issue by acowley** [ROCm/ROCm#874]
If I am understanding correctly, the `default.xml` specifies the `roc-hcc-2.7.0` tag for `llvm` and the `roc-2.7.0` tag for `clang` for building `hcc`. This combination does not build because that tag of `llvm` [does not define](https://github.com/RadeonOpenCompute/llvm/blob/9a9477021e6998100ff64d1360dcfe64f65cebe5/include/llvm/Support/TargetParser.h#L123) `GK_GFX908`, while the given revision of `clang` [does refer to it](https://github.com/RadeonOpenCompute/clang/blob/roc-2.7.0/lib/Basic/Targets/AMDGPU.cpp#L155).

**Comment by acowley** [comment]
I think the problem is that the `default.xml` should have 

<project name="hcc-clang-upgrade" path="llvm_amd-common/clang" revision="refs/tags/roc-hcc-2.7.0" /> on [line 50](https://github.com/RadeonOpenCompute/ROCm/blob/master/default.xml#L50).

**Comment by tasso** [comment]
Is this still an issue?  If not, can we please close it?  Thanks!
