### ISSUE TITLE
when it support windows?

### ISSUE THREAD

**Issue by ice-bird** [ROCm/ROCm#882]
did you plan to support windows?  if yes,when?

**Comment by Bengt** [comment]
You can install a Linux distribution that ROCm supports into the Windows subsystem for Linux via the Microsoft store. However, WSL does not support passing through GPUs, yet. Maybe ask there for GPU support.

**Comment by tasso** [comment]
Since there is WINDOWS support:

https://rocm.docs.amd.com/projects/install-on-windows/en/latest/

I think this issue can be closed.  Can you please confirm?  Thanks!

**Comment by nartmada** [comment]
https://rocm.docs.amd.com/projects/install-on-windows/en/latest/how-to/install.html
