### ISSUE TITLE
Does ROCm 2.7.2 support APU V1000? especially V1807B?

### ISSUE THREAD

**Issue by edward-yang-tw** [ROCm/ROCm#890]
We are working with a V1807b based platform with RX Vega11 integrated GPPU. We would like to know if ROCm support this APU.

thanks!

**Comment by tuxzz** [comment]
Seems no, but you can use OpenCL instead.
From README.md
> The integrated GPUs in AMD APUs are not officially supported targets for ROCm. As described below, "Carrizo", "Bristol Ridge", and "Raven Ridge" APUs are enabled in our upstream drivers and the ROCm OpenCL runtime. However, they are not enabled in our HCC or HIP runtimes, and may not work due to motherboard or OEM hardware limitations. As such, they are not yet officially supported targets for ROCm.

**Comment by nartmada** [comment]
Please check latest ROCm Documentation and ROCm 5.7.1 to see if your query has been resolved.  If resolved, please close the ticket.  Thanks.

**Comment by nartmada** [comment]
Original ticket is more than a year old and the person that opened the ticket has not responded to the latest request.  If this is still an issue, please file a new ticket and we will investigate.  Thanks!
