### ISSUE TITLE
Should rocminfo and rocm_agent_enumerator show R9 390 as gfx702?

### ISSUE THREAD

**Issue by Lucretia** [ROCm/ROCm#891]
I'm asking because according to [LLVM docs](https://llvm.org/docs/AMDGPUUsage.html#processors) my card shows as gfx702. I know HCC is deprecated, but I'm helping with Gentoo ROCm and I have implemented the patches for gfx700, gfx701, gfx702 from https://github.com/RadeonOpenCompute/hcc-clang-upgrade/pull/149 and I now have a compiler using the correct bitcodes.

So, really shouldn't these tools return gfx702 in my case? If so, I can send a patch in.

**Comment by fxkamd** [comment]
As I understand the definition of gfx701 vs gfx702, the only difference is the 64-bit floating point rate. There are different Hawaii variants available that are fused differently depending on the target market. The driver doesn't currently distinguish the two. If we unconditionally change all Hawaiis from one gfx version to the other, we'll always get it wrong for someone.

**Comment by nartmada** [comment]
Please check latest ROCm Documentation and ROCm 5.7.1 to see if your query has been resolved.  If resolved, please close the ticket.  Thanks.

**Comment by nartmada** [comment]
Original ticket is more than a year old and the person that opened the ticket has not responded to the latest request.  If this is still an issue, please file a new ticket and we will investigate.  Thanks!

**Comment by Lucretia** [comment]
Because AMD just drops users and did with rocm, I bought an NV card so i could use CUDA instead. Fix your stuff properly and stop dropping support for users who have shelled out money on your hardware. I still have numerous AMD gfx cards and another one in another slot for vfio passthrough. It's not you can blame me given the total lack of support since I opened this ticket 4 (READ IT! 4!!!) years ago.
