### ISSUE TITLE
Repo issues for rocprofiler-dev and rocr_debug_agent

### ISSUE THREAD

**Issue by VincentSC** [ROCm/ROCm#914]
This is the output
```Get:1 http://repo.radeon.com/rocm/apt/debian xenial/main amd64 rocprofiler-dev amd64 1.0.0 [217 kB]
Err:1 http://repo.radeon.com/rocm/apt/debian xenial/main amd64 rocprofiler-dev amd64 1.0.0
  Hash Sum mismatch
Get:2 http://repo.radeon.com/rocm/apt/debian xenial/main amd64 rocr_debug_agent amd64 1.0.0 [890 kB]
Err:2 http://repo.radeon.com/rocm/apt/debian xenial/main amd64 rocr_debug_agent amd64 1.0.0
  Writing more data than expected (890180 > 890176)
Fetched 216 kB in 0s (2032 kB/s)         
E: Failed to fetch http://repo.radeon.com/rocm/apt/debian/pool/main/r/rocprofiler-dev/rocprofiler-dev_1.0.0_amd64.deb  Hash Sum mismatch

E: Failed to fetch http://repo.radeon.com/rocm/apt/debian/pool/main/r/rocr_debug_agent/rocr_debug_agent_1.0.0_amd64.deb  Writing more data than expected (890180 > 890176)
```
The update of the deb-database is not done (correctly)?

**Comment by zhang2amd** [comment]
I tested the repo again. Didn't see this issue. The current release is 2.10. I also tried 2.9 release which was the latest in October and no issue too.
Did you clear apt cache before install? Are you behind a firewall or using proxy servers? These are possible reasons from your side to see this error.

**Comment by VincentSC** [comment]
Missed your reply. Cache cleared, no proxy, all other repos work. I solved it by manually downloading rocprofiler-dev, removing rocprofiler-dev, manually installing rocprofiler-dev with dpkg -i, and then reinstalling "hipblas rocblas rocm-dev rocprofiler-dev rocrand".

Is the repo hosted on a server that has FAT or any other MS filesystem? It seems that the more data is sent than advertised. When I download the file on Windows, the file-size and size-on-disk are equal to what is printed. I think it would be solved by or updating the filesize to size-on-disk, or by not sending the trailing zeroes.

**Comment by nartmada** [comment]
Please check latest ROCm Documentation and ROCm 5.7.1 to see if your issue has been resolved.  If resolved, please close the ticket.  Thanks.

**Comment by nartmada** [comment]
Original ticket is more than a year old and the person that opened the ticket has not responded to the latest request.  If this is still an issue, please file a new ticket and we will investigate.  Thanks!
