### ISSUE TITLE
Does ROCm support AMD SR-IOV GPU virtualization

### ISSUE THREAD

**Issue by zhangyy91** [ROCm/ROCm#917]
Hi, Guys, I am new to ROCm and GPU virtualization. I wonder if ROCm supports to run in a virtual machine with SR-IOV virtual GPUs.

**Comment by heero-yuy** [comment]
Hi,
ROCm didn't support the Virtual GPU usage, instead that have Docker can play a role under Host with mutliple GPU on same Host.

if need seperate Virtual Machine, maybe Linux KVM can use, but just only computing feature, there's no function related VDI usage on ROCm, thanks!

**Comment by nartmada** [comment]
Please check latest ROCm Documentation and ROCm 5.7.1 to see if your query has been resolved.  If resolved, please close the ticket.  Thanks.

**Comment by zhangyy91** [comment]
@nartmada Thanks for your reply and I will close this issue.

**Comment by zhangyy91** [comment]
@nartmada Thanks for your reply and I will close this issue.
