### ISSUE TITLE
Supported GPU Typo RX 570 -> Rx 560

### ISSUE THREAD

**Issue by kbitGit** [ROCm/ROCm#925]
Hello there,
I noticed, that currently the RX 570 is listed as Polaris 11 under the supported GPUs section.
My current understanding is, that the RX 570 is a Polaris 10 Cutdown and that the RX 560 is the Polaris 11 .

It may cause confusion to some users and i did not found an issue regarding this.

**Comment by keryell** [comment]
Is this fixed?

**Comment by nartmada** [comment]
Hi @kbitGit, please check latest ROCm Documentation and ROCm 5.7.1 to see if your query has been resolved.  If resolved, please close the ticket.  Thanks.

**Comment by nartmada** [comment]
Original ticket is more than a year old and the person that opened the ticket has not responded to the latest request.  If this is still an issue, please file a new ticket and we will investigate.  Thanks!
