### ISSUE TITLE
rocm installation issue in my pc

### ISSUE THREAD

**Issue by kabish01** [ROCm/ROCm#930]
hsa api call failure at: /data/jenkins_workspace/compute-rocm-rel-2.9/rocminfo/rocminfo.cc:1102
Call returned HSA_STATUS_ERROR_OUT_OF_RESOURCES: The runtime failed to allocate the necessary resources. This error may also occur when the core runtime library needs to spawn threads or create internal OS-specific events.

**Comment by Burstaholic** [comment]
What hardware are you using? This happens to me on my Vega M laptop (i7-8705G).

**Comment by kabish01** [comment]
I am using Ryzen 5 3550h CPU with Vega 8 integrated graphics and Radeon RX560X dedicated GPU.

**Comment by bugparty** [comment]
amd 1800x + amd470 and centos8.3 failed too

**Comment by Shreyashwaghe** [comment]
Any luck with the recent rocm 4.1 or 4.0 with your rx560x card, i am facing few problems too

**Comment by nartmada** [comment]
Original ticket is more than a year old and the person that opened the ticket has not responded to the latest request.  If this is still an issue, please file a new ticket and we will investigate.  Thanks!
