### ISSUE TITLE
vega 11 support status? (Ryzen 5 3400G)

### ISSUE THREAD

**Issue by linas** [ROCm/ROCm#949]
So - Ryzen 5 3400G is an entry-level 4core cpu plus "Vega 11 graphics".  Introduced summer 2019. it gets enthusiastic reviews on the interwebs...

This page: https://rocm.github.io/hardware.html makes no mention of it, one way or another.

Given that ROCm is aimed at "HPC and Ultrascale computing", I am not surprised by the overall silence on 3400G ... It's just that I bought one by mistake :-p and am now wondering what I can do with it...

**Comment by smartbitcoin** [comment]
when I got navi , I have same expectation as you have for ryzen APU.  later I realize I have to do it by myself as ROCM is oss.
what you really want from apu?  hip compiling stack or tensoflow,   if it's only hip compiler maybe I can help you get a working binary in one week.

**Comment by linas** [comment]
Short answer: "Ability to compile & run plain-old opencl2.0 code".  Question:: what's missing for vega11 support?  A compiler backend (hcc or clang)? Can I assume the existing compilers work (because otherwise "hip in a week" would not be possible, right?) 

So I assume that what's missing is dkms or runtime shims to initialize vega11, to load/start/stop apps running on vega11? If that's whats missing, then it sounds like maybe 20 different 10-line tweaks to 6 different packages?

**Comment by smartbitcoin** [comment]
@linas   you are right in most part.   from my experience to turn on navi ( https://github.com/smartbitcoin/MyROCm ),   the linux kernel 5.4 are pretty good for Ryzen APU ,  the llvm also should be ok , if just turn on xnack.  ( for navi , llvm 10 have few bugs which bring unstable issue ).

the component need change is the rocr runtime,  hip and hcc compiler .

for your case , if you only need run opencl, you can use proprietary linux driver for APU, which already support it long time ago.

**Comment by luyatshimbalanga** [comment]
@smartbitcoin The catch with amdpgu pro open-cl is the reading of the GPU part of APU as "unknown AMD GPU". It would be great both internal AMD team and ROCm properly coordinate their effort to get out the current mess.

**Comment by Alfcyber** [comment]
on my laptop (tinkpad e485 (Marketing Name: AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx)) I have a working clinfo and rocminfo, however, I see Pool Info:
    Pool 1
      Segment: GROUP
      Size: 64 (0x40) KB
      Allocatable: FALSE
      Alloc Granule: 0KB
      Alloc Alignment: 0KB
      Acessible by all: FALSE

However, it is still possible to compile simple kernel on the gpu, but it has no advantage over a single cpu thread

**Comment by eapenfold** [comment]
Is there any update on this? I would like to know if it can be used as a GPU for tensorflow in Linux.

**Comment by nartmada** [comment]
Hi @linas, please check latest ROCm Documentation and ROCm 5.7.1 to see if your query has been resolved.  If resolved, please close the ticket.  Thanks.

**Comment by linas** [comment]
Closing. This is four years old & stale.
