### ISSUE TITLE
warning: argument unused during compilation: '-I .'

### ISSUE THREAD

**Issue by valeriob01** [ROCm/ROCm#952]
```
1 warning generated.
2019-11-26 06:06:12 warning: argument unused during compilation: '-I .'
```

This happens with the gpuowl program. ROCm 2.10

**Comment by boxerab** [comment]
This just means that it is no longer necessary to add the current compile directory as an include directory when compiling opencl to binary format. To fix, simply remove this from the opencl compile settings.

**Comment by preda** [comment]
I understand what it means, but I can't simply remove it, because with other OpenCL backends would not work anymore. That's one of the points of OpenCL, being portable to more than just ROCm.

**Comment by boxerab** [comment]
What is odd is that if this build parameter is removed, then my kernels will not find include files in the same directory. So, it is needed, and there should not be a warning.

**Comment by nartmada** [comment]
Hi @valeriob01, please check latest ROCm Documentation and ROCm 5.7.1 to see if your query has been resolved.  If resolved, please close the ticket.  Thanks.

**Comment by nartmada** [comment]
Original ticket is more than a year old and the person that opened the ticket has not responded to the latest request.  If this is still an issue, please file a new ticket and we will investigate.  Thanks!
