### ISSUE TITLE
How do i enable a debug build for the rocm source installed via apt install rocm? 

### ISSUE THREAD

**Issue by johnutz-PNSR** [ROCm/ROCm#961]
Hello;
I would like to rebuild the rocm i installed from Release to Debug. so I can have a more informative stack trace from gdb.

How can i do this?

I am attempting to run clinfo. I get a segfault in amd::GpuAgent::GetInfo() in /opt/rocm/hsa/lib/libhsa-ext-image64.so.1.

But libhsa-ext-image64.so.1 is stripped  and so the stack from the core file is less useful
than hoped:
gdb /usr/bin/clinfo -c ~/core
Reading symbols from /usr/bin/clinfo...(no debugging symbols found)...done.
[New LWP 1531]
[New LWP 1534]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".     Core was generated by `clinfo'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f7cf8f3b850 in ?? () from /opt/rocm/hsa/lib/libhsa-ext-image64.so.1
[Current thread is 1 (Thread 0x7f7cfc44e740 (LWP 1531))]
(gdb) bt
#0  0x00007f7cf8f3b850 in ?? () from /opt/rocm/hsa/lib/libhsa-ext-image64.so.1
#1  0x00007f7cfae924d9 in amd::GpuAgent::GetInfo(hsa_agent_info_t, void*) const () from /opt/rocm/hsa/lib/libhsa-runtime64.so.1
#2  0x00007f7cfaea6e68 in HSA::hsa_agent_get_info(hsa_agent_s, hsa_agent_info_t, void*) () from /opt/rocm/hsa/lib/libhsa-runtime64.so.1
#3  0x00007f7cfb270733 in ?? ()
   from /opt/rocm/opencl/lib/x86_64/libamdocl64.so
#4  0x00007f7cfb270e32 in ?? ()
   from /opt/rocm/opencl/lib/x86_64/libamdocl64.so
#5  0x00007f7cfb27245a in ?? ()
   from /opt/rocm/opencl/lib/x86_64/libamdocl64.so
#6  0x00007f7cfb23f28f in ?? ()
   from /opt/rocm/opencl/lib/x86_64/libamdocl64.so
#7  0x00007f7cfb23a297 in ?? ()
   from /opt/rocm/opencl/lib/x86_64/libamdocl64.so
#8  0x00007f7cfb20dad5 in ?? ()
   from /opt/rocm/opencl/lib/x86_64/libamdocl64.so
#9  0x00007f7cfb3853c9 in ?? ()
   from /opt/rocm/opencl/lib/x86_64/libamdocl64.so
#10 0x00007f7cfb20dc0c in clIcdGetPlatformIDsKHR ()
   from /opt/rocm/opencl/lib/x86_64/libamdocl64.so
#11 0x00007f7cfc4563c5 in ?? ()
   from /opt/rocm/opencl/lib/x86_64/libOpenCL.so.1
#12 0x00007f7cfc45818f in ?? ()
   from /opt/rocm/opencl/lib/x86_64/libOpenCL.so.1
#13 0x00007f7cfb4a1827 in __pthread_once_slow (once_control=0x7f7cfc45c0d8,        init_routine=0x7f7cfc457fb0) at pthread_once.c:116
#14 0x00007f7cfc4568f1 in clGetPlatformIDs ()
   from /opt/rocm/opencl/lib/x86_64/libOpenCL.so.1
#15 0x000055fbf38ff722 in ?? ()
#16 0x00007f7cfbc78b97 in __libc_start_main (main=0x55fbf38ff5d0, argc=1,          argv=0x7fff359e5e98, init=<optimized out>, fini=<optimized out>,
    rtld_fini=<optimized out>, stack_end=0x7fff359e5e88)
    at ../csu/libc-start.c:310
#17 0x000055fbf38ffb3a in ?? ()
(gdb)

Any help with this would be greatly appreciated!
Thankyou very much in advance!

John Utz 
Pensar Development

**Comment by nartmada** [comment]
Please check latest ROCm Documentation and ROCm 5.7.1 to see if your query has been resolved.  If resolved, please close the ticket.  Thanks.

**Comment by nartmada** [comment]
Original ticket is more than a year old and the person that opened the ticket has not responded to the latest request.  If this is still an issue, please file a new ticket and we will investigate.  Thanks!
