### ISSUE TITLE
Inline assembly Mul:2 Div:2 modifiers ignored

### ISSUE THREAD

**Issue by gwoltman** [ROCm/ROCm#964]
Take any working code with inline assembly.  Add mul:2 or div:2 modifiers to the assembly and your code will still work!

This is the assembly code I wrote to calculate tmp = 2 * a.x * a.y:
              __asm( "v_mul_f64 %0, %1, %2 mul:2\n" : "=v" (tmp) : "v" (a.x), "v" (a.y));

**Comment by b-sumner** [comment]
Unfortunately, the documentation doesn't really spell out the fact that output modifiers are not compatible with denorms enabled, nor are they compatible with IEEE mode, and you are likely using both.

**Comment by preda** [comment]
How can IEEE mode be controlled in OpenCL? (or controlled at all). What would disabling IEEE mode entail?

**Comment by b-sumner** [comment]
There is a whole section on the MODE register in the ISA document.  (Latest vega 7nm guide here: https://gpuopen.com/wp-content/uploads/2019/11/Vega_7nm_Shader_ISA_26November2019.pdf )

There are no compiler options to directly manipulate any MODE register fields.  I need to check on whether we turn off IEEE when flushing denorms.  Can you comment on why you're flushing denorms?

**Comment by preda** [comment]
I see in the kernel ISA dump that the float_mode is always 240 (0xF0). That corresponds to IEEE_MODE being set unless I'm mistaken. This is for a compilation done with -cl-fast-relaxed-math.

According to the OpenCL docs https://www.khronos.org/registry/OpenCL/sdk/2.0/docs/man/xhtml/clBuildProgram.html

-cl-fast-relaxed-math:
Sets the optimization options -cl-finite-math-only and -cl-unsafe-math-optimizations. This allows optimizations for floating-point arithmetic that may violate the IEEE 754 standard and the OpenCL numerical compliance requirements defined in the specification in section 7.4 for single-precision and double precision floating-point, and edge case behavior in section 7.5. This option also relaxes the precision of commonly used math functions (refer to table 7.2 defined in section 7.4). This option causes the preprocessor macro __FAST_RELAXED_MATH__ to be defined in the OpenCL program. 

-cl-unsafe-math-optimizations:
    Allow optimizations for floating-point arithmetic that (a) assume that arguments and results are valid, (b) may violate IEEE 754 standard and (c) may violate the OpenCL numerical compliance requirements as defined in section 7.4 for single precision and double precision floating-point, and edge case behavior in section 7.5. This option includes the -cl-no-signed-zeros and -cl-mad-enable options. 

-cl-finite-math-only:
    Allow optimizations for floating-point arithmetic that assume that arguments and results are not NaNs or ±∞. This option may violate the OpenCL numerical compliance requirements defined in section 7.4 for single precision and double precision floating point, and edge case behavior in section 7.5. 

So the OpenCL doc seems to suggest that IEEE_MODE should be disabled when -cl-fast-relaxed-math is requested. This becomes more important as there is no other way to disable IEEE_MODE in OpenCL.

**Comment by preda** [comment]
I would associate IEEE_MODE with -cl-finite-math-only (vs. flushing of denormals), as IEEE_MODE in my reading from the ISA doc seems to be concerned with the handling of NaNs and maybe INFs.

**Comment by preda** [comment]
After more careful consideration, I see that  *float_mode = 240* indicates that denorms aren't flushed (top 4 bits), and there is a separate enable_ieee_mode which is set. So the question becomes, is this the intended behavior of -cl-fast-relaxed-math ?

**Comment by gwoltman** [comment]
I can confirm that adding these two lines to the start of the kernel fixes the problem.  I'll leave it to others to work out whether the OpenCL -cl-fast-relaxed-math switch is setting bits properly.

 

`__asm("s_setreg_imm32_b32 hwreg(HW_REG_MODE, 9, 1), 0\n");
 __asm("s_setreg_imm32_b32 hwreg(HW_REG_MODE, 4, 4), 5\n"); `

**Comment by nartmada** [comment]
Hi @gwoltman, please close this ticket if your issue has been resolved.  Thanks.

**Comment by gwoltman** [comment]
Closing ticket.  I'm no longer doing Radeon VII development work.
