### ISSUE TITLE
Opencl segmentation (core dumped) error

### ISSUE THREAD

**Issue by Srikar-Ganta** [ROCm/ROCm#965]
I installed using https://rocm.github.io/ROCmInstall.html.
When testing rocm installation using /opt/rocm/opencl/bin/x86_64/clinfo getting error as: **Segmentation fault (core dumped)**

**Comment by johnutz-PNSR** [comment]
is the segfault the same as the one that i report in issue 962 from a few days before your report?

**Comment by nartmada** [comment]
Hi @Srikar-Ganta, please check latest ROCm Documentation and ROCm 5.7.1 to see if your issue has been resolved.  If resolved, please close the ticket.  Thanks.

**Comment by nartmada** [comment]
Original ticket is more than a year old and the person that opened the ticket has not responded to the latest request.  If this is still an issue, please file a new ticket and we will investigate.  Thanks!
