### ISSUE TITLE
hsa-ext-rocr-dev is broken since ROCm 2.9

### ISSUE THREAD

**Issue by btspce** [ROCm/ROCm#981]
When hsa-ext-rocr-dev is upgraded from ROCm repo 2.10 or 3.0 for image support clinfo segfaults and so does Darktable. Last version that worked was hsa-ext-rocr-dev-1.1.9-122-ge5c4efb1-Linux.rpm from ROCm 2.9. Downgrading to package hsa-ext-rocr-dev-1.1.9-122-ge5c4efb1-Linux.rpm solves the issue.

ROCm 2.2 to 2.9 works
2.10 and 3.0 does not.

AMD Raven Ridge APU 2700u Fedora 31 x64

**Comment by vsrikarunyan** [comment]
Yes, looks like it. Since the update to ROCm v3, my environment is broken. Output for `rocminfo` is as below

```
ROCk module is loaded
<username> is member of video group
hsa api call failure at: /data/jenkins-workspace/compute-rocm-rel-3.0/rocminfo/rocminfo.cc:1102
Call returned HSA_STATUS_ERROR_OUT_OF_RESOURCES: The runtime failed to allocate the necessary resources. This error may also occur when the core runtime library needs to spawn threads or create internal OS-specific events.

```

**Comment by DeadEnded** [comment]
Just did a fresh install on Ryzen 2400G and getting this too... anyone have an idea when it might be addressed?

**Comment by btspce** [comment]
Still broken in ROCm 3.1

**Comment by btspce** [comment]
Still broken in ROCm 3.3

**Comment by nartmada** [comment]
Hi @btspce, please check latest ROCm Documentation and ROCm 5.7.1 to see if your issue has been resolved.  If resolved, please close the ticket.  Thanks.

**Comment by btspce** [comment]
I don't have this laptop anymore so I can't verify if it is fixed. Closing for now.
